### ISSUE TITLE
[java]I have written a custom rule，but I get the error when I run “mvn clean package”

### ISSUE THREAD

**Issue by Wchenghui** [pmd/pmd#1001]
PMD-6.1.0

I have written a custom rule，but it fails when I run “mvn clean package” in the "/pmd-src-6.1.0/pmd-java". Here are the errors.

[INFO] Executed tasks
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ pmd-java ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 1.8.0-131 is not in the allowed range [9,).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.019 s
[INFO] Finished at: 2018-03-25T21:42:57+08:00
[INFO] Final Memory: 19M/103M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) on project pmd-java: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by oowekyala** [comment]
PMD's build requires a Java 9 runtime, but you're apparently using Java 8. See https://github.com/pmd/pmd/blob/master/BUILDING.md for more info about building PMD from source
