### ISSUE TITLE
[java] UnnecessaryConstructor triggered on required empty constructor (Dagger @Inject)

### ISSUE THREAD

**Issue by friederbluemle** [pmd/pmd#1003]
**Affects PMD Version:** 
6.1.0

**Rule:**
category/java/codestyle.xml/UnnecessaryConstructor

**Description:**
Using Dagger dependency injection, I am _required_ to have an empty constructor in my class which extends an abstract base class. The instance is provided using Dagger multibinding.

**Code Sample demonstrating the issue:**

```
// MainViewModel.java
public class MainViewModel extends BaseViewModel {
    @Inject
    public MainViewModel() {
        super();
    }

    // ...
}

// ViewModelModule.java
@Module
abstract class ViewModelModule {
    @Binds
    @IntoMap
    @ViewModelKey(MainViewModel.class)
    abstract ViewModel bindMainViewModel(MainViewModel viewModel);

    // ...
}

```

The error message (when removing the empty constructor to fix the PMD warning) is:

```
[dagger.android.AndroidInjector.inject(T)] MainViewModel cannot be provided without an @Inject constructor or from an @Provides-annotated method. This type supports members injection but cannot be implicitly provided.
```

**Running PMD through:** *Gradle*

It would be great to be able to skip *annotated* (e.g. `@Inject`) constructors, as this rule is still useful for "normal" constructors.

**Comment by djydewang** [comment]
It seems that the rule should extend the `AbtractIgnoredAnnotataionsRule` class and set default value of `ignoredAnnotations` property to "javax.inject.Inject".

**Comment by djydewang** [comment]
It seems that the rule class should extend `AbstractIgnoredAnnotationsRule` class and set default value of the `ignoredAnnotations` property to "javax.inject.Inject". I‘m willing to submit a PR:)

**Comment by friederbluemle** [comment]
@djydewang That would be great! Thanks

**Comment by jsotuyod** [comment]
@djydewang you are absolutely right! Should be very easy now you took care of that refactor ;)

**Comment by djydewang** [comment]
@jsotuyod It's a XPath rule, we have two ways to fix this issue:

- Changing this rule to java rule and extend `AbstractIgnoredAnnotationsRule`

- Fixing it in XPath expression.

Which one do you think is better?

**Comment by jsotuyod** [comment]
@djydewang considering the XPath expression is very straightforward, and in favor of extensibility, I'd suggest rewriting the rule in Java. I believe you should be more than capable if you feel up to it.

**Comment by friederbluemle** [comment]
:tada: Thanks! :+1:
