### ISSUE TITLE
[java] False positive for `DoNotExtendJavaLangError`

### ISSUE THREAD

**Issue by mnlipp** [pmd/pmd#1021]
**Affects PMD Version:** 6.2.0

**Rule:** DoNotExtendJavaLangError

**Description:** If I extend a class `Error` (a class of my own, *not* `java.lang.Error`) PMD finds a false positive.

**Code Sample demonstrating the issue:** Too difficult to cut and paste here. Just declare a class `Error` and another one that extends it.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]* pmd-eclipse 1.11.0

**Comment by adangel** [comment]
Thanks for reporting.
Yes, this rule does a simple String match to determine, whether it is `java.lang.Error` or not.
The rule should be updated to use type resolution, which is also available for XPath rules.

**Comment by akshatbahety** [comment]
@oowekyala @adangel I will try to solve this.
