### ISSUE TITLE
[core] Apply the new PropertyDescriptor<Pattern> type where applicable

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1027]
The newly introduced `PropertyDescriptor<Pattern>` type should be applied to several properties that are currently being treated as plain String properties.

A couple of examples:
* `Rule.VIOLATION_SUPPRESS_REGEX_DESCRIPTOR`
* Java's `EmptyCatchBlock.allowExceptionNameRegex`

There are probably other cases, we need to look them up and change their types accordingly.

**Comment by jsotuyod** [comment]
@keerthikorivi the issue is still required, but as noted, `RegexProperty` shouldn't be used anymore, but `PropertyDescriptor<Pattern>` is. I'll update the issue to reflect this.

**Comment by adangel** [comment]
@oowekyala I know, you are working in this area. When converting the StringProperty to PropertyDescriptor<String>, maybe you can just collect those properties, that could be Regex Properties here?

**Comment by oowekyala** [comment]
@adangel Yeah this can be taken care of in the deprecation PR for StringProperty :)

**Comment by keerthikorivi** [comment]
@oowekyala Just wanted to confirm, will this be addressed in any other PR?

**Comment by oowekyala** [comment]
@keerthikorivi Do you mean to ask whether the issue will take several PRs to resolve? If so, then I think yes. Some of the property descriptors are published API (most notably, [violationSuppressRegex](https://github.com/pmd/pmd/blob/c93e2378c45ea94758a087ccc0d5468943607116/pmd-core/src/main/java/net/sourceforge/pmd/Rule.java#L31)), and changing their type would only be appropriate for 7.0.0. So I think two PRs may do the trick
