### ISSUE TITLE
[java] Prepare for Java 11

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1038]
Java 11 (aka. Java 18.9) is going to extend the local-variable declaration syntax `var XXX` to lambda parameters.

This should be a very lightweight change once Java 10 is supported, as having lambda parameters' type inferred is nothing new, just with a different syntax (ie: `(a, b) -> …`).

The full JEP can be found here: http://openjdk.java.net/jeps/323

Schedule and features: http://openjdk.java.net/projects/jdk/11/
Builds are available at: http://jdk.java.net/11/
Java 11 is planned to be released in September 2018 (General Availability).

Depends on #743

**Comment by adangel** [comment]
Additionally, Java 11 won't ship JavaFX anymore. We'll need to integrate OpenJFX.
See https://blogs.oracle.com/java-platform-group/the-future-of-javafx-and-other-java-client-roadmap-updates

**Comment by adangel** [comment]
For the JLS changes, see attachment at https://bugs.openjdk.java.net/browse/JDK-8193259

**Comment by jsotuyod** [comment]
The [JEP 181](http://openjdk.java.net/jeps/181) will make obsolete rules such as `AccessorClassGeneration` and `AccessorMethodGeneration`. We should probably add `maximumLanguageVersion="11"` to those rules to automatically disable them under Java 11.
