### ISSUE TITLE
[java] AvoidInstantiatingObjectsInLoops won't detect assigning object to array

### ISSUE THREAD

**Issue by GiantCrocodile** [pmd/pmd#1043]
**Affects PMD Version:** 6.2.0

**Rule:** [AvoidInstantiatingObjectsInLoops](https://pmd.github.io/latest/pmd_rules_java_performance.html#avoidinstantiatingobjectsinloops)

**Description:** This rule won't detect if you create an object inside a loop but assign it to an array.

**Code Sample demonstrating the issue:**

```java
Car[] cars = new Car[3];
for(int i = 0;i < cars.length;++i) {
   cars[i] = new Car();
}
```

**Running PMD through:** Eclipse

**Comment by adangel** [comment]
I think, it is not useful to flag such code: In this sample, you clearly want to create 3 cars, so it is natural to do this in a loop.

With #2207, we are changing the rule to not flag instantiations within loops, if collections are in use (e.g. collecting the created instance in a list, etc.).
