### ISSUE TITLE
[java] Property ignoredAnnotations does not work for SingularField and ImmutableField

### ISSUE THREAD

**Issue by mkordas** [pmd/pmd#1056]
**Affects PMD Version:** 
6.2.0

**Rule:**
`ImmutableField` and `SingularField`

**Description:**
Newly announced parameter `ignoredAnnotations` is present in these rules, but it doesn't ignore any violations. 
Method `net.sourceforge.pmd.lang.java.rule.AbstractIgnoredAnnotationRule#hasIgnoredAnnotation` is used only in `UnusedPrivateField` and `UnusedPrivateMethod` rules and feature works well for them.

**Code Sample demonstrating the issue:**

```xml
    <rule ref="category/java/design.xml/SingularField">
        <properties>
            <property name="ignoredAnnotations" value="java.lang.Deprecated"/>
        </properties>
    </rule>
```
```java
            public class Source {
                @Deprecated
                private Object o; //violation!

                Object m() {
                    o = new Object();
                    return o;
                }
            }
```
**Running PMD through:** Gradle

**Comment by adangel** [comment]
Thanks for reporting! It looks like, we are missing a call to actually use the new property, we inherited from the super class....
