### ISSUE TITLE
[java] ClassNamingConventions suggests to add Util suffix for simple exception wrappers

### ISSUE THREAD

**Issue by mkordas** [pmd/pmd#1064]
**Affects PMD Version:** 
6.3.0

**Rule:**
`ClassNamingConventions`

**Description:**
`ClassNamingConventions` violation triggers for simple Exception

**Code Sample demonstrating the issue:**

```
public class MyException extends RuntimeException {
	public MyException(Exception exception) {
		super(exception);
	}
}
```
```
[ClassNamingConventions] The utility class name 'MyException' doesn't match '[A-Z][a-zA-Z]+Util'
```

**Running PMD through:** Gradle

**Comment by oowekyala** [comment]
Thanks for the report! We'll fix that Asap

**Comment by oowekyala** [comment]
I can't reproduce that bug... There's already a test case against something very similar too. Is the class in its own file or nested? Do you use incremental analysis?

**Comment by muminc** [comment]
```
import java.util.ArrayList;

public class StringList extends ArrayList<String> {
}
```

```
INFO] PMD Failure: StringList:5 Rule:ClassNamingConventions Priority:3 The utility class
name 'StringList' doesn't match '[A-Z][a-zA-Z]+Util'.
```
Seeing the above if I use PMD version 6.3.0,  if I downgrade to version 6.2.0 then the it's fine.

**Comment by oowekyala** [comment]
@muminc Thanks for the report. Unfortunately I can't reproduce that bug either, and there's already a test case for that... May I ask for your OS and JDK version information?

**Comment by muminc** [comment]
Couldn't get my above example to fail in the PMD unit test,  but if I modify a bit and add this test case to ClassNamingConventions.xml

 ```
  <test-code>
        <description>Class extending another class should not be utility class</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            public class StringList extends ArrayList<String> {
                static StringList emptyList() {
                    return new StringList();
                }
            }
            ]]></code>
    </test-code>
```

Test CodeStyleRulesTest reports failure

```
--------------------------------------------------------------
Test Failure: Class extending another class should not be utility class
 -> Expected 0 problem(s), 1 problem(s) found.
 -> Expected messages: []
 -> Expected line numbers: []

n/a:1:	The utility class name 'StringList' doesn't match '[A-Z][a-zA-Z]+Util'

```
