### ISSUE TITLE
[java] Java 10 build failure

### ISSUE THREAD

**Issue by ilovezfs** [pmd/pmd#1066]
**Affects PMD Version:** 
6.3.0

https://gist.github.com/ilovezfs/bd9e202801a822b09f604e2bc54ba7fd
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/23163/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_pmd/

**Comment by adangel** [comment]
Hm... that's weird. Such NPE while determining the java version were usually happening when a maven plugin was not java9 or java10 ready. I'm using Linux with the following config:

```
pmd-src-6.3.0$ mvn --version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /home/andreas/programs/apache-maven-3.5.3
Java version: 10.0.1, vendor: Oracle Corporation
Java home: /home/andreas/programs/jdk-10.0.1
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-3-amd64", arch: "amd64", family: "unix"
```

And this error doesn't occur for me. Maybe it is a OS X specific problem?
We both seem to use the same maven (3.5.3) and same java version (10.0.1)....

For reference, stacktrace is:
```
Caused by: java.lang.NullPointerException
    at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast (SystemUtils.java:1626)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.getJavadocExecutable (AbstractJavadocMojo.java:3589)
    at org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (AbstractJavadocMojo.java:1963)
at org.apache.maven.plugins.javadoc.JavadocJar.doExecute (JavadocJar.java:188)
```

It seems to be an issue of the javadoc plugin: https://issues.apache.org/jira/browse/MJAVADOC-517

A possible workaround until m-javadoc-p 3.0.1 is released is: using version 3.7 of commons-lang3.

@ilovezfs 
Is it required for homebrew to rebuild PMD from source? It would be much faster, if the prebuilt binaries could be used....

**Comment by ilovezfs** [comment]
Maybe the problem has something to do with https://github.com/Homebrew/homebrew-core/blob/master/Formula/pmd.rb#L24-L45

>Is it required for homebrew to rebuild PMD from source? It would be much faster, if the prebuilt binaries could be used....

As long as the prebuilt stuff is cross-platform jars, it wouldn't violate our policies to use it. See https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae

**Comment by adangel** [comment]
> Maybe the problem has something to do with https://github.com/Homebrew/homebrew-core/blob/master/Formula/pmd.rb#L24-L45

Hm...Yes, that could be the reason. However, it actually should not be used anymore, since we don't have the toolchain plugin configured. So, you can try removing this part (it is really not needed anymore) - but I guess, it won't fix the build.
Btw. building PMD requires at least a Java9 Oracle JDK (since java9 is outdated, java10 is usually used now).



>> Is it required for homebrew to rebuild PMD from source? It would be much faster, if the prebuilt binaries could be used....

> As long as the prebuilt stuff is cross-platform jars, it wouldn't violate our policies to use it. See https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#we-dont-like-binary-formulae

The binary (e.g. https://github.com/pmd/pmd/releases/download/pmd_releases/6.3.0/pmd-bin-6.3.0.zip) is exactly the same, as you would build locally. It is cross-platform already.

**Comment by jsotuyod** [comment]
The exact Java requirements are:

9+ to build
8+ to run the designer & APEX module
7+ to run anything else
