### ISSUE TITLE
[java] Allow JUnitTestsShouldIncludeAssert to configure verification methods

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1084]
As per https://github.com/pmd/pmd/issues/358#issuecomment-387209633, we should probably add a property to allow the user to configure which static methods are valid verification methods to allow users of any mocking library to use it properly.

**Comment by bohni** [comment]
org.springframework.test.web.servlet.ResultActions is an interface - are interface mathods treated as static (e.g. ResultAction#andExpect)?

**Comment by freshone** [comment]
I'm running into this problem with 6.23.0

Adding configuration to this rule would be helpful

**Comment by adangel** [comment]
... also found a case of false positive, when using verify() inside a foreach this warning is also triggered

_Originally posted by @yasmimc in https://github.com/pmd/pmd/issues/358#issuecomment-1230831671_

**Comment by emouty** [comment]
It would be nice to have this feature, because I get some false positive when using awaitility
