### ISSUE TITLE
[xml] java.lang.NoSuchMethodError: net.sourceforge.pmd.lang.xml.rule.AbstractXmlRule.definePropertyDescriptor(Lnet/sourceforge/pmd/properties/PropertyDescriptor;)

### ISSUE THREAD

**Issue by nareshl119** [pmd/pmd#1104]
**Affects PMD Version:**
 6.2.0

**Rule:**
Writing pmd custom rules for xml files

**Description:**
We are writing custom rules for XML files in our project. We are using PMD 6.2.0 version. We are getting below error while running pmd rules using gradle.
java.lang.NoSuchMethodError: net.sourceforge.pmd.lang.xml.rule.AbstractXmlRule.definePropertyDescriptor(Lnet/sourceforge/pmd/properties/PropertyDescriptor;)

Please let me know If I am missing anything in the code or any configuartion stuff.

Thank you in advance.

Regards,
Naresh.

**Code Sample demonstrating the issue:**

1) ruleset xml file looks like below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="Xml Rules"
		 xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
   <description>This ruleset validates xml files</description>
  
   <rule name = "XmlRuleDemo" language="xml" message= "Able to parse Xml file using pmd" class = "com.sample.demo.xml.XmlRuleDemo">
   		<description>Able to parse Xml file using pmd</description>
   		<priority>3</priority>
   </rule>   
</ruleset>
```

2) XmlRuleDemo class extends AbstractXmlRule and looks like below:

```java
public class XmlRuleDemo extends AbstractXmlRule{
	
	 @Override
	public void visit(XmlNode xmlNode, RuleContext ruleContext){
		 System.out.println(xmlNode.getImage());
		 System.out.println(xmlNode.getAsDocument().getNodeName());
		 System.out.println(xmlNode.getAsDocument().getNodeValue());
		 addViolation(ruleContext, xmlNode);
	}

}
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Gradle
build.gradle file

```
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'pmd'
pmd {
	ruleSetFiles = rootProject.files("src/main/resources/archruleset1.xml")
}

dependencies {
	compile group: 'net.sourceforge.pmd', name: 'pmd', version: '6.3.0'
	compile group: 'net.sourceforge.pmd', name: 'pmd-java', version: '6.3.0'
	compile group: 'net.sourceforge.pmd', name: 'pmd-xml', version: '6.3.0'
	compile group: 'log4j', name: 'log4j', version: '1.2.16'
	compile group: 'org.springframework', name: 'spring-web', version: '3.0.4.RELEASE'
	compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.0'
}
```

**Comment by adangel** [comment]
Hi @nareshl119 , thanks for reporting!

Are you using PMD 6.2.0 or 6.3.0 (your gradle file tells 6.3.0)? But that should not actually matter - both versions should be compatible enough.

Do you have maybe the complete stacktrace for this exception?
`java.lang.NoSuchMethodError: net.sourceforge.pmd.lang.xml.rule.AbstractXmlRule.definePropertyDescriptor(Lnet/sourceforge/pmd/properties/PropertyDescriptor;)`

The method `definePropertyDescriptor` does indeed not exist in `AbstractXmlRule`, but at `AbstractPropertySource`. How did you compile your rule `XmlRuleDemo`?

Would it be possible for you to share the complete project? You can attach a zip file here. That way, it's easier to reproduce the problem. If you are ok with it, I would also like to at it then to https://github.com/pmd/pmd-examples - where we are missing a gradle example.

Thanks!

**Comment by nareshl119** [comment]
Hi Andreas,

Thank you for your response.

I have tried with above changes in the gradle, I am not getting the java.lang.NoSuchMethodError.
but getting "java.lang.IllegalArgumentException: Unknown Language 'xml' for ruleXmlRuleDemo, supported Languages are java" error as you mentioned.

As you suggested, I will explore more about SourceSet and sourceSets in gradle build file and let you know if I find anything.

Please let me know if you find a way avoid this error.

Best Regards,
Naresh

**Comment by adangel** [comment]
> "java.lang.IllegalArgumentException: Unknown Language 'xml' for ruleXmlRuleDemo, supported Languages are java" 

You need to configure the dependencies for the pmd plugin, as above:

```
dependencies {
   // dependencies for pmd plugin
    pmd 'net.sourceforge.pmd:pmd-xml:6.3.0'
    pmd 'com.sample:pmd xml rules:0.0.1-SNAPSHOT'
}
```

**Comment by adangel** [comment]
Ok, so the last bit, that is missing is this line in build.gradle:

```
pmdMain.source = sourceSets.main.allSource
```

If you then run `gradlew build`, PMD should be executed running the rule XmlRuleDemo against the xml file.
You'll notice, that the rule throws some exceptions: `xmlNode.getAsDocument()` is not available. You can access the underlying DOM node via `xmlNode.getNode()`.

**Comment by nareshl119** [comment]
Hi Andreas,

I would like to know what is the default value of toolVersion property? 

https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.PmdExtension.html#org.gradle.api.plugins.quality.PmdExtension:toolVersion_

Naresh
_
