### ISSUE TITLE
[doc] The devdocs/Contributing link in the sidebar doesn't work

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1112]
It's supposed to redirect to https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md but the slashes are omitted : 

https://github.com/pmd/pmd.github.io/commit/34c073275cc993408cfb28c9529565ee8b9fa18c#diff-8f78ad75689de164bf25af966a11eed7R965

**Comment by adangel** [comment]
The same on the generated site by github: https://pmd.github.io/pmd/

**Comment by adangel** [comment]
I think, we need to add a check for external urls at least here: https://github.com/pmd/pmd/blob/master/docs/_includes/sidebar.html#L25

**Comment by adangel** [comment]
Actually, we have `external_url` property, so the sidebar just needs to be changed: https://github.com/pmd/pmd/blob/master/docs/_data/sidebars/pmd_sidebar.yml#L314 : url -> external_url

**Comment by oowekyala** [comment]
Thanks @adangel that works!
