### ISSUE TITLE
[java] Star import overwritten by explicit import is not correctly handled

### ISSUE THREAD

**Issue by freafrea** [pmd/pmd#1114]
**Affects PMD Version:** ??

**Rule:** [java-codestyle.xml/UnnecessaryFullyQualifiedName](https://pmd.github.io/pmd-6.3.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname)??

**Description:**
Hi,
When we have two classes with the same name, but in separate packages and one is imported by 
`import package.*`
and the other by
`import otherPackage.fullName;`

Then in code if I use for example new fullName() java uses class defined by otherPackage.fullName.
So if I want to instantiate package.fullname I have to write new package.fullname(). But PMD says that it should not be fully qualified. But if it were not fully qualified then it would mean an another class.

**Code Sample demonstrating the issue:**

Please see attached sample:
./pmd.bat -d import_sample -format text -R default-java-ruleset.xml -version 1.6
[import_sample.zip](https://github.com/pmd/pmd/files/2016167/import_sample.zip)

**Running PMD through:** *[Maven]*

**Comment by freafrea** [comment]
Thank you for the response. The original case which I had in my code was actually run through maven in the way you suggest.

I just thought you would prefer a test case that uses raw pmd :), thats why I provided such a one.

If you need I can create a maven project out of this sample.

**Comment by jsotuyod** [comment]
@freafrea welcomed and thanks for the report. I'm uncertain of which rule it is that is flagging your code. Is it [java/codestyle.xml/DuplicateImports](https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#duplicateimports)? The referenced ruleset (`default-java-ruleset.xml`) is not par of PMD nor included in your sample project.

**Comment by adangel** [comment]
I think, it is [UnnecessaryFullyQualifiedName](https://pmd.github.io/pmd-6.3.0/pmd_rules_java_codestyle.html#unnecessaryfullyqualifiedname)

**Comment by freafrea** [comment]
Oh, sorry. This is the output I get:
C:\praca\pmd\import_sample\src\main\java\CauseProblem.java:1:   Avoid unused imports such as 'One'
C:\praca\pmd\import_sample\src\main\java\CauseProblem.java:5:   Unnecessary use of fully qualified name 'One.Problem' due to existing import 'One.*'

So I meant the last one.

**Comment by oowekyala** [comment]
I've started looking into this, it's not a type resolution problem. UnnecessaryFullyQualifiedName uses its own algorithm to find unused imports, which falls back on type resolution when it has no other choice, but this is not the case here. I'll dig further
