### ISSUE TITLE
[java] Simplify xpath typeof syntax

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1115]
The `typeof` function currently uses three arguments that appear to be quite redundant (and are not documented other than [a single example](https://pmd.github.io/pmd-6.3.0/pmd_userdocs_extending_writing_pmd_rules.html#inside-an-xpath-query)). The documentation is outdated too, mentioning that only ClassOrInterfaceType is supported

What I gather is
* First arg is always `@Image` -> this could be inferred from the context node, just like the metric function is called with simply `metric('NCSS')`.
* Second arg is FQCN of the type we want to match
* Third arg is the simple name of the type -> redundant, could be inferred from the FQCN

I think we could create a new function (for compatibility), e.g. `typeIs` (this name seems clearer anyway since it returns a boolean), that you could call like:
```xpath
//ClassOrInterfaceType[typeIs('java.lang.StringBuilder')]
```

**Comment by jsotuyod** [comment]
@oowekyala I totally agree. Actually, I would allow this method to have an optional second arg:

```
typeIs('java.lang.StringBuilder', true)
```

Where the second arg checks if we want to have an exact match (ie: class == instead of instanceof). This would address #672 (which by the way reminds me my recent PR #1097 is broken).

I'll be fixing this before 6.4.0

**Comment by oowekyala** [comment]
Good idea! I'll assign you

**Comment by oowekyala** [comment]
@jsotuyod Maybe a slightly more readable solution would be to have two different functions for exact and loose type matching. The thing is xpath has no named parameters for function calls, so without knowing it or diving into the doc your `true` argument would be cryptic. Maybe having both `typeIs` and `typeIsExactly` would be nicer for readability
