### ISSUE TITLE
[doc] Make the landing page of the documentation website more useful

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1119]
The [current landing page](https://pmd.github.io/pmd-6.3.0/) of the doc website basically repeats the info given in [this paragraph](https://pmd.github.io/#about) of the main landing page, with more `<li>`s and more links -> not that useful for a landing page.

Our Jekyl theme does give us much better alternatives to build a sleek and useful interface using special page layouts, eg a [shuffled layout](https://idratherbewriting.com/documentation-theme-jekyll//mydoc_shuffle.html) or a [knowledge-base layout](https://idratherbewriting.com/documentation-theme-jekyll//mydoc_kb_layout.html).

My personal favourite is the latter, which would allow us to put forward some particular page sets depending on the visitor's goal, eg
* Getting started
* Writing rules
* Rule reference
* Contributing
  
on a clutter-free and easily navigable page. I personnally think the sidebar could be more useful as a navigation tool *if it didn't fold*, because when you have no idea what you're looking for you have to open all the menus one by one. Even when you do know where to go, having to click 5 times to get to your page is awkward. So having this kind of easily accessible shortcuts is IMO necessary for a more navigable site.

**Comment by oowekyala** [comment]
In the end I decided to use a kind of shuffled layout. Here's where I'm at for the moment (a bit zoomed out to see more of it): 

![new](https://user-images.githubusercontent.com/24524930/40302105-60a02996-5cee-11e8-8295-0fd7e96621c4.png)

![output](https://user-images.githubusercontent.com/24524930/40302624-fddf9b64-5cef-11e8-8c7b-f0698c4924ba.gif)

I still have some things to work out, like ordering the pages in the individual boxes. Wdyt?

**Comment by adangel** [comment]
This looks great! Cool! :+1:

**Comment by jsotuyod** [comment]
I think I liked the knowledge base layout better... I find it easier to scan and search for things, as it's more tidy, plus I didn't get at first that those where filters in the shuffled layout. From a newcomer's perspective, finding stuff on the knowledge based one seems easier to me, but that's jsut my own biased opinion.

**Comment by oowekyala** [comment]
Maybe we should use more conspicuous buttons for the filters, perhaps even mimicking the knowledge based layout's big buttons with images. But I was happier with the shuffle layout since I find it's easier to grok the structure of the site. With the KBL
* you don't know what's behind the button you click
* if the info you're looking for isn't there, you have to go back and pick another theme

I'll try to implement something with the KBL's buttons shortly to test the idea
