### ISSUE TITLE
[java] Improve ASTLocalVariableDeclaration

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1128]
As per https://github.com/pmd/pmd/pull/1046#discussion_r187517805

`ASTLocalVariableDeclaration.getVariableName()` returns the name of the *first* variable declarator id, but there may be more in the case of `byte var1, var2, var3;` and even the types may be slightly different thanks to arrays (ie: `byte var1, var2[], var3[][];`).

The Javadoc for `getVariableName` says this, but I fail to find a use-case where only the first one is going to be needed... I think we should deprecate it and simply have `ASTLocalVariableDeclaration` implement `Iterable<ASTVariableDeclarator>` and we should just use those...

**Comment by oowekyala** [comment]
>  simply have `ASTLocalVariableDeclaration` implement `Iterable<ASTVariableDeclarator>`

Yes! I totally support that. 

> ASTLocalVariableDeclaration.getVariableName() returns the name of the *first* variable declarator id

That's funny considering `isArray` and `getArrayDepth` only take the *last* declarator id into account for this node...

It also doesn't make sense that  LocalVariableDeclaration is an AccessNode. That's only used for `final`...

**Comment by oowekyala** [comment]
The same holds true for `ASTFieldDeclaration` btw

**Comment by oowekyala** [comment]
Fixed on the java-grammar branch, deprecations on master are in place though they could use a `DeprecatedAttribute(replaceWith=something)`

**Comment by adangel** [comment]
Notes:
* Deprecated on master since 6.10.0 via #1436
* Iterable has been implemented on master since 6.6.0 via #1214
* The method `getVariableName()` has been removed for ASTLocalVariableDeclarion in PMD7 since then.
* ASTFieldDeclaration still has the deprecated method `getVariableName()`.
