### ISSUE TITLE
[core] Deploy snapshots to sonatype central

### ISSUE THREAD

**Issue by krichter722** [pmd/pmd#1130]
**Affects PMD Version:** ---

**Rule:** ---

**Description:**
[Sonatype central](https://search.maven.org/) is a place which hosts Maven snapshots to the main release hosting Maven central and other snapshot repositories. [Their setup guide](https://central.sonatype.org/pages/ossrh-guide.html) provides a quick overview over the necessary steps to register for credentials and how to configure automated deployment for every commit or manual.

The provision of snapshots there (or at a similar location) would ease the investigation of issues since users only have to add the snapshot repository and try the latest snapshot version.

**Code Sample demonstrating the issue:** ---

**Running PMD through:** ---

**Comment by jsotuyod** [comment]
@krichter722 we DO publish snapshots to the Sonatype OSS repository... Actually, we have 7 deployed snapshots today alone...

https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/pmd/pmd-core/6.4.0-SNAPSHOT/

Every time something gets merged on master it's automatically published.
