### ISSUE TITLE
Update Eclipse Plugin

### ISSUE THREAD

**Issue by nathanila** [pmd/pmd#1177]
**Affects PMD Version:** 

6.4.0

**Rule:**

Not applicable

**Description:**

I run PMD in Eclipse for analyzing Java code.  The Eclipse plugin is on version 5.8.0 but PMD is on version 6.4.0.  Please either keep the Eclipse plugin up to date with the latest version of PMD or make it possible for the Eclipse plugin to point to a different version of PMD.

**Code Sample demonstrating the issue:**

Not applicable

**Running PMD through:**

Eclipse

**Comment by adangel** [comment]
I'm closing this issue in favor of the pmd/pmd-eclipse-plugin#50 since this is a eclipse plugin issue.

By the way, the latest eclipse plugin version  uses PMD 6.2.0: https://github.com/pmd/pmd-eclipse-plugin/releases/tag/4.0.16.v20180412-0833
