### ISSUE TITLE
[core] "Unsupported build listener" in gradle build

### ISSUE THREAD

**Issue by mmoehring** [pmd/pmd#1178]
**Affects PMD Version:** 
6.40

**Description:**
Since the switch to 6.40 we are getting build warnings from PMD

    Unsupported build listener: class org.gradle.api.internal.project.ant.AntLoggingAdapter
    Unsupported build listener: class org.apache.tools.ant.loader.AntClassLoader5

from https://github.com/pmd/pmd/commit/a4e4acb4d9e3e404d76be2fe8eda80db4cb3d160.
Is there any way to suppress them?

**Running PMD through:** Gradle 3.5.1

**Comment by AdamCarroll** [comment]
This also affects PMD v6.5.0 when running with Gradle v4.8.1 (the latest versions in both cases at the time of writing this).

**Comment by jsotuyod** [comment]
I'll change this log to debug, and add a warn only when no matching listeners are found for 6.6.0.

**Comment by AdamCarroll** [comment]
Great stuff.  Thanks @jsotuyod
