### ISSUE TITLE
[java] A checker that for unnecessary @SuppressWarnings("PMD.*")

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#1188]
This is a feature request.

I have a bunch of `@SuppressWarnings("PMD.*")` suppressions (some of them because of PMD bugs) and with every new release I have to check if they are needed or not any more. Such a check would be nice.

**Comment by jsotuyod** [comment]
@boris-petrov thanks for the suggestions. This is a duplicate of #648, I'll close this to keep tracking it there.
