### ISSUE TITLE
[java] New default NcssCount method report level is drastically reduced from values of deprecated NcssMethodCount and NcssTypeCount

### ISSUE THREAD

**Issue by paulberg** [pmd/pmd#1200]
**Affects PMD Version:** 
6.4.0

**Rule:**
NcssCount

**Description:**
The older NcssMethodCount rule flagged on 100 line methods or above. The new rule flags on 12 lines or above. This is a huge drop in the reporting threshold and seems suspiciously low. Likewise, the class level rule dropped from a default of 1500 to 250. I'm thinking these defaults may have erroneously been set to levels intended for cyclomatic complexity rather than statement count.

**Comment by oowekyala** [comment]
I think you're right it's a mistake. I don't remember how I came up with those values but they're indeed very low. Especially since the maximum allowed value for the class level is 1000 now... I'll change that, it will be part of 6.5.0.
