### ISSUE TITLE
[core] Error in sed expression on line 82 of run.sh while detecting installed version of Java

### ISSUE THREAD

**Issue by noahsussman** [pmd/pmd#1225]
[core]

**Affects PMD Version:** 6.5.0, 6.6.0

**Description:** When invoking `run.sh` I receive the error `/usr/local/Cellar/pmd/6.5.0/libexec/bin/run.sh: line 82: [: : integer expression expected`

I believe the direct cause is that the `$java_ver` variable is not properly set, on line 79 of `run.sh`

Replacing line 79 with `java_var=100` fixes the error message.

I encountered this with 6.5.0 installed via Homebrew, and also with 6.6.0 which I built using Maven.

This is the output produced by `java -version` on my machine. I am using the Java installed by Homebrew.

```
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

**Comment by kenji21** [comment]
Got the same issue (using cpd objc/swift, pmd 6.5.0 installed via homebrew), and macOS's `sed` doesn't like the `/i`, minimal reproduction:

````
echo "11-ea" | sed -n -e 's/-ea/.0.0/i'
sed: 1: "s/-ea/.0.0/i
": bad flag in substitute command: 'i'
````

I think `/i` can be removed:

````
echo 'java version "11-ea"' | sed -n -e 's/-ea/.0.0/'  -e 's/^.* version "\(.*\)\.\(.*\)\..*".*$/\1\2/p'
110

echo 'java version "1.8.0_121"' | sed -n -e 's/-ea/.0.0/'  -e 's/^.* version "\(.*\)\.\(.*\)\..*".*$/\1\2/p'
18
````

Tested on:

````
sw_vers -productVersion
10.13.6
````

**Comment by adangel** [comment]
Thanks for pointing out the problem with the flag "i". According to the docs at https://www.gnu.org/software/sed/manual/sed.txt , this is a GNU-extension - MacOSX is some version of BSD...

>
> 'I'
> 'i'
>     The 'I' modifier to regular-expression matching is a GNU extension
>     which makes 'sed' match REGEXP in a case-insensitive manner.

I've changed the script, so that it works with sed, that has been shipped with FreeBSD 6 a couple of years ago...
