### ISSUE TITLE
[java] UnnecessaryCastRule is incomplete

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1228]
**Rule:** see https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/migrating/UnnecessaryCastRule.java

**Description:**

This is a Java rule, that is not referenced in any ruleset. We should either complete this rule or delete it.

Proposed ruleset: codestyle

**Comment by oowekyala** [comment]
See #3218
