### ISSUE TITLE
[apex] Can't run PMD Apex code check using Ant. NoClassDefFoundError.

### ISSUE THREAD

**Issue by Rest0** [pmd/pmd#1230]
PMD 6.5.0

Need help with connecting PMD to Ant through Ivy. When I download the full package from https://pmd.github.io and just run it using Ant target everything works fine. But I don't want to add the PMD folder to the repo. So, I tried to add an Ivy dependency to the build. With JS everything works fine, but when adding an Apex dependency an error is thrown:

```build.xml:216: java.lang.NoClassDefFoundError: apex/jorje/semantic/ast/AstNode```

**Ant's Build.xml**

    <target name="init">
        <taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask" 
        classpathref="pmd.classpath"/>
    </target>

    <path id="pmd.classpath">
        <fileset dir="${outputdir}/lib/">
            <include name="*.jar"/>
        </fileset>
    </path>

    <target name="pmd" depends="init">
        <pmd shortFilenames="true">
            <ruleset>pmdRulesets/jsCustomRuleset.xml</ruleset>
            <formatter type="text" toFile="whaaaaaaat.txt" toConsole="true"/>
            <fileset dir="src">
            </fileset>
        </pmd>
    </target>

**Ivy's xml**

    <dependencies>
        <dependency org="com.aquivalabs.force.ant" name="antforce" rev="0.10" conf="tasks->default">
            <exclude name="ant" />
            <exclude name="ant-launcher" />
        </dependency>

        <dependency org="net.sourceforge.pmd" name="pmd-core" rev="6.5.0">
            <artifact name="pmd-core" type="jar" />
            <exclude name="pmd-core-6.5.0.pom" />
        </dependency>
        <dependency org="net.sourceforge.pmd" name="pmd-apex" rev="6.5.0">
            <artifact name="pmd-apex" type="jar" />
        </dependency>

        <dependency org="net.sourceforge.pmd" name="pmd-javascript" rev="6.5.0">
            <artifact name="pmd-javascript" type="jar" />
        </dependency>

    </dependencies>

**Running PMD through:** *[Ant]*

**Comment by jsotuyod** [comment]
I've very limited experience with Ivy, but make sure to include transitive dependencies, in particular `pmd-apex-jorje-6.5.0-lib.jar` (notice the `lib` classifier).

My first guess is that you are missing this.

**Comment by Rest0** [comment]
Well, probably that's because there is a POM file that is being downloaded, not a JAR. And seems like Ivy and Ant are unable to work with it. Or I didn't get something right.

**Comment by adangel** [comment]
Maybe you need to use this additionally:

```xml
    <dependency org="net.sourceforge.pmd" name="pmd-apex-jorje" rev="6.5.0" m:classifier="lib" />
```
(from http://czetsuya-tech.blogspot.com/2011/09/how-to-use-mclassifier-in-apache-ivy.html)

But maybe Ivy loads all the dependency transitively, if you don't specify an artifact for pmd-apex?

```xml
 <dependency org="net.sourceforge.pmd" name="pmd-apex" rev="6.5.0"/>
```

**Comment by Rest0** [comment]
Yes, this one
```<dependency org="net.sourceforge.pmd" name="pmd-apex" rev="6.5.0"/>```
also downloads *-jorje.pom .
The problem is probably because Ant or Ivy can't work with .pom files.
