### ISSUE TITLE
[java] Detector for large numbers not separated by _

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#1232]
Java allows numbers like `1000000` to be written like `1_000_000` which is much more readable. A detector that warns about numbers that have more than 3 digits not separated by `_` would be nice.

**Comment by jsotuyod** [comment]
@boris-petrov this should be very straight forward. Anyone wanting to learn how to write a rule should [look me up on gitter](https://gitter.im/pmd/pmd) for some pointers.

**Comment by rajeshggwp** [comment]
I'm interested in working on this!
