### ISSUE TITLE
[javascript] Use of let results in an Empty Statement in the AST

### ISSUE THREAD

**Issue by justgrumpy** [pmd/pmd#1235]
I am attempting to write an xpath rule for JavaScript, but have noticed using let (https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Statements/let) in my JavaScript results in an Empty Statement in the AST. If let is used in the initializer of a for loop, the entire block shows as an Empty Statement in the AST, which can hide problematic code.

**Comment by hudec117** [comment]
I am facing this issue too. Any possible update on this?
