### ISSUE TITLE
[core] Abstract XPath rulechain conversion using our own XPath parser

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1243]
Fact: Saxon’s API is very impractical, not made for expression transformation or even inspection at all. Given how deep we’d have to delve to get anything working, it’s likely that version updates would break everything anyway.

We could maintain our own XPath parser. This would abstract us from Saxon/Jaxen and individual versions thereof, and allow us to identify more optimisation opportunities. Given an AST, we can perform optimising transformations, and identify rulechain visits, then dump it to an XPath expression string and let Saxon parse it to its own representation. This parser could also be used in the designer, as suggested in #1192

Interesting things that could be done with that: 
  * Prune alternation branches that are conditioned by a rule property. E.g: `//N[$reportNs=true()] | //M[$reportMs=true()]`.  The value of the property never changes at run time, which Saxon can’t know (we use a dynamic context). But if e.g. `$reportMs` is set to false, then the M branch can be safely discarded, and only one rulechain visit would be added.
  * Identify more rulechain conversion opportunities (eg `//A/(B | C)/X` -> `//A/B/X | //A/C/X`, which is currently ignored by Jaxen IIRC)
  * Identify PMD function calls, to determine framework dependencies of the rule automatically (refs #437)
  * Add our own compatibility layer to port old Jaxen rules to Saxon, for example to address #1244
  * Identify deprecated/ inexistent attribute usage statically, before rule execution, instead of inspecting attributes at runtime 
  * Identify and report inexistent node names

Things to care about:
* Avoid doing that analysis several times for the same query. Currently, preliminary transformations are done during rule initialisation, which means they're done k times if we have k threads (right?).

**Comment by oowekyala** [comment]
As explained on #2523, this is probably overkill. We may unearth the idea later

**Comment by adangel** [comment]
Moving the comment from #2523 to here:

>
> Rulechain: Transforming XPath expressions to use the rulechain with Saxon
> 
> There's a prototype XPath parser in [this branch](https://github.com/oowekyala/pmd/tree/xpath-parser)
> *   Includes a complete JavaCC parser for XPath 3.1
> *   Includes a prototype optimiser that, for now, is able to inline the values of properties to allow Saxon's AOT optimizer to prune some branches
> *   Rulechain conversion is still TODO
> *   Open question: the set of XPath expressions that are valid PMD rules is a subset of all XPath expressions. 
>     *   The main requirement is that the expression evaluate to a sequence of nodes, and not e.g. of numbers.
>     *   The set of expressions that can be converted to the rulechain is even stricter
>     *   So, should we try to enforce that the expression ends up in one of those sets?
>
> :x: I'd say, we don't need it, since we have now rulechain support for XPath. But it has some > interesting ideas, like support for XPath 3.1 as a PMD language...
