### ISSUE TITLE
[apex] Double-counting generated getters and setters

### ISSUE THREAD

**Issue by aheber** [pmd/pmd#1245]
**Affects PMD Version:**  6.4.0

**Rule:** category/apex/design.xml/ExcessivePublicCount

**Description:** PMD double-counting {get;set;} attributes. I expect this is because the AST creates two public methods from the single public attribute. I would like to see this error reduced when it is only the generated methods. You do have the ability to specify full methods with this syntax and that might still be a concern that needs to be resolved.

**Code Sample demonstrating the issue:**
Easiest if you configure the rule to throw and error when there are two or more public methods or attributes. You'll see that this rule
RULE
```
<rule 
    name="ExcessivePublicCount"
    ref="category/apex/design.xml/ExcessivePublicCount"
    message="This class has too many public methods and attributes">
  <properties>
    <property name="minimum" value="2"/>
  </properties>
</rule>
```
Example Apex Class which only has a single public attribute but the automatic generation spools out into two public methods.
```
public Example {
    public String example {get;set;}
}
```

**Running PMD through:** CLI

**Comment by rsoesemann** [comment]
I strongly disagree. It's always 2 public methods no matter if they are empty, complex or abbreviated:

`public String example {get;set;} `

or

`public String example {get { // complex code }; set { // complex code };}`

or

```
private String example;

public String getExample() { 
..
}

public void setExample(String value) {
...
}
```

**Comment by aheber** [comment]
@rsoesemann, if you are stating that the behavior is always the same today I completely agree.

I'm suggesting that the resolution I would like to see would be that if the public attribute is only using the implicit get/set then it should only count as a single public element rather than two. 

Speaking from a place of complexity to maintain or mental burden in understanding the class an empty or implicit get/set would not add any significant complexity when interacting with the class via code or during maintenance which as I understand it would meet the intentions of the rule.

As it stands today I have to disable this rule on reasonably concise classes, if I have a limit of 25 public attributes or methods I actually only get a maximum of 12 public attributes if I implement the {get;set;} syntax. Increasing the rule limit isn't a viable option because there are other cases like public methods that are able to maximize the limits correctly.

I hope I'm making my request clear. The rule is behaving exactly to specification but when "tagging" a public attribute with the implicit {get;set;} syntax I am frustrated that my single public attribute consumes two "slots."

**Comment by aheber** [comment]
Thank you for the feedback, my thinking was that the spirit of the rule was violated but it appears not.

Closing.
