### ISSUE TITLE
[java] NcssCount default methodReportLevel ignored?

### ISSUE THREAD

**Issue by TrackerSB** [pmd/pmd#1247]
Affects PMD Version: 6.4.0
Running PMD through: Maven
maven-pmd-Plugin: 3.10.0

Rule: NcssCount

Description: When not specifying the methodReportLevel explicitely it seems it is not defaulting to 60 ([https://pmd.github.io/pmd-6.5.0/pmd_rules_java_design.html#ncsscount](https://pmd.github.io/pmd-6.5.0/pmd_rules_java_design.html#ncsscount)).

Code Sample demonstrating the issue:
The following class is analysed:
```java
public class NcssCountSmall {
    public static void main(String[] args) {
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
        System.out.println("line");
    }
}
```
This method is listed as a violation "The method 'main(String)' has a NCSS line count of 22.".
But when specifying the methodReportLevel explicetely like:
```xml
<rule ref="category/java/design.xml/NcssCount">
    <properties>
        <property name="methodReportLevel" value="30" />
    </properties>
</rule>
```
Then it is not listed as a violation.
Shortening this method line by line reveals (when *not* specifying methodReportLevel explicitely) that this method is not listed as violation only if its ncss count is less than 12.

Is this intended behaviour?

**Comment by oowekyala** [comment]
@TrackerSB The report level in 6.5.0 is 60, in 6.4.0 (the version you're using) it [was still 12](https://pmd.github.io/pmd-6.4.0/pmd_rules_java_design.html#ncsscount) (-> you're looking at the doc of another version). The report level was propped up after #1200
