### ISSUE TITLE
[java] Validation Fails for http://pmd.sourceforge.net/ruleset/2.0.0

### ISSUE THREAD

**Issue by chimpytt** [pmd/pmd#1249]
XML Header details from: [https://pmd.github.io/pmd-6.0.1/pmd_userdocs_understanding_rulesets.html](https://pmd.github.io/pmd-6.0.1/pmd_userdocs_understanding_rulesets.html) and the pre-fab rulesets that use the same header information result in the following error:

"White spaces are required between publicId and systemId" at line 1

**Comment by adangel** [comment]
Can you give a bit more details, about when you get this error? We didn't change the schema/samples for a while...

Is PMD raising this error or is it some other software?
What are the exact steps to reproduce the problem?

Maybe there is a problem with the redirect from http://pmd.sourceforge.net/ruleset_2_0_0.xsd to https://pmd.sourceforge.io/ruleset_2_0_0.xsd ?

**Comment by chimpytt** [comment]
Changing the URL at xmlns from "http" to "https" resolves the error. My setup and the steps that produced the original error are below.

IDE: Eclipse Neon.2 (4.6.2)
Plug-in: eclipse-pmd 1.12

New install of the plug-in and steps to reproduce were:
1. Create XML file in project
2. Copy/Paste XML header information into file
3. Save file (error produced)

**Comment by Geoffrey555** [comment]
Output XML file is also not valid against schema in Eclipse.
File has been generated with maven-pmd-plugin 3.10.0 (see header below).
URL must be changed from "http" to "https" to resolves the error.

<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.4.0" timestamp="2018-07-31T16:07:59.403">

**Comment by Geoffrey555** [comment]
`<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd"
    version="6.4.0" timestamp="2018-07-31T16:07:59.403">`

**Comment by jsotuyod** [comment]
For reference, there was a bug in Eclipse regarding this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=474741

It was fixed, but some users report it coming back. The proposed solution is:

> The problem is gone after cleaning cache entries in org.eclipse.wst.internet.cache folder and restarting Eclipse.

**Comment by adangel** [comment]
Similar issue with the produced PMD reports and schema "report_2_0_0.xsd":
https://github.com/pmd/pmd/blob/a46331264651423e8a11c748561a5704eca5524b/pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java#L175

**Comment by botolairputih** [comment]
> Changing the URL at xmlns from "http" to "https" resolves the error. My setup and the steps that produced the original error are below.
> 
> IDE: Eclipse Neon.2 (4.6.2)
> Plug-in: eclipse-pmd 1.12
> 
> New install of the plug-in and steps to reproduce were:
> 
> 1. Create XML file in project
> 2. Copy/Paste XML header information into file
> 3. Save file (error produced)

1. Tq sir, its working on me. I change from http to be https.
2. use jdk1.8.0_171  +  eclipse Oxygen.3a Release (4.7.3a)
