### ISSUE TITLE
[core] No supported build listeners found with Gradle

### ISSUE THREAD

**Issue by john3300** [pmd/pmd#1288]
**Affects PMD Version:** 
6.6.0

**Description:**
Using Gradle I get the following log messages with every `pmdMain` execution:
```
Could not determine ant log level, no supported build listeners found. Log level is set to FINEST
```
I don't know if this is just a configuration issue with my Gradle setup or what?  No custom logging configuration has been done in Gradle.  Specifying a Gradle logging level (`--debug`) has no effect.

I was previously getting the error from #1178 but it has been replaced by this with the move to 6.6.0.

Is this something I need to configure in Gradle or is this an issue with PMD?

**Running PMD through:**
Gradle 4.9

**Comment by adangel** [comment]
Hi @john3300 , do you have a small test project with gradle, so that we can reproduce the problem? Thanks!

**Comment by adangel** [comment]
It seems, the default ant logger is deliberately removed and replaced by gradle's AntLoggingAdapter: https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultAntBuilderFactory.java#L41

**Comment by adangel** [comment]
The logger is actually configured here: https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/antbuilder/DefaultIsolatedAntBuilder.java#L190
