### ISSUE TITLE
[java] RedundantFieldInitializer - NumberFormatException with Long

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1298]
**Affects PMD Version:** 6.7.0-SNAPSHOT (and earlier)

**Rule:** java-performance/RedundantFieldInitializer

**Description:** The rule fails to parse `0xffffffffffffffffL` with a NumberFormatException.

**Code Sample demonstrating the issue:**

```
public class RedundantFieldInitializerTest {
    private long hexLongMinusOne = 0xffffffffffffffffL;
}
```

**Running PMD through:** any

Thanks to @djydewang for finding this bug!

**Comment by jsotuyod** [comment]
The regression tester has already paid itself off so many times in just a couple of weeks... I'm so glad @djydewang stood up to the challenge
