### ISSUE TITLE
[core] PMD stops processing file completely, if one rule in a rule chain fails

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1300]
**Affects PMD Version:** 6.7.0-SNAPSHOT (probably earlier)

**Rule:** any rule, that uses rule chain

**Description:** If during the rule chain execution an exception occurs (processing error of a specific rule), then all remaining rules in the rule chain for this file are skipped. This leads to not detecting violations, when one rule fails. This leads to false-negatives in the PMD report.

**Running PMD through:** any

Thanks to @djydewang for finding this bug.

**Comment by jsotuyod** [comment]
Nice catch!
