### ISSUE TITLE
[java] Can't find resource 'category/java/security.xml' for rule 'null'.

### ISSUE THREAD

**Issue by mmoehring** [pmd/pmd#1313]
**Affects PMD Version:** 6.60

**Description:**
When using  a custom ruleset which references the builtin rulesets with Java 10 and Gradle 4.9, the build fails when PMD encounters the first reference to a builtin ruleset. (security.xml in this case).

The error message is

    Can't find resource 'category/java/security.xml' for rule 'null'.  Make sure the resource is a valid file or URL and is on the CLASSPATH. Here's the current classpath: /Users/mmoehring/.gradle/wrapper/dists/gradle-4.9-all/491wbe0x5d54n9cojs2p0zv90/gradle-4.9/lib/gradle-launcher-4.9.jar

Stacktrace: [stacktrace.txt](https://github.com/pmd/pmd/files/2306295/stacktrace.txt)

**Running PMD through:** *Gradle 4.9*

**Comment by jsotuyod** [comment]
@mmoehring interesting... could you provide a sample ruleset? This seems to be a misconfiguration problem.

**Comment by jsotuyod** [comment]
If it works with 3.5.1, it would seem gradle 4.9 is not really using pmd 6.6.0 (the security ruleset was introduced in 6.4.0 if I recall correctly).

How are you configuring pmd in gradle?

**Comment by mmoehring** [comment]
in config-version.gradle:

    ext {
        dependency_management_config = {
            dependencies {
                dependency "net.sourceforge.pmd:pmd-java:6.6.0"
            }
        }
    }


in config-pmd.gradle:

    ext {
        pmd_main_config = {
            ignoreFailures false
            ruleSetFiles = files("config/global/pmd/config-pmd-main.xml")
            ruleSets = []
        }

        pmd_test_config = {
            ignoreFailures false
            ruleSetFiles = files("config/global/pmd/config-pmd-test.xml")
            ruleSets = []
        }

        pmd_report_config = {
            reports {
                html.enabled true
                xml.enabled false
            }
        }
    }


in build.gradle:

    buildscript {
        apply from: "config/global/pmd/config-pmd.gradle"
        apply from: "config/global/version/config-version.gradle"
    }

    dependencyManagement dependency_management_config

    pmdMain pmd_main_config
    pmdTest pmd_test_config

    tasks.withType(Pmd, pmd_report_config)


Setting ``toolVersion = '6.6.0`` manually does not fix the error.

**Comment by mmoehring** [comment]
Your assumption was correct.

I cleared all cached and PMD 5.6.1 got downloaded, so the wrong version was used. And the toolVersion was not used because it has to be set on ``pmd`` and can not be configured on ``pmdMain`` or ``pmdTest``.
