### ISSUE TITLE
[ci] Coveralls hasn't built the project since June 25th

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1317]
https://coveralls.io/github/pmd/pmd

This is the last built commit: https://github.com/pmd/pmd/commit/21a5e4732247810682cfad44b131f434d813c621

The next commit to master is this one: https://github.com/pmd/pmd/commit/74cf7dc77b2c26e8a4bb0660690c3df871bead93

And right next PMD 6.5.0 was released. 

* Maybe 74cf7dc makes coveralls fail
* Maybe there was a coveralls update that made our configuration obsolete (https://github.com/asciidoctor/asciidoctor/wiki/Coveralls.io-configuration-for-maven-projects)

**Comment by adangel** [comment]
Indeed, we need to execute the "package" phase, so that the shade plugin is executed and the build works... (currently, only "test" is executed).

**Comment by adangel** [comment]
That's not all - coveralls plugin needs jaxb, which has been removed from JDK11 SE - since it is a EE feature (http://openjdk.java.net/jeps/320).
Hope, I get it working soon...

**Comment by adangel** [comment]
It's working again :tada:
