### ISSUE TITLE
[apex] Should VariableNamingConventions require properties to start with a lowercase letter?

### ISSUE THREAD

**Issue by jeffhube** [pmd/pmd#1321]
**Affects PMD Version:** 6.6.0

**Rule:** VariableNamingConventions

**Description:** Should VariableNamingConventions require properties to start with a lowercase letter? Currently, this is the case because VariableNamingConventions applies to ASTField nodes, and ASTProperty nodes contain ASTField nodes.

The only official documentation I have found so far contains properties that start with a lowercase letter AND properties that start with an uppercase letter: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_properties.htm

Some libraries, like [fflib-apex-mocks](https://github.com/financialforcedev/fflib-apex-mocks/blob/5137e26ed6567632368e4997739aef6749856a61/src/classes/fflib_ApexMocks.cls#L19) start properties with an uppercase letter, while others start them with a lowercase letter.

Should there be a PropertyNamingConventions, separate from VariableNamingConventions? Perhaps whether it enforces uppercase or lowercase could be controlled by a property?

**Comment by oowekyala** [comment]
I don't know about Apex conventions, but it's true the VariableNamingConventions rule is a bit slacky on configurability. Just FYI, the Java one was just the same, and has just been deprecated in favour of more configurable rules: [FieldNamingConventions](http://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java) and  [LocalVariableNamingConventions](http://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableNamingConventionsRule.java). These allow you to define a convention as a regex, that applies to members of a certain kind (eg one regex for final fields, one regex for static final fields, etc). If you want to revamp the Apex rules, these implementations could be used as a template. For example, the FieldNamingConventions for Apex could also target properties, if you think this is appropriate.

**Comment by adangel** [comment]
The suggestion is not to apply the Java naming conventions to Apex but rather change the rule to be more flexible. I assume, that there are as many naming conventions as dev teams, so the rule might not work for everybody. With the pattern exposed as rule properties, it can be adjusted to whatever naming convention should be used. Unless the goal is to enforce a single naming convention without exception...
