### ISSUE TITLE
[apex] SuppressWarnings annotation errors

### ISSUE THREAD

**Issue by simeonKondr** [pmd/pmd#1333]
[apex]

**Affects PMD Version: 6.6.0** 

**Rule: all rules**

**Description: when I'm trying to use @SuppressWarnings('PMD'), Idea shows me warnings, and also when I'm trying to use quick format for this file it does not work**

**Code Sample demonstrating the issue:**
![screenshot from 2018-09-05 13-46-29](https://user-images.githubusercontent.com/42644177/45088736-9741ce00-b112-11e8-9a8d-b66fa05d5de9.png)
![123](https://user-images.githubusercontent.com/42644177/45088738-9741ce00-b112-11e8-882c-0a44be388ced.png)
![screenshot from 2018-09-05 13-49-40](https://user-images.githubusercontent.com/42644177/45088739-9741ce00-b112-11e8-8cda-7fa9f58fc565.png)

```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@simeonKondr these are issues with the intellij plugin youbare using to integrate PMD, and not with PMD itself.

Those plugins are not maintained by the PMD team.

I suggest you reach out to the team behind the plugin you are currently using to get these sorted out.
