### ISSUE TITLE
[java] Update CommentDefaultAccessModifierRule to extend AbstractIgnoredAnnotationRule

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1343]
CommentDefaultAccessModifierRule currently ignores nodes annotated with `@VisibleForTesting`, but does so in a very ad-hoc (and undocumented) way.

We should rework it to extend AbstractIgnoredAnnotationRule instead which will:
 - make it customizable
 - document the behavior in the properties

It would be a nice time to revamp the description to mention this exception to the rule.

**Comment by CrazyUnderdog** [comment]
Hi,
is this issue still opened?

**Comment by adangel** [comment]
Yes, this task still needs to be worked on...
