### ISSUE TITLE
[website] 404 error on getting started link

### ISSUE THREAD

**Issue by roipoussiere** [pmd/pmd#1347]
On the [website](https://pmd.github.io/), there is a *Getting Started* link, just under the *Quickstart* section, which redirect to [a 404 page](https://pmd.sourceforge.io/pmd-6.7.0/pmd_userdocs_getting_started.html).

**Comment by jsotuyod** [comment]
@roipoussiere thanks for pointing this out.

Indeed, the link should direct you to https://pmd.github.io/pmd-6.7.0/pmd_userdocs_installation.html

**Comment by adangel** [comment]
The code, that needs to be changed, lives here:
https://github.com/pmd/pmd.github.io/blob/master/_includes/quickstart.html
