### ISSUE TITLE
[java] EmptyMethodInAbstractClassShouldBeAbstract false-positive

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#1355]
PMD version 6.7.0.

```java
public abstract class A implements B {
	protected C.D getSomething(@SuppressWarnings("unused") E e) {
		return null;
	}

	...
}
```

This gives an `EmptyMethodInAbstractClassShouldBeAbstract` warning which is wrong.

**Comment by adangel** [comment]
The reason why this method raises the warning is in the description of the rule [EmptyMethodInAbstractClassShouldBeAbstract](https://pmd.github.io/pmd-6.7.0/pmd_rules_java_codestyle.html#emptymethodinabstractclassshouldbeabstract):

> Empty or auto-generated methods in an abstract class should be tagged as abstract.

`return null;` looks like auto-generated.

**Comment by boris-petrov** [comment]
Well... that's my real implementation and what I actually want. It's not autogenerated. :) Perhaps you could check for an autogenerated comment instead? Or you think this is fine and rather I should just suppress the warning?

**Comment by jolkdarr** [comment]
Hi

Another option is to return an optional instance:
```java
public abstract class A implements B {
	protected Optional<C.D> getSomething(@SuppressWarnings(“unused”) E e) {
		return Optional.empty();
	}

	...
}
```

**Comment by jsotuyod** [comment]
As there is no way to detect wether the method was autogenerated or intentionally written to return false, i'm closing this.
It should simply be suppressed or the rule removed from the ruleset in use.

**Comment by cowwoc** [comment]
@jsotuyod Given the lack of customization of this rule, and the vulnerability to false positives, I suggest either removing it completely or at least lowering the priority (currently it's "high").
