### ISSUE TITLE
[doc] How to configure "-cache <path>"

### ISSUE THREAD

**Issue by xyf0921** [pmd/pmd#1394]
**Affects PMD Version:** 6.8.0

**Rule:**

**Description:**

I want to use the incremental analysis of the PMD. I looked up the document and it says use -cache <path> to specify a location for the analysis cache file to use.But when I use the '-cache' argument within CLI, I just can't set the right parameter. It seems like I have trouble in generating the cache file at the first running , I do it like "-cache /path" which '/path' is the directory where I want to store the cache file. But I got the Error says"Could not load analysis cache from file. /***/*** (Is a directory)" . Then I set the path as an empty file like '.../cache' , and I got "Cache file a is malformed, will not be used for current analysis" . It seems like I can't generate the cache file at the first time . This may be an simple question but I am new for PMD and I didn't find the right way to do this on Internet. So I would be appreciated if you can help me with this.
Thanks a lot.

**Code Sample demonstrating the issue:**

```

```

**Running PMD through:** *[CLI]*

**Comment by jsotuyod** [comment]
@xyf0921 the `-cache` param, as you figured out, should point to a file, not a directory. If the file doesn't exist, it should create it just fine. If the file exists however, even if empty, it will attempt to load it, triggering the malformed error you saw; but it should rewrite it at the end of analysis, so following executions should use it without the message.

The way I see it:
1. we should improve the docs and error messages to make it clear you should provide a path to a file.
2. we should not say an empty file is malformed, but treat it as non-existing

On your end, could you please confirm that the cache has been created when a file was provided, and that following executions can use it?

**Comment by xyf0921** [comment]
Hi @adangel , I just tested the second case . It logs "Analysis cache invalidated, rulesets changed." and "Analysis cache invalidated, execution classpath changed." . But the cache file can be created after analysis.

**Comment by adangel** [comment]
Thanks for checking.

I guess, we should log out instead of "Analysis cache invalided..." just something like "Creating new analysis cache file..." (and do this only once, not for both rulesets and classpath changes).

And update the documentation to clearly state, that this is a file, that and when it is being created, when it is being invalidated (malformed, ruleset and/or classpath changes).

**Comment by xyf0921** [comment]
That's great! Thanks. @adangel
