### ISSUE TITLE
[Apex] PMD 6.8 exceptions processing ruleSet - generates no results

### ISSUE THREAD

**Issue by JeffMTI** [pmd/pmd#1397]
Using my ruleset from PMD 6.7 (which processes successfully), PMD 6.8 reports many exceptions

[PMD_68_CLI_errors.txt](https://github.com/pmd/pmd/files/2487478/PMD_68_CLI_errors.txt)

**Affects PMD Version:**  6.8 (Release)

**Rule:**
Multiple

**Description:**
The attached log shows the java exceptions caused when running my ruleset with PMD 6.8.  This ruleset runs successfully on PMD 6.7, 6.6, 6.5, 6.4.  Tested by changing the path to PMD in the CLI command.

**Code Sample demonstrating the issue:**

The following file is my ruleset (ext changed to txt from xml)
[apex-all_xml.txt](https://github.com/pmd/pmd/files/2487499/apex-all_xml.txt)

```

```

**Running PMD through:** *[CLI]*

Ubuntu 18.04.1
Java 1.8.0_171
JRE  1.8.0_171-b11

**Comment by adangel** [comment]
Thanks for reporting. This looks like a duplication of #1396 , therefore I'm closing this one.
