### ISSUE TITLE
[jsp] JspTokenManager has a problem about jsp scriptlet

### ISSUE THREAD

**Issue by duanyanan** [pmd/pmd#1402]
Affects PMD Version: 6.7.0 

Rule: None

Description:  I use pmd-jsp.jar to tokenize the jsp source file, and I want to extract jspscriptlet from the file, but the bound about "%>" has some problems. 

Code Sample demonstrating the issue:

    //just get the token list
    String filepath = "C:\\test.jsp";
    File f = new File(filepath);
    InputStreamReader isr = new InputStreamReader(new FileInputStream(f));
    JspTokenManager jspTokenManager = new JspTokenManager(isr);
    List<Token> tokenList = new ArrayList<Token>();
    Token token = (Token)jspTokenManager.getNextToken();
    tokenList.add(token);
    while (!token.image.isEmpty()){
        token = (Token)jspTokenManager.getNextToken();
        tokenList.add(token);
    }

Following is a part of source code:

    <%
    String nodeContent = "<% %>";
    %>
    <%
    <![cdata[
    String nodeContent = "<% %>";
    ]]>
    %>

And the token list is below:

    "<%", "\nString nodeContent = \"<%lalal" ,"%>", "lalala\";%>\n"
    "<%", "\n<![cdata[\nString nodeContent = \"<%", "%>", "\";\n]]>\n%>"

So  the bound about "%>" has some problems.

Running PMD through: pmd-jsp-6.7.0.jar & pmd-core-6.7.0.jar

**Comment by adangel** [comment]
Thanks for reporting this. It's definitely a bug in the parser/grammar.
I had a short look into the grammar, and it seems, that we would need an additional state for entering the string... currently, we consider anything except "%>" as part of the scriptlet but any "%>" is interpreted as the end of the scriptlet (regardless, whether it is in quotes or not).

**Comment by duanyanan** [comment]
Though the problem with string "<% %>" has been solved, the tag "<jsp:scriptlet> </jsp:scriptlet> “ still can't correctly deal the string. Because of this, JspParser also has the same problem. Please check :）

**Comment by adangel** [comment]
Can you please open a new issue for this? Thanks!

**Comment by duanyanan** [comment]
https://github.com/pmd/pmd/issues/1421  Here is the new issue. : )
