### ISSUE TITLE
[apex] Rule class not found: ExcessiveClassLengthRule

### ISSUE THREAD

**Issue by Puneet1726** [pmd/pmd#1416]
[Apex]

**Affects PMD Version:** pmd-bin-6.7.0

**Rule:** net.sourceforge.pmd.lang.apex.rule.complexity.ExcessiveClassLengthRule

**Description:** Oct 29, 2018 6:15:01 PM net.sourceforge.pmd.rules.RuleFactory buildRule
SEVERE: Error instantiating a rule
java.lang.ClassNotFoundException: net.sourceforge.pmd.lang.apex.rule.complexity.ExcessiveClassLengthRule

**Code Sample demonstrating the issue:**

```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]* CLI

 

Oct 29, 2018 6:15:01 PM net.sourceforge.pmd.rules.RuleFactory buildRule
SEVERE: Error instantiating a rule
java.lang.ClassNotFoundException: net.sourceforge.pmd.lang.apex.rule.complexity.ExcessiveClassLengthRule

**Comment by Puneet1726** [comment]
I am running analysis on Apex code and i am getting rule instantiating issue.
Please help me on how to run PMD on Apex code.

Followed this link: https://www.jitendrazaa.com/blog/salesforce/automated-code-review-for-apex-in-salesforce-static-code-analysis-video/

**Comment by adangel** [comment]
Hi @Puneet1726 ,
The rule "ExcessiveClassLengthRule" has been moved to a different package. It seems, that the blog post is using a old PMD 5 version - with PMD 6, we introduced categories.
But it any case, one should not reference the full classname of the rule, but just a rule reference, e.g.

```xml
<rule ref="category/apex/design.xml/ExcessiveClassLength" />
```

So, you'll need to update your ruleset. Refer to the rules documented here: https://pmd.github.io/pmd-6.9.0/pmd_rules_apex.html
If you go the details of a rule, e.g. [ExcessiveClassLength](https://pmd.github.io/pmd-6.9.0/pmd_rules_apex_design.html#excessiveclasslength) you'll see the section "Use this rule by referencing it:".

You can find more info about writing your own ruleset here: https://pmd.github.io/pmd-6.9.0/pmd_userdocs_making_rulesets.html

If you run into further problems, please post your ruleset here.

**Comment by Puneet1726** [comment]
I have given my like below, let me know if i need to change anything.

<?xml version="1.0"?>
<ruleset name="Apex Rules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

	<rule ref="category/apex/design.xml/ExcessiveClassLength" />
	 <description>
      Excessive class file lengths are usually indications that the class may be burdened with excessive responsibilities that could be provided by external classes or functions. In breaking these methods apart the code becomes more managable and ripe for reuse.
      </description>
        <priority>3</priority> 
      <example>
		<![CDATA[ 
public class Foo { public void bar(Integer x, Integer y, Integer z) { if (x>y) {
						if (y>z) {
							if (z==x) {
								// !! too deep
							}
						}
					}
				}
			}
		]]>
      </example>
    </rule>
	
	<rule name="NcssMethodCount" message="This rule uses the NCSS (Non-Commenting Source Statements) algorithm to determine the number of lines of code for a given method. NCSS ignores comments, and counts actual statements. Using this algorithm, lines of code that are split are counted as one." class="net.sourceforge.pmd.lang.apex.rule.complexity.NcssMethodCountRule">
      <description>
      This rule uses the NCSS (Non-Commenting Source Statements) algorithm to determine the number of lines of code for a given method. NCSS ignores comments, and counts actual statements. Using this algorithm, lines of code that are split are counted as one.
      </description>
        <priority>3</priority> 
      <example>
		<![CDATA[ 
public class Foo extends Bar 
{ 
//this method only has 1 NCSS lines 
public Integer methd() { 
super.methd(); 
return 1; 
} } 
]]>
      </example>
    </rule> 
</ruleset>

**Comment by Puneet1726** [comment]
<?xml version="1.0"?>
<ruleset name="Apex Rules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

	<rule ref="category/apex/design.xml/ExcessiveClassLength" />
	 <description>
      Excessive class file lengths are usually indications that the class may be burdened with excessive responsibilities that could be provided by external classes or functions. In breaking these methods apart the code becomes more managable and ripe for reuse.
      </description>
        <priority>3</priority> 
      <example>
		<![CDATA[ 
public class Foo { public void bar(Integer x, Integer y, Integer z) { if (x>y) {
						if (y>z) {
							if (z==x) {
								// !! too deep
							}
						}
					}
				}
			}
		]]>
      </example>
    </rule>
</ruleset>

**Comment by adangel** [comment]
Here is an example ruleset, which enabled the two rules "ExcessiveClassLength" and "NcssMethodCount". It has an example to set the properties to further customize the rules (although the set values are actually the default ones):

```xml
<?xml version="1.0"?>
<ruleset name="Apex Rules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <rule ref="category/apex/design.xml/ExcessiveClassLength">
        <properties>
            <property name="minimum" value="1000" />
        </properties>
    </rule>
    <rule ref="category/apex/design.xml/NcssMethodCount">
        <properties>
            <property name="minimum" value="40" />
        </properties>
    </rule>
</ruleset>
```

**Comment by Puneet1726** [comment]
Thanks so much. Its working fine
