### ISSUE TITLE
[core] RulesetFactoryCompatibility stores the whole ruleset file in memory as a string

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1451]
See here:

https://github.com/pmd/pmd/blob/0c1afc426debff979b25219dbc8f4e07c76645b5/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactoryCompatibility.java#L108-L116

`applyAllFilters` performs a bunch of regex replacements on the entire String, which creates many copies of it. We could do better by only filtering the `ref` attributes when parsing a rule reference node, this just seems very inefficient. 

@jsotuyod This may offset your performance comparison of DOM and SAX for #724

**Comment by adangel** [comment]
Fixed with PMD 7 via #2969 .
