### ISSUE TITLE
False positive for "Use equals() to compare object references."

### ISSUE THREAD

**Issue by benmccann** [pmd/pmd#1456]
**Affects PMD Version:** 6.4.0

**Rule:** Use equals() to compare object references.

**Description:** This rule is alerting on an enum creating a false positive

**Code Sample demonstrating the issue:**

https://github.com/jtablesaw/tablesaw/blob/509dd6ea481f0c60c4e8117b637755e107776808/jsplot/src/main/java/tech/tablesaw/plotly/components/Marker.java#L138

**Running PMD through:** Codacy

Select the rule under pattern on https://app.codacy.com/app/jtablesaw/tablesaw/issues to see it being triggered

**Comment by jsotuyod** [comment]
@benmccann thanks for the report.

The rule actually checks for enums to avoid such issues:

https://github.com/pmd/pmd/blob/331e29e034399edd81584bddd63669c1e31b1b5a/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CompareObjectsWithEqualsRule.java#L87-L90

However, this check requires type resolution to be enabled (compiling and passing the .class files along the dependencies to PMD). Codacy is a very limited tool, as it has no real understanding of how to build your project, and therefore doesn't pass any of such info to PMD.

I see you project uses Maven. If you were to use Maven's PMD plugin instead (probably bound to your CI workflow), doing this is actually enabled by default, and will just work when doing `mvn verify` or similar goals.

Similarly, on Gradle, PMD will automatically work with type resolution.

This is a problem with your integration, and not with PMD itself. Therefore, I'm closing this.

I'd advise you to either push for Codacy to improve it's support; or simply drop it in favor of better integrations.
