### ISSUE TITLE
[core] Failed build on Windows with source zip archive

### ISSUE THREAD

**Issue by jmetertea** [pmd/pmd#1462]
I'm using Windows and I download PMD source as a zip
I'm working with JDK 11
I failed mvnw.cmd clean verify with the following irrelevant test:

`[ERROR] Failures:[ERROR]
YAHTMLRendererTest.testReportMultipleViolations:109 File
YAHTMLSampleClass1.html is different expected:<<html>[
    <head>
        <title>PMD - YAHTMLSampleClass1</title>
    </head>
    <body>
        <h2>Class View</h2>
        <h3 align="center">Class: YAHTMLSampleClass1</h3>
        <table border="" align="center" cellspacing="0" cellpadding="3">
        <tr><th>Method</th><th>Violation</th></tr>
        <tr><td></td><td><table
border="0"><tr><td><b>Rule:</b></td><td>Foo</td></tr><tr><td><b>Description:</b></td><td>blah</td></tr><tr><td><b>Line:</b></td><td>1
and 1</td></tr></table></td></tr>
        <tr><td></td><td><table
border="0"><tr><td><b>Rule:</b></td><td>Foo</td></tr><tr><td><b>Description:</b></td><td>blah</td></tr><tr><td><b>Line:</b></td><td>1
and 1</td></tr></table></td></tr>
        </table>
    </body></html>]> but was:<<html>[
    <head>
        <title>PMD - YAHTMLSampleClass1</title>
    </head>
    <body>
        <h2>Class View</h2>
        <h3 align="center">Class: YAHTMLSampleClass1</h3>
        <table border="" align="center" cellspacing="0" cellpadding="3">
        <tr><th>Method</th><th>Violation</th></tr>
        <tr><td></td><td><table
border="0"><tr><td><b>Rule:</b></td><td>Foo</td></tr><tr><td><b>Description:</b></td><td>blah</td></tr><tr><td><b>Line:</b></td><td>1
and 1</td></tr></table></td></tr>
        <tr><td></td><td><table
border="0"><tr><td><b>Rule:</b></td><td>Foo</td></tr><tr><td><b>Description:</b></td><td>blah</td></tr><tr><td><b>Line:</b></td><td>1
and 1</td></tr></table></td></tr>
        </table>
    </body>]/html>>`

**Affects PMD Version:** 
latest
**Rule:**
NA
**Description:**
I'm using Windows and I download source as a zip
**Code Sample demonstrating the issue:**
NA

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
CLI

**Comment by adangel** [comment]
Cross-referencing from https://sourceforge.net/p/pmd/discussion/188194/thread/6af1be1134/

> Is there a workaround?

The workaround is definitely using `git` to checkout the source code. There we have the setting, that such (test) resources like `YAHTMLSampleClass1.html` are checked out under Windows with "\r\n" line ending and under unix-like operating systems with "\n" line endings. This is configured in our [.gitattributes](https://github.com/pmd/pmd/blob/master/.gitattributes) file.
Then it should work.

This raises the question: What use is the source zip file, if it only works under unix like systems?
We could get rid of it.
Or we could add more code in our tests to accommodate the differences in line endings...

**Comment by adangel** [comment]
Oh, one question though: From where did you download the source zip?

Is it this one? https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.9.0/pmd-src-6.9.0.zip (under releases)
Or this one? https://github.com/pmd/pmd/archive/pmd_releases/6.9.0.zip (also under releases but created by github)

**Comment by jmetertea** [comment]
I download from github -> Clone or download -> Download ZIP
Link is https://github.com/pmd/pmd/archive/master.zip
