### ISSUE TITLE
[core] Stylesheet pmd-report.xslt fails to display filepath if 'java' in path

### ISSUE THREAD

**Issue by dellgreen** [pmd/pmd#1465]
**Affects PMD Version:** 6.9.0

**Description:** bug in xslt stylesheet that truncate file path if java in file path like src/main/java/... because forward slashes are being replaced with dots followed by substring function the matches on '.java'. It would simpler to keep the slashes which fixes the problem

**Code Sample demonstrating the issue:**

```
    Line 56:  <H3><xsl:value-of disable-output-escaping="yes" select="substring-before(translate(@name,'/','.'),'.java')"/></H3>

```

**Proposed solution:**

```
    Line 56:  <H3><xsl:value-of disable-output-escaping="yes" select="substring-before(@name,'.java')"/></H3>

```

**Running PMD through:** *https://www.freeformatter.com/xsl-transformer.html, gradle, java*

**Comment by jsotuyod** [comment]
@dellgreen thanks for the report.

The suggestion goes in the right direction, but would end up showing slashes instead of a FQCN.

I guess the best alternative would be to use:

```xml
<H3><xsl:value-of disable-output-escaping="yes" select="translate(substring-before(@name,'.java'),'/','.')"/></H3>
```

**Comment by shahamish150294** [comment]
I would like to take this issue. Is this still available?

**Comment by jsotuyod** [comment]
@shahamish150294 it is! Please feel free to do so!

**Comment by dellgreen** [comment]
I think I would of been running it via the gradle plugin

**Comment by shahamish150294** [comment]
@dellgreen do you remember whether you received this issue on a unix-like OS?

I am currently working on windows. Probably, that's why I was not able to reproduce it. As I changed the `translate(@name,'/','.')` to `translate(@name,'\','.')` in the pmd-report.xslt. I saw it getting truncated in xslt report.

**Comment by dellgreen** [comment]
Yes, it would of been Linux, Ubuntu 16.04
