### ISSUE TITLE
[java] Run PMD Analysis after Eclipse Build

### ISSUE THREAD

**Issue by nathanila** [pmd/pmd#1479]
**Affects PMD Version:** 

eclipse-pmd Core/Java: 1.15.0.201810271110

**Rule:**

N/A

**Description:**

Currently, the Eclipse plugin runs PMD analysis as part of the build.  This means the build step takes much longer.  Instead, PMD should record what files were built and then after the build step completes run a non-blocking PMD step.

**Code Sample demonstrating the issue:**

N/A

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Eclipse

**Comment by jsotuyod** [comment]
Yes, we could have the plugin use incremental analysis....

**Comment by adangel** [comment]
@nathanila Please note, you seem to be using https://github.com/acanda/eclipse-pmd - please create an issue there. For our own plugin, I've created a separate issue: pmd/pmd-eclipse-plugin#72.
Therefore I'm closing this.
