### ISSUE TITLE
[core] Make the metrics cache local to a RuleContext

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1497]
Using a JVM-static cache for metrics is a pain because of the clean-up logic required eg between tests. The implicit caching also gets in the way of the designer, since metrics are not recomputed when eg the code of a method is modified, unless its name changes. 

One solution would be to make the metrics cache local to the RuleContext, i.e. local to a single analysis. We'd need to deprecate the static façades, e.g. JavaMetrics, and instead add methods on the RuleContext and AbstractRule to make use of it. 

 Overall I think using jvm static state should be gradually discouraged in PMD, bc they're more trouble than they're worth.

**Comment by adangel** [comment]
This has been fixed with #2241 (6.22.0)
