### ISSUE TITLE
[java] New Rule: UseDiamondOperator

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1517]
In pmd-build-tools, we have a rule, that searches for unnecessary generic arguments, e.g.

```java
List<String> myList = new ArrayList<String>();

//this can be written as
List<String> myList = newArrayList<>();
```

See: 
https://github.com/pmd/build-tools/blob/e2cda582cb5e685855ecce02fb4f941f6bb2a851/src/main/resources/net/sourceforge/pmd/pmd-dogfood-config.xml#L603-L627

Proposed category: codestyle

What needs to be done here:
* Move the rule into the codestyle category xml of java
* Add proper documentation/description and examples
* Move the rule tests (and maybe add some more)

**Comment by hemanshu070** [comment]
Hi @adangel  I did not understood the requirement. Can you please walk me through

**Comment by jsotuyod** [comment]
@hemanshu070 we have a internal rule to enforce the use of diamond operator ([here](https://github.com/pmd/build-tools/blob/e2cda582cb5e685855ecce02fb4f941f6bb2a851/src/main/resources/net/sourceforge/pmd/pmd-dogfood-config.xml#L603-L627))

We want to promote that from an internal rule to part of the standard PMD rulesets users can use.

To do so, we need to move that rule from the dogfooding ruleset into the main PMD codebase, along with it's tests; and improve the documentation for general usage.

**Comment by hemanshu070** [comment]
Understood the requirement. I don't know where the files to be changed are. and I don't know what is codestyle category xml of java.

**Comment by adangel** [comment]
Hi @hemanshu070 ,

the rules, that are shipped with PMD are organized into categories. Each category is represented by an own ruleset XML file. For java, these are under the path `pmd-java/src/main/resources/category/java/`, so e.g. the "Codestyle Category" can be found here: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/category/java/codestyle.xml

For the info, what is in a ruleset XML file is exactly, please check out https://pmd.github.io/pmd-6.10.0/pmd_userdocs_extending_writing_xpath_rules.html#creating-a-new-rule-definition - which explains it for a XPath-based rule.
More background info about testing: https://pmd.github.io/pmd-6.10.0/pmd_userdocs_extending_testing.html

Please also make sure, you have a working development environment setup first: https://github.com/pmd/pmd/wiki/Newcomers%27-Guide .

Feel free, to reach out to use via gitter: https://gitter.im/pmd/pmd
