### ISSUE TITLE
[java] UseUnderscoresInNumericLiterals false positive on floating point numbers

### ISSUE THREAD

**Issue by ylexus** [pmd/pmd#1527]
**Affects PMD Version:** 
6.10.0

**Rule:**
UseUnderscoresInNumericLiterals

**Description:**
Gets triggered on 36.363_636_363_636_37

**Code Sample demonstrating the issue:**
Just use 36.363_636_363_636_37 as a literal

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
IDEA plugin & maven

**Comment by jsotuyod** [comment]
@ylexus the rule is actually designed to enforce `36.36_363_636_363_637` (same as the integer part, group digits to the right, for consistency).

I'm unsure as to wether grouping to the left on decimals is better than the current approach, but if you feel it is, please make your case / reference any sources.

**Comment by ylexus** [comment]
1) To me it's common sense. You group the integer part in thousands and you group the decimal part in thousandths: 0.001 is one thousandth, 0.000_001 is 1 millionth etc. You cannot claim consistency between integer and decimal point here, they are the opposite!
2) https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID309 has an example showing "let justOverOneMillion = 1_000_000.000_000_1"
3) IntelliJ IDEA's intention action does group decimal part like I suggested (breaking the PMD rule)
4) in general, user may prefer grouping in any other way, so at least needs to be customisable

**Comment by nathanila** [comment]
This number `0.0000001` must be formatted like this `0.0_000_001` or `0.000_000_100` in order to resolve the rule violation.  The first format is terrible.  The second format adds a few unnecessary digits.  I would prefer `0.000_000_1` to resolve the rule violation.  This splits the decimal digits into millis, micros and nanos.
