### ISSUE TITLE
[java] Java 12 support

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1537]
Java 12 has entered Rampdown Phase, which means, the overall feature set is frozen and only bug fixing will occur.

Schedule: http://openjdk.java.net/projects/jdk/12/#Schedule
The planned general availability of Java 12 is 2019-03-19

Early Access builds for java 12 are available here: http://jdk.java.net/12/

There is one feature, that changes the language: [JEP 325: Switch Expressions (Preview)](http://openjdk.java.net/jeps/325). It is a preview language feature, which means, it might be removed again - but it will be there at least for java 12.

**The feature has 3 manifestations:**
* multiple case labels:
```java
        switch (day) {
            case MONDAY, FRIDAY, SUNDAY: System.out.println("  6"); break;
            case TUESDAY               : System.out.println("  7"); break;
            case THURSDAY, SATURDAY    : System.out.println("  8"); break;
            case WEDNESDAY             : System.out.println("  9"); break;
        }
```
* switch rules:
```java
        switch (day) {
            case MONDAY, FRIDAY, SUNDAY -> System.out.println("  6");
            case TUESDAY                -> System.out.println("  7");
            case THURSDAY, SATURDAY     -> System.out.println("  8");
            case WEDNESDAY              -> System.out.println("  9");
        }
```
* switch expressions:
```java
        int numLetters = switch (day) {
            case MONDAY, FRIDAY, SUNDAY -> 6;
            case TUESDAY                -> 7;
            case THURSDAY, SATURDAY     -> 8;
            case WEDNESDAY              -> 9;
            default                     -> {
                int k = day * 2;
                int result = f(k);
                break result;
            }
        };
```

**Tasks:**
* Enhance grammar according to the language specification, see [JDK-8207241](https://bugs.openjdk.java.net/browse/JDK-8207241) and http://cr.openjdk.java.net/~gbierman/switch-expressions.html
* Support class loading of java12 (ASM update)
* Support type resolution for switch expressions
* Maybe add a new rule. There is at least one rule, we could create: Suggesting to use a switch expression instead of a traditional switch statement when "each arm either assigns to a common target variable or returns a value" (see example in http://openjdk.java.net/jeps/325).

**Sample Code:**
[SwitchExpressions.java.txt](https://github.com/pmd/pmd/files/2702206/SwitchExpressions.java.txt)

**Comment by jsotuyod** [comment]
> * Maybe add a new rule. There is at least one rule, we could create: Suggesting to use a switch expression instead of a traditional switch statement when "each arm either assigns to a common target variable or returns a value" (see example in http://openjdk.java.net/jeps/325).

The switch expression support in Java 12 is going to be a [preview language feature](http://openjdk.java.net/jeps/12).

> A preview language or VM feature is a new feature of the Java SE Platform that is fully specified, fully implemented, and yet impermanent.

So even 'though we should support it in the grammar, I wouldn't invest time in adding such a rule until the feature is promoted, hopefully in the roadmap to Java 13.
