### ISSUE TITLE
[java] Instantiation rules cannot tell apart java.lang primitive wrappers and same named classes

### ISSUE THREAD

**Issue by aaime** [pmd/pmd#1548]
**Affects PMD Version:** Using the maven pmd plugin, https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-pmd-plugin/3.11.0 which in turn depends on PMD 6.8

**Rule:** IntegerInstantiation, LongInstantiation, ByteInstantiation, ShortInstantiation, believe BooleanInstantiation too

**Description:**

When a local inner class named Integer, Long, Byte, Short or Boolean, placed in a package other than java.lang gets instantiated PMD reports instantiation related warnings, suggesting to use valueOf instead. I'm guessing this happens because there is no import for those classes, making PMD believe that they are from java.lang, whilst the import is not needed because the instantiation happens inside the same named class.

**Code Sample demonstrating the issue:**

Check this class, having various inner classes named after data types, where instantiations are reported by the checkers:
https://github.com/geotools/geotools/blob/master/modules/library/xml/src/main/java/org/geotools/xml/xsi/XSISimpleTypes.java#L322

**Running PMD through:** *Maven*

**Comment by jsotuyod** [comment]
PMD 7.0.0 no longer fails on this scenario.
