### ISSUE TITLE
Any justification for CallSuperInConstructor?

### ISSUE THREAD

**Issue by golszewski86** [pmd/pmd#1564]
The description of _CallSuperInConstructor_ says:
> It is a good practice to call super() in a constructor. 

Is it? Any justification for that? For me, it's just the opposite. It's not only an unnecessary line of code, but also suggests I don't believe that Java works and calls the default constructor for me.

**Comment by jsotuyod** [comment]
@golszewski86 this rule is part of the `codestyle` category. As such, it has no other reason than stylistic consistency.

IDEs tend to allow to customize this too. For instance, Eclipse even adds the call to `super()` by default:

![image](https://user-images.githubusercontent.com/802626/50829492-70dfa980-1323-11e9-8633-511c87809a5d.png?v=4&s=200)

**Comment by Fernal73** [comment]
It might be a good idea to retire this rule.
This clashes with Checkstyle's [AvoidNoArgumentSuperConstructorCall](https://checkstyle.sourceforge.io/config_coding.html#AvoidNoArgumentSuperConstructorCall).
I will not be using it anymore.
