### ISSUE TITLE
[cpd][core] Add displaying total number of tokens per file

### ISSUE THREAD

**Issue by baziorek** [pmd/pmd#1569]
**Affects PMD Version:** 
6.10.0
**Rule:**
cpd for any language
**Description:**
CPD is good tool to detect plagiarism in code between students. In this situation it would be really useful if the tool would also display total number of tockens in file.

That option is rather not useful for all CPD users so additional command line option would be good solution for universities' teachers and rest of programmers.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
CLI

**Comment by adangel** [comment]
This as actually been implemented via #4021 for PMD 6.48.0.
It has been additionally extended via #4095 in PMD 6.49.0.
