### ISSUE TITLE
[apex] allow test method names to contain underscores

### ISSUE THREAD

**Issue by SalesforceBobLightning** [pmd/pmd#1573]
Firstly, PMD is great - thank you!

I have a feature request for the Salesforce Apex language, regarding the warning "Method names should not contain underscores"

I would be great if this warning did not appear if a method is marked as 'testMethod' or '@istest'

Because using underscores in unit test method names is a common practice to make them readable.

Would this be possible?

**Comment by tomdaly** [comment]
Hi @jsotuyod, I'm interested in contributing to this change :)
Is it fair to say that it would make sense for a test name to include underscores but not begin or end with an underscore?

Thanks

**Comment by jsotuyod** [comment]
@tomdaly definitely! I looking forward for your PR!
