### ISSUE TITLE
can't find JavaParser.java in source code

### ISSUE THREAD

**Issue by hongpuwu** [pmd/pmd#1575]
can't find JavaParser.java in source code

**Comment by jsotuyod** [comment]
@hongpuwu the `JavaParser` is autogenerated by JavaCC during source-generation step of the build.

You can find some config on that parser in the grammar file itself:

https://github.com/pmd/pmd/blob/master/pmd-java/etc/grammar/Java.jjt#L207

Once you run the `./mvwn generate-sources` step the class will be available under pmd-java/target/generated-sources/javacc

**Comment by hongpuwu** [comment]
@jsotuyod 3Q，but i build pmd fail, any idea? 
![image](https://user-images.githubusercontent.com/19198552/50969932-e2357d00-151a-11e9-861b-586b1e6af3b5.png)

**Comment by hongpuwu** [comment]
@jsotuyod thank you, but i build pmd fail, also generate-sources fail, any idea?
![image](https://user-images.githubusercontent.com/19198552/50969977-0ee99480-151b-11e9-9532-805f5cf6e5b3.png)

**Comment by jsotuyod** [comment]
@hongpuwu if you scroll up a little you will see the cause of the failure.

As it's the `maven-enforcer-plugin` I guess it's probably the version of Java you are using. PMD requires Java 10+ to build (only Java 7/8 to run)

**Comment by hongpuwu** [comment]
@jsotuyod it work, thank you so much
