### ISSUE TITLE
[java] Disable SystemPrintln

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1602]
**Affects PMD Version:** 

2.1+

**Rule:**

SystemPrintln

**Description:**

PMD claims that System.out.print is often used improperly, for logging. In fact, System.out.print is convenient for REPL's, and should probably not trigger a warning by default.

As a workaround, I am configuring this in my rulesets.xml:

```xml
<rule ref="category/java/bestpractices.xml">
    <exclude name="SystemPrintln" />
</rule>
```

**Comment by jsotuyod** [comment]
As per #1600, you are misunderstanding categories altogether.

The rule exists for every project that is not actually writing a CLI program that wants to enforce the usage of a logging library, it not included by default in any non-deprecated shipped ruleset, and is not to be removed from PMD itself as it's a valuable tool for plenty of projects.

**Comment by Fernal73** [comment]
This rule could do with added granularity as to whether to include only System.err calls or both. It could also be modified to allow exclusion of these calls in any main() body.

https://stackoverflow.com/a/2750562/3924108
