### ISSUE TITLE
[java] Deprecate AvoidFinalLocalVariable

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1612]
**Affects PMD Version:** 

4.1+

**Rule:**

AvoidFinalLocalVariable

**Description:**

This rule is suspect in general, but it really encourages bad code in unit tests. It is okay, even recommended, to use `final` local variables. Not everything needs to be the `public class Animal` we were taught in school. As a workaround, I am disabling this rule in my rulesets.xml:

```xml
<rule ref="category/java/codestyle.xml">
    <exclude name="AvoidFinalLocalVariable" />
</rule>
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by oowekyala** [comment]
Thanks for your insight. That rule has already been proposed for deprecation, as per the comments on #1482. I'll keep this issue open to track that.
