### ISSUE TITLE
[java] How to resolve AvoidInstantiatingObjectsInLoops with Date?

### ISSUE THREAD

**Issue by mcandre** [pmd/pmd#1615]
**Affects PMD Version:** 

2.2+

**Rule:**

AvoidInstantiatingObjectsInLoops

**Description:**

This rule is generally a good practice. However, when a process needs to query the current date, I'm not sure of a way to accomplish this with the Java standard library without using the `new Date()` constructor. Could someone point out a way to do this?

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by jsotuyod** [comment]
@mcandre depends on what your application is trying to achieve and the level of detail required.

If running through a loop, and only interested in date (ie: 'YYYY-MM-DD'), you can probably get one instance outside the loop and use that each time (it's unlikely to change unless your loop runs for a REALLY long time).

If you need a timestamp, (ie: `new Date().getTime()`), you can avoid the instantiation completely using `System.currentTimeMillis()`.

It may also be possible you simply need a new instance and should suppress the warning.

Without further insight into your application, it's hard to tell.

**Comment by mcandre** [comment]
> If running through a loop, and only interested in date (ie: 'YYYY-MM-DD'), you can probably get one instance outside the loop and use that each time (it's unlikely to change unless your loop runs for a REALLY long time).

Nonstarter, hence the original post.

> System.currentTimeMillis()

That's not a bad idea, but unfortunately many API's expect a `Date` object, and so one must be constructed.

In any case, many applications do require the construction of objects within loops, and modern JVM features a garbage collector specifically optimized for this case.

Is it the worst programming style? Sometimes. Is it the best programming style? Usually not. In any case, this check should probably make an exception for the `Date` class, since that API does not offer a better way to approach this concern.
