### ISSUE TITLE
[java] UselessAssignment is not references by any ruleset

### ISSUE THREAD

**Issue by krichter722** [pmd/pmd#1629]
**Affects PMD Version:** ./.

**Rule:** UselessAssignment

**Description:**
https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/UselessAssignment.java is not available in any ruleset and has a comment
```
//FUTURE This is not referenced by any RuleSet?
```
which indicates that this has been forgotten. If it's no longer use it should be marked deprecated or removed all together (and its removal should be noted somewhere since users will search for the functionality it provides).

**Code Sample demonstrating the issue:** ./.

**Running PMD through:** ./.

**Comment by oowekyala** [comment]
UselessAssignment is a cool idea for a rule. The fact that it uses the outdated data flow framework probably makes that implementation quite brittle though. I think it would be nice to rehabilitate it if it can be done.

There are also some other unused rules, which can IMO all be scrapped:
* StringConcatenationRule: doesn't do anything
https://github.com/pmd/pmd/blob/72900e25f6b4f788b7c8c87cf05f4cf4189ff089/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/StringConcatenationRule.java#L11-L12
* SymbolTableTestRule: this apparently just a debug thing that was never cleaned up
https://github.com/pmd/pmd/blob/72900e25f6b4f788b7c8c87cf05f4cf4189ff089/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/SymbolTableTestRule.java#L12-L13
* PositionalIteratorRule: I tried running it but it didn't find any violations. I can't guess what it's supposed to do.
https://github.com/pmd/pmd/blob/72900e25f6b4f788b7c8c87cf05f4cf4189ff089/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/PositionalIteratorRule.java#L15
* JavadocRule: plain empty
https://github.com/pmd/pmd/blob/72900e25f6b4f788b7c8c87cf05f4cf4189ff089/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/JavadocRule.java#L7-L9
* CodeInCommentsRule: empty as well
https://github.com/pmd/pmd/blob/72900e25f6b4f788b7c8c87cf05f4cf4189ff089/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CodeInCommentsRule.java#L11-L16

**Comment by oowekyala** [comment]
Fixed by #2022
