### ISSUE TITLE
[apex,vf] Remove CodeClimate dependency

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#1648]
Applies to all rules related to Apex and Visualforce. Back then when I ported PDM to Salesforce CodeClimate was the only platform to integrate with. To make PMD work with them we had to add custom renderers and properties.

Neighter I nor somebody else is using this anymore and it clutters the rule and ruleset code. So I'd suggest we remove this again. 

I can provide a PR for that. But I want to hear your opinion on this @jsotuyod @adangel

**Comment by adangel** [comment]
Since this is removing a feature, it won't be backwards compatible. We can only remove this with the next major release, which is 7.0.0.

While maybe the code climate renderer is not demanded, there is a request about adding a generic json renderer, see #1286

**Comment by rsoesemann** [comment]
Hi Andreas, I didn't touch the CodeClimate renderer as it was added by another person and might be of use.
