### ISSUE TITLE
[java] BeanMembersShouldSerialize is extremely noisy

### ISSUE THREAD

**Issue by Vampire** [pmd/pmd#1668]
Rule doc: [BeanMembersShouldSerialize](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#beanmembersshouldserialize)

This is more of a question but could be seen as documentation bug.
How does the `BeanMembersShouldSerialize` rule classify a class as bean or used by a bean?
I have a class that will never be serialized ever or someone did something horribly wrong.
I see that for some cases it makes sense to mark members as `transient` even if they do not implement `Serializable` as other serialization mechanisms like Gson could also take that modifier into account.
But from the description I don't see when this rule applies to a class and when not and why it is applied to my class which is actually used by no other code as it is meant to be used by consumers of my library.

**Comment by jsotuyod** [comment]
@Vampire the rule has no criteria to determine which classes are intended as a bean and which are not; and defaults to treating all classes as beans.

After all, a Java Bean is just a standard class where:
 * All properties private (use getters/setters)
 * A public no-argument constructor
 * Implements Serializable

Any rule to enforce these can't rely on them being followed.

I agree the rule is probably too noisy… but the only way around I can think of, is requiring the user to configure a property with a set of packages where beans are to be found, and disable the rule as misconfigured if not present… I'm not thrilled by this alternative either, but maybe someone else has a better idea.

**Comment by Vampire** [comment]
If not, maybe at least the name should change. :-)
I think I just disable it here.

**Comment by wyldbill** [comment]
@jsotuyod - This:

- Implements Serializable

is where the hassle is. PMD seems to assume that classes are beans when they don't implement/aren't Serializable. BeanMembersShouldSerialize is triggered despite the fact that by (the supplied) definition, a class is not a bean.
Check it out:

    public class NotSerializable {
        private final int myValue;
        public NotSerializable(final int value) {
            myValue = value;
        }
    }
PMD will raise BeanMembersShouldSerialize on the _myValue_ field, despite the fact that the class is not Serializable. As far as being used by another bean, the failure should be in the composing bean for including a field of non-Serializable type. In this case, the composing bean should declare the offedning field **transient**

**Comment by wyldbill** [comment]
[Seems that I'm not alone here](http://www.adamkoch.com/2012/08/28/serialization-beans-and-pmd/), and that this is a long-standing issue with this rule.

**Comment by jsotuyod** [comment]
@wyldbill thanks for your comments.

Unfortunately, as already explained, looking for serializable classes is not a fix. Not all serializable classes are intended to be Java beans, and the same problem would arise with anyone using standard Java serialization and coming across these reports. We would be just shoving this under the carpet.

The only true fix I can think for this rule, as already stated is requiring the user to configure a property with a set of packages where beans are to be found, and disable the rule as misconfigured if not present.

Moreover, given the rule name, I would say the rule is actually incomplete, and if something is intended to be a bean, it should check for both, the existence of the no-arg constructor and the implementation of  `Serializable` (none of which are currently performed). This way, when I say "my beans are under this package" the rule can enforce those are actually proper Java beans without assuming I did right any particular requirement.

Help implementing this is always welcomed.

**Comment by CristianGM** [comment]
This rule is forcing me to stop using ErrorProne ruleset on all the company projects.
Every single warning I have it's a false positive, and I have hundreds, I would vote to at least remove it from ErrorProne as that's the Gradle plugin default ( I guess it's useful for someone so I don't say removing it )

**Comment by adangel** [comment]
@CristianGM It seems, that you don't use a custom ruleset.
Please refer to https://pmd.github.io/latest/pmd_userdocs_making_rulesets.html to customize, which rules you want to have executed and are useful for your project.
We definitely won't remove the rule from the error prone category, but I'd rather recommend, that you override the default gradle configuration to use your custom ruleset.
*Note:* Since gradle provides two ways for configuring rulesets, you need probably to remove the defaults via `ruleSets = []` and configure your custom ruleset via `ruleSetFiles = files("config/pmd/myRuleSet.xml")`.
Hope that helps.

**Comment by CristianGM** [comment]
I know how to use a custom ruleset but, don't you think that having a rule in the default ruleset that is known to give false positives is not the right thing to do?
IMHO for a rule to be a default it should be proven to be useful and correct.

**Comment by jsotuyod** [comment]
@CristianGM please notice, PMD has no such thing as a "default configuration", that is actually up to Gradle.

**Comment by CristianGM** [comment]
@jsotuyod true, Gradle defaults to ErrorProne and this rule is definitely ErrorProne, but the rule itself, not just what it checks for.

**Comment by Fernal73** [comment]
The only other option is to add a SuppressWarnings annotation for each class. Is it worth considering enabling the annotation at the package level?

**Comment by Fernal73** [comment]
https://github.com/pmd/pmd/issues/403#issuecomment-557942733

**Comment by christianhujer** [comment]
I agree that this rule is too noisy and should be fixed. If something is called `ErrorProne`, it should talk about errors, and not create so many false positives. Saying that people should use custom rulesets has a few issues. Without that, using PMD in Gradle would be as simple as just adding `id 'pmd'` to the `build.gradle` file. Which doesn't work because of `BeanMembersShouldSerialize` coming up with false positives almost every single time. And then people have to create a custom configuration. Which is bad because of at least three reasons:
* Some people will simple not spend the effort of creating a custom configuration. Instead they will simply not use PMD.
* Everyone who wants to use PMD and has problems with exactly this one rule (and that's _everyone!_) has to create their own configuration which will be identical with that created by everyone else. Which is very redundant.
* I'd like to avoid creating my own configuration because of the errors and maintenance efforts that come with it. What about new rules? Will my configuration benefit from them when I update PMD? Now I have to delve far deeper into the configuration magic of PMD than I should have to for just using this otherwise so wonderful tool.

**Comment by Fernal73** [comment]
@christianhujer How can this rule be improved?

**Comment by CristianGM** [comment]
> The only true fix I can think for this rule, as already stated is requiring the user to configure a property with a set of packages where beans are to be found, and disable the rule as misconfigured if not present.

https://github.com/pmd/pmd/issues/1668#issuecomment-542968545

It would mean if I don't configure the rule I'll be happy and just skip that annoying rule.
It's nearly as good as removing the rule for me, but you can keep the rule and anyone interested (if any) can configure it.

**Comment by Fernal73** [comment]
Checkstyle and Spotbugs allow files and classes to be
omitted/suppressed/excluded from specific checks via suppressions and
exclusions respectively.
I'm surprised that the idea hasn't been broached before.

**Comment by christianhujer** [comment]
I'm trying to come up with a Pull Request for this. It's the first time that I'm working on PMD. I assume that I have to do the following things:

1. Change `BeanMembersShouldSerialize.xml` to test for the desired behavior. This is mostly duplicating the test cases to have one with and one without `implements java.io.Serializable`, and expect the corresponding number of errors.
2. Change `BeanMembersShouldSerializeRule.visit(ASTClassOrInterfaceDeclaration node, Object data)` and add a check whether the `node` implements `java.io.Serializable`. I haven't worked with PMD's internals before. Here's what I came up with so far:

```
    private boolean isSerializable(ASTClassOrInterfaceDeclaration node) {
        List<ASTClassOrInterfaceType> superInterfacesTypeNodes = node.getSuperInterfacesTypeNodes();
        for (ASTClassOrInterfaceType superInterfacesTypeNode : superInterfacesTypeNodes) {
            if (superInterfacesTypeNode.getType().isAssignableFrom(java.io.Serializable.class)) {
                return true;
            }
        }
        return false;
    }
```

This works just fine. But I'm wondering, is there a better way to use the library of PMD to find out whether the declaration `implements java.io.Serializable`? (Not looking for a `Stream.filter() suggestion, AFAIK PMD must be runnable on Java 7, so `Stream.filter()` is out of the question. Looking for smarter PMD API usage.)

**Comment by oowekyala** [comment]
>  But I'm wondering, is there a better way to use the library of PMD to find out whether the declaration

```java
 private boolean isSerializable(ASTClassOrInterfaceDeclaration node) {
        return TypeHelper.isA(node, java.io.Serializable.class);
 }
```

This also accounts for whether the interface is inherited transitively from some superclass, and doesn't fail with an NPE if we couldn't resolve the type (in which case `node.getType()` returns null)

**Comment by christianhujer** [comment]
There's something very interesting. The function `isSerializable()` which I wrote passed my tests. The function `isSerializable()` implemented with `TypeHelper.isA(node, java.io.Serializable.class)` fails 7 of my tests with wrong results. I'll look into this in more detail tomorrow.

**Comment by oowekyala** [comment]
This is probably because the type of the example classes used in the tests are not on the classpath. We should improve this function to look into the ExtendsList and ImplementsList if the parameter is a type declaration.

**Comment by CristianGM** [comment]
@christianhujer could you try now that TypeHelper has been improved by @oowekyala ?

**Comment by marcindabrowski** [comment]
It is still very noisy :(.
