### ISSUE TITLE
[java] documentation of CommentDefaultAccessModifier is wrong

### ISSUE THREAD

**Issue by Vampire** [pmd/pmd#1674]
![grafik](https://user-images.githubusercontent.com/325196/53050542-d2a24000-3499-11e9-9660-0b0bb8dbd384.png)

should probably be `/* default */ or /* package */` instead.

**Comment by jsotuyod** [comment]
Thanks! The escaping during the doc site generation seems to be missing some scenarios

**Comment by itaigilo** [comment]
Took this as my first issue -
Fixed at #1737.
