### ISSUE TITLE
[core] CPD: Failure evaluating files with the same file name

### ISSUE THREAD

**Issue by AndreasTu** [pmd/pmd#1678]
[core]
**Affects PMD Version:** 6.11.0 
**Rule:** CPD

**Description:**
When analyzing a source project with CPD, which contains two different files of the same name in different folders CPD does evaluate both file. 
The results is non deterministic behavior and file system + OS dependent.

Two File with different content:
folderA/File.txt
folderB/File.txt

CPD will only evaluate one of the Files.
See class `net.sourceforge.pmd.cpd.CPD`
Method: [addAndThrowLexicalError](https://github.com/pmd/pmd/blob/c4ce925997917e741c9d53258c0090b1f8c327d8/pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java#L144)
The line 
    
     source.put(sourceCode.getFileName(), sourceCode);

will replace the first file silently and will only evaluate the last one.
If the file iteration order is non deterministic the output of CPD will be non deterministic.

The SkipDuplicates option does not help, because it takes the file size into account. 
See [line](https://github.com/pmd/pmd/blob/c4ce925997917e741c9d53258c0090b1f8c327d8/pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java#L86):
    
    String signature = file.getName() + '_' + file.length();)

**Running PMD through:** Gradle

**Comment by AndreasTu** [comment]
Sorry the cause with:

     source.put(sourceCode.getFileName(), sourceCode);

is wrong. Because `FileCodeLoader` will use the `file.getAbsolutePath()` as FileName.
But I still see non-deterministic behavior with duplicated file names.

**Comment by jsotuyod** [comment]
@AndreasTu this is interesting… starting from PMD 6.11.0, the files are ordered prior to analysis to actually tackle most inconsistencies (see #1584), but maybe we have a different scenario with equally named files.

**Comment by AndreasTu** [comment]
I have investigated the problem a bit further and it seams that the issue comes from the [gradle-cpd-plugin](https://github.com/aaschmid/gradle-cpd-plugin) which does not use the cpd API which sorts the Input-Files for cpd.
The sort of the input files by cpd after the Tokenizer (`TreeMap`) will not help because the `TokenEntry` will use unique IDs for the Tokens without the ordering. These IDs are later on used to calculate results and sort the reports etc., which lead to the non-deterministic behavior.

See [code](https://github.com/aaschmid/gradle-cpd-plugin/blob/4f0cda80e60f686612e482101652a3e3d2fa74ba/src/main/groovy/de/aaschmid/gradle/plugins/cpd/internal/CpdExecutor.groovy#L67) for the used cpd API. The method `add(File)` will not sort it.

I have created an internal patch of gradle-cpd-plugin and I will test it. 
I think this is not an issue of cpd rather then in gradle-cpd-plugin.

**Comment by jsotuyod** [comment]
@AndreasTu yeap, it looks that way… they are directly depending on PMD and using the API programmatically rather than using the CPD Ant task or similar.

For reference, [this plugin](https://github.com/Monits/static-code-analysis-plugin/blob/staging/src/main/groovy/com/monits/gradle/sca/task/CPDTask.groovy#L65) uses the CPD Ant task from the PMD version in use (rather than built-in to the plugin) and shouldn't be subject to this issue.

I'll wait for your confirmation before closing this issue nonetheless.

**Comment by AndreasTu** [comment]
@jsotuyod with the changes in the 
[gradle-cpd-plugin](https://github.com/aaschmid/gradle-cpd-plugin) the issue seems to be gone. 
So you can close the issue.
Sorry for the inconveniance and thank you for the fast replies.
