### ISSUE TITLE
[java] CommentRequired property names are inconsistent

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1683]
[CommentRequired](https://pmd.github.io/latest/pmd_rules_java_documentation.html#commentrequired) calls the class-level JavaDoc comment a "header comment". Usually, the header comment is a top-level comment before the package declaration (ie: license).

The behavior should be aligned with the property name, and a new property be added, so we can configure and check both for header comments and class comments.

**Comment by adangel** [comment]
I've decided not to add a header/package comment requirement property for the following reasons (see #2069):

> We might introduce a new property "packageCommentRequired" in order to check for formal 
> comments for packages. However, this is completely different:
>
> *   package javadoc comments are not in every file, but only in the file package-info.java
> *   if the file package-info.java doesn't exist, we won't analyze it, so we can't require this comment
> *   the only check we could do here is "Unwanted"
> *   So, I'm not sure, whether checking for package comments makes sense at all?

The rule is only about javadoc/formal comments. license comments should actually not be a javadoc comment.
