### ISSUE TITLE
[java] Properly whitelist serialPersistentFields

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#1684]
A number of rules currently understand that `serialVersionUID` should largely ignore several rules, as it doesn't follow all conventions (ie: it's not following [`FieldNamingConventions`](https://pmd.github.io/pmd-6.11.0/pmd_rules_java_codestyle.html#fieldnamingconventions)).

However, none of PMD rules have the same regard for `serialPersistentFields`.

I think we should look at all rules whitelisting `serialVersionUID` and check if the same should be applied to `serialPersistentFields`.

More info on `serialPersistentFields` is available at https://docs.oracle.com/javase/7/docs/platform/serialization/spec/serial-arch.html#6250

**Comment by marcelhaerle** [comment]
I'd like to 'grab' this issue.

I've found only two rules where `serialPersitentFields` should be whitelisted like `serialVersionUID`:
* FieldNamingConventions in codestyle rules
* CommentRequiredRule in documentation rules

Are there other rules/locations that should be considered?

**Comment by jsotuyod** [comment]
@marcelhaerle thanks for your interest! It's greatly appreciated. Those 2 rules seem ok, on a first quick review over existing rules, the only other rule I found should apply is `UnusedPrivateFieldRule`, but that one is already handling `serialPersitentFields` properly.
