### ISSUE TITLE
[java] Add rule to avoid unnecessary boxing of boolean with Boolean.valueOf and parseBoolean

### ISSUE THREAD

**Issue by krichter722** [pmd/pmd#1690]
**Affects PMD Version:** 6.11.0

**Rule:** either `BooleanInstantiation` or a new rule

**Description:**
`Boolean.valueOf` creates a `Boolean` whereas `Boolean.parseBoolean` creates a `boolean`. Using `valueOf` where a `boolean` is assigned and vice versa causes unnecessary (un)boxing.

**Code Sample demonstrating the issue:**

```
boolean a = Boolean.valueOf("true");
```

**Running PMD through:** Maven

**Comment by jsotuyod** [comment]
@krichter722 thanks for the suggestion. I think this deserves a new rule altogether. Avoiding boxing / unboxing of all primitives where avoidable seems desirable independently of the specific instantiation rules.

**Comment by oowekyala** [comment]
If I may chime in, I think a single rule for all types of unnecessary (un)boxing is better than one for each primitive type. I say this because we have BooleanInstantiation, ByteInstantiation, etc and IMO it's quite noisy

**Comment by jainrish** [comment]
@jsotuyod I want to work on this issue. Do you have any approach in mind? Should the rule cover all 8 primitive types?

**Comment by jsotuyod** [comment]
@jainrish thanks for stepping up!

Firstly, yes, the new rule should cover all 8 types:

Primitive | Boxed
-- | --
boolean | Boolean
byte | Byte
char | Character
float | Float
int | Integer
long | Long
short | Short
double | Double

As for the approach… I'm unsure. Using type resolution you can detect scenarios where automatic boxing / unboxing is occurring, but from there to actually detecting an unnecessary boxing / unboxing… I can only think of dealing with particular scenarios in a case-by-case approach:

1. assigning `Boolean.TRUE` or `Boolean.FALSE` to a primitive.
2. assigning the result from `valueOf()` to a primitive.
3. assigning the result from `parse*()` to a boxed type
4. assigning the result from `*Value()` to a boxed type (careful here with `Double d = intVal.doubleValue()` should probably not be flagged, as the alternative `Double d = Double.valueOf(intVal)` would still produce an auto boxing / unboxing)
5. assigning a `new` Boxed type to a primitive

Am I missing any scenario?

**Comment by jainrish** [comment]
@jsotuyod Scenarios like 
```
int var = new Integer(2);
```
These should also be flagged right?

**Comment by jsotuyod** [comment]
Yes, that corresponds to

> 5. assigning a `new` Boxed type to a primitive

**Comment by jainrish** [comment]
oh yeah, sorry I missed that. Should this rule come under bestpractices?

**Comment by jsotuyod** [comment]
This is covered in PMD 7.0.0's [`UnnecessaryBoxing`](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#unnecessaryboxing)
