### ISSUE TITLE
[java] Add rule to avoid declaration of throwing unchecked exception

### ISSUE THREAD

**Issue by krichter722** [pmd/pmd#1692]
**Affects PMD Version:** 6.11.0

**Rule:** ./.

**Description:**
Skimming through [the list of available rules for Java and their short descriptions](https://pmd.github.io/latest/pmd_rules_java.html) I don't see one matching the potentially unwanted declaration of `throws SomeUncheckedException` where `SomeUncheckedException` is a specific type extending `RuntimeException`.

This is not always what users want, but is recommended because it only adds overhead to have these declarations.

**Code Sample demonstrating the issue:**
```
public void someMethod throws IllegalArgumentException;
```
or
```
private String someOtherMethod(String someArgument) throws IllegalStateException {
    //some code eventually throwing IllegalStateException
}
```

**Running PMD through:** ./.

**Comment by jsotuyod** [comment]
@krichter722 thanks for the suggestion.

I'm unsure 'though how useful this rule would be to the larger developer community. If I understand correctly, you are basically attempting to forbid developers from manually throwing any runtime exceptions (library methods throwing them would be ok, such as `Objects.requireNonNull`).

I think `RuntimeException` have a well defined use-case, throwing under scenarios where there is nothing reasonable the program can do to handle the problem, and therefore forcing the caller to always catch it is useless, as more often than not, the catch would simply log / rethrow the exception. Under this perspective is that, for instance, Spring Framework decides to wrap `SQLException` in a runtime exception (if the database is unreachable, you program has probably little to do about it / if you have a SQL grammar issue, you should see it easily in development and not sporadically in production).

This therefore looks more like a project / organization specific rule. Either something in the lines of "we don't like them" or "feel people abuse them".

If it is the former, a custom rule in XPath should be easy and address the issue:

```
//ThrowStatement/Expression[typeIs('java.lang.RuntimeException')]
```

If the later, maybe there is potential to create a more useful rule… is there any scenario where we can *know*  a runtime exception is an abuse and shouldn't be used?

**Comment by oowekyala** [comment]
@jsotuyod I think he's talking about `throws` clauses of method signatures, eg `void foo(int i) throws IllegalArgumentException`. These are indeed unnecessary since Java doesn't even force callers to handle the exception. Documenting thrown exceptions in javadoc instead of a `throws` clause seems like a better policy, e.g. it's the stance taken by the standard library.

**Comment by jsotuyod** [comment]
@oowekyala oh! ok, that would make sense as a new rule. Definitely.

**Comment by krichter722** [comment]
And that's why there's an example code section in the issue template...

> I think he's talking about `throws` clauses of method signatures, eg `void foo(int i) throws IllegalArgumentException`. These are indeed unnecessary since Java doesn't even force callers to handle the exception. Documenting thrown exceptions in javadoc instead of a `throws` clause seems like a better policy, e.g. it's the stance taken by the standard library.

That's what I meant. Thanks for the clarification.

**Comment by jsotuyod** [comment]
Then this one is actually trivial for anyone wanting to submit a first PR to PMD

```xpath
//NameList/Name[typeIs('java.lang.RuntimeException')]
```
