### ISSUE TITLE
[kotlin] CPD: Lexical error in file when using Mockito.`when` or Hamcrest.`is`

### ISSUE THREAD

**Issue by MatFl** [pmd/pmd#1722]
**Affects PMD Version:** 6.11.0

**Description:** In Koltin when and is are reserved keywords, so when using Mockito or Hamcrest the usages have to be escaped with back ticks

```
import org.mockito.Mockito.`when`
or
import org.hamcrest.Matchers.`is`
assertThat(xyz, `is`(0))
```

**Running PMD through:** Gradle

**Stacktrace:**
> Caused by: net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file xyz.kt at line 21, column 30.  Encountered: "`" (96), after : ""
>         at net.sourceforge.pmd.lang.java.ast.JavaParserTokenManager.getNextToken(JavaParserTokenManager.java:2393)
>         at net.sourceforge.pmd.lang.java.JavaTokenManager.getNextToken(JavaTokenManager.java:25)
>         at net.sourceforge.pmd.cpd.token.JavaCCTokenFilter.getNextToken(JavaCCTokenFilter.java:38)
>         at net.sourceforge.pmd.cpd.JavaTokenizer.tokenize(JavaTokenizer.java:42)
>         at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:142)
>         at net.sourceforge.pmd.cpd.CPD.add(CPD.java:137)
>         at net.sourceforge.pmd.cpd.CPD.add(CPD.java:107)
>         at net.sourceforge.pmd.cpd.CPD$add.call(Unknown Source)
>         at de.aaschmid.gradle.plugins.cpd.internal.CpdExecutor.run(CpdExecutor.groovy:67)

**Comment by jsotuyod** [comment]
@MatFl thanks for the report! This is effectively a bug in the Kotlin grammar. Backticks are considered as identifiers, but seems to be neglected here…

We should probably just upgrade the grammar to the latest from https://github.com/antlr/grammars-v4/tree/master/kotlin-formal

**Comment by jsotuyod** [comment]
I can't reproduce this issue with the given snippet:

```kotlin
import org.mockito.Mockito.`when`
import org.hamcrest.Matchers.`is`

fun foo() {
  assertThat(0, `is`(0))
}
```

**Comment by MatFl** [comment]
This issue is still happening with 6.13.0 for me. This is for CPD, not PMD!

Very small example:
src/main/kotlin/samples/HelloWorld.kt:
```
package samples

fun main(args: Array<String>) {
    println("Hello, world!")
    `this is legal kotlin`()
}

fun `this is legal kotlin`(){
    println("Test")
}
```
build.gradle.kts:
```
import de.aaschmid.gradle.plugins.cpd.CpdExtension

plugins {
    application
    kotlin("jvm") version "1.3.20"
    id("de.aaschmid.cpd") version "1.2"
}

configure<CpdExtension> {
    toolVersion = "6.13.0"
}

application {
    mainClassName = "samples.HelloWorldKt"
}

dependencies {
    compile(kotlin("stdlib"))
}

repositories {
    jcenter()
}
```
Running `gradlew cpd` reproduces the error from above.

**Comment by maikelsteneker** [comment]
I can confirm that the reproduction from @MatFl above also triggers the error for me.

**Comment by maikelsteneker** [comment]
The problem doesn't lie in the tokenizer, since it can successfully tokenize this file. It turns out that this is due to the language being configured to Java instead of Kotlin. The problem is resolved by setting the language as follows in build.gradle.kts:
```
configure<CpdExtension> {
    toolVersion = "6.13.0"
    language = "kotlin"
}
```

**Comment by jsotuyod** [comment]
@maikelsteneker thanks, then I keep this closed.

**Comment by MatFl** [comment]
Oh, so for a mixed java and kotlin code base I would need two separate tasks? That's unfortunate...

**Comment by maikelsteneker** [comment]
@MatFl I'm afraid that's how CPD works at the moment. It's invoked on a set of source files for a single language. Since duplicates across languages cannot be recognized, this does make sense. Perhaps the gradle-cpd-plugin project (https://github.com/aaschmid/gradle-cpd-plugin) could be improved to correctly determine the language for these Kotlin files, which I believe would make it invoke CPD correctly.
