### ISSUE TITLE
[plsql] % not supported in "TestSearch%notfound"

### ISSUE THREAD

**Issue by lpeddy** [pmd/pmd#1733]
**Affects PMD Version:** 
pmd-bin-6.12.0
**Rule:**
TomKytesDespair
**Description:**
Parse Exception:

Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered " "%" "% "" at line 23, column 18.

**Code Sample demonstrating the issue:**

``` plsql
CREATE OR REPLACE PACKAGE lpe_test is

procedure testif;

end lpe_test;
/

CREATE OR REPLACE PACKAGE BODY lpe_test is


procedure testif
is
cursor TestSearch
is
select 1 from dual;

TestRow TestSearch%rowtype;

begin
    open TestSearch;
    fetch TestSearch into TestRow;

    if TestSearch%notfound then
        DBMS_OUTPUT.PUT_LINE('Not found');
    else
        DBMS_OUTPUT.PUT_LINE('Found');
    end if;
    close TestSearch;
end testif;

end lpe_test;
/
```

**Running PMD through:** *[ Ant or standalone with JDK 1.8]*
pmd-bin-6.12.0/bin/run.sh pmd -d /home/tstdba/dcs/jenkins/test_plsql_pmd_issue.sql -l plsql -R rulesets/plsql/TomKytesDespair.xml -f xml

**Comment by adangel** [comment]
This is about cursor attributes: https://docs.oracle.com/en/database/oracle/oracle-database/18/lnpls/named-cursor-attribute.html#GUID-CD8D8415-FF19-4D81-99BA-7825FD40CC96
