### ISSUE TITLE
Azure maven task is taking too long to download pmd

### ISSUE THREAD

**Issue by prabhushrikant** [pmd/pmd#1748]
My maven task "mvn clean install " in azure cloud gets stuck in pmd download step before it times out  
```Downloading from central: https://repo.maven.apache.org/maven2/net/sourceforge/pmd/pmd-core/6.4.0/pmd-core-6.4.0.pom```

Is this a know issue.

**Comment by jsotuyod** [comment]
@prabhushrikant no, this is the first time I hear something of the sort… Nonetheless, this is not an issue with PMD itself, but with the maven central repository at https://issues.sonatype.org/projects/MVNCENTRAL/summary

They will probably want to know if this only happens with this artifact or with all; and may ask you to do some network diagnostics.

In the meantime, you can use jCenter as an alternative download source. jCenter mirrors Maven Central: https://bintray.com/bintray/jcenter/net.sourceforge.pmd%3Apmd-core
