### ISSUE TITLE
[java] Error while processing class when super constructor is called from static inner class

### ISSUE THREAD

**Issue by nareshl119** [pmd/pmd#1780]
**Affects PMD Version:**  
6.13.0

**Rule:**
PMD Java custom rule

**Description:**
Getting "java.lang.ArrayIndexOutOfBoundsException: -1" processing errors if super class constructor is called from static inner class which extends inner class.
**new OuterClass().super();**

Attached complete stack trace for the same.

**Code Sample demonstrating the issue:**

package com.pmd.test;

public class OuterClass {
	public OuterClass() {
		System.out.println("Inner Class AdapterClass");
	}	
	public class InnerClass {		
		public InnerClass() {
			System.out.println("Inner Class Constructor");
		}		
	}	
	private static class StaticInnerClass extends InnerClass {		
		public StaticInnerClass() {
			new OuterClass().super();
			System.out.println("StaticInnerClass Constructor");
		}		
	}	
	public static void main(String args[]) {
		new OuterClass.StaticInnerClass(); 
	}
}

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Gradle 

[stacktrace.txt](https://github.com/pmd/pmd/files/3087674/stacktrace.txt)

**Comment by jsotuyod** [comment]
@nareshl119 thanks for the report! I've to admit I had no idea that cumbersome construction logic was even valid.

The exception is being thrown in the Symbol Table code, as NameFinder tries to resolve names. None of the nodes in `new OuterClass().super();` have a proper image, so no names are found and produce the error.

Probably, the sane thing would be to tackle this in 7.0.0, as the revised grammar should make this way easier than it currently is.

**Comment by nareshl119** [comment]
@jsotuyod thanks for the response. The above logic is valid and you can test and reproduce the error with the given class.

**Comment by jsotuyod** [comment]
This is no longer reproducible under PMD 7.0.0. The symbol table code was completely rewritten and the new implementation handles this properly.
