### ISSUE TITLE
[core] Ruleset Compatibility fails with excluding rules

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1794]
**Affects PMD Version:** 6.13.0

**Description:**

When a PMD5 ruleset is used, that excludes are rule, that has been both moved and renamed, then the ruleset can't be loaded anymore.

<details>
<summary>Stacktrace</summary>
<p>

```
java.lang.IllegalArgumentException: Unable to exclude rules [GuardLogStatement]; perhaps the rule name is mispelled?
at net.sourceforge.pmd.RuleSetFactory.parseRuleSetReferenceNode(RuleSetFactory.java:536)
at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:459)
at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:367)
at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:214)
at net.sourceforge.pmd.RuleSetFactory.createRuleSet(RuleSetFactory.java:209)
...
```

</p>
</details>

**Code Sample demonstrating the issue:**

```
<rule ref="rulesets/java/logging-java.xml">
    <exclude name="GuardLogStatementJavaUtil"/>
</rule>
```

The issue originated here: https://github.com/m2e-code-quality/m2e-code-quality/issues/213

**Comment by Fernal73** [comment]
Can you explain what the rule set compatibility option does for the CLI version? I tried using the option and the command fell over displaying the complete help for CLI.

Am I missing something or is it a neglected bug?

https://github.com/Fernal73/LearnJava/blob/master/pmd

**Comment by adangel** [comment]
Sorry, I don't understand your question. There is no rule set compatibility CLI option...

Ruleset compatibility is enabled by default and tries to do a best guess to fix the ruleset that is used. Often rulesets are not fully adjusted when one updates PMD and thus might reference rules, that have been moved/renamed/deleted. The ruleset compatibility tries to replay the changes happend in PMD onto the ruleset, so that the current PMD can actually use the ruleset.

Please describe the error you observe.

**Comment by Fernal73** [comment]
I added the option -norulesetcompatibility true to the PMD script right
after the -min true and it displays the PMD CLI help.

It's the same with -norulesetcompatibility false. The default as listed in
the CLI options is false.

https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#options

**Comment by adangel** [comment]
Please create a new issue and most important: please add the observed (actual) command output from the console and the expected output and also, what exactly you are trying to do. Thanks.

**Comment by Fernal73** [comment]
What I was trying to do? I was simply testing that option to see what it
does! I was surprised to see that it doesn't work.

**Comment by Fernal73** [comment]
Why don't you tell me if there are any options that ought to be omitted for
the above to work? Are there any options to be used in tandem? I don't want
to write up an issue for nothing.

**Comment by oowekyala** [comment]
@Fernal73 Either use just `-norulesetcompatibility` on your command line or omit it. By default it's enabled, the switch turns it off. There should be no default value in the doc, but the description explains that.

**Comment by Fernal73** [comment]
Ok. What a whole lot of confusion. Now I wonder why that happens.

**Comment by Fernal73** [comment]
Thanks. One good thing came of this . I learnt that PMD uses JCommander to
parse command line parameters.
