### ISSUE TITLE
[core] Remove duplicate code between PMD Processors and PMDRunnable

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#180]
Currently `MonoThreadProcessor` and `MultiThreadProcessor` + `PmdRunnable` do pretty much the same, and in doing so, they are repeating a lot of code with even some slight inconsistencies.

For instance, `MonoThreadProcessor` calls `rs.start(ctx);` for the rulesets once per file. `MultiThreadProcessor` on the other hand, does so only once, and not even on the `RuleSets` instance being used (this means both `GenericClassCounterRule` and `CommentContentRule` are broken unless run with `-threads 0`).

We can't kill `MonoThreadProcessor` (it's used from ant by default, and not launching threads has advantages for tasks such as profiling / benchmarking), but those classes could certainly share more code to provide a more concise implementation. For instance, ee could probably pull all logic up to `AbstractPMDProcessor` and just let as extension point the strategy for running a given `PmdRunnable` (with the `MonoThreadProcessor` simply doing `call()`). This would require creating a new `PmdRunnable` per file even on mono thread AND we would probably have to get rid of `PmdThread` (or at least make sure `PmdRunnable` doesn't depend on it), but is the cleanest alternative I've come up with so far.

**Comment by adangel** [comment]
Makes sense. There is already a related issue on the start/stop logic: https://sourceforge.net/p/pmd/bugs/1511/
