### ISSUE TITLE
[Apex] CDP Gui doesn't display Apex as supported language (and won't run on it)

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#182]
I downloaded the latest PMD bin 5.4.1 and ran the CPD Gui from my Mac OS command line.
I tried to check some Apex classes *.cls files but failed as the extension is not show in the pull down. It also didn't work with the option to enter a custom extension.

<img width="1053" alt="bildschirmfoto 2017-01-10 um 14 18 40" src="https://cloud.githubusercontent.com/assets/8180281/21807581/c2795bc8-d73f-11e6-9236-c098f1cca905.png">

When I compare the Apex CDP files at
https://github.com/pmd/pmd/tree/master/pmd-apex/src/main/java/net/sourceforge/pmd/cpd
with other languages everything looks fine and enabled.

FYI: @adangel

**Comment by jsotuyod** [comment]
@up2go-rsoesemann Apex support was added in PMD 5.5.0. The latest release for that version is PMD 5.5.2 which you can download [from here](https://github.com/pmd/pmd/releases/download/pmd_releases%2F5.5.2/pmd-bin-5.5.2.zip).

Next release (5.5.3) will include several improvements and new rules to Apex.
