### ISSUE TITLE
[plsql] Parentheses stopped working

### ISSUE THREAD

**Issue by kabroxiko** [pmd/pmd#1828]
**Affects PMD Version:** 6.11.0

**Rule:** Parentheses

**Description:** Parentheses stopped working from version 6.11.0

**Code Sample demonstrating the issue:**

select *
from dual
where (dummy = X or 1 = 2)
and 1=1;

**Comment by adangel** [comment]
Similar case is fixed with #1874:

```
update employees
     set salary = salary + sal_raise,
         salary = (salary - discounts) * sal_raise
     where employee_id = emp_id;
```
