### ISSUE TITLE
[java] False positives for MissingStaticMethodInNonInstantiatableClass when DI is used

### ISSUE THREAD

**Issue by Vampire** [pmd/pmd#1832]
**Affects PMD Version:** 
6.14.0
**Rule:**
[MissingStaticMethodInNonInstantiatableClass](https://pmd.github.io/pmd-6.14.0/pmd_rules_java_errorprone.html#missingstaticmethodinnoninstantiatableclass)
**Description:**
When using dependency injection like CDI, Spring or similar, a "non instantiable class" is not necessarily really "non instantiable" as long as the private constructor does not also throw an exception.
When there are dependency injection annotations like `@Inject`, `@Produces`, `@Observes`,  `@Autowire`, and so on or bean defining annotations on the class like `@ApplicationScoped`, `@Dependent`, `@RequestScoped` and so on, the class should not be considered "non instantiable", except if it was determined that the constructor also always throws an exception.

It is pretty common practice to make those classes have a private constructor to ensure they are instaniated by the DI framework and not manually (except through reflection of course).

**Running PMD through:** *Gradle*

**Comment by AnthonyKot** [comment]
https://github.com/pmd/pmd/pull/1916

**Comment by Vampire** [comment]
@adangel from a quick look, the PR only fixes some of the cases, doesn't it?
Only if the contructor is annotated with `@Inject` or `@Autowired` is covered.
But all the other cases, where fields or methods are injected, producer methods are present,
the class has a bean defining annotation and so on are not covered.

**Comment by adangel** [comment]
@Vampire The rule looks for classes, which has only private constructors. It has been changed, to ignore private constructors, which are called by the DI (as marked via the annotations), which means the class can (and maybe will) be instantiated by the DI framework. But without that, we can't see, whether and how it might be instantiated despite the fact it has no callable constructor.

It would be best, if you could provide complete code samples. Maybe the rule is not really useful in your case?
Btw. a class, that can only be instantiated through DI/reflection prevents you from writing a simple unit test.
