### ISSUE TITLE
[java] Could not find class **/**, due to: java.lang.IncompatibleClassChangeError: net/sourceforge/pmd/lang/java/typeresolution/visitors/PMDASMVisitor

### ISSUE THREAD

**Issue by test-git-hook** [pmd/pmd#1835]
**Affects PMD Version:** 
PMD 6.12.0
**Rule:**
Custom rule of use AST
**Description:**

**Code Sample demonstrating the issue:**
I use inspection for class resolved info.
but PMDASMVisitor could not give that infomation.

my rule source 

```java
public class CustomRule extends AbstractJavaRule {

@Override
	public final Object visit(ASTPrimaryPrefix node, Object data) {
	...
	    Node node1 = node.jjtGetChild(0);
	    String image = node1.getImage();

	    if(node1 == null){
	      return false;
	    }
	   if(node1 instanceof ASTName) {
	    	JavaTypeDefinition typeDefinition = ((ASTName)node1).getTypeDefinition();
	    }
		....
	 }   
}
```

my java file source for inspection 

```java
public class MyJava {
	public void test(){
	 	System.out.plintln("something"); 
	}
}
```

If I got that image "System.out.plintln",  typeDefinition is void 
- JavaTypeDefinition [clazz=void, definitionType=EXACT, genericArgs=[], isGeneric=false]

I gave classpath Whole project class file include MyJava.class.
I am forced to do so at the convenience of the project.

My ant file like this
```xml
	<target name="pmd" >
	    <taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask" classpathref="pmd1.classpath"/>
	    <pmd rulesetfiles="java-imports,./ruleset/my/custom.xml" auxclasspath="C:/workspace/A-Project/bin">
	        <sourceLanguage name="java" version="1.8"/>
	    	<formatter type="xml" toFile="C:\pmd_report.xml"/>
	        <fileset dir="C:/workspace/A-Project/src/test/">
	            <include name="**/*.java"/>
	        </fileset>
	    	<classpath>
	    	  <pathelement path="${classpath}"/>
	    	  <fileset dir="C:/configuration/lib/">
	    	    <include name="**/*.jar"/>
	    	  </fileset>
	    	</classpath>
	    </pmd>
	</target>
```

and Ant return message 
`Could not find class A.Myjava, due to: java.lang.IncompatibleClassChangeError: class net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor has interface org.objectweb.asm.ClassVisitor as super class`

when I remove 'auxclasspath', I got typeDefinition Java.lang.System
but the other values ​​used were returned as null like IO.
Please help me.
this is bug? or Am I missing something?
**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
Ant

**Comment by jsotuyod** [comment]
@test-git-hook first of, I'd like to know the exact contents of both `C:/configuration/lib/` and `C:/workspace/A-Project/bin`.

Under `C:/configuration/lib/` you should **only** have the jars for your rules. No PMD jar nor PMD dependency should be located there.

Given your exception, it seems most likely that is not the case, and you are even mixing some incompatible versions (maybe major versions).

**Comment by test-git-hook** [comment]
@jsotuyod Thank you for your reply.
I tried except classpath and only give auxclasspath.
`<target name="pmd" >
	    <taskdef name="pmd" classname="net.sourceforge.pmd.ant.PMDTask" classpathref="pmd1.classpath"/>
	    <pmd rulesetfiles="java-imports,./ruleset/my/custom.xml" auxclasspath="C:/workspace/A-Project/bin">
	        <sourceLanguage name="java" version="1.8"/>
	    	<formatter type="xml" toFile="C:\pmd_report.xml"/>
	        <fileset dir="C:/workspace/A-Project/src/test/">
	            <include name="**/*.java"/>
	        </fileset>
	    </pmd>
	</target>`
but I got same exception.
Contents of C:/workspace/A-Project/bin is just classes.

**Comment by jsotuyod** [comment]
@test-git-hook just out of curiosity, I see there is a 1 in `pmd1.classpath`… are there other pmd classpaths / tasks being defined? Is the ant file available to inspect?

**Comment by test-git-hook** [comment]
@jsotuyod 
pmd1.classpath is fileset of pmd lib 
because It did not work without that classpath in my eclipse.
Is that my problem?

The reason for 'pmd1' is that I have done a lot of testing.

**Comment by adangel** [comment]
@test-git-hook 
Judging from the error message

```
Could not find class A.Myjava, due to: java.lang.IncompatibleClassChangeError: class net.sourceforge.pmd.lang.java.typeresolution.visitors.PMDASMVisitor has interface org.objectweb.asm.ClassVisitor as super class
```

you seem to have a very old version of ASM on the classpath (see also https://stackoverflow.com/questions/11738732/exception-java-lang-incompatibleclasschangeerror-while-running-groovy-in-eclipse): `org.objectweb.asm.ClassVisitor` was indeed a interface with ASM 3.x, but it is a abstract class since ASM 4.x and the current PMD version actually uses ASM 7.x...

Please do the following:
* check, that you are using PMD version 6.12.0 (you might as well update to PMD 6.15.0)
* check, which files are in `pmd1.classpath`? It basically should be all the jar files that are in the lib folder of the binary distribution of pmd (you downloaded pmd-bin-6.12.0.zip, right?) There should be no more and no less jar files than in the original pmd zip file.
* you'll need to add the `<classpath` element with folder "C:/configuration/lib/". Otherwise the PMDTask won't find your custom rule and ruleset.
    * The `<pathelement path="${classpath}"/>` looks suspicious. What is `classpath`? It would add potentially unnecessary jars to the class path (such as a very old ASM library, which will create the IncompatibleClassChangeError problem). I'd try to add the `<classpath` element without this `pathelement`.

**Comment by test-git-hook** [comment]
@adangel 
Thank you for your interest.
But I want to use my rules. Is it ok to add this to 'pmd path'? The jar does not contain the pmd library.

**Comment by jsotuyod** [comment]
@test-git-hook you can add the jar with your rules to `pmd1.classpath`. But remember, that jar should **not** be a fat-jar, you don't want to duplicate any of PMD' classes or it's dependencies.
