### ISSUE TITLE
[java] simple string literal concatenation should not trigger GuardLogStatement

### ISSUE THREAD

**Issue by Vampire** [pmd/pmd#1841]
**Affects PMD Version:** 
6.14.0
**Rule:**
[GuardLogStatement](https://pmd.github.io/pmd-6.14.0/pmd_rules_java_bestpractices.html#guardlogstatement)
**Description:**
The line `LOG.warn("foo " + "bar")` will trigger the GuardLogStatement rule
while `LOG.warn("foo bar")` will not.
But any recent Java compiler should optimize away the concatenation of string literals at compile time, so both lines are usually effectively the same.
Even if final strings (fields, local variables, static fields) are involved, those get inlined too.
So I suggest adding some logic to not show these cases as violations.
**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment]
@Vampire thanks for the report. I'm merging this onto #957 as a duplicate.
