### ISSUE TITLE
[java] Rule to check for double brace initialisation

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1854]
[Double brace initialisation](https://stackoverflow.com/questions/1958636/what-is-double-brace-initialization-in-java) is a pattern to initialise eg collections concisely. But it implicitly generates a new `.class` file, and the object holds a strong reference to the enclosing object... 

Example:
```java
 new ArrayList<String>() {{ addAll("a", "b", "c"); }};
```

I think, we could detect that for collections as a first step. But any instance initialiser in an anonymous class that calls only public methods of the object could be considered an instance of this code smell, if no methods are overridden.

**Comment by jsotuyod** [comment]
@oowekyala I strongly support this.
