### ISSUE TITLE
[ant] Reflective access warnings on java > 9 and java < 17

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1860]
From #584 :

> I also receive the following warning message while running the Java Ant Task:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by net.sourceforge.pmd.ant.Formatter (file:/data/data/com.termux/files/home/LearnJava/lib/pmd-core-6.15.0.jar) to field java.io.Console.cs
> WARNING: Please consider reporting this to the maintainers of net.sourceforge.pmd.ant.Formatter WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release.

> I'm running Ant against an Open Jdk 1.10 version on Arch Linux on Termux.

Here's the relevant code:

https://github.com/pmd/pmd/blob/89bb73fc99bb2f4e01cca7bdc3de403c009219e2/pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java#L197-L229

Maybe there's a better way to fetch that?

**Comment by adangel** [comment]
https://dzone.com/articles/java-19-reflection-and-package-access-changes

**Comment by jsotuyod** [comment]
I believe this is no longer an issue, right?
At least all Ant tests are emitting 0 warnings…

**Comment by adangel** [comment]
This warning is actually still printed out for Java11. With Java17 (and later), we already use the public API to determine the console encoding, but for older java version, we use reflection. Java 8 doesn't report this, but Java 11 reports this illegal reflective access operation by default.
