### ISSUE TITLE
[java] Be more lenient with version numbers

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1861]
Language versions like in the Ant task:

https://pmd.github.io/pmd-6.15.0/pmd_userdocs_tools_ant.html#language-version-selection

or the CLI

https://pmd.github.io/pmd-6.15.0/pmd_userdocs_cli_reference.html#version

Should probably be more lenient, eg accept both `1.9` and `9` for java 9, etc. Javac is more lenient than PMD:
* The `-source` option has some synonyms:  `1.3`, `1.4` have no synonyms, but all versions from then on accept both `1.X`  and `X`
* The `--release` option only accepts short forms, eg in jdk 10 : "Supported `release` targets are 6, 7, 8, 9, and 10."

**Comment by Fernal73** [comment]
This has not yet been fixed. Setting the version to 8 terminates the ant task saying that the language version is not supported. Either support both versions i.e, 1.XX and simply XX, or drop the sourcelanguage element  completely for java. How will that impact the other languages supported by PMD?
