### ISSUE TITLE
[doc] Incorrect code example for DoubleBraceInitialization in documentation on website

### ISSUE THREAD

**Issue by maikelsteneker** [pmd/pmd#1898]
**Affects PMD Version:** 6.16.0

**Rule:** DoubleBraceInitialization

**Description:**
See https://pmd.github.io/pmd-6.16.0/pmd_rules_java_bestpractices.html#doublebraceinitialization.

The following code example is listed as an example for double-brace initialization:
`            return new ArrayList<String>();`
It looks like the part within the double braces has been excluded, since it does appear in the original XML...

On a related note, there is a lot of unnecessary indentation.

**Code Sample demonstrating the issue:** N/A

**Running PMD through:** N/A

**Comment by oowekyala** [comment]
Thanks for the report! The text was not properly escaped for Liquid, which is fixed in 1a690ed1e83875773183b73a333d421b3cdff062

**Comment by adangel** [comment]
Actually we should fix it in the rule documentation generation - otherwise we need to fix it for each example. Also the xml file shouldn't need to be aware that it might be rendered via liquid...
