### ISSUE TITLE
[apex] Expose super type name of UserClass

### ISSUE THREAD

**Issue by rodolfonoviski** [pmd/pmd#1901]
Hi everyone
I'm trying to create a custom rule to get if a class have a specific extend class.
But the node of UserClass doesn't have a extends node like Java.

For example:

`public class AccountTriggerHandler extends TriggerHandler` 

Java:
`//ClassOrInterfaceDeclaration[contains(@Image,'TriggerHandler') and //ClassOrInterfaceDeclaration/ExtendsList/ClassOrInterfaceType[not(@Image='TriggerHandler')]]`

For Java it's working fine, I can't do the same for APEX though

`//UserClass[contains(@Image,'TriggerHandler')]`

Someone can help me with this?

Best Regards

**Comment by rsoesemann** [comment]
@adangel didn’t you recently make a change so more properties are exposed in the AST ?

**Comment by adangel** [comment]
There is indeed no information about the extends clause available in the AST:

![grafik](https://user-images.githubusercontent.com/1573684/60587195-21d77600-9d94-11e9-833f-9e4c2f51fd2e.png)

**Comment by rsoesemann** [comment]
Are you sure it’s not in the AST or just not exposed in the designer?

**Comment by rodolfonoviski** [comment]
Hi 

I try to do the same rule for apex:

`//UserClass[contains(@Image,'TriggerHandler') and //UserClass/ExtendsList/UserClass[not(@Image='TriggerHandler')]]`

And still, doesn't work

**Comment by adangel** [comment]
> Are you sure it’s not in the AST or just not exposed in the designer?

With AST I mean "our" (PMD's) AST and then AST and what is exposed in designer is equivalent. Our AST is completely available in the designer...

We'll need to dig deep into jorje binaries to figure out the super class. So far I tried this snippet:

```
    public String getSuperType() {
        try {
            return this.node.getDefiningType().parents().superType().toString();
        } catch (NullPointerException e) {
            return "";
        }
    }
```

But all I get is "Object" - which indicates, that Jorje maybe need access to the whole source code to resolve the types... if the class extends "String", then the supertype is String... So I guess, the Jorje Parser doesn't know at all what "TriggerHandler" is.

**Comment by rsoesemann** [comment]
I will ask for help by salesforce

**Comment by rsoesemann** [comment]
@ntotten This is the issue we need the help of you and your team.

**Comment by adangel** [comment]
Another thing, that's maybe related: #1741 - we currently fail, if jorje couldn't parse the code properly. I don't know, if the parse result, we are working with, is maybe wrong. So, I'm pretty sure, we don't use jorje the way it is intended.
Mabye we should more look into this direction? https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/language-server

**Comment by rodolfonoviski** [comment]
Hi, any update about this question?
I really need to do this validation =/

Best Regards

**Comment by oowekyala** [comment]
@adangel I think you're right and Jorje probably needs access to all the source for TypeInfo to work...

The CodeUnitDetails class provides raw info about the supertype even when it can't be resolved. We may use it like this:

```java
    public String getSuperTypeName() {
        return node.getDefiningType().getCodeUnitDetails().getSuperTypeRef().map(TypeRef::getNames)
                   .map(it -> it.stream().map(Identifier::getValue).collect(Collectors.joining(".")))
                   .orElse("");
    }
```

![Capture du 2019-08-02 20-23-49](https://user-images.githubusercontent.com/24524930/62390829-7e7cab00-b563-11e9-8e15-8df347ef9d9f.png)

**Comment by adangel** [comment]
@oowekyala I think, that's the best we can do for now. I've created a PR: #1959
