### ISSUE TITLE
[java] Metrics not computed correctly with annotations

### ISSUE THREAD

**Issue by karwer** [pmd/pmd#1912]
**Affects PMD Version:** 
6.16.0

**Rule:**
[DataClassRule](https://pmd.github.io/latest/pmd_rules_java_design.html#dataclass), rules based on custom metrics

**Description:**
The rule does not count annotated methods.

The problem source is in

https://github.com/pmd/pmd/blob/45facbd32308e81c0e567e3f400f8161e30b5791/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/AbstractJavaClassMetric.java#L118

where only the first child of the declaration block is considered which in case of annotated methods/fields is the annotation and not the method or field itself.

**Code Sample demonstrating the issue:**

```
@Override
public getName() {
    ...
}
```

**Running PMD through:** *CLI*

**Comment by andipabst** [comment]
I would be willing to work on this and provide a pull request, if you are open to this?

**Comment by oowekyala** [comment]
@andipabst Hi, your contribution would be very welcome! You can go ahead, this has not been fixed yet. Feel free to ask for pointers here if you want.
