### ISSUE TITLE
[core] Render config errors

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#194]
[Report.configErrors()](https://github.com/pmd/pmd/blob/5b3142433bcfd037ac3a15c2e704f701b93c3cac/pmd-core/src/main/java/net/sourceforge/pmd/Report.java#L428) stores configuration errors for rules, but those are not used in any renderer.

We should start rendering these, exposing all errors to the user. This feature would be a good place to start registering missing classes during analysis, as discussed [here](https://github.com/pmd/pmd/pull/171#issuecomment-270433150)

**Checklist:**
 - [x] Add config errors to renderers
 - [ ] #3914
    - Add missing classes as config errors
    - in type resolution in general
    - in MissingOverrideRule (see #1267)
 - [ ] Review no phony missing classes are reported (specially regarding generics)
   - **WIP:** Found and fixed a couple of scenarios. See #225 and #226. I still see a few generics references we shouldn't.
 - [x] Avoid duplicate dysfunctional rules report
   - [x] Make `RuleSets` deep-copyable

**Comment by Reissner** [comment]
The problem did not vanish. Still the workaround 
  &lt;rule ref="rulesets/java/controversial.xml/AvoidLiteralsInIfCondition">
    &lt;properties>
      &lt;property name="ignoreMagicNumbers"    value="-1,-1L,0,0L,1,1L,2,2L, 0.0"/>
    &lt;/properties>
   &lt;/rule>

value without blank works but with blank, not yet.

**Comment by jsotuyod** [comment]
Moving this back to 6.0.0 since it would require API changes.

I'd split this into 2:
 1. config error when using a typresolution rule with no auxclasspath configured
 1. a new kind of error (`MissingClassError`?) when finding an incomplete classpath during execution

The new type of error I believe is necessary in order to:
 - don't have the error bound to a specific rule
 - avoid duplicate reports (several rules missing the same class)

**Comment by jsotuyod** [comment]
Also of note, currently ConfigErrors for dysfunctional rules are reported per thread used during analysis in `PMD.setupReport`.

We need `RuleSets` to be deep-copy-constructable in order to have it sanitized once on startup, and not during analysis. Adding missing auxclasspath check during this startup sanitization would be trivial.

**Comment by jsotuyod** [comment]
All needed breaking API changes are now in place for 6.0.0.

We may end up pushing the feature itself back to 6.1.0 to avoid holding the 6.0.0 release, but that will depend on the speed we move forward with #610 which is the only major task currently blocking 6.0.0

**Comment by jsotuyod** [comment]
I'm pushing this back to 6.1.0. No more breaking API changes should be needed

**Comment by adangel** [comment]
Closing this one as won't fix. See #3901 for the latest discussions.
Logging missing classes somehow is tracked as #3914.
