### ISSUE TITLE
[core] Consider to remove the generated rule doc from git

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#1949]
Many PRs include the generated rule doc, which is just noise.
In order to have these generated rule documentation (`docs/pages/pmd/rules`) in the git repository committed is only needed to have the github hosted github pages working: https://pmd.github.io/pmd/

* Anybody uses this url?
* We have an alternative, that we also update with every build: https://pmd.sourceforge.io/snapshot/

I'd suggest to remove this from our repository and our build scripts (`.travis/...`).

Wdyt?

**Comment by adangel** [comment]
Actually, https://pmd.github.io/pmd/ is served from the branch "gh-pages"... so we could even leave this intact and just remove `docs/pages/pmd/rules` and the commits to this directory by travis...

**Comment by jsotuyod** [comment]
I think having a single snapshot version should be enough (ie: to check if everything looks good after changes), which ever that one is. As long as we keep the released docs under the github.io domain I think we are ok.

Bare in mind the code actually points to https://pmd.github.io/latest/ under certain circumstances…

https://github.com/pmd/pmd/blob/d935db0a6d293532c4beb684bb7abc8715c589e1/pmd-core/src/main/java/net/sourceforge/pmd/PMD.java#L309-L311

**Comment by adangel** [comment]
Good point about


https://github.com/pmd/pmd/blob/d935db0a6d293532c4beb684bb7abc8715c589e1/pmd-core/src/main/java/net/sourceforge/pmd/PMD.java#L309-L311

The url is actually wrong: https://pmd.github.io/latest/ is the latest release, not a snapshot...
We have the url also in the pom as property `pmd.website.baseurl`...

https://github.com/pmd/pmd/blob/d935db0a6d293532c4beb684bb7abc8715c589e1/pom.xml#L103

Which is set during a release to a different url in the pmd-release profile.

**Comment by adangel** [comment]
This has been fixed with #2027 (since 6.19.0)
