### ISSUE TITLE
[core] Text renderer should include name of violated rule

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#1961]
**Affects PMD Version:** 
6.16.0, 6.17.0

**Description:**
Error messages generated in text output do not reference the name of the rule violated. Without it, it's hard to find documentation on how to resolve the error. The rule name is needed for the SuppressWarnings annotation. 

**Running PMD through:** [CLI | Ant]

**Comment by Fernal73** [comment]
The SuppressWarnings annotation requires the full name of the rule like PMD.RuleName or RuleName. 
Are there any plans to simply allow regex-like prefix and let PMD's implementation decide which rule is referenced. Ambiguities are to be flagged, of course, and rejected.

**Comment by Fernal73** [comment]
This would be a good issue to be fixed as well.

**Comment by GuntherSchrijvers** [comment]
Hello @Fernal73 ,

How would the output need to look like? 
Would this be ok?
`SourceCodeFileName:LineNumber:<TAB>RuleName:<TAB>:RuleDescription`

**Comment by Fernal73** [comment]
> Hello @Fernal73 ,
> 
> How would the output need to look like?
> Would this be ok?
> `SourceCodeFileName:LineNumber:<TAB>RuleName:<TAB>RuleDescription`

`SourceCodeFileName:LineNumber:<TAB>RuleDescription:<TAB>RuleName`
to maintain compatibility in case this output is parsed by any programs. The RuleDescription would be the same as currently output.

**Comment by GuntherSchrijvers** [comment]
Ok, thank you for the feedback,

**Comment by Fernal73** [comment]
> Ok, thank you for the feedback,

It would have helped if you had informed me that you were concerned about field alignment. That's a legitimate reason to retain your original format. I don't see any backward compatibility use, either.

**Comment by GuntherSchrijvers** [comment]
Hello @Fernal73,

I hadn't considered the field alignment, It is only thanks to the feedback of @oowekyala on the pull request that this was taken into consideration.

**Comment by Fernal73** [comment]
Thanks, @oowekyala @GuntherSchrijvers !
