### ISSUE TITLE
[core] Simplify Report API

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#1962]
Summary of discussion with @pzygielo on #1960:
* `Report::size/getNumViolations` needs a comment because it's the size of the `iterator`
* `Report::isEmpty` doesn't necessarily mean that there are some violations, which is counter-intuitive (it considers violations and processing errors). 

So maybe `isEmpty` is badly named. However it looks like the issue is a bit bigger. The `isEmpty` method is useless on its own, as it doesn't say anything about either the size of `iterator()` or of `errors()`, since the results are merged. It also doesn't take config errors into account which undermines its only usefulness (maybe checking that there is nothing to report, but with this implementation there can still be config errors). So you can't derive anything useful from a method call to `isEmpty` and will need another check (either hasErrors, or hasNext on the iterator, or a zero `size()` check). 

So probably, `isEmpty` shouldn't even exist. But maybe the problem is *even bigger*.
The `Report` class appears to try *being three lists at a time*, as evidenced by the following methods:
* ` boolean isEmpty()`
* `boolean hasErrors()`
* `boolean hasConfigErrors()`
* (notice no `hasViolations`)
* `Iterator<RuleViolation> iterator()` 
* `Iterator<ProcessingError> errors()`
* `Iterator<ConfigurationError> configErrors()`
* `int size()`
* (notice no `numErrors` or `numConfigErrors`)

I shouldn't be mentioning the ReportTree and Metric methods, because they're supposed to be deprecated, but they aren't for now so let's just make a list to deprecate them later:
* `treeIterator()`, `treeIsEmpty()`, `treeSize()`  
* `metrics()`, `hasMetrics()`

So Report attempts to be 5 collections at a time and does a meh job of it, because the API is assymmetric and very rudimentary.

I think making Report expose those collections independently would be a big upgrade to that API. We could replace all the above-mentioned methods by just
* `List<RuleViolation> getViolations()`
* `List<ProcessingError> getProcessingErrors()`
* `List<ConfigurationError> getConfigErrors()`

This would reduce greatly the API surface we have to maintain while improving the API available to users. Besides, since Report is implemented with Lists internally, it would be trivial to implement.

Making this change would supersede #1960

Should we do that?

**Comment by adangel** [comment]
I think, this makes sense. However, this is just a very tiny part of the API and I don't know yet, whether this fits into the bigger picture of "Programmatic API" (https://github.com/pmd/pmd/wiki/PMD-7.0.0).

**Comment by jsotuyod** [comment]
I support the proposed refactor. We should make sure the returned collections are read-only.

I also think the current logic to apply `// NOPMD` suppressions should be removed from `Report`, and have it in the same place were we apply `@SuppressWarnings` suppressions.

**Comment by oowekyala** [comment]
@jsotuyod Cool

> I also think the current logic to apply // NOPMD suppressions should be removed from Report, and have it in the same place were we apply @SuppressWarnings suppressions.

In fact I recently did something to simplify violation suppression. It removes a lot of duplication and treats `// NOPMD`, `@SuppressWarnings`, `violationSuppressXPath` and `violationSuppressRegex` uniformly (they're extensible too) for very little trouble. This also might improve reports, which for now only consider that violations may be suppressed through comment or annotation...

Eg 

https://github.com/pmd/pmd/blob/fac5604d63744337209516a976a1132e0404f776/pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java#L177

The current version I have depends on #1927 though
