### ISSUE TITLE
[core] PMD fails on excluding unknown rules

### ISSUE THREAD

**Issue by malejpavouk** [pmd/pmd#1978]
Not sure if error or missing feature. But the thing is that we have a common project that contains rule files for all quality plugins and one of them is PMD. The projects are set up in a way that they always fetch the latest bundle of rulefiles (so we can update the quality gates without changing the projects). So far so good,

But the issue is that we updated PMD in some project and noticed that of the rules does not suite our needs. So we suppresed it... And now the issue. Not all projects have the latest PMD -> _Unable to exclude rules [AvoidUncheckedExceptionsInSignatures]; perhaps the rule name is mispelled?_

Is it somehow possible to get rid of this behavior and set PMD to tolerant mode. Maybe write some warning to log... but not fail the build? From my perspective its much cleaner approach, as not applying exclusion at all (the worst case) cannot lower the quality of the checked product...
Essentially this makes any changes to shared rulesets to be backward incompatible...

**Comment by adangel** [comment]
See #2082 and https://sourceforge.net/p/pmd/bugs/1231/

The error message / hard failure was introduced with https://sourceforge.net/p/pmd/bugs/1231/ . However, now I think, it would be better to just log a warning and continue.

As you reasoned - as not applying the exclusion cannot lower the quality of the checked product. It is just, that the ruleset is outdated and tries to exclude a rule, which doesn't exist (anymore?).
So, the end result is: the excluded rule is not executed - and that was the main intention of the exclusion.

**Comment by malejpavouk** [comment]
Cool, thanks for fixing this! 👍
