### ISSUE TITLE
[doc] Issue with http://pmdapplied.com/ linking to a gambling Web site

### ISSUE THREAD

**Issue by jslaroch** [pmd/pmd#2002]
The link for PMD applied brings us to a gambling web site somewhere in Asia
Starting at:

https://pmd.github.io/pmd-6.17.0/pmd_userdocs_extending_writing_pmd_rules.html#

At the bottom the link is:

http://pmdapplied.com/

Hop, you are now gambling in Asia somewhere.

Sorry, I don't know where else I can log this.

**Comment by adangel** [comment]
Thanks for bringing this to our attention. I think, we should simply point to the following page instead: https://pmdapplied.thomasleecopeland.com/

**Comment by jsotuyod** [comment]
@adangel probably, but that book is crazy outdated. It dates back to PMD 3, lots of things changed since then.

**Comment by oowekyala** [comment]
I agree, that that book is most probably not a reliable source of information on PMD anymore. IIRC the book only talks about Java too. Our website should be the reference here.

**Comment by adangel** [comment]
Agreed. Maybe should just update the reference on https://pmd.github.io/latest/pmd_projectdocs_trivia_products.html and mention, that it is outdated (from November 2005).

There are for sure more pages, which refer to pmdapplied (such as the mentioned https://pmd.github.io/latest/pmd_userdocs_extending_writing_pmd_rules.html), where we should then simply remove the link.
