### ISSUE TITLE
[core] Refrain from using File / filename internally in favor of DataSource

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#2004]
The DataSource seems like a good name for an abstraction of what PMD is analyzing. However, the rule context e.g. needs a file/filename. As does the rule violation. While DataSource is abstract to work with more than files, anything else doesn't seem to be. That's something we should aim to fix for PMD 7, but not in PMD 6 (unless there is a bug to fix).

_Originally posted by @adangel in https://github.com/pmd/pmd/pull/1982_

**Comment by adangel** [comment]
In PMD 7, DataSource is deprecated and will be gone in favor of TextFile.
I'm closing this as won't fix, as this issue is now irrelevant.
