### ISSUE TITLE
[javascript] template strings are not correctly parsed

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#201]
**Rule Set:** N/A

**Description:** EcmaScript 5 added support for template strings, delimited by backsticks (`` ` ``). The current grammar does not support this properly, meaning template strings throw lexical errors.

**Code Sample demonstrating the issue:**

```
var markup = `<p>${content}</p>`;
```

**Running PMD through:** *Any*

**Comment by jsotuyod** [comment]
Resolved through #200

**Comment by molomby** [comment]
Fyi, pretty sure template strings were added in ECMAScript 6 (ES2015).

**Comment by adangel** [comment]
Note, the grammar is only used for CPD tokenization.
For PMD parsing, we use Rhino. I've just seen, that [Rhino](https://github.com/mozilla/rhino) seems to be still under development, so we might consider updating from 1.7.7 to 1.7.7.2

**Comment by adangel** [comment]
Correct: It's part of ECMAScript 2015 (6th Edition): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
