### ISSUE TITLE
[core] Making add(SourceCode sourceCode) public for alternative file systems

### ISSUE THREAD

**Issue by nbraun-Google** [pmd/pmd#2014]
**Affects PMD Version:** 6.17.0

**Rule:** n/a

**Description:**
I'm trying to integrate CPD with my team's code base, but I'm running into some issues. The way that we store our source code makes it impossible for us to access it using Java's File API. Meaning that if we try to run CPD against "/path/to/my/source/", CPD cannot find anything within that directory. 

We have another API that we can use to retrieve the source code, and I can convert it to a String. I have 2 potential solutions to integrate with CPD.

1. Use the API, retrieve the source as a String, write all of the source to a temporary file, run CPD, and then delete the temporary files.

2. Make CPD's  [add(SourceCode sourceCode)](https://github.com/pmd/pmd/blob/c8fdd5f0c0581e2ea6a8518a09f823db00b1f6eb/pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java#L133) method public, and then create a [StringCodeLoader](https://github.com/pmd/pmd/blob/c8fdd5f0c0581e2ea6a8518a09f823db00b1f6eb/pmd-core/src/main/java/net/sourceforge/pmd/cpd/SourceCode.java#L124) for each file. I could convert the String from the API into a StringCodeLoader and feed that into CPD.

I prefer option 2 over option 1 since I'll be reading a very large amount of code, and writing it all to temporary files will be too slow. Can you see any issues with option 2, or have a better approach?

**Comment by jsotuyod** [comment]
@nbraun-Google thanks for the report.

The `CPD` class in general is in need of some major tidying up, but doing so is currently unscheduled, so I don't foresee us doing that for PMD 7.0.0, maybe for 8.0.0 we will.

Therefore, I see no harm in proceeding with increasing the visibility of the method from `private` to `public` in master for your use case in the meantime. Feel free to submit a PR to help this move forward faster.

**Comment by nbraun-Google** [comment]
Thanks for the help Juan! I created this pull request: https://github.com/pmd/pmd/pull/2032
