### ISSUE TITLE
[core] Wrong deprecation warnings for unused XPath attributes

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2020]
**Affects PMD Version:** 6.18.0

**Description:**
PMD 6.18.0 reports deprecation warnings for XPath attributes, that are not really used.
This is irritating and a bug.

See also #2019 for an improvement for the deprecation warnings in general.

A partial fix is already available: https://github.com/pmd/pmd/commit/e4ce2faf78c2b08aa1663ebc1a76f110a09a9bba

What's missing:
* handling of null values
* making PMDCoverageTest fail, to detect these problems in the future

I think, the reason, why PMDCoverageTest didn't detect the problem is, that we only log the warnings once per attribute. In other tests, that were executed before PMDCoverageTest, the warnings was already logged, so it wasn't logged again and thus wasn't detected and failed the build. We could execute PMDCoverageTest in a separate jvm (to avoid the static cache) or we could add a integration test in pmd-dist. PMDCoverageTest is only java and we would only detect these problems for our java rulesets, but the same problem could apply for apex as well.

**Comment by oowekyala** [comment]
Note: #1964 touches that logic, I think we need to close it and make a new PR (based on those changes, but without touching rules)

**Comment by adangel** [comment]
For now, first I want to have a build, that tells me, if something is wrong... I think #1964 needs to be checked with #2019.
