### ISSUE TITLE
[javascript] Failing with OutOfMemoryError parsing a Javascript file

### ISSUE THREAD

**Issue by lolgab** [pmd/pmd#2081]
At [Codacy](https://codacy.com) we ran into this issue analysing some Javascript files. It seems to loop infinitely consuming the entire heap and failing with `OutOfMemoryError`
You can find a reproducing repository [here](https://github.com/lolgab/pmd-bug-repro)
**Affects PMD Version:** 
- 6.18.0
- [current master](https://github.com/pmd/pmd/commit/63395684c4e333ccec3fdc489e6a21b92aadf370)

**Description:**
PMD fails with `OutOfMemoryError` parsing a Javascript file
**Code Sample demonstrating the issue:**
```javascript
(``
);
```
note: Removing the newline changes behavior:
```javascript
(``);
```
is parsed correctly.
**Running PMD through:** *CLI*

**Codacy Issue:** 
https://github.com/codacy/codacy-meta/issues/207

cc: @andreaTP

**Comment by lolgab** [comment]
The bug is related with Rhino. Updating rhino to `1.7.11` should solve the problem:
https://github.com/lolgab/pmd-bug-repro/blob/master/README.md

**Comment by jsotuyod** [comment]
@lolgab thanks for the report.

Upgrading Rhino is going to be part of PMD 7.0.0, as per #1699 

Rhino doesn't use semantic versioning, and starting on Rhino 1.7.8 it requires Java 8 instead of Java 7. PMD 6 requires Java 7 (excepto for Apex and the designer that use Java 8), but starting with PMD 7 all modules will require Java 8.

**Comment by lolgab** [comment]
Thank you for your answer @jsotuyod 
So, we are going to wait for PMD 7.0.0 to be released.

**Comment by hudec117** [comment]
A temporary workaround until PMD 7 comes out:
1. Download the latest `rhino-1.7.13.jar` from the [Rhino repo](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_13_Release)
2. Go to your PMD installation and "lib" folder
3. Replace existing `rhino-X.X.X.X.jar` with downloaded
4. See it working

I tested this with PMD 6.31.0 and it seems to work.
