### ISSUE TITLE
[core] Incorrect logging of deprecated/renamed rules

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2082]
With the logging, there seem to be more issues:
* deprecation warning is logged twice, although the rule is referenced only once
* if the complete category ruleset is referenced, the deprecation warning is logged once - but I think, in that case, we should not consider renamed rules and ignore such deprecated rules
* if the complete category ruleset is referenced and the deprecated rule is excluded, we still log the deprecation warning. this looks totally wrong.

This logging is somehow related to #2059, which is just a special case.
Fixing these issues is outside of the scope of this PR.

_Originally posted by @adangel in https://github.com/pmd/pmd/pull/2054#issuecomment-546582446_

**Comment by adangel** [comment]
Test cases:

## Single rule reference

Ruleset:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml/InvalidSlf4jMessageFormat" />
</ruleset>
```

Expected output when running `run.sh pmd -R myruleset.xml -f text -d src`:
* Only one deprecation warning: `WARNING: Use Rule name category/java/errorprone.xml/InvalidLogMessageFormat instead of the deprecated Rule name category/java/errorprone.xml/InvalidSlf4jMessageFormat. PMD 7.0.0 will remove support for this deprecated Rule name usage.`

## Complete category reference

Like it is described here:  https://pmd.github.io/latest/pmd_userdocs_making_rulesets.html#bulk-adding-rules

Ruleset is:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml"/>
</ruleset>
```
Expected output:
* Only one deprecation warning: `WARNING: Use Rule name category/java/errorprone.xml/InvalidLogMessageFormat instead of the deprecated Rule name category/java/errorprone.xml/InvalidSlf4jMessageFormat. PMD 7.0.0 will remove support for this deprecated Rule name usage.`

Note: if there are more renamed rules in this category, we get for each rule a separate warning. But only once.

## Complete category reference with exclusion

Ruleset is:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml">
        <exclude name="InvalidSlf4jMessageFormat" />
    </rule>
</ruleset>
```
Expected output:
* No deprecation warning for InvalidSlf4jMessageFormat

Note: we might get warnings for other rules, if there are more deprecated rules.

## Duplicated rule reference
See also #2059 
Ruleset:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat" />
    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat" />
</ruleset>
```
Expected: Log message about duplicated rule in the ruleset

## Duplicated rule reference with override
Ruleset:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml" />
    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat">
        <priority>1</priority>
    </rule>
</ruleset>
```
Expected: This should not produce a log message, since e.g. the priority is overridden.

## Duplicated rule reference with unintended override
Ruleset:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat">
        <priority>1</priority>
    </rule>
    <rule ref="category/java/errorprone.xml" />
</ruleset>
```
Expected: This however should produce a warning, since with referencing the complete category, the single reference rule is overridden again, so the priority is ignored.

## Duplicated rule references with bulk references
Ruleset:
```
<?xml version="1.0"?>

<ruleset name="Custom Rules"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>My custom rules</description>

    <rule ref="category/java/errorprone.xml" />
    <rule ref="category/java/errorprone.xml" />

    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat">
        <priority>1</priority>
    </rule>
    <rule ref="category/java/errorprone.xml/InvalidLogMessageFormat">
        <priority>2</priority>
    </rule>
</ruleset>
```
Expected: This should produce two warnings:
* one for the second bulk reference of errorprone
* one for the second rule reference of InvalidLogMessageFormat

**Comment by huxi** [comment]
@adangel It looks in this issue like the problem is fixed in 6.19.0 but I still see strange warnings...

Excerpt of my config:
```xml
<rule ref="category/java/errorprone.xml">
    <exclude name="AvoidCatchingThrowable"/>
    <exclude name="AvoidDuplicateLiterals"/>
    <exclude name="AvoidLiteralsInIfCondition"/>
    <exclude name="BeanMembersShouldSerialize"/>
    <exclude name="DataflowAnomalyAnalysis"/>
    <exclude name="EmptyCatchBlock"/>
    <exclude name="InvalidSlf4jMessageFormat"/> <!-- deprecated, InvalidLogMessageFormat is used instead -->
    <exclude name="LoggerIsNotStaticFinal"/>
    <exclude name="MoreThanOneLogger"/>
    <exclude name="NullAssignment"/>
</rule>
```

Even with the exclude for `InvalidSlf4jMessageFormat` in place, I still get the following message:

```text
Use Rule name category/java/errorprone.xml/InvalidLogMessageFormat instead of the deprecated Rule name category/java/errorprone.xml/InvalidSlf4jMessageFormat. PMD 7.0.0 will remove support for this deprecated Rule name usage.
```

**Comment by jsotuyod** [comment]
@huxi actually, that message is correct… that exclude would have no impact unless the name is updated to reference the proper rule name.

**Comment by adangel** [comment]
@huxi there's actually still a bug in reporting deprecated rules, see #2096

**Comment by huxi** [comment]
@jsotuyod I'd agree if the name wasn't used in an `<exclude>`. The exclude was my (failed) attempt to suppress that warning message. The rule itself is included by `errorprone.xml`.
