### ISSUE TITLE
[apex] ApexLexer logs visible when Apex is the selected language upon starting the designer

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#2092]
**Describe the bug**
When the designer is open, **if** Apex is the currently selected language, the console outputs:

```
Oct 29, 2019 10:42:39 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7272051 shorts which is 13MB not including array overhead. Removed 6615472 shorts which is 12MB not counting array overhead. Took 5 ms.
```

Which seems to ignore the fixes introduced in https://github.com/pmd/pmd/pull/503

If upon opening the designer the language is not Apex, simply changing it to apex would not produce the logs. It has to be the selected language upon executing the designer.

**To Reproduce**
1. Launch the designer from run.sh
2. Change the language to Apex
3. Close the desinger
4. Restart the designer from CLI
5. See error

**Expected behavior**
No ApexLexer logs should be visible.

**Comment by adangel** [comment]
This is actually a bug in PMD: The fix for #500 introduced with #503 was incomplete and probably never working: The logger needs to use the full class name instead of just the simple name. So we always configured the wrong logger and thus never disabled the INFO log.
