### ISSUE TITLE
[core] Referencing category errorprone.xml produces deprecation warnings for InvalidSlf4jMessageFormat

### ISSUE THREAD

**Issue by cmuchinsky** [pmd/pmd#2096]
**Affects PMD Version:** 

6.19.0

**Rule:**

category/java/errorprone.xml

**Description:**

After upgrading from `6.17.0` to `6.19.0` started seeing deprecation warnings for a rule that is never explicitly referenced (InvalidSlf4jMessageFormat):

`Use Rule name category/java/errorprone.xml/InvalidLogMessageFormat instead of the deprecated Rule name category/java/errorprone.xml/InvalidSlf4jMessageFormat. PMD 7.0.0 will remove support for this deprecated Rule name usage.`

**Code Sample demonstrating the issue:**

```
<rule ref="category/java/errorprone.xml"/>
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle

**Comment by adangel** [comment]
I unfortunately used a different variant of deprecating/renaming the rule than I used in the unit test, that checks for the message:

```
    <rule name="InvalidSlf4jMessageFormat"
          ref="category/java/errorprone.xml/InvalidLogMessageFormat"
          deprecated="true" />
```

vs.

```
    <rule name="InvalidSlf4jMessageFormat"
          ref="InvalidLogMessageFormat"
          deprecated="true" />
```

But this will be fixed with 6.20.0 as well. Thanks for reporting.
