### ISSUE TITLE
Homebrew version doesn't accept any command line flags

### ISSUE THREAD

**Issue by AndrewRayCode** [pmd/pmd#2107]
**Affects PMD Version:** 
6.16.0

**Reproduction**

```sh
brew install pmd
 pmd -d .```

output:
```
-d is NOT a valid application name, valid options are:pmd, cpd, cpdgui, designer, bgastviewer, designerold
Error: Could not find or load main class
Caused by: java.lang.ClassNotFoundException:
```
None of the command line flags are accepted

**Comment by adangel** [comment]
It looks like the homebrew package used "run.sh" as "pmd".... So, in order to run pmd, you'll need to execute: `pmd pmd -d . -R rulesets/java/quickstart.xml`

**Comment by oowekyala** [comment]
This is a problem with the homebrew package, which we don't maintain. If the proposed workaround is unsatisfactory, open an issue at https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pmd.rb
