### ISSUE TITLE
PMD should join the new Sponsor program. What do you think?

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#2110]
@jsotuyod @adangel  @oowekyala have you seen or heard about https://github.com/sponsors. 
I think you and PMD should definitely apply for this. Let's use this issue to discuss or organize it if you don't think this is nuts ;-).

**Comment by adangel** [comment]
From https://github.com/pmd/pmd/issues/2033#issuecomment-554404330 :

> Can you go ahead and write up the issues if you think they're worth implementing?
> What's the criteria for triaging them, anyway? The impression I have is that
> issues are taken up by volunteers interested and willing to implement them after
> they're ? Is there any other methodology followed? If you subscribed to Github
> sponsors, then it's possible that you'd attract talent willing to do it faster.
> That's a big If depending on whether users are  profiting from using your project
> and are willing to support it? What's your take on this? I have no idea.
> My feeling was it's always better for companies to do it instead. Is that
> because it'll simply be the same as companies hiring people that Github has
> decided to go this way instead?

**Comment by adangel** [comment]
I'm open to try it out, but I don't quite understand it yet - e.g. who is sponsoring who? Under what terms? Is it like the [patreon](https://www.patreon.com/) model?

**Comment by rsoesemann** [comment]
I just wanted to point attention to this to you guys who involve way more in PMD. I don't want to own this so I close it.
