### ISSUE TITLE
Data Flow code is outdated?

### ISSUE THREAD

**Issue by michaelhoefer** [pmd/pmd#2124]
[java][apex]

Greetings all.  Issue here is it is unclear from reading the code and open issues, it is not clear why part of the data flow code is deprecated.  I've seen statements in other issues to the effect that the current data flow code framework is "outdated".  Can someone share more about that?  There are deprecations with no alternatives.

I'm looking at the feasibility of DFA in PMD, especially for Apex and JS, and for obvious reasons do not want to travel down an abandoned road.  Would appreciate any insight you can provide into what is wrong with the current impl and what the plans are to replace it.

thanks!

**Comment by adangel** [comment]
Hi,

the only language, that has some kind of "data flow support" is Java. And that implementation is now more than 10 years old and has not been updated (e.g. it doesn't support for-each loops).

It is also very limited, e.g. it is more a simple control flow. It only looks at one method. It has some endless loops in the implementation. It's also questionable, whether the current abstractions we have are useful if you want to implement DFA in other languages.

Most of the deprecations you see on master are in combination with "InternalApi" (see also https://pmd.github.io/latest/pmd_next_major_development.html#internal-packages-and-internalapi-annotation) . We try to reshape the API in PMD 7 and at the moment, it's not clear yet, how the API for a language to implement DFA would look like.

It's pretty sure, that DFA would be implemented via a separate AST processing stage (see also #1426). But API design is needed e.g. to define how the results of DFA (e.g. flow graphs) are made available for consumption in rules (the only rule that's using DFA on master is [DataFlowAnomalyAnalysisRule](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/DataflowAnomalyAnalysisRule.java)).

Any input, thought, requirements, etc. for shaping the data flow API are very much welcome!

**Comment by Fernal73** [comment]
Why only look at this rule? Why not the law of Demeter as well? I, for one, don't use the rule since it flags just so many errors in my code.

But I think it could be useful if refined further.

https://stackoverflow.com/a/59124629/3924108

Another problem appears to be streams or lambdas:
https://stackoverflow.com/q/53777038/3924108

Another issue to be raised for this?

Another side note:

Do we need rules to enforce refactoring such as split a method that has a boolean parameter into two so that each method does just one thing.

https://martinfowler.com/bliki/FlagArgument.html

**Comment by adangel** [comment]
The rule [DataflowAnomalyAnalysis](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#dataflowanomalyanalysis) has been deprecated in favour of [UnusedAssignment](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedassignment), which is available with PMD 6.26.0.

Therefore this issue wont be fixed.

See also #2647.
