### ISSUE TITLE
[java][doc] DataflowAnomalyAnalysis rule needs to be more descriptive and explanatory

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2129]
**Affects PMD Version:** 
Versions since DataflowAnomalyAnalysis rule was implemented.

**Rule:**
[DataflowAnomalyAnalysis](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedlocalvariable)

**Description:**

The documentation does not adequately cover an explanation of the rule. The terms DU and DD are not explained adequately either. This rule , as it stands, will only be used by developers familiar with Data flow Anomaly Analysis. I've had to look at other sources such as StackOverflow and Google it to gain some understanding myself. Do you wish other users to do the same?

https://pmd.github.io/latest/pmd_rules_java_errorprone.html#dataflowanomalyanalysis

**Running PMD through:** *[CLI | Ant |**

**Comment by adangel** [comment]
Hi @Fernal73, could you give some example of what we are missing or even better make a suggestion, how you would envision the description of this rule? Thanks!

**Comment by Fernal73** [comment]
I have a couple of PDF slides I found useful on the net. Unfortunately, I
don't have the links to them right now. I can send you the docs but I
imagine you'd have to cite them while using it in the documentation.

**Comment by Fernal73** [comment]
None of these explanatory texts or slides will inform developers how to
refactor their code, though.
I'm unaware if there are any texts that addresses the issue. My limited
reading on the matter (refactoring) never encountered the term 'Dataflow
Anomaly Analysis' until now.

**Comment by oowekyala** [comment]
The rule reports unused assignments. DU anomalies are unused assignments, DD anomalies are overwritten assignments. Refactoring only needs removing the assignment, possibly extracting side effects if any. 

The rule would probably be easier to use if it didn't use its current adhoc terminology. And you're right, a "data flow anomaly" is not a thing. The rule could as well be renamed eg UnusedAssignment

**Comment by Fernal73** [comment]
https://github.com/Fernal73/LearnJava/commit/e4517fe5bdf7c164469d3f8368ca3bbfb477a1ef#r36128774

The rule also flags assignments outside loops as Du but the resulting
refactoring is inefficient since it calls the method multiple times. Or is
there a better way of doing it?

**Comment by Fernal73** [comment]
What do you think of these two ways of getting rid of du-anomalies?

https://github.com/Fernal73/LearnJava/commit/cd6f95cb739dfe3c31093a1ff399d3d7239894b1#r36133433

https://github.com/Fernal73/LearnJava/commit/cd6f95cb739dfe3c31093a1ff399d3d7239894b1#r36133417

**Comment by Fernal73** [comment]
https://github.com/pmd/pmd/issues/1304#issuecomment-412925368

**Comment by Fernal73** [comment]
https://github.com/pmd/pmd/issues/2124

**Comment by Fernal73** [comment]
https://github.com/Fernal73/LearnJava/commit/e4517fe5bdf7c164469d3f8368ca3bbfb477a1ef#r36154814

**Comment by Fernal73** [comment]
Closing issue since DFA rule has been deprecated.
