### ISSUE TITLE
[java] CPD: OutOfMemory when analyzing Lucene

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#213]
see original ticket #185 

>  jsotuyod commented 9 days ago
>
> As for the OOM, the problem is the sheer number of duplicate code violations being found on 
> Lucene's source code when using ignore literals.
>
> With 6GB of Heap Space, current PMD versions are able to find over 37500 instances of duplicate 
> code of length 75+.
>
> Even after doing some things to improve allocations / GC, this is simply too much to keep in memory. 
> We will have to refactor our grouping stage code to report and discard matches on to go, rather than
> passing them all at once.

-----

Related Pull request: #198 

-----

> jsotuyod commented 9 days ago • edited
>
> I did some improvements to the codebase, and CPD is now able to analyze the lucene source code 
> given a sufficiently large heap (~7-8G) even when using --ignore-literals.
> 
> Bare in mind that --ignore-literals may not be the best option when analyzing Lucene. The source 
> code has plenty of large arrays of strings (words in different languages), which to CPD are just a 
> sequence of N string literals, and being ignored, duplicate code to be removed; and is therefore 
> currently producing a plain text report of over 800MB (much larger as XML). Such arrays should 
> probably either be ignored by CPD (see CPD Suppression), or moved out of the Java code into 
> resource files loaded at runtime.

> Still a complete rewrite of the CPD renderers is needed. Rendering to a String in memory is
> unsustainable. Once that's done the needed memory for analysis will drop dramatically.

**Comment by jsotuyod** [comment]
The refactoring of CPD renderers was tracked in #795 and fixed in #919 which was part of PMD 6.1.0. Newer PMD versions don't have that problem anymore.
