### ISSUE TITLE
[java] Deprecate rules PositionLiteralsFirstIn(CaseInsensitive)Comparisons in favor of LiteralsFirstInComparisons

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2145]
**Affects PMD Version:** 
6.20.0

**Rule:**
[PositionLiteralsFirstInComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#positionliteralsfirstincomparisons)
[PositionLiteralsFirstInCaseInsensitiveComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#positionliteralsfirstincaseinsensitivecomparisons)

**Description:**
The above two rules must be merged into one with a property to decide whether to ignore case-sensitive or not.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by adangel** [comment]
Thanks for the suggestion. Do you have a special reason, why to do this?

**Comment by Fernal73** [comment]
It's confusing to the user. I was confused when I first saw it. I used one, then discovered the other. I use both. Any particular reason why users would use one and not the other? Implemenation-wise, is it difficult to wrap two rules into one? 
Secondly, isn't PMD working on rationalising rules for version 7? This will certainly help.

**Comment by jsotuyod** [comment]
This is actually a very reasonable idea…

Both rules are exactly identical except one checks for `ends-with(@Image, '.equalsIgnoreCase')` and the other for `ends-with(@Image, '.equals')`. I'd even go further and merge them without a property, I see no reason a developer may want to do this for one but not for the other…

**Comment by adangel** [comment]
> Why ask me this question? Are you questioning the rest of the people posting bug reports or 
> suggestions?

I asked, because you didn't give any explanation at all. I could come up with my own assumptions, why this makes sense, but without being explicit of why you suggest what, it's just questionable. If I do something, I'd like to know why.

**Comment by Fernal73** [comment]
Ok. My fault. I tend to assume that others see my point of view or will realize that if they ask themselves why. I understand that's not always the case. It takes time to sometimes arrive at the same conclusion.

**Comment by Fernal73** [comment]
There's this rule as well:

AvoidDuplicateLiterals

Should we allow for case-insensitive mapping? Is there any use case for it?

**Comment by adangel** [comment]
> Are the reasons provided above not sufficient? Do you need more justification?

That's fine, thanks.

**Comment by John-Teng** [comment]
@adangel I'd like to work on this as my first contribution!

**Comment by adangel** [comment]
@John-Teng Awesome!

We might have a single rule for the following cases (all related to comparison):

```java
String s = "foo";
if (s.equals("bar")) { // currently PositionLiteralsFirstInComparisons
    // should be:
   "bar".equals(s);
}
if (s.equalsIgnoreCase("bar")) { // currently PositionLiteralsFirstInCaseInsensitiveComparisons
    // should be:
    "bar".equalsIgnoreCase(s);
}
if (s.compareTo("bar") > 0) { // currently missing - note: that needs special explanation, since switching the operands changes the result
    // should be:
    if ("bar".compareTo(s) < 0) { ... }
}
if (s.compareToIgnoreCase("bar") > 0) { // currently missing
    // should be:
    if ("bar".compareToIgnoreCase(s) < 0) { ... }
}
if (s.contentEquals("bar")) { // currently missing
    // should be:
    "bar".contentEquals(s);
}
```

I'd start with creating a new rule and afterwards retiring the existing rules.
Here are some pointers for writing rules:
* https://pmd.github.io/latest/pmd_userdocs_extending_writing_rules_intro.html
* current rule:
    * https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PositionLiteralsFirstInComparisonsRule.java, https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractPositionLiteralsFirstInComparisons.java
    * test: https://github.com/pmd/pmd/blob/master/pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PositionLiteralsFirstInComparisonsTest.java
    * test cases: https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/PositionLiteralsFirstInComparisons.xml

**Comment by John-Teng** [comment]
@adangel thanks for the pointers! I have submitted PR #2478, please take a look and provide feedback. Once this PR looks good, I'll open another PR that deprecates the existing rules.

**Comment by John-Teng** [comment]
I've opened up PR #2493 to deprecate the existing rules.
