### ISSUE TITLE
[apex] Cognitive Complexity rule

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#2162]
New Rule Idea Cognitive Complexity as its way better than Cyclomatic Complexity which was until now the static code analyzers gold-standard for detecting hard to maintain code.

- https://t.co/44yjw02uHc?amp=1
- https://www.tomasvotruba.cz/blog/2018/05/21/is-your-code-readable-by-humans-cognitive-complexity-tells-you/
- https://www.sonarsource.com/docs/CognitiveComplexity.pdf

I know this story needs more details and discussions but this is a start for an ongoing discussion.

**Comment by Fernal73** [comment]
You ought to pin this.

**Comment by rsoesemann** [comment]
Pin? How would I do this @Fernal73 ?

**Comment by Fernal73** [comment]
Before we get rid of CyclomaticComplexity completely, do you know how this metric will map to the number of unit test cases to test a method's path?

https://www.codementor.io/@etharalali/code-coverage-metrics-cyclomatic-complexity-71n4rrs4r

Do you think that PMD can come up with a way of verifying that each method has the requisite number of test cases needed to cover every eventuality? 
https://softwareengineering.stackexchange.com/a/110953/205864

**Comment by rsoesemann** [comment]
You are totally right. We need be both one for minimum test paths and the other for complexity. I changed the title accordingly.

**Comment by oowekyala** [comment]
I think we could just introduce a rule about cognitive complexity alongside the cyclomatic complexity rule? I don't think deprecating the other rule is useful in this case, it's still a fully functional rule that some people may use.

**Comment by Fernal73** [comment]
I'm inclined to leave the rule there. It might give us a better idea of the threshold value for this rule when both are in use. 
https://github.com/pmd/pmd/issues/2162#issuecomment-568034768

**Comment by rsoesemann** [comment]
After hearing @Fernal73 argument I am against deprecating it and no really changed the issue title. 😉

**Comment by Fernal73** [comment]
Cyclomatic complexity may not always give an idea of testing effort involved.

See https://stackoverflow.com/q/59666990/3924108

**Comment by Fernal73** [comment]
Any particular reason why this rule was not implemented for Java as well? Do you need a new issue raised?

**Comment by adangel** [comment]
@Fernal73 Thanks for the comment. There is no particular reason. Feel free to create a PR to contribute this rule for Java as well.
