### ISSUE TITLE
Numerous rules fail with "IllegalArgumentException" in Java 11, but not Java 8

### ISSUE THREAD

**Issue by ksilz** [pmd/pmd#2224]
**Affects PMD Version:** 6.20.0
**Gradle Version:** 6.0.1
**JVM Version:** 11.0.5
**Rule:** `AvoidDollarSigns` and more
**Running PMD through:** *Gradle*

**Description:**

Some rules fail when run under Java 11 with a `java.lang.IllegalArgumentException`, but work fine with Java 8. The resulting report is attached, renamed to `.txt` from `.xml` to please Github:

[main.txt](https://github.com/pmd/pmd/files/4060801/main.txt)

Here are some of the rules that fail under Java 11, but work in Java 8. This list is not complete, I just stopped after a while:

- codestyle.xml/AvoidDollarSigns
- codestyle.xml/DontImportJavaLang
- codestyle.xml/ClassNamingConventions
- bestpractices.xml/AvoidReassigningParameters
- bestpractices.xml/PreserveStackTrace
- bestpractices.xml/UnusedLocalVariable
- bestpractices.xml/UnusedPrivateField
- bestpractices.xml/SwitchStmtsShouldHaveDefault

Here are some rules that work fine both under Java 8 and 11:

- bestpractices.xml/AvoidPrintStackTrace
- bestpractices.xml/DefaultLabelNotLastInSwitchStmt
- bestpractices.xml/OneDeclarationPerLine
- bestpractices.xml/PositionLiteralsFirstInCaseInsensitiveComparisons
- bestpractices.xml/PositionLiteralsFirstInComparisons
- codestyle.xml/AvoidProtectedFieldInFinalClass
- codestyle.xml/CallSuperInConstructor
 

**Code Sample demonstrating the issue:**

I created a [demo project](https://github.com/ksilz/check-pmd). Please clone it and run the following command under Java 11: `./gradlew clean pmdMain` You should see the failure in an output like below. Please note both the Java version and the target compatibility are printed:

````
check-pmd [master] $ ./gradlew clean pmdMain

> Task :compileJava
  JVM vendor:           Eclipse OpenJ9
  JVM name:             Eclipse OpenJ9 VM
  Java version:         11.0.5
  Target Compatibility: 11

> Task :pmdMain
/Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java    -       Error while processing /Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
check-pmd [master] $
````

Now if you change [line 15 in `build.gradle`](https://github.com/ksilz/check-pmd/blob/master/build.gradle) to `targetCompatibility = 1.8`, then it works just fine:

````
check-pmd [master] $ ./gradlew clean pmdMain

> Task :compileJava
  JVM vendor:           Eclipse OpenJ9
  JVM name:             Eclipse OpenJ9 VM
  Java version:         11.0.5
  Target Compatibility: 1.8

BUILD SUCCESSFUL in 2s
3 actionable tasks: 3 executed
check-pmd [master !] $
````

I tried this with two different Java 11 JVMs, Hotspot and OpenJ9. They both behaved the same:

````
check-pmd [master !] $ ./gradlew clean pmdMain
Starting a Gradle Daemon, 3 incompatible and 16 stopped Daemons could not be reused, use --status for details

> Task :compileJava
  JVM vendor:           Eclipse OpenJ9
  JVM name:             Eclipse OpenJ9 VM
  Java version:         11.0.5
  Target Compatibility: 11

> Task :pmdMain
/Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java    -       Error while processing /Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java

BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed
check-pmd [master *] $ j11h

Using java version 11.0.5.hs-adpt in this shell.
check-pmd [master *] $ ./gradlew clean pmdMain

> Task :compileJava
  JVM vendor:           AdoptOpenJDK
  JVM name:             OpenJDK 64-Bit Server VM
  Java version:         11.0.5
  Target Compatibility: 11

> Task :pmdMain
/Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java    -       Error while processing /Users/karsten/workspaces/me/services/hs/research/check-pmd/src/main/java/com/bpf/test/pmd/Main.java

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
check-pmd [master *] $ ./gradlew clean pmdMain

> Task :compileJava
  JVM vendor:           AdoptOpenJDK
  JVM name:             OpenJDK 64-Bit Server VM
  Java version:         11.0.5
  Target Compatibility: 1.8

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
check-pmd [master !] $ j11j

Using java version 11.0.5.j9-adpt in this shell.
check-pmd [master !] $ ./gradlew clean pmdMain
Starting a Gradle Daemon, 3 incompatible and 17 stopped Daemons could not be reused, use --status for details

> Task :compileJava
  JVM vendor:           Eclipse OpenJ9
  JVM name:             Eclipse OpenJ9 VM
  Java version:         11.0.5
  Target Compatibility: 1.8

BUILD SUCCESSFUL in 5s
3 actionable tasks: 3 executed
check-pmd [master !] $ j8

Using java version 8.0.232.hs-adpt in this shell.
check-pmd [master !] $ ./gradlew clean pmdMain

> Task :compileJava
  JVM vendor:           AdoptOpenJDK
  JVM name:             OpenJDK 64-Bit Server VM
  Java version:         1.8.0_232
  Target Compatibility: 1.8

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
check-pmd [master !] $
````

**Comment by jsotuyod** [comment]
Thanks for the report.

Just by a quick scan of your sample project… you are **not** using PMD 6.20.0, but 6.2.0, as per https://github.com/ksilz/check-pmd/blob/8ff2e27bb057e2440a34d54e090d49400ae8e8c4/build.gradle#L22

Java 11 compatibility was added in PMD 6.6.0, so having it fail when loading Java 11 bytecode would be expectable.

**Comment by ksilz** [comment]
Yep, that's it. A stupid typo on my end... Thank you for pointing that out to me!
