### ISSUE TITLE
[java] SuspiciousEqualsMethodName: Improve description about error-prone overloading of equals()

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2264]
**Affects PMD Version:** 6.21.0

**Rule:** [SuspiciousEqualsMethodName](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#suspiciousequalsmethodname)

**Description:**

I like to write code as the sample below shows.  The `equals(Object)` method checks the class of `other` and calls `equals(MyClass)` if applicable.  This provides a few possible performance optimizations.  First, if `javac` knows that the parameter is of type `MyClass`, then it will call `equals(MyClass)` directly and thereby skip the performance impact of `instanceof` operator.  Second, if JIT knows that the parameter is always of type `MyClass`, then it will write the executable code to call `equals(MyClass)` directly.

The problem is that `SuspiciousEqualsMethodName` flags the code and could cause programmers to miss the potential optimizations.  On the other hand, classes that derive from `MyClass` have to override both `equals()` and thus having two `equals()` is error prone.  (Perhaps a PMD rule could catch this.)

So, I post this as something to consider knowing it may not be a good idea to change `SuspiciousEqualsMethodName`.

**Code Sample demonstrating the issue:**

``` java
public class MyClass
{
   public boolean equals(Object other)
   {
      if (other instanceof MyClass)
         return(equals((MyClass) other);

      return(false);
   }

   public boolean equals(MyClass other)
   {
      ...
   }
}
```

**Running PMD through:** Eclipse

**Comment by tweimer** [comment]
Well, I do not see much (if any) performance gain from this, as all generic containers do not have that knowledge. It will just make the code harder to maintain and error-prone with regard to inheritance.

None of the JDK classes (or *any* other class) i have seen have such an overload, and I'm quite sure they would have it if there would be any performance gain.

Do you have any measurements about performance in a real-world-scenario?

However, that rule could be ignored if a valid override does exist.

**Comment by numeralnathan** [comment]
> It will just make the code harder to maintain and error-prone with regard to inheritance.

Agreed.  If `SuspiciousEqualsMethodName` is made to no longer flag this case, then we would need another PMD rule to flag when a deriving class does not override all of the `equals` methods.

> None of the JDK classes ... have such an overload

I would think that they understand the above problem of having multiple `equals` methods and avoid doing so since there are no tools that would flag not overriding all of the `equals` methods.  Even if there were tools, not everyone would use the tools.

> I do not see much ... performance gain

Let's assume JIT is able to optimize `other instanceof MyClass` into loading the class id from `other`'s header and check if it is equal to a constant for `MyClass`'s id.  If the check is predictable (i.e. always true or false), then the x86 processor will be able to do the whole thing in 6 cycles.  Measuring 6 cycles in the real world would be very tough.  However, I already know that `javac` does the optimization by calling `equals(MyClass)` directly instead of `equals(Object)`.

Why would we bother if the performance gain is only 6 cycles?  6 rain drops do not make a river.  However, when 6 rain drops combine with 6 more rain drops and more and more, then you have a river.  Likewise, if everyone were to do this optimization, individual software performance may not be very noticeable.  However, the global impact will be significant.

**Comment by oowekyala** [comment]
> However, I already know that javac does the optimization by calling equals(MyClass) directly instead of equals(Object).

The JIT speculates on the type of values, and on their nullity. Type checks are eliminated on paths where the JIT knows that the operand is of a given type, just like null checks or array bounds checks are eliminated. This is much more powerful and general than what the static "optimisation" you describe can do.

@tweimer raises excellent points too. Many usages of `equals` that matter are in collection classes, where your optimisation is lost. The JIT also doesn't do double-dispatch. If your equals call is not on a hot path, then your 6 cycles don't matter at all. If it is on a hot path, then the method will most likely be inlined, which allows the JIT to eliminate more checks, based on speculative info at the call site. If it's inlined, then whether you dispatch to equals(Object) or equals(MyClass) doesn't matter anymore.

Tbh the JIT developers have probably already thought about this at length, and it's useless to try to outsmart them. Duplicating an equals method just adds brittle boilerplate to your code.

**Comment by Fernal73** [comment]
Anything actionable here?

**Comment by numeralnathan** [comment]
I am thinking there is nothing actionable here.  I do not think I have convinced @oowekyala or @tweimer of the usefulness.  I was dubious to begin with.

**Comment by Fernal73** [comment]
https://stackoverflow.com/questions/2910520/best-practices-regarding-equals-to-overload-or-not-to-overload#comment106234807_2910520

There's this StackOverflow post that discusses just this. Apart from Clement's bit about JIT inlining, everything else has been discussed threadbare. Am I missing something? Does this rule need to be changed in any way?

**Comment by tweimer** [comment]
@Fernal73 The first answer in that stackoverflow post is pretty much my point:

> I'dont see the case for overloading equals, except that is more error-prone and harder to maintain, especially when using inheritance.
> 
> Here, it can be extremly hard to maintain reflexivity, symmetry and transitivity or to detect their inconsistencies, because you always must be aware of the actual equals method that gets invoked. Just think of a large inheritance hierarchie and only some of the types implementing their own overloading method.
> 
> So I'd say just don't do it.

Also, if there would be an actual performance improvement, the JDK creators would have used it in their own classes. For example, String is final, so none of the inheritance arguments above do apply here, and String.equals is propably one of the most used equal methods ever. ´There is not a single class in the whole JDK that implements equals with overloads.

**Comment by Fernal73** [comment]
So should we allow a private method overloading in the rule?

**Comment by tweimer** [comment]
> So should we allow a private method overloading in the rule?

In my opinion you shouldn't. But it's not my decision to make.

**Comment by Fernal73** [comment]
To be frank, I've yet to encounter a flagging for this method. But I can see why someone would like to overload this method albeit as a private one. 

https://pmd.github.io/latest/pmd_rules_java_errorprone.html#suspiciousequalsmethodname

**Comment by adangel** [comment]
Let's improve the description of the rule to say additionally, that overloading equals is error-prone and harder to maintain, especially when using inheritance. Equals must implement an equivalence relation with certain properties (reflexive, symmetric, transitive, consistent) - see https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/Object.html#equals(java.lang.Object).

We won't change the rule as-is. If you want to create a private method to help in the implementation, you can do so - as long as you don't call this method equals...
