### ISSUE TITLE
[java] New Rule: Enum constants should be long enough to have descriptive, self-documenting names

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2266]
**Rule:** ShortEnumConstant

**Description:**

Just like class, method and field names, enum constants should be long enough to be descriptive and self-documenting.

**Code Sample demonstrating the issue:**

```
public enum Operation
{
   EqualTo,   // Descriptive and okay
   NE;        // Too short to be descriptive and self-documenting
}
```

**Rule Definition:**

```
   <rule name="ShortEnumConstant"
         language="java"
         message="Enums should have descriptive, self-documenting names"
         class="net.sourceforge.pmd.lang.rule.XPathRule">
      <description>Enums should be long enough to have descriptive, self-documenting names</description>   
      <priority>3</priority>
      <properties>
         <property name="xpath">
            <value>
               <![CDATA[
                  //EnumConstant[string-length(@Image) < 3]
               ]]>
            </value>
         </property>
      </properties>
      <example>
         <![CDATA[
            public enum Operation
            {
               EqualTo,   // Descriptive and okay
               NE;        // Too short to be descriptive and self-documenting
            }
         ]]>
      </example>
   </rule>
```

**Comment by adangel** [comment]
Hm... this should already be possible by using [FieldNamingConventions](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#fieldnamingconventions):

``` xml
<rule ref="category/java/codestyle.xml/FieldNamingConventions">
    <properties>
        <property name="enumConstantPattern" value=".{3,}" />
    </properties>
</rule>
```

So I don't think, we need an additional rule.
We might need some more example ruleset configurations...

**Comment by numeralnathan** [comment]
@adangel Thanks for the solution.  Consider changing the default values for the properties for [FieldNamingConventions](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#fieldnamingconventions) to have `{2,}` instead of `*`.  This would ensure all of the names would be at least 3 characters.

**Comment by adangel** [comment]
I think, the default values are generic enough and don't need to be adjusted. I've created an issue for having preconfigured naming convention rulesets though.
