### ISSUE TITLE
[doc] Java API documentation for PMD

### ISSUE THREAD

**Issue by clsaa** [pmd/pmd#2274]
Is there any Java API document for PMD, especially some quick start and features documents? I want to import PMD through Maven in my Java project. And use Java call the PMD interface to implement some code checking.

**Comment by adangel** [comment]
Hi @clsaa,

There is no explicit Java API yet, but I have written something up now: See #2283. Is this, what you need?

You mention, that you use Maven. Are you aware, that there is a maven plugin for pmd already? https://maven.apache.org/plugins/maven-pmd-plugin/ and https://pmd.github.io/latest/pmd_userdocs_tools_maven.html

**Comment by clsaa** [comment]
Great! This is exactly what I need. Thank you very much!
I have known the plugin.
The purpose of my project using PMD is to static code check(for DDD constraint), which provides as IDE's plugin and cloud service.
