### ISSUE TITLE
[java] Negative performance impact of UseConcurrentHashMap

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2310]
**Affects PMD Version:** 

6.21.0

**Rule:**

`UseConcurrentHashMap`

**Description:**

The rule `UseConcurrentHashMap` encourages programmers to use `ConcurrentHashMap` instead of `HashMap`.  This seems like a premature optimization.

For single-threaded use, a `ConcurrentHashMap` is a bad idea since it has a significant performance impact.  `ConcurrentHashMap`s are heavy in terms of CPU performance and heap space.

For multi-threaded use, I use synchronization around a `HashMap` since most of the time locks are not contended.  This avoids the CPU and heap penalties of `ConcurrentHashMap`.  Once the lock becomes a bottleneck, I switch to `ConcurrentHashMap`.

Please enhance `UseConcurrentHashMap` to only trigger if the `Map` is used as the lock for a `synchronized` block or the `Map` is only used inside `synchronized` blocks.

Please enhance the documentation to talk about when it is a good idea to use a `ConcurrentHashMap`.  This way the programmer can make a better informed decision.  

**Running PMD through:** Eclipse

**Comment by Fernal73** [comment]
https://github.com/pmd/pmd/issues/1022
