### ISSUE TITLE
[java] Documenation for DoNotUseThreads is outdated

### ISSUE THREAD

**Issue by franciscodua** [pmd/pmd#2313]
**Rule:**
[DoNotUseThreads](https://pmd.github.io/latest/pmd_rules_java_multithreading.html#donotusethreads)

**Description:**
The documentation in [here](https://pmd.github.io/pmd/pmd_rules_java_multithreading.html#donotusethreads) still shows Runnable as a problematic pattern. However, according to [this issue](https://github.com/pmd/pmd/issues/1627) this is no longer the case. Running the tool doesn't flag Runnable either.

--> The example needs to be updated to not show "Runnable" as problematic:
https://github.com/pmd/pmd/blob/90f286a4a156ecb467eec76c96d2bd3a233860f9/pmd-java/src/main/resources/category/java/multithreading.xml#L142-L157

**Comment by s4ik4t** [comment]
May I fix this?

**Comment by adangel** [comment]
Sure! PRs are welcome!

**Comment by s4ik4t** [comment]
> Sure! PRs are welcome!

Tried to fix in PR #2401
