### ISSUE TITLE
[java] Parse errors with yield statement

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2319]
**Affects PMD Version:** 6.21.0

**Description:** Our parser is not conservative enough when it comes to parsing yield statements. For now javac has the following behaviour:
- [ ] yield *may* only start a yield statement inside a switch
- [ ] even in this case, yield is only tokenized as a statement if it's followed by a token that may start an expression (eg not `=`), allowing `yield = 0;` to parse as an assignment
- [ ] if it's followed by an opening parenthesis, javac counts the commas (balancing parentheses), to allow eg `yield(a,b);` or `yield((a),b);` to parse as method calls

https://hg.openjdk.java.net/jdk/jdk/file/bc3da0226ffa/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#l2580

**Code Sample demonstrating the issue:**

```java
class Foo {
 {
  int yield = 0;
  yield = 0; // not even inside a switch  (currently an error)
  yield(2);  // not even inside a switch, should be a method call  (currently an error)

  switch (e) {
    case 1 -> {
       yield(a,b); // should be a method call     (currently an error)
       yield = 2;  // should be an assignment     (currently an error)
       yield (2);  // should be a yield statement (currently ok)
    }
  }
 }
}
```

The parse exception is either `yield statements are only supported on java 13 preview` or 
```
Encountered "=" at line ....
Was expecting one of:
    "++" ...
    "--" ...
    "+" ...
    "-" ... 
```

**Comment by adangel** [comment]
We might have a similar case with `var` and now with `record`. All three "keywords" are not real keywords, but so called restricted identifiers: 

https://docs.oracle.com/javase/specs/jls/se13/html/jls-3.html#jls-3.9

> var is not a keyword, but rather an identifier with special meaning as the type of a local variable declaration (§14.4, §14.14.1, §14.14.2, §14.20.3) and the type of a lambda formal parameter (§15.27.1). 

https://docs.oracle.com/javase/specs/jls/se13/preview/switch-expressions.html#jep354-3.9

> The restricted identifiers var and yield are not keywords. var has special meaning as the type of a local variable declaration (14.4, 14.14.1, 14.14.2, 14.20.3) and the type of a lambda formal parameter (15.27.1). yield has special meaning in a yield statement (14.21). All invocations of a method called yield must be qualified so as to be distinguished from a yield statement.

http://cr.openjdk.java.net/~gbierman/jep359/jep359-20191121/specs/records-jls.html#jls-3.9

> The restricted identifiers var and record are not keywords. var has special meaning as the type of a local variable declaration (14.4, 14.14.1, 14.14.2, 14.20.3) and the type of a lambda formal parameter (15.27.1). record has a special meaning in a record type declaration (8.10).
