### ISSUE TITLE
Add topics to PMD's github project

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#233]
Recently GitHub released a new features called [topics](https://github.com/blog/2309-introducing-topics), which are basically tags.

We should add tags to help discovery / search. My suggested topics:
 - code-analysis
 - code-quality
 - static-analysis
 - static-code-analysis
 - linter
 - java
 - apex
 - plsql
 - swift

Feel free to suggest more!

**Comment by adangel** [comment]
I've added the topics.
