### ISSUE TITLE
add a rule in PMD to find the missing method

### ISSUE THREAD

**Issue by darrenmiliband** [pmd/pmd#2351]
Hi there,
I'm trying to add a rule in PMD so it can identify the missing method. for instance in the following lines, I want to add a rule if user misses typing  "super.onRestoreInstanceState(savedInstanceState) " this will raise an error. can you please help me . I really appreciate your time.
Many Thanks

```kotlin
override fun onRestoreInstanceState(savedInstanceState: Bundle?) {
    // Always call the superclass so it can restore the view hierarchy
    super.onRestoreInstanceState(savedInstanceState)

    // Restore state members from saved instance
    savedInstanceState?.run {
        currentScore = getInt(STATE_SCORE)
        currentLevel = getInt(STATE_LEVEL)
    }
}
```

**Comment by adangel** [comment]
Thanks for the suggestion.
Your code sample looks like Kotlin, which is not supported by PMD.
For Java, there is a similar rule which you could use as a base: [CallSuperFirst](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#callsuperfirst). This rule is targeted at the Android SDK, but you could easily take this and adjust it for your use case (given, that you analyze **Java** code...).
More info about rule development is here: https://pmd.github.io/latest/pmd_userdocs_extending_writing_rules_intro.html

**Comment by darrenmiliband** [comment]
Hi Andreas,
 Thank you so much for your prompt response. I apologise, you were right,
sorry I copied the kotlin version of the code by accident. the following is
the code in Java and I need to add a rule to PMD so if "
super.onRestoreInstanceState(savedInstanceState)"
is missing the rule can detect it as a bug, can you please help me? I have
adjusted the link that you sent me to the following, can you kindly please
check it and let me know if this code is the correct one?
thank you so much for your time and help in advance.
Darren.


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

*Code to detect the bug*

//MethodDeclaration[

  @Name='onRestoreInstanceState'  ]

    /Block[not(

      (BlockStatement[1]/Statement/StatementExpression/PrimaryExpression[./PrimaryPrefix[@SuperModifier='true']]/PrimarySuffix[@Image=
ancestor::MethodDeclaration/@Name]))]

[ancestor::ClassOrInterfaceDeclaration[ExtendsList/ClassOrInterfaceType[

  pmd-java:typeIs('android.app.Activity') or

  pmd-java:typeIs('android.app.Application') or

  pmd-java:typeIs('android.app.Service')

]]]


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*The Code* *that needs to be checked for missing *
" super.onRestoreInstanceState(savedInstanceState)"

public void onRestoreInstanceState(Bundle savedInstanceState) {
    // Always call the superclass so it can restore the view hierarchy
    super.onRestoreInstanceState(savedInstanceState);

    // Restore state members from saved instance
    currentScore = savedInstanceState.getInt(STATE_SCORE);
    currentLevel = savedInstanceState.getInt(STATE_LEVEL);
}
