### ISSUE TITLE
Add code of conduct: Contributor Covenant

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2357]
* That's (besides from issue templates #2286) the only missing piece: https://github.com/pmd/pmd/community
* More info about code of conduct: https://opensource.guide/code-of-conduct/

I propose to adopt https://www.contributor-covenant.org/

**Comment by oowekyala** [comment]
This looks fine to me. We'll need to clear up the details of the contact method:
* We maintainers already all have a public email address on our github profile, but afaik there's no document in the repo that designates us as maintainers.
* Would it be useful to create a single email address, eg `community@pmd-code.org`?

**Comment by adangel** [comment]
`community@...` sounds a bit too general IMHO. Maybe `moderators@...` is better?

It will be forwarding to all maintainers.
