### ISSUE TITLE
[java] New Rule: UnnecessaryLocal

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#241]
**Rule Set:** probably java-unnecessary

**Description:**
See discussion in #221:
> this rule could be expanded to all "unnecessary" variables, not just return statements. We could add a property to allow such variables if declared as final. The Java code will produce an extra store / load instruction in bytecode, but being final, the JIT will remove them and effectively be the same for long running processes.

Also deprecate the rule `UnnecessaryLocalBeforeReturn`

We should think about the following problem: if the whole java-design ruleset is active, and we have both rules `UnnecessaryLocalBeforeReturn` and the new `UnnecessaryLocal`, they might report the same issues...

**Comment by jsotuyod** [comment]
There is already a `UnusedLocalVariable` rule in the unused ruleset, which could also have some collisions with this.

**Comment by adangel** [comment]
So we should have already an overlapping between [`UnnecessaryLocalBeforeReturn`](https://pmd.github.io/pmd-5.5.3/pmd-java/rules/java/design.html#UnnecessaryLocalBeforeReturn) and [`UnusedLocalVariable`](https://pmd.github.io/pmd-5.5.3/pmd-java/rules/java/unusedcode.html#UnusedLocalVariable)?

**Comment by jsotuyod** [comment]
No. `UnusedLocalVariable` is usages == 0, ie: `int x = 9;` and no further references to `x` found.

`UnnecessaryLocalBeforeReturn` is `int x = 9; return x;`.

However, if we use the symbol table info and check for usages < 2 as discussed we would match both, `UnusedLocalVariable` (usages == 0), and `UnnecessaryLocalBeforeReturn` (usages == 1).

We can probably keep `UnusedLocalVariable` and make the new rule only check for usages == 1.

**Comment by adangel** [comment]
You're right - seems like we can close the issue then....

**Comment by jsotuyod** [comment]
So, summing up.

**Rule Set:** probably java-unnecessary

The rule will check for each context if the [number of uses of the variable](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UnnecessaryLocalBeforeReturnRule.java#L52) **is exactly 1**. If it is, it will check if it's final and the corresponding property to ignore finals is true.

By definition, all errors currently reported by `UnnecessaryLocalBeforeReturn` will be covered by this rule too. Not the other way around.

Shall `UnnecessaryLocalBeforeReturn` be deprecated? Disabled automatically upon finding both rules configured? Add a flag to the new rule to only check returned locals and keep the old behavior?

**Comment by jsotuyod** [comment]
The new rule should also consider annotated variables as valid, even if used only once. See #262

**Comment by jsotuyod** [comment]
This rule should also consider scenarios were a temp variable is needed because it's initialized with fields / variables that are later modified. See #282

**Comment by jsotuyod** [comment]
I'm having second thoughts about this rule. I've ceased to see scenarios were this would report on any case where:

1. it's not already detected by `UnnecessaryLocalBeforeReturn`
1. it's not a variable introduced for readability

If someone does see a use-case for this, please let me know, otherwise, I'd just drop it; and add a property on `UnnecessaryLocalBeforeReturn` to assume statement order matters (go back to the old behavior of having statements immediately follow one another) to solve issues such as #310
