### ISSUE TITLE
[java] XPath rule has different violations before and after compiling with Maven

### ISSUE THREAD

**Issue by MikeDombo** [pmd/pmd#2416]
**Affects PMD Version:** 
6.21.0, 6.22.0

**Description:**
I have written a custom XPath rule for Java to find instances where we call `get()` on a `Future` without a timeout. The rule is having different results (finding non-overlapping violations) when run in maven before vs. after compiling. If I do `mvn clean pmd:check` then it finds 1 true violation, however if I do `mvn compile test-compile pmd:check` then it finds 1 completely different violation (which is not a real violation anyway).

**Code Sample demonstrating the issue:**

```
<rule name="AvoidGettingFutureWithoutTimeout"
          language="java"
          message="Calls to 'get()' on Futures must have a timeout"
          class="net.sourceforge.pmd.lang.rule.XPathRule">
        <description>
            Calls to Future.get() will block forever. This is almost always undesirable.
            To mitigate this potential issue, all calls to Future.get() ought to have a timeout.
        </description>
        <priority>2</priority>
        <properties>
            <property name="version" value="2.0"/>
            <property name="xpath">
                <value>
                    <![CDATA[
//PrimaryExpression[pmd-java:typeIs("java.util.concurrent.Future") and (PrimaryPrefix/Name[contains(@Image, "get")] and PrimarySuffix[@ArgumentCount=0]) or (PrimarySuffix/MemberSelector/MethodReference[@Image="get"])]
]]>
                </value>
            </property>
        </properties>
    </rule>
```

True violation which is found pre-compilation:
```
Future f = new CompletableFuture<>();
f.get();
```

False violation after compilation (and the above true violation is missed):

```
AtomicReference<Future> ref = new AtomicReference<>(new CompletableFuture());
Future f = ref.get(); // have not yet called "get" on the future, so this should not fail, and the designer agrees with me.
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  `mvn clean pmd:check` -- View output shows some violation
2.  `mvn compile test-compile pmd:check` -- view that output shows completely separate violation

**Running PMD through:** Maven

Running with OpenJDK 8 on Mac.

**Comment by jsotuyod** [comment]
@MikeDombo this is stale, as PMD 7.0.0 completely rewrote it's type resolution logic. Feel free to open a new issue if you have any problems with that version.
