### ISSUE TITLE
[core] CodeClimate renderer links are dead

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2426]
The dead links checker reports the links
* `[PMD properties](https://pmd.github.io/pmd-6.22.0/pmd_devdocs_working_with_properties.html)`
* `[Categories](https://github.com/codeclimate/spec/blob/master/SPEC.md#categories)`

_Originally posted by @oowekyala in https://github.com/pmd/pmd/pull/2413/review_comment/create_

https://github.com/pmd/pmd/blob/491e51377573120e66f96d135d7378648b655660/pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java#L47-L47

Has been moved to https://pmd.github.io/latest/pmd_userdocs_configuring_rules.html#rule-properties

These two other links have moved i don't know where

https://github.com/pmd/pmd/blob/491e51377573120e66f96d135d7378648b655660/pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java#L149

https://github.com/pmd/pmd/blob/491e51377573120e66f96d135d7378648b655660/pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java#L151

**Comment by adangel** [comment]
The last two links to the CodeClimate SPEC, I've fixed already -> https://github.com/pmd/pmd/pull/2413/files#diff-585f902f0d53776784118420c8c01259L149-L152

I'll fix that for 6.23.0 as well, should be easy.
