### ISSUE TITLE
[apex] False Positives on ApexXSSFromURLParamRule

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#243]
FYI: @sergeygorbaty

**Rule:**

ApexXSSFromURLParamRule

**Description:**
This rule even seems to apply in cases where NO data is taken from the URL. Instead I construct a URL in my code. Eighter the detection is wrong or the error message.

**Code Sample demonstrating the issue:**

<img width="829" alt="cprm-pm_saveastemplatectrl_cls_at_master_ _up2go_cprm-pm" src="https://cloud.githubusercontent.com/assets/8180281/22733357/b8434eca-edf1-11e6-984b-bb5633a0cca2.png">

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
CodeClimate engine ApexMetrics

**Comment by sgorbaty** [comment]
@up2go-rsoesemann I will definitely investigate. Could you point me to the whole class?

**Comment by up2go-rsoesemann** [comment]
@sgorbaty it's a class in a private repo therefore I can't. But just add a PMD test using 23 and 24 should show the problem.

**Comment by sgorbaty** [comment]
@up2go-rsoesemann  Could you check if `bpiId` or `bpiType` were populated from a URL in another method?

**Comment by up2go-rsoesemann** [comment]
OMD. A false false positive. I didn't expect you rule to be that smart.
