### ISSUE TITLE
[core] Deprecate support for List attributes with XPath 2.0

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2451]
Part of #2523

When we update Saxon on PMD 7, attributes of type List (`List<String>`) won't work anymore, since with newer Saxon versions, attributes are supposed to be always non-sequences.

That's why we should deprecate the usage of such attributes for XPath (via `@DeprecatedAttribute`).

**Affects PMD Version:** 6.x + 7

**Affected Attributes:**
I grepped our code (`find -wholename "*/lang/*/ast/*.java"|grep -i -v test|grep -v generated-sources | xargs grep "List<"`) and found only these usages:

```
./pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTReferenceExpression.java:51:    public List<String> getNames() {
./pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserTrigger.java:41:    public List<TriggerUsage> getUsages() {
./pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTFieldDeclarationStatements.java:62:    public List<String> getTypeArguments() {
```

All are in Apex and could be potentially used by some XPath 2.0 rule. (TriggerUsage is a enum). I didn't find any usage of these getters/attributes in our apex rules.

**Note**
* This is a requirement for PMD 7, so that we can update Saxon
* It only affects XPath 2.0 rules, for Jaxen, we already filter out Lists (see `net.sourceforge.pmd.lang.ast.xpath.DocumentNavigator.ListFilteringAttributeIterator`).
* Not sure, whether we really need to provide an alternative right now to make Lists accessible in XPath. I'd rather wait until we have a concrete use case before we start inventing something.
* This also relates to List properties (#736). I didn't investigate yet, what the consequences are.

**Proposed Steps:**
* [x] Deprecate the three apex getters for XPath
* [x] Update documentation, if any. Maybe fix xpath example queries.
* [x] Mention this in the release notes

**Comment by oowekyala** [comment]
> Not sure, whether we really need to provide an alternative right now to make Lists accessible in XPath. I'd rather wait until we have a concrete use case before we start inventing something.

I agree with that. If those are useful in XPath there there's always the possibility to add a custom function. So instead of writing `@TypeArguments` you'd write eg `pmd-apex:typeArguments()`

> This also relates to List properties (#736). I didn't investigate yet, what the consequences are.

Apparently this still works, I added a test for it:

http://github.com/oowekyala/pmd/blob/4fb56bf32c7fe25b44592659642e5ab1cd6dfb54/pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQueryTest.java#L52-L60
