### ISSUE TITLE
Minimum set of jars required for Apex

### ISSUE THREAD

**Issue by ChuckJonas** [pmd/pmd#2459]
**Description:**
I manage the vscode apex pmd extension.  I include a copy of PMD in the extension to make setup as easy as possible.

Right now I'm just including the entire binary, but I was wondering if I could remove unnecessary weight. 

I'm guessing I could get rid of all the language specific jars? (eg: `pmd-go.jar`, `pmd-java.jar`)

Would be good to get it down the the minimum set.

**Comment by oowekyala** [comment]
Thanks for maintaining that plugin!

I created a sample POM for your use case: https://github.com/pmd/pmd-examples/tree/apex-only-dist#apex-only-distribution

The zip is 18 MB instead of 60. Does this do the trick?

**Comment by ChuckJonas** [comment]
hmm... my java capabilities are pretty poor.

I guess I would need to install mavens & mavenswrapper to use this?  Would this always grab  the latest version, or would it need to be updated?

I currently am just using curl to upgrade via the lastest github release:

```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rm -rf ${DIR}/pmd/*
VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq --raw-output ".tag_name")
DOWNLOAD_URL=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | jq --raw-output ".assets[].browser_download_url" | grep pmd-bin)
echo "version=${VERSION}"
echo "url=${DOWNLOAD_URL}"
curl $DOWNLOAD_URL -L -o ${DIR}/pmd.zip
bsdtar --strip-components=1 -xvf ${DIR}/pmd.zip -C ${DIR}/pmd
rm ${DIR}/pmd.zip
```

I was planning on just updating the script to grab only the jars that I needed.

I looked through the source from the repo you linked but did see where the jars were referenced...

**Comment by oowekyala** [comment]
The maven wrapper installs maven automatically if it's missing. So you don't need to install maven explicitly, just run `./mvnw` instead of `mvn`. The pom uses this property for the pmd version:

https://github.com/pmd/pmd-examples/blob/apex-only-dist/pom.xml#L14

Because of this this pom will build pmd 6.23.0, but you can change that:
* To build a specific version: `./mvnw clean package -Dpmd.version=6.25.0`
* To update the property to the latest released version: `./mvnw versions:update-properties` (this will modify the pom file)

A simple update script could be
```
./mvnw versions:upate-properties
./mvnw clean package -Dpmd.dist.bin.baseDirectory=pmd # change the zip name so it is not version-dependent
mv target/pmd.zip $DIR
# .. extract, etc
```

The dependencies are described here

https://github.com/pmd/pmd-examples/blob/apex-only-dist/pom.xml#L79-L85

The beauty of it is that maven resolves the necessary transitive dependencies itself and packs only those. 

I realise now that probably this script executes on the end user machines, so maybe downloading maven is not an option... Other possible options to continue using your script:
* use the pom I linked once at home, and `ls` the lib dir to make a list of jars to keep. You'll have to check this list for changes every time you upgrade the pmd version. 
   * alternatively, use the maven dependency plugin in a pmd clone (sample output below), but you'll have to do some cleanup to end up with the jar names
* make a dummy github repo whose release page just publishes the reduced zip (which you build at home with the custom pom), then use that release url instead of the main pmd repo

All of those involve some degree of manual maintenance though, and upgrades won't be incremental as maven would do.

```java
@~/Documents/Git/pmd (master) $ mvn dependency:list -DincludeScope=runtime -pl pmd-apex
...
[INFO] The following files have been resolved:
[INFO]    com.google.code.findbugs:jsr305:jar:3.0.2:compile -- module jsr305 (auto)
[INFO]    com.google.guava:guava:jar:26.0-jre:compile -- module com.google.common [auto]
[INFO]    net.java.dev.javacc:javacc:jar:5.0:compile
[INFO]    net.sourceforge.pmd:pmd-apex-jorje:pom:6.24.0-SNAPSHOT:compile
[INFO]    net.sourceforge.saxon:saxon:jar:dom:9.1.0.8:runtime -- module saxon (auto)
[INFO]    aopalliance:aopalliance:jar:1.0:compile -- module aopalliance (auto)
[INFO]    com.google.j2objc:j2objc-annotations:jar:1.1:compile -- module j2objc.annotations (auto)
[INFO]    org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile -- module animal.sniffer.annotations (auto)
[INFO]    net.sourceforge.saxon:saxon:jar:9.1.0.8:compile -- module saxon (auto)
[INFO]    com.beust:jcommander:jar:1.72:compile -- module jcommander (auto)
[INFO]    antlr:antlr:jar:2.7.7:compile -- module antlr (auto)
[INFO]    commons-io:commons-io:jar:2.6:compile -- module org.apache.commons.io [auto]
[INFO]    org.antlr:stringtemplate:jar:3.2.1:compile -- module stringtemplate (auto)
[INFO]    net.sourceforge.pmd:pmd-apex-jorje:jar:lib:6.24.0-SNAPSHOT:compile -- module pmd.apex.jorje (auto)
[INFO]    org.antlr:antlr-runtime:jar:3.5.2:compile -- module antlr.runtime (auto)
[INFO]    org.yaml:snakeyaml:jar:1.17:compile -- module snakeyaml (auto)
[INFO]    com.google.errorprone:error_prone_annotations:jar:2.1.3:compile -- module error.prone.annotations (auto)
[INFO]    cglib:cglib:jar:3.2.0:compile -- module cglib (auto)
[INFO]    org.antlr:antlr4-runtime:jar:4.7:compile -- module antlr4.runtime (auto)
[INFO]    javax.inject:javax.inject:jar:1:compile -- module javax.inject (auto)
[INFO]    org.apache.commons:commons-lang3:jar:3.8.1:compile -- module org.apache.commons.lang3 [auto]
[INFO]    net.sourceforge.pmd:pmd-core:jar:6.24.0-SNAPSHOT:compile -- module pmd.core (auto)
[INFO]    com.google.code.gson:gson:jar:2.8.5:compile -- module gson (auto)
[INFO]    org.apache.ant:ant-launcher:jar:1.10.1:compile -- module ant.launcher (auto)
[INFO]    org.slf4j:slf4j-api:jar:1.7.25:compile -- module slf4j.api (auto)
[INFO]    org.apache.ant:ant:jar:1.10.1:compile -- module ant (auto)
[INFO]    ch.qos.logback:logback-classic:jar:1.1.7:compile -- module logback.classic (auto)
[INFO]    org.openjdk.jol:jol-core:jar:0.4:compile -- module jol.core (auto)
[INFO]    org.ow2.asm:asm:jar:7.3.1:compile -- module org.objectweb.asm
[INFO]    org.checkerframework:checker-qual:jar:2.5.2:compile -- module checker.qual (auto)
[INFO]    ch.qos.logback:logback-core:jar:1.1.7:compile -- module logback.core (auto)
```

**Comment by ChuckJonas** [comment]
Thanks, that really clears things up!

The goal is eventually to get to a place where the PMD dist can be upgraded without updating the vscode extension, but as of now I'm actually just packaging it with the extension.  

For now this should be sufficient.  The idea of having a repo somewhere with would work well

I think the most ideal would be to actually just have a separate release on this repo with the apex specific release... While I think you could probably do most the work via CI, that does open up a big can of worms if you then are expected to do the same for every language.

**Comment by ChuckJonas** [comment]
There's also been quite a few request to support other languages on my extension (mainly java).

It actually wouldn't require much effort, but I've been hesitant, simply because I know that will open it up to more support requests.

But, if I was going to do that, I would need to have the entire dist downloaded AFTER they install the extension anyways... so that would simplify things

**Comment by ChuckJonas** [comment]
looks like the VisualForce jars are missing (sorry should have specified: "minimum set of jars for salesforce languages".

Can you walk me through how I would add those to this build?

**Comment by oowekyala** [comment]
> The goal is eventually to get to a place where the PMD dist can be upgraded without updating the vscode extension, but as of now I'm actually just packaging it with the extension.

This might be a problem with other IDE integrations too...  It would be nice to have a tool to manage a local pmd distribution module by module, sort of like a package manager. Ideally we could use the system package manager, but this is another can of worms

> I think the most ideal would be to actually just have a separate release on this repo with the apex specific release... While I think you could probably do most the work via CI, that does open up a big can of worms if you then are expected to do the same for every language.

Yes I think this is not really where we want to go. If you use another github repo then possibly you can setup your own CI there though

> looks like the VisualForce jars are missing (sorry should have specified: "minimum set of jars for salesforce languages".

Looks like another reason why we shouldn't have our CI publish reduced distributions directly :smile: The needs of users change.

> Can you walk me through how I would add those to this build?

I added some info here https://github.com/pmd/pmd-examples/tree/apex-only-dist#dependencies

Let me know if you have trouble.

**Comment by ChuckJonas** [comment]
>This might be a problem with other IDE integrations too... It would be nice to have a tool to manage a local pmd distribution module by module, sort of like a package manager. Ideally we could use the system package manager, but this is another can of worms

Ya I was thinking I could have the an "Enable Languages" in vscode settings.json and then i would resolve the dependencies as needed...  However, it does seem like more trouble than it's worth.  Keeping the vscode package size down is somewhat important, but does it really matter if an extra 40-50mb is downloaded to the clients comp?  Probably not.

> Yes I think this is not really where we want to go. If you use another github repo then possibly you can setup your own CI there though

Ya, if I keep it apex only that's an easy enough route to go.. just clone the mavens wrapper and and a github action that reads the target version, creates the dist and then adds a new release.

Anyways, this is more than sufficient for now... 

Thanks for the help!
