### ISSUE TITLE
[java] LooseCoupling must ignore class literals: ArrayList.class

### ISSUE THREAD

**Issue by rxmicro** [pmd/pmd#2464]
**Affects PMD Version:** 

6.23.0.

**Description:**

**LooseCoupling** must ignore class literals. For Example **ArrayList.class**

**Code Sample demonstrating the issue:**

```
void someMethod(Object o){
       if ( o.getClass() == ArrayList.class ) { // This case must be ignored by rule!
             // do something
       }
}
```

**Running PMD through:** *Maven*

**Comment by adangel** [comment]
This has been fixed with PMD 7.0.0-rc1.
