### ISSUE TITLE
[apex] @SuppressWarnings has no effect

### ISSUE THREAD

**Issue by anmolgkv** [pmd/pmd#2482]
**Affects PMD Version:** 
 PMD 6.0.0

**Description:**
Even after adding @SuppressWarnings('PMD.EmptyStatementBlock') PMD shows 

> Avoid empty block statements warning message

**Code Sample demonstrating the issue:**

```
public class Foo {

   private Integer _bar;

   @SuppressWarnings('PMD.EmptyStatementBlock') 
   public void setBar(Integer bar) {
        // empty
   }

}
```

**Running PMD through** *Codacy*

**Comment by rsoesemann** [comment]
Codacy is running PMD 6.23 I think. Can you please check if PMD in the command line or using the ApexPMD plugin in Vscode shows the same issue? I assume it’s a Codacy issue.

**Comment by anmolgkv** [comment]
Yes looks like it was a temporary thing with Codacy. It works fine in my vscode.
