### ISSUE TITLE
[apex] NCSS Type length is incorrect when using method chaining

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#251]
**Rule Set:** apex-complexity

**Description:**

Follow up on #183. Line count for types is incorrectly computed.

**Code Sample demonstrating the issue:**

https://dl.dropboxusercontent.com/u/240888/WrongNcssCount.cls

PMD says The type has an NCSS line count of 704 although there are only 486 lines.

**Running PMD through:** Any

**Comment by jsotuyod** [comment]
@up2go-rsoesemann there you go. New issue, and submitted a fix for PMD 5.5.4.

**Comment by up2go-rsoesemann** [comment]
Your are fantastic!
