### ISSUE TITLE
[java] MethodNamingConventions - JUnit 5 method naming not support ParameterizedTest

### ISSUE THREAD

**Issue by Casara** [pmd/pmd#2528]
**Affects PMD Version:** 6.24.0

**Rule:** [MethodNamingConventions](https://pmd.github.io/pmd-6.24.0/pmd_rules_java_codestyle.html#methodnamingconventions)

**Description:**

The PMD does not use the `junit5TestPattern` rule for tests annotated with `org.junit.jupiter.params.ParameterizedTest`.

**Code Sample demonstrating the issue:**

pmd.xml:
```xml
  <rule ref="category/java/codestyle.xml/MethodNamingConventions">
    <properties>
      <property name="methodPattern" value="[a-z][a-zA-Z0-9]*"/>
      <property name="staticPattern" value="[a-z][a-zA-Z0-9]*"/>
      <property name="nativePattern" value="[a-z][a-zA-Z0-9]*"/>
      <property name="junit3TestPattern"
                value="test_[a-z][a-zA-Z0-9]*(_with(out)?[A-Z0-9][a-zA-Z0-9]*)?_should[A-Z0-9][a-zA-Z0-9]*"/>
      <property name="junit4TestPattern"
                value="test_[a-z][a-zA-Z0-9]*(_with(out)?[A-Z0-9][a-zA-Z0-9]*)?_should[A-Z0-9][a-zA-Z0-9]*"/>
      <property name="junit5TestPattern"
                value="test_[a-z][a-zA-Z0-9]*(_with(out)?[A-Z0-9][a-zA-Z0-9]*)?_should[A-Z0-9][a-zA-Z0-9]*"/>
    </properties>
  </rule>
```

Test code:

```java
  @ParameterizedTest
  @ValueSource(strings = { "FEMALE", "MALE" })
  public void test_fromValue_withGenderValues_shouldReturnEnumType(final String value) {
    assertNotNull(Gender.fromValue(value));
  }
```

Problem:

> The instance method name 'test_fromValue_withGenderValues_shouldReturnEnumType' doesn't match '[a-z][a-zA-Z0-9]*'

**Expected outcome:**

*   Does PMD report a violation, where there shouldn't be one? -> false-positive

**Running PMD through:** *Gradle*

**Comment by adangel** [comment]
Fixed via #2899 for PMD 7.
