### ISSUE TITLE
Eclipse update-site and update-site-latest not working with eclipse.

### ISSUE THREAD

**Issue by atulkaushal** [pmd/pmd#254]
Update site latest is not working in Eclipse Neon .2. There is no content.xml at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/

Error Message:
```
Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/content.xml.
Unable to read repository at https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site-latest/content.xml.
Received fatal alert: handshake_failure
```

**Comment by jsotuyod** [comment]
@adangel maybe we should consider publishing the update site to http://pmd.github.io/ ?

**Comment by adangel** [comment]
Maybe - but it is a known problem with a known workaround: https://github.com/pmd/pmd-eclipse-plugin/issues/19
I'll add your suggestion there...
