### ISSUE TITLE
[java] Auxclasspath in PMD CLI does not support absolute path to jars in classpath

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2548]
**Affects PMD Version:** 
6.24.0

**Description:**
Option auxclasspath in PMD CLI does not support absolute path for jars specified in the classpath supplied. 

**Exception Stacktrace:**

```

+ java -cp @../pmd.cp net.sourceforge.pmd.PMD -filelist pmdfiles.txt -R ../pmdrules.xml -f text -min 5 -norulesetcompatibility -failOnViolation true -cache pmd.cache -reportfile pmd.errors -auxclasspath file:///data/data/com.termux/files/home/LearnJava/Unsafe/pmdaux.cp -t 5
May 28, 2020 1:46:33 AM net.sourceforge.pmd.cache.FileAnalysisCache loadFromFile
INFO: Analysis cache loaded
May 28, 2020 1:46:50 AM net.sourceforge.pmd.cache.AbstractAnalysisCache checkValidity
INFO: Analysis cache invalidated, auxclasspath changed.
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/Matcher
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
	at java.base/java.lang.Class.getMethods(Class.java:1904)
	at net.sourceforge.pmd.lang.rule.ImportWrapper.<init>(ImportWrapper.java:33)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit(UnusedImportsRule.java:121)
	at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept(ASTImportDeclaration.java:143)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:225)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit(AbstractJavaRule.java:397)
	at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit(UnusedImportsRule.java:58)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll(AbstractJavaRule.java:168)
	at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply(AbstractJavaRule.java:156)
	at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:336)
	at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:575)
	at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:143)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:194)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:107)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:89)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:51)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at net.sourceforge.pmd.util.ClasspathClassLoader.loadClass(ClasspathClassLoader.java:123)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 27 more
+ exitCode=1
+ echo './pmd exited with error code 1'
./pmd exited with error code 1
+ exit 1

```

Contents of pmdaux.cp
```
$ cat pmdaux.cp
/data/data/com.termux/files/home/LearnJava/lib/junit-4.13.jar
.
```

Contents of PMD.cp
```
/data/data/com.termux/files/home/LearnJava/lib/antlr4-runtime-4.7.jar:/data/data/com.termux/files/home/LearnJava/lib/asm-7.3.1.jar:/data/data/com.termux/files/home/LearnJava/lib/commons-io-2.6.jar:/data/data/com.termux/files/home/LearnJava/lib/commons-lang3-3.8.1.jar:/data/data/com.termux/files/home/LearnJava/lib/gson-2.8.5.jar:/data/data/com.termux/files/home/LearnJava/lib/javacc-5.0.jar:/data/data/com.termux/files/home/LearnJava/lib/jcommander-1.72.jar:/data/data/com.termux/files/home/LearnJava/lib/pmd-core-6.24.0.jar:/data/data/com.termux/files/home/LearnJava/lib/pmd-java-6.24.0.jar:/data/data/com.termux/files/home/LearnJava/lib/pmd-jsp-6.24.0.jar:/data/data/com.termux/files/home/LearnJava/lib/pmd-xml-6.24.0.jar:/data/data/com.termux/files/home/LearnJava/lib/saxon-9.1.0.8-dom.jar:/data/data/com.termux/files/home/LearnJava/lib/saxon-9.1.0.8.jar
```

Same error occurs when auxclasspath is specified via command line as against input file.

**Steps to reproduce:**

Specify absolute path to jar file preferably not in working directory as part of the auxclasspath.

**Running PMD through:** *[CLI ]*

**Comment by Fernal73** [comment]
There is a workaround to the above i.e., you add the auxclasspath to the existing classpath and forget about specifying auxclasspath completely.

**Comment by adangel** [comment]
I think, the error message is correct: `org.hamcrest.Matcher` is indeed not on the classpath, neither in pmd.cp nor in pmdaux.cp.
Hamcrest is not included in junit, but junit uses it and therefore declares a dependency on hamcrest.
You'd need to add junit + all the dependencies of junit to the auxclasspath.

If you add the hamcrest.jar, then it should work. I see no problem in the current implementation of the auxclasspath, that it would not support absolute or relative paths (so both your entries should work).

Can you try again?

**Comment by Fernal73** [comment]
You could be right, @adangel .
I've since modified my script to omit the auxclasspath and add the junit classpath to the main classpath.
That resolves my issue. 
Additionally, I've since migrated to Junit5.
However, I did not have any issue using the said classpath via the ant pmd task.

Is that because the hamcrest class files are in Ant's classpath?

The issue crops up with resolving imports if they're from an external jar which is not accessible to PMD.

**Comment by Fernal73** [comment]
I've retested using Junit5 and auxclasspath works as expected. Hamcrest is a compile time dependency for Junit4 and as far as I can see, it was missing in my junit.cp file which was the classpath for Junit4.

**Comment by adangel** [comment]
Thanks for retesting, I think, the issue can be closed now.

> Is that because the hamcrest class files are in Ant's classpath?

Not automatically, you'll need to configure the classpath in ant also manually.

> Are you suggesting that Hamcrest has a better Assertion framework for use with unit tests in Java?

Junit's Assert implementation uses Hamcrest under the hood. That's all. If you call `org.junit.Assert.assertEquals` internally hamcrest is called - that's why you need to have Hamcrest in the classpath - even if you don't use it directly. So more specifically: hamcrest needs to be at least on the runtime classpath of your project. The exception stacktrace above suggests however, that you directly used hamcrest (PMD fails while analyzing imports), so I assume, you have at least one java file with `import org.hamcrest.Matcher` in it - which means, you use hamcrest directly, which means, you need to put it on the compile-time classpath and therefore it needs to be on the auxclasspath of PMD.
However, I don't find a java file anymore, that imports hamcrest in your repository...

**Comment by Fernal73** [comment]
The salient point is that with the Hamcrest.jar present, evidently the error does not occur. However, how does this explain the ant task working and producing the correct output with the same classpath that had the hamcrest jar missing?
This is the listing of my /use/share/ant/lib directory i.e. the ANT_LIB directory:


  ant-antlr.jar                               ant-apache-bcel.jar                         ant-apache-bsf.jar                          ant-apache-log4j.jar                        ant-apache-oro.jar                          ant-apache-regexp.jar                       ant-apache-resolver.jar                     ant-apache-xalan2.jar                       ant-commons-logging.jar                     ant-commons-net.jar                         ant-contrib-1.0b3.jar                       ant-imageio.jar                             ant-jai.jar                                 ant.jar                                     ant-javamail.jar                            ant-jdepend.jar                             ant-jmf.jar                                 ant-jsch.jar                                ant-junit4.jar                              ant-junit.jar                               ant-junitlauncher.jar                       ant-launcher.jar                            ant-netrexx.jar                             ant-swing.jar                               ant-testutil.jar                            ant-xz.jar                                  apiguardian-api-1.1.0.jar                   ivy.jar                                     junit-platform-commons-1.7.0-M1.jar         junit-platform-engine-1.7.0-M1.jar          junit-platform-launcher-1.7.0-M1.jar        opentest4j-1.2.0.jar

The junit-platform  , opentest4j and apiguardian are from JUnit5. These have to be present in the ANT_LIB directory.

The rest are what were present earlier.

**Comment by Fernal73** [comment]
I have only two tests in Unsafe projects which I'm quite sure were not importing any Hamcrest classes directly. UnsafeTest.java and SampleTest.java.

You can search their history on github if you like. I'll have to look that up myself.

**Comment by adangel** [comment]
If you want me to analyze further, you need to provide me a simple isolated reproduction test case. Your project has the problem, that it only works on your computer, since it uses absolute paths everywhere...
I'll stop investigating here - sorry.

**Comment by Fernal73** [comment]
I cannot find any such reference by running the following command under Unsafe/unsafe:

$ git rev-list --all | xargs git grep 'hamcrest'

**Comment by adangel** [comment]
I think, this is what happened:

We were loading the class "org.junit.Assert" (since this is used directly in the imports). This class references Hamcrest - and that's why java tries to load org.hamcrest.Matcher - which it didn't find.

Maybe you used a dependency resolver to create the classpath used by ant (I see many references to ivy) - that would resolve transitive dependencies as well...

**Comment by Fernal73** [comment]
I am using the same classpath in ant as well. In fact, what's done via ant is done via the scripts as well with very few exceptions.

**Comment by Fernal73** [comment]
I'm unable to reproduce this error. I have another project JCommander that references the JUnit4 classes but don't have any tests created.
I tried both with and without the hamcrest jar but there was no error generated either through the ant task or the pmd script.

Best to close this as unreproducible (as already done).

Thanks.
