### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by eperret** [pmd/pmd#2596]
The links on the https://github.com/pmd/pmd/wiki/Rule-Categories page for all of the categories are broken and return a 404 error,.

**Comment by oowekyala** [comment]
Not sure how you found this page as it isn't on the sidebar? It was a working document for PMD 6, so it's nearly 3 years old. The website now has [indices](https://pmd.github.io/latest/pmd_rules_java.html) for every language. If anything the whole wiki page should be deleted.

**Comment by adangel** [comment]
I've removed the wiki document (it would still be in the git history of the wiki).

As @oowekyala  said, this was a working document, the changes have been implemented. The links referred to the old rulesets, which are gone.
