### ISSUE TITLE
[core] Ruleset schema compatibility steps

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2612]
Placeholder issue to track changes to the ruleset schema, for which we could prepare on master by issuing deprecation warnings/ support new syntax for forward compatibility

- [x] #2617
- [x] #2352

## Related issues
* #1676 

### Probably for PMD 7
* #4313
* #4314

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
