### ISSUE TITLE
[core] PMD/CPD produces invalid XML (insufficient escaping/wrong encoding)

### ISSUE THREAD

**Issue by maikelsteneker** [pmd/pmd#2615]
**Affects PMD Version:** PMD 6.24.0

**Description:**

When running on a file with a different encoding than the system default, PMD can produce invalid XML.

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  Use the following UTF-8 encoded source file: [MyClass.java.zip](https://github.com/pmd/pmd/files/4837505/MyClass.java.zip)
2.  Invoke PMD on Windows 10 as follows: `pmd -d C:/tmp/MyClass.java -rulesets category/java/errorprone.xml/AvoidDuplicateLiterals -format xml -language java > out.xml`
This produces the following XML output: [out.xml.zip](https://github.com/pmd/pmd/files/4837506/out.xml.zip)
The encoding of this file should be UTF-8 (as indicated at the start of the file), but contains files in a different encoding. Running xmllint on it produces:
`/tmp/out.xml:8: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0xE9 0xE9 0xE9 0xE9
The String literal &quot;��������&quot; appears 5 times in this file; the first 
                         ^
`

In fact, in my case, these characters are in the Windows-1255 encoding. I think PMD uses this encoding because it uses the system property `file.encoding`. One workaround is to use the same encoding as the file (UTF-8 by default).

**Running PMD through:** *[CLI]*

**Comment by maikelsteneker** [comment]
The same can happen with CPD when it includes code in its `<codefragment>` blocks. I've also seen it include form feed characters (`^L` in vim), which aren't valid in XML 1.0.

**Comment by SulisNyx** [comment]
I have seen invalid xml in the <codefragment> many times. I've included an example output for pypy-5.4.0.
[pypy-cpd.xml.zip](https://github.com/pmd/pmd/files/4853106/pypy-cpd.xml.zip)

The xmllint errors:
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38108: parser error : CData section not finished
import unittest
from test.test_support import run_


^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38108: parser error : PCDATA invalid Char value 12


^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38129: parser error : StartTag: invalid element name
            ('\x1b$B%O%m!<%o!<%k%I!*\x1b(B', 'iso-2022-jp'),
                          ^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38129: parser error : StartTag: invalid element name
            ('\x1b$B%O%m!<%o!<%k%I!*\x1b(B', 'iso-2022-jp'),
                              ^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38151: parser error : PCDATA invalid Char value 12


^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38162: parser error : PCDATA invalid Char value 12


^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38164: parser error : Sequence ']]>' not allowed in content


 ^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38164: parser error : Sequence ']]>' not allowed in content
    unittest.main(defaultTest='suite')]]></codefragment>
                                      ^
vaults/cpd_test/projects/vault-sample/systems/pypy-5.4.0/data/cpd_results/cpd-python.xml:38164: parser error : internal error: detected an error in element content

    unittest.main(defaultTest='suite')]]></codefragment>

**Comment by maikelsteneker** [comment]
@SulisNyx: thanks. This is a good example of a file with a couple of those form feed characters that are invalid in XML. After removing those, valid XML remains.
