### ISSUE TITLE
[core] PMD CLI output file is not created if directory or directories in path don't exist

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2639]
**Affects PMD Version:** 
6.25.0

**Description:**
The option -r which specifies the report file throws an exception if directory or directories in the specified report path do not exist.

**Exception StackTrace**

FINE: Exception during processing           java.lang.IllegalArgumentException: java.nio.file.NoSuchFileException: /data/data/com.termux/files/home/DSAlgos/target/pmdxml.txt           at net.sourceforge.pmd.util.IOUtil.createWriter(IOUtil.java:43)                         at net.sourceforge.pmd.PMD.doPMD(PMD.java:221)                                          at net.sourceforge.pmd.PMD.run(PMD.java:482)                                            at net.sourceforge.pmd.cli.PMDCommandLineInterface.run(PMDCommandLineInterface.java:166)                                            at net.sourceforge.pmd.PMD.main(PMD.java:452)                                   Caused by: java.nio.file.NoSuchFileException: /data/data/com.termux/files/home/DSAlgos/target/pmdxml.txt                                    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)                                                 at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)                                                  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)                                                  at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)                                      at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)                                      at java.base/java.nio.file.Files.newOutputStream(Files.java:219)                        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2919)                     at net.sourceforge.pmd.util.IOUtil.createWriter(IOUtil.java:41)                         ... 4 more

**Running PMD through:** *[CLI ]*

**Comment by oowekyala** [comment]
This could be fixed by simply calling Files.createDirectories I think
