### ISSUE TITLE
[apex] ApexXSSFromURLParamRule shouldn't enforce ESAPI usage. String.escapeHtml4 is sufficient.

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#264]
@sergeygorbaty the is the issue we discussed over Slack. Please make rule less restrictive. Not everbody wants and needs the ESAPI library to prevent XSS from URLs.

**Comment by sgorbaty** [comment]
@up2go-rsoesemann @jsotuyod ack.

**Comment by sgorbaty** [comment]
[PR](https://github.com/pmd/pmd/pull/268)

**Comment by jsotuyod** [comment]
Fixed in #268, will be released in PMD 5.5.4 and later.
