### ISSUE TITLE
[java] Deprecate rule DataFlowAnomalyAnalysis

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2647]
Thanks to #2618 we have a perfect replacement for [DataFlowAnomalyAnalysis](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#dataflowanomalyanalysis).

Tasks:
- [x] Deprecate DataFlowAnomalyAnalysis (see #2681)
- [x] Close all issues with this rule as wont-fix: https://github.com/pmd/pmd/labels/in%3Adata-flow

**Comment by oowekyala** [comment]
This also lets us deprecate all the DFA framework. The code is heavily outdated and not useful anymore. See #2124 

I would be for removing the dependencies we have on it in pmd-java at least. It's not useful and will be a pain to update to the newer java-grammar.

AFAIK the PL/SQL module implements the framework but no rule uses it? @adangel if you agree we can get rid of this too.
