### ISSUE TITLE
[java] Enhancement: Include or exclude nested asserts 

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2660]
**Description:**

With regards to the rule [JUnitTestContainsTooManyAsserts](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junittestcontainstoomanyasserts), is it worth excluding an assert statement from the count when its return value is used to check another condition or property?

For example, in JUnit 5, the assertThrows returns the caught exception and the error message contents  checked in yet another assert statement.

Should the first assert be ignored in the count or should it stay? In practice, it's the second assert that's critical to the test else you wouldn't capture the exception at all.

This is an issue when the default value of 1 is used in the rule.

This rule uses Xpath; is it trivial to modify it or is this change better migrated to the API?

```java

@Test
    void exceptionTesting() {
        Exception exception = assertThrows(ArithmeticException.class, () ->
            calculator.divide(1, 0));
        assertEquals("/ by zero", exception.getMessage());
    }


```
This could be mitigated by nesting asserts:
```java
assertEquals("/ by zero", assertThrows(ArithmeticException.class, () -> calculator.divide(1, 0).getMessage());
```

A property can be added whether to include nested asserts in the count or not.

**Properties**
includeNestedAsserts

**Comment by amithkumarg** [comment]
You should nest the assertion to avoid flagging:

```
  assertEquals("/ by zero", assertThrows(ArithmeticException.class, () ->
            calculator.divide(1, 0).getMessage());
```

**Comment by Fernal73** [comment]
Good point.

**Comment by Fernal73** [comment]
> Good point.
> […](#)
> On Sat, 7 Nov 2020, 03:03 Amith Kumar, ***@***.***> wrote: You should nest the assertion to avoid flagging: assertEquals("/ by zero", assertThrows(ArithmeticException.class, () -> calculator.divide(1, 0).getMessage()); 

A property could be added whether to include nested asserts in the count.

**Comment by Fernal73** [comment]
Updated OP.
