### ISSUE TITLE
[core] Most links broken on maven site "best practices" page

### ISSUE THREAD

**Issue by zman0900** [pmd/pmd#269]
Most of the links on the page https://pmd.github.io/pmd-5.5.3/overview/bestpractices.html are broken.  For example:

Broken:
https://pmd.github.io/pmd-5.5.3/usage/howtomakearuleset.html

Expected?:
https://pmd.github.io/pmd-5.5.3/customizing/howtomakearuleset.html

**Comment by jsotuyod** [comment]
@zman0900 thanks for the report. You are absolutely right. I'm gonna fix it right away.

**Comment by zman0900** [comment]
On the [snapshot page](http://pmd.sourceforge.net/snapshot/overview/bestpractices.html) it looks like all the links are now fixed, except the "via a custom ruleset" link.  Still has the same problem from the example above.

**Comment by jsotuyod** [comment]
@zman0900 you are right, that page was moved from usage to customizing. Once Travis runs and deploys it should be fixed too.

Thanks!
