### ISSUE TITLE
[ci] Add integration tests with real open-source projects

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#2693]
**Is your feature request related to a problem? Please describe.**
In order to find problems like #2663 earlier, we should have a way to run the latest PMD on real projects.
We already have pmd-regression-tester, but that does have some limitations (e.g. typeresolution) and has (maybe?) a slightly different goal (fine grained rule violation comparisons).

At least, we should see, when the real open-source projects fail to build (like smoke test), but better even would be to see, which rules behave different now and cause the builds to fail (or which stacktraces).

**Describe the solution you'd like**
* Improve and use directly pmd-regression-tester
    * Add the following projects to https://github.com/pmd/pmd/blob/master/.travis/project-list.xml
    * Implement pmd/pmd-regression-tester#48
    * Enhance project list configuration to have a flexible way to configure a script snippet, that tells the tool, how to
        * modify the project to use the latest PMD snapshot
        * execute PMD on the projects as the projects themselves do
        * where to find the pmd report files for diffing
        * see also reproducible builds "buildinfo" file for ideas
    * Add also non-java projects, e.g. apex
* Consider running not all projects on pull-request, but only for pushes, or maybe we could even split this into a completely separate build task? So that it appears as a second commit verification in github.
    * we could also use github-action maybe?

Projects that can be used:
* java
    * https://github.com/huxi/sulky
        * reproduce: change pmdVersion in build.gradle to 6.26.0 and run `./gradlew pmdMain pmdTest`
        * `> java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException`
    * https://github.com/neowu/core-ng-project
        * Use openjdk14
        * reproduce: change pmdVersion in gradle/check.gradle to 6.26.0 and run `./gradlew pmdMain pmdTest
        * `> java.lang.NoClassDefFoundError: javassist/CannotCompileException`
* apex
    * https://github.com/SalesforceLabs/Schedul-o-matic-9000
        * from https://github.com/pmd/pmd/pull/2791/files#r490452799
    * https://github.com/apex-enterprise-patterns/fflib-apex-common
        * from https://github.com/pmd/pmd-regression-tester/pull/69#issuecomment-706768700
    * https://github.com/nawforce/apex-link/tree/master/samples
    * Github Search: https://github.com/search?l=Apex&o=desc&q=apex&s=stars&type=Repositories

**Describe alternatives you've considered**
Have a separate project, e.g. pmd/pmd-it .
* Add there some scripts to
    * clone one or more projects
    * modify the project to use the latest PMD snapshot
    * execute PMD on the projects as the projects themselves do
* Configure travis to build this
* Trigger the travis build after building the main repo pmd/pmd (e.g. via https://docs.travis-ci.com/user/triggering-builds/)
* That would give us a smoke test at least - but nothing to analyze directly.

**Additional context**

**Comment by Fernal73** [comment]
Ideally, you'd want to have some sort of Automated Error Reporting Tools that sends PMD details about every crash or error that occurs when it's enabled on the user's machine. This includes tools such as Codacy and SonarSource that use PMD within their systems.

One concern would be is the volume of data returned from such a system.

Some links:


https://www.codeproject.com/Articles/163223/What-s-Automated-Error-Reporting-and-How-Does-it-W

https://www.eclipse.org/community/eclipse_newsletter/2016/july/article3.php

https://www.infoq.com/articles/Error-Reporting/

**Comment by rsoesemann** [comment]
@adangel if you need more than one Apex repo just use the top candidates on Github https://github.com/search?l=Apex&o=desc&q=apex&s=stars&type=Repositories They are all good candidates
