### ISSUE TITLE
[apex] Fix False Negatives with Salesforce-specific Dataflow/Multifile

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#2717]
One of the most requested feature of Salesforce-based rules (Apex, Visualforce, and in the future XML) is checking across file boundaries. I am not talking about dynamic flow in its full complexity. Just across file boundaries. 

@adangel @oowekyala @jsotuyod is there anything on the long or short term roadmap where you could need support by a dev team?

I know someone who could also contribute time and effort there.

**Comment by rsoesemann** [comment]
Talking to @adangel I learned about those two documents that touch this topic:
- The PMD 7 Plans https://github.com/pmd/pmd/wiki/PMD-7.0.0-API 
- And the State of PMD internal protocoll https://docs.google.com/document/d/1AmfzLUTnmdV08_F8f9gTKo1G7cfA2_B-lOOu7Hn3m5U/edit#heading=h.jimdq2npqnge

Both seem to indicate that there are plans to tackle Multifile and Flow with a new API approach. According to Andreas @oowekyala is already thinking about details.

**Comment by rsoesemann** [comment]
Thanks @oowekyala for clarification towards the timeline and your ideas to better implement flow.

> My preferred approach would be to integrate an external dataflow solver, to not have to build something from scratch. Maybe some exist that are language independent. The approach of jdataflow comes to mind. Probably, to be worth the effort, this would need multifile analysis, which I think is a more important feature. I don't think I'll work on dataflow myself for pmd 7, beyond improving #2618 --but this is not language independent.

FYI: @rmohan20 what do you think about this? Didn't you also thing of leveraging an external flow tool?

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann I agree that it makes sense to leverage existing solutions instead of building something from scratch. Wala is one implementation that we have looked into. It currently supports Java and JavaScript, the Data Flow layer is well separated from the language specific layers, and it is multifile.

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc sounds like a great match for PMD and Salesforce (if it works for Java it will probably work for Apex). 

Did you and @rmohan20  have time to look into and think about the in-memory org idea and metadata connectivity @nawforce put into his ApexLink flow/multifile solution?

**Comment by nawforce** [comment]
If it helps, I have done work on Apex->Java transpiling. Mostly its straight forward but you do have the same issue that I have been dealing with where you require visibility of all Apex files (and other related 'metadata') to remove the type ambiguity that is caused by not having imports in the language.

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc @rmohan20 are you still investigating here or shall I close this. Seems like there is no need for collaboration here. At least I see no one contributing actively.

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann this is still an area of interest to us, @rmohan20 and I are currently coming up to speed on the codebase by fixing some of the issues related to single file analysis. We will have more useful thoughts once we are more familiar with the existing single file implementation. I'll leave it up to you if you want to leave it open or not.

**Comment by rsoesemann** [comment]
Closing this as Salesforce found PMD to not be the right tool for that and instead build GraphEngine for that https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/introduction/
