### ISSUE TITLE
[java] Deprecate rule SimplifyStartsWith

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2740]
Rule: [SimplifyStartsWith](https://pmd.github.io/latest/pmd_rules_java_performance.html#simplifystartswith)

From #1868:

> But I'm wondering, whether this performance improvement is still valid with today's VMs...

> We can probably write a JMH test to make sure of it before we make a decision, as we did for ConsecutiveAppendShouldReuse https://stackoverflow.com/questions/37672785/how-can-i-improve-performance-if-append-is-called-on-stringbuffer-or-stringb/41839223#41839223

**Comment by oowekyala** [comment]
I wrote a small benchmark for that, and it appears there is a slight difference in performance, but no earlier than jdk 15:

https://github.com/oowekyala/pmd-jmh/blob/a045b6ef3337858d7541f41b19e34895d64a0286/src/main/java/net/sourceforge/pmd/MyBenchmark.java#L62-L91

Regardless, I don't think PMD should recommend micro-optimisations like this, especially when they decrease readability.

**Comment by adangel** [comment]
Thanks for looking into this.

> Regardless, I don't think PMD should recommend micro-optimisations like this, especially when they decrease readability.

I fully agree. These micro-optimisations should be left to the JVM.

I change the title of the issue to deprecate the rule and then we can remove it with PMD 7.
