### ISSUE TITLE
[javascript] support ecmascript decorator?

### ISSUE THREAD

**Issue by wjljack** [pmd/pmd#2769]
support ecmascript decorator?

**Comment by oowekyala** [comment]
Please edit your question to clarify what you want.

**Comment by adangel** [comment]
@wjljack Are you referring to https://github.com/tc39/proposal-decorators ?
PMD uses https://github.com/mozilla/rhino to parse javascript/ecmascript and decorators are probably not supported by rhino yet. As far as I understand, decorators are a draft proposal and not standardized yet.
