### ISSUE TITLE
[java] MissingOverride long-standing issues 

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2797]
**Affects PMD Version:** Since 6.2.0, when the rule was introduced

**Rule:** [MissingOverride](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#missingoverride)

**Description:** There are 2 long-standing issues with MissingOverride, related to overriding of a method using type parameters of a parameterized supertype. This is caused by its implementation strategy, since it counts bridge methods in a Class file.

The issue is described at length around this line:

https://github.com/pmd/pmd/blob/59f1fe251e36ee586d1e91796aab054a98a15872/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java#L286

There are already regression tests in the test file:

https://github.com/pmd/pmd/blob/59f1fe251e36ee586d1e91796aab054a98a15872/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MissingOverride.xml#L379-L444

This may be fixed easily in PMD 7, since we don't use Class files and have all necessary utilities to test for overriding in TypeOps already:

https://github.com/pmd/pmd/blob/1b1377175c15d9ec8ca00404b229a713b3864080/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java#L1317

https://github.com/pmd/pmd/blob/1b1377175c15d9ec8ca00404b229a713b3864080/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java#L1213

**Expected outcome:**

PMD should report violations for the two test cases, this is a false negative

**Comment by adangel** [comment]
Fixed by #2800
