### ISSUE TITLE
[java] JUnitTestsShouldIncludeAssertRule should support @Rule as well as @Test(expected = ...)

### ISSUE THREAD

**Issue by blerner** [pmd/pmd#285]
**Rule Set:** JUnit

**Description:** Currently, the [JUnitTestsShouldIncludeAssertRule](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/junit/JUnitTestsShouldIncludeAssertRule.java) checks whether a method is annotated `@Test(expected = ...class)` to check for expected exceptions.  JUnit4 includes the `@Rule` form to define `ExpectedException`s, too, but if code uses that, then the rule above will fire and complain that no assertions were found.

**Code Sample demonstrating the issue:**
(Excerpted from https://github.com/junit-team/junit4/wiki/Rules)
```java
public class DigitalAssetManagerTest {
  @Rule
  public final ExpectedException exception = ExpectedException.none();
  @Test
  public void throwsIllegalArgumentExceptionIfIconIsNull() {
    exception.expect(IllegalArgumentException.class);
    exception.expectMessage("Icon is null, not a file, or doesn't exist.");
    new DigitalAssetManager(null, null);
  }
}
```
It seems to me the rule needs to check:
- For each `@Test` method that isn't annotated with an `expected = ...class` attribute,
- Is there an `@Rule`-annotated `ExpectedException` field in that test's class,
- and is that field used in a `.expect(...class)` call within the test?  (I think the `expectMessage` call is inessential elaboration, for the purpose of this rule.)

I tried writing this rule in XPath, but got stymied trying to match up the field name correctly...

**Running PMD through:** CLI 

#

**Comment by jsotuyod** [comment]
@blerner thanks for the report! This is a neat improvement!

Hopefully we can get this for the next patch release version.

Rather than a new rule, we should probably just edit the existing one to be able to handle these scenarios.

**Comment by Oowekyala** [comment]
@jsotuyod And yet another PR fixing that ;)

**Comment by jsotuyod** [comment]
This will be included on the next release cycle!
