### ISSUE TITLE
[java] Avoid Reassigning Catch Variables

### ISSUE THREAD

**Issue by numeralnathan** [pmd/pmd#2851]
**Proposed Rule Name:** AvoidReassigningCatchVariables

**Proposed Category:** Best Practices

**Description:**

The rule [`AvoidReassigningParameters`](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#avoidreassigningparameters) flags a problem if the programmer reassigns a method's parameter.  Please create a rule to do the same for `catch` variables.

**Code Sample:**

Here is some code that reassigns the `catch` variable.

```java
try
{
   Files.newInputStream(...);
}
catch (IOException e)
{
   e = new FileNotFoundException(e);
   ... more code ...
}
```

**Possible Properties:**

I cannot think of any.  Can you?

**Comment by oowekyala** [comment]
Fixed in PMD 6.27.0, refs #2682
