### ISSUE TITLE
[java] Separate pattern for test classes in ClassNamingConventions rule for Java

### ISSUE THREAD

**Issue by sabi0** [pmd/pmd#2867]
Apex has `testClassPattern` - https://pmd.github.io/latest/pmd_rules_apex_codestyle.html#classnamingconventions

Java doesn't - https://pmd.github.io/latest/pmd_rules_java_codestyle.html#classnamingconventions

Having test classes names consistently end with "Test" is important to make sure they are correctly picked up by Maven Surefire plugin. I would say this is even more important than following other naming conventions.

**Comment by adangel** [comment]
Note: Since PMD 6.51.0, the rule TestClassWithoutTestCases has a testClassPattern (#4162) - but here it's the other way around: we need to detect class, that don't follow the testClassPattern, but are probably tests (by checking the imports or the used annotations or the base class junit.TestCase)
