### ISSUE TITLE
[core] Error recovery mode

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2885]
It's probably not a super good idea to recover from StackOverflowErrors in all cases (#2808). Possibly, we could be leaving some external library in an inconsistent state. However, for a developer of PMD, it may be useful to do so, so that the error ends up in a report, or so that more errors can be discovered by continuing the run.

So we could have a "debug" mode that tries to be more error tolerant, but which is not the default behavior. This could be used in tests, and in particular, for the regression tester. This could also be useful for bug reports ("run pmd with these options and paste the report").

As a first step we could enable such a "debug" mode with a system property (`PMD_JAVA_OPTS=”-Derror_recovery -ea” run.sh ...`). 

If it's worth it we could also add a CLI switch for that, eg `-Xerror_recovery`. Other obscure system properties we use to enable advanced logging (like the Java type inference logger) could be added as switches too.

**Comment by adangel** [comment]
As background info: https://stackoverflow.com/questions/28551767/is-it-safe-to-catch-stackoverflowerror-in-java

**Comment by adangel** [comment]
Ok, the PR is merged in pmd/7.0.x and the new pmd-regression-tester is activated on master + pmd/7.0.x.
