### ISSUE TITLE
[java] UnusedPrivateMethod false positive with generics

### ISSUE THREAD

**Issue by Adam-** [pmd/pmd#2890]
**Affects PMD Version:** 6.29.0

**Rule:** UnusedPrivateMethod 

Please provide the rule name and a link to the rule documentation:
<https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#unusedprivatemethod>

**Description:** See link to code below. The method is clearly being used a few lines above it (L807/808). If I had to guess probably something with the generics is throwing it off, since PMD has ran over the rest of the codebase okay.

**Code Sample demonstrating the issue:**

https://github.com/runelite/runelite/blob/7ceb3c9e020aa8316ddc5809a2d409d5d2efb697/runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java#L811

**Expected outcome:**

PMD should not report `sortedInsert` as unused.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]* maven

**Comment by adangel** [comment]
This has been fixed with PMD 7.0.0-rc1.
