### ISSUE TITLE
[java] ClassTypeResolver#searchNodeNameForClass leaks memory

### ISSUE THREAD

**Issue by danberindei** [pmd/pmd#2911]
**Affects PMD Version:** 

6.29.0

**Description:**

`ClassTypeResolver#searchNodeNameForClass` does many more `ClassLoader.loadClass()` calls than there are classes in the project. Because the looked up names do not exist, the calls go through all the classloaders in the hierarchy, and every classloader creates an entry for the name in its `parallelLockMap`.

In turn, `JavaTypeDefinition#CLASS_EXACT_TYPE_DEF_CACHE` holds references to the types that do exist in the project, which keep alive the classloaders of all the modules in the Maven reactor, along with their `parallelLockMap`.

**Steps to reproduce:**

1. Set a conditional breakpoint in `ClassLoader#getClassLoadingLock` with condition `className.contains(".get")`
1. Start a debug configuration listening on port 5005
1. Run `MAVEN_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,server=n,suspend=y,address=localhost:5006" mvn pmd:pmd`

**Running PMD through:** *Maven*

**Comment by oowekyala** [comment]
What JDK version are you running? I could only confirm this on JDK 1.7, I think in later JDKs the parallelLockMap was replaced with another map and it looks like it doesn't grow as much. Does the problem also occur on JDK >= 1.8?

There is definitely a leak in JavaTypeDefinition too. This is part of a larger problem with analysis lifecycle. FWIW in PMD 7 we don't load classes anymore (#2689), and so don't keep Class instances alive, and we'll fix the lifecycle problem (#2518).

On master we could
1. remove the cache in JavaTypeDefinition. Maybe we can make the constructor of JavaTypeDefinitionSimple cheaper, to limit the performance regression
2. stop attempting to load method names (I think we already don't end up doing it if the classpath is full)

**Comment by danberindei** [comment]
@oowekyala `ClassLoader.parallelLockMap` is definitely present in JDK 11+:

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/ClassLoader.java#L297

I'm glad to see #2689, and I'm looking forward to using PMD 7 once it's released.

**Comment by oowekyala** [comment]
> @oowekyala ClassLoader.parallelLockMap is definitely present in JDK 11+:

Ah thanks I missed that. Do you think there is something we could do to limit the problem with `parallelLockMap`? I'm not sure what we can do about it, apart from making fewer calls to the classloader. I guess, if the classloaders can be garbage collected when analysis ends, then this is already less of a problem?

**Comment by adangel** [comment]
There is also [MPMD-297 Classloader not being closed after PMD run](https://issues.apache.org/jira/browse/MPMD-297). Is this maybe the root cause of memory not being freed?

**Comment by danberindei** [comment]
Yes, MPMD-297 will definitely fix it. 

I assume removing calls to the classloader for all member variables/methods would also have been enough to make the leak negligible in our case (although I didn't actually test it), but closing the classloader is even better.
