### ISSUE TITLE
[java] New rule AvoidVowelOnlyNames: Addendum rule to AvoidConsonantsOnlyName

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2927]
**Proposed Rule Name:**
AvoidVowelOnlyNames

**Proposed Category:** Code Style

**Description:**
This is an addendum rule to AvoidConsonantsOnlyName (#2919 )

Avoid names that contain only vowels for length >= 2.

**Possible Properties:**

Applicable to:
Class, interfaces,enums,method, fields and local variables.
Default to fields and local variables.

*Should this rule be customizable via properties?*

Yes, see above.

**Comment by Fernal73** [comment]
https://github.com/pmd/pmd/issues/2919

**Comment by numeralnathan** [comment]
The title says to avoid consonant only names.  The description says to avoid vowel only names.  Which rule is this?  Is it both?

**Comment by numeralnathan** [comment]
This will flag acronyms such as SMS.  One property should be an array of regular expressions that are okay to use.  One such regular expression could be "sms.*|.+Sms.*".  This would allow the acronym to be used at the beginning of an identifier or in the middle with proper camel casing.

**Comment by numeralnathan** [comment]
If we have a rule called `AvoidVowelsOnlyName`, then we would need to provide an exclusion for these cases and a parameter to allow other cases.

There are words without consonants: aa, ai, aye-aye, euouae, euoi, iouea
There are names without consonants: Aeaea, Aiea, Aia, Io, Eiao, Oea.

https://en.wikipedia.org/wiki/Words_without_consonants

**Comment by Fernal73** [comment]
I don't see any of these words used while programming. The only word I
thought of without consonants that could be possible is IOU.

**Comment by Fernal73** [comment]
We could skip constants. And I'm with not using acronyms as capitalised
fully. Just the first letter.

**Comment by Fernal73** [comment]
> I don't see any of these words used while programming. The only word I thought of without consonants that could be possible is IOU.

This rule is more of a way of preventing users subverting the AvoidConsonantsOnlyName rule.

**Comment by adangel** [comment]
If that rule is supposed to improve the other rule, maybe we should have only one rule? So merge #2919 and #2927 ?

**Comment by Fernal73** [comment]
> If that rule is supposed to improve the other rule, maybe we should have only one rule? So merge #2919 and #2927 ?

Yes, I haven't figured out as to how to configure them together!!!!

**Comment by Fernal73** [comment]
> If that rule is supposed to improve the other rule, maybe we should have only one rule? So merge #2919 and #2927 ?

What would you term the combined rule?
**UseNaturalLanguageNames** or **AvoidAbbreviatedNames**?

**Comment by numeralnathan** [comment]
I think **AvoidAbbreviatedNames** is better name since **UseNaturalLanguageNames** suggests a more complicated rule than just ensuring the name has constants and vowels.

**Comment by Fernal73** [comment]
@numeralnathan You're right. I was concerned that it might clash with 
https://checkstyle.sourceforge.io/config_naming.html#AbbreviationAsWordInName but this is a Checkstyle rule.

**Comment by Fernal73** [comment]
> I think **AvoidAbbreviatedNames** is better name since **UseNaturalLanguageNames** suggests a more complicated rule than just ensuring the name has constants and vowels.

Do you know of any easy way of merging two or more issues on GitHub?

**Comment by Fernal73** [comment]
Merged rule.
