### ISSUE TITLE
[java] New rule to prevent abbreviated identifiers

### ISSUE THREAD

**Issue by linusjf** [pmd/pmd#2948]
**Proposed Rule Name:**
AvoidAbbreviatedNames

**Proposed Category:** Code Style

**Description:**
This rule is composed of two parts:
Prevent consonant only naming i.e., names that contain only consonants.
Prevent vowel only naming i.e., names that contain only vowels.

**Code Sample:** 

```
var jmh; int tfd; 
var aaa, bbb, ccc;
```

**Possible Properties:**

*Applicable to*:
Class, interfaces, annotations, records, enums,method, fields and local variables.
Default to fields and local variables.

*Minimum applicable length*:
Should this be a property? The minimum applicable length would be 2. I'm inclined to have it fixed at 2 to avoid names like tm, nm etc.

*Customisable list of exceptions (regexed)*:
E.g., msg, tmp, txt.

*   Should this rule be customizable via properties?
See above.

Referred from:
https://github.com/pmd/pmd/issues/2919
https://github.com/pmd/pmd/issues/2927

**Comment by jsotuyod** [comment]
I'm unsure how this would be better than the currently existing [`ShortClassName`](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#shortclassname), [`ShortMethodName`](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#shortmethodname) and [`ShortVariable`](https://docs.pmd-code.org/latest/pmd_rules_java_codestyle.html#shortvariable)… 

I don't think that the only consonants / only vowels makes much difference… there are plenty of acronyms that don't use one or the other exclusively… `DOJ`, `FMI`… even within Java… `JPA`, `JDO`…

I'm closing this, but feel free to re-open if you think you have a strong case for it… and even then, it can possibly be resolved by adding a regex property to the existing rules…
