### ISSUE TITLE
[core] CPD: Add -filelist support to cpd

### ISSUE THREAD

**Issue by impmihai** [pmd/pmd#295]
Hello! I would like to suggest an enhancement to cpd. Pmd has the -filelist option that takes a csv file containing the files it should be run on. This is very useful when running on big projects, because if you list all the files in a command, you receive an argument list too long error. Can this be added to cpd too?

**Comment by jsotuyod** [comment]
Thanks @impmihai! That sounds like a very reasonable feature request, although we don't have a schedule for this anytime soon.

If this is important to you, please consider submitting a PR. It should be pretty easy, since the PMD code is already in place as reference, and parsing is resolved.

**Comment by impmihai** [comment]
I would like to help with that! I already looked up how it is done in PMD. I will submit a PR this evening! :D

**Comment by jsotuyod** [comment]
@impmihai amazing! Can't wait for it!

**Comment by impmihai** [comment]
`Exception in thread "main" java.util.ServiceConfigurationError: net.sourceforge.pmd.cpd.Language: Provider net.sourceforge.pmd.cpd.VFLanguage not found`

I am getting this exception when running the compiled version, but when running the official one i have no problem. Any package that i am missing and i should have installed? This happens to the clean project (aka. just git cloned) too.

**Comment by jsotuyod** [comment]
You are actually right, CPD support for Visualforce is broken. I'll try to fix it ASAP. In the mean time, you could temporally remove the dependency from pmd-dist on pmd-visualforce.

**Comment by jsotuyod** [comment]
There you go! Fixed on master, just pull and rebase your local branch.

**Comment by impmihai** [comment]
Thank you! It is working now 👍

**Comment by adangel** [comment]
@impmihai Awesome! Thanks for the PR - will review and merge it soon.

@jsotuyod FYI: I've extended our integration test to check CPD, too. We should now see such problems with new languages earlier.

**Comment by jsotuyod** [comment]
@adangel amazing!
