### ISSUE TITLE
[core] Support SARIF JSON Format

### ISSUE THREAD

**Issue by josepalafox** [pmd/pmd#2953]
**Is your feature request related to a problem? Please describe.**
SARIF is an OASIS Standard for static analysis alerts. GitHub support uploading SARIF formatted alerts to their CodeScanning API which allows alerts to be surfaced in the Github UI.

**Describe the solution you'd like**
Enable a flag for outputting reports in SARIF.

**Describe alternatives you've considered**

**Additional context**
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github
https://sarifweb.azurewebsites.net/Validation

**Comment by adangel** [comment]
More info about that topic:

* https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=sarif
* https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html
* https://github.com/oasis-tcs/sarif-spec
* https://github.blog/2020-09-30-code-scanning-is-now-available/

**Comment by rsoesemann** [comment]
@adangel @oowekyala would you agree that this is not so much work? Basically taking an existing JSON renderer like https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/renderers/JsonRenderer.java and adding a new one. Including all test and related changes.

**Comment by rsoesemann** [comment]
@adangel a teammate of me is going to work on this soon. How can I assign it to @mmoyaferrer?

**Comment by rsoesemann** [comment]
@mmoyaferrer to understand which files (besides the Renderer) need to be touched look at the PRs around https://github.com/pmd/pmd/issues/1286.

I guess @adangel can tell us also which changes need to be done in other repos (tools, documentation, etc).

**Comment by adangel** [comment]
@rsoesemann I've invited @mmoyaferrer as outside-collaborator - that seems to be the only possibility on github for assigning issues.

Since this is an enhancement which doesn't break existing functionality (I think), it can also be done for PMD 6. I guess, in the end, we'll have an additional renderer format.

Documentation for the renderer needs to be updated/added here: https://pmd.github.io/latest/pmd_userdocs_report_formats.html

**Comment by josepalafox** [comment]
If you get stuck on Actions or uploading the SARIF please feel free to reach out and we'll help where we can.

cc @swinton

**Comment by adangel** [comment]
@josepalafox Thanks for the offer! Do you know a tool, which we can use to verify/validate the SARIF file, we produced? I assume, we'll create a direct producer instead of a converter. So we'd like to verify, that we satisfy the “Direct producer” conformance profile.

**Comment by mmoyaferrer** [comment]
Thank @josepalafox , @adangel , I will keep you updated.
@adangel I've previously used this validator https://sarifweb.azurewebsites.net/Validation

**Comment by swinton** [comment]
> I've previously used this validator https://sarifweb.azurewebsites.net/Validation

+1 for this tool. Note, there's a `GitHub ingestion rules`checkbox which is handy for validating SARIF files that are intended to be uploaded to GitHub:

![image](https://user-images.githubusercontent.com/27806/104063009-1c48c080-51c1-11eb-96db-2c1fa8c20d4d.png)

Separately, I also found [these SARIF tutorials](https://github.com/microsoft/sarif-tutorials/tree/main/docs) to be quite enlightening.

**Comment by mmoyaferrer** [comment]
I have some misconfiguration which does not allow me to execute pmd from the source code. 
However, I'm able to execute tests and they pass. That latest point allows me to make progress on this issue, however I would also like to execute pmd from source code.

Could you please help me with that? I attach a screenshot:

![Screenshot 2021-01-15 at 13 10 45](https://user-images.githubusercontent.com/15876612/104726233-933b0780-5733-11eb-8975-1ee67daf95bc.png)

Thank you in advance

**Comment by adangel** [comment]
The NPE probably means, that you use pmd-core as the only module on the classpath. This means, that there are no supported languages.

Try to use the classpath of module "pmd-java".

**Comment by rsoesemann** [comment]
@adangel we will submit our PR in the next days so I am very confident we can release this in 6.31.

**Comment by josepalafox** [comment]
Hi @rsoesemann are you interested taking on the Action and Workflow file for GH integration in https://github.com/pmd/pmd/issues/2954 ? If not, no worries. But if so, I can collect a bit of information from you so I can include PMD in the GitHub UI.

**Comment by rsoesemann** [comment]
@josepalafox I think I can't. At least not from my daily job role at Copado because Github Devops is competing with our own solution. Why can't some developers of your team not do this? No that we have SARIF support?

**Comment by josepalafox** [comment]
@rsoesemann ok thanks. I didn't realize. We'll look into it!

**Comment by rsoesemann** [comment]
@josepalafox and @swinton could you please check and confirm that the SARIF PMD now produces is wellformed so Github can handle it properly and report to me and @mmoyaferrer when you see room for optimizations?

**Comment by swinton** [comment]
> could you please check and confirm that the SARIF PMD now produces is wellformed

Happy to! Is there an existing repo with known vulnerabilities that I can use to generate a sample SARIF?

**Comment by rsoesemann** [comment]
@swinton 
This one for Salesforce code: https://github.com/rsoesemann/fflib-apex-common
and maybe PMD for Java: https://github.com/pmd/pmd/

I guess @adangel and @oowekyala there is some PMD issues in PMD code, right?

**Comment by adangel** [comment]
Yes, there are some issues there as well. You can run it as follows:

1. clone https://github.com/pmd/pmd
2. run `./mvnw clean package pmd:pmd -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Dcpd.skip=true -Dformat=net.sourceforge.pmd.renderers.SarifRenderer`
3. check the results: `find -name "pmd.net.sourceforge.pmd.renderers.SarifRenderer"|xargs ls -l`

The sarif reports can be found in "*/target/pmd.net.sourceforge.pmd.renderers.SarifRenderer", e.g. ./pmd-java/target/pmd.net.sourceforge.pmd.renderers.SarifRenderer

**Comment by Clint-Chester** [comment]
> @josepalafox and @swinton could you please check and confirm that the SARIF PMD now produces is wellformed so Github can handle it properly and report to me and @mmoyaferrer when you see room for optimizations?

@rsoesemann  & @mmoyaferrer made a GitHub Action to test it out - https://github.com/synergy-au/pmd-analyser-action

I was testing it on Salesforce code and noticed it wasn't reporting the fullDescription.text object in the report (so no description gets provided unfortunately). Details on the GitHub properties that get checked for are here - https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/sarif-support-for-code-scanning

There's other cool things that could be done such as setting tags for rule categories and precision on rules, but the fullDescription would be the most immediate thing.

Absolutely love using this already though so great work on this, really appreciate it 😄

**Comment by josepalafox** [comment]
Hi, thanks @Clint-Chester this is great. If you're still up for playing around with it there's a validator that might help troubleshoot:

https://sarifweb.azurewebsites.net/Validation

If the SARIF is coming through, make a PR here and I'll have the team add the action as the default for Apex in the GitHub.com UI.

https://github.com/actions/starter-workflows

Also ping me at my username at github.com with your shirt size and details I'll send ya a something from the GitHub shop!

**Comment by Clint-Chester** [comment]
> Hi, thanks @Clint-Chester this is great. If you're still up for playing around with it there's a validator that might help troubleshoot:
> 
> https://sarifweb.azurewebsites.net/Validation
> 
> If the SARIF is coming through, make a PR here and I'll have the team add the action as the default for Apex in the GitHub.com UI.
> 
> https://github.com/actions/starter-workflows
> 
> Also ping me at my username at github.com with your shirt size and details I'll send ya a something from the GitHub shop!

Thanks @josepalafox 😄 no need to send me anything, would much rather see a donation go to the PMD maintainers 😄 they are the real MVPs (I just cobbled together a bash script).
