### ISSUE TITLE
Whitelist "ignored" parameters in UnusedFormalParameter

### ISSUE THREAD

**Issue by marquiswang** [pmd/pmd#2958]
**Is your feature request related to a problem? Please describe.**
There are a few cases where you intentionally want an unused parameter. In these cases it is common to name the parameter some variant of "ignored" or "unused". In these cases I would go in and suppress the warning for the one method, but we should be able to detect them automatically and suppress the rule implicitly.

**Describe the solution you'd like**
It would be nice if there was a property on this rule that let you choose whitelisted parameter names that auto-suppress the rule.

**Describe alternatives you've considered**
Suppress the rule explicitly for the methods in question.

**Comment by Fernal73** [comment]
This could be merged with https://github.com/pmd/pmd/issues/2957

**Comment by marquiswang** [comment]
I agree, this is duplicated with #2957.

**Comment by Fernal73** [comment]
This adds to the other issue by possibly resolving the main method conundrum where `args` could be whitelisted. Worth updating https://github.com/pmd/pmd/issues/2957.
