### ISSUE TITLE
[GSoC][java] Contributing into the project

### ISSUE THREAD

**Issue by ddashenkov** [pmd/pmd#301]
Hi, guys.
I'm interested in  __PMD__ and want to contribute to the project.
I study _Software Engineering_ in Kharkiv National University of Radioelectronics (Ukraine) on the 2nd year.
I've got several years of experience in coding (mainly __Java__ and __Android__) and I'm the person who appreciates clean code a lot.
I've got several ideas that might improve the project. Also, I'm ready to take up one or several of those ideas from your [Wiki](https://github.com/pmd/pmd/wiki).
Hope this will make your interest.

**Comment by jsotuyod** [comment]
@ddashenkov that certainly sounds interesting. Please, feel free to submit a proposal for whichever project you are willing to take on. If it's an idea of your own, I would strongly suggest you discuss it with us before submitting a proposal to GSoC. Doing so on this issue should be good enough.

Please, let us know if you have doubts or need any assistance.

**Comment by ddashenkov** [comment]
@jsotuyod Thanks. I'll structure my proposal formally by tomorrow and publish it here.

**Comment by ddashenkov** [comment]
#### Here is my proposal.

The state of art in static code analyzers is checking separate _statements/instructions/\<whatever name you can imagine\>_ for possible errors. Though programming is not about separate statements, but about their cooperation. And _Java (OOP) programming_ is about cooperation between separate __components__, which form the system.

My idea is to design and implement an API for performing a high-level analysis of an Object Oriented system architecture:
 - Adherence to SOLID principles
 - Class dependencies analysis
 - Design pattern detection (goes side by side with badly implemented design pattern detection)
 - etc.

The goal of this work is to build __an API__ which will be used later by the developers who introduce the specific rulesets.

@jsotuyod How do you feel about this idea?

**Comment by jsotuyod** [comment]
@ddashenkov that sounds interesting! What do you think is missing today in PMD to be able to implement such checks?

* SOLID is solely dependent on the contents of a single java file, at most needing type resolution (which PMD supports) to check if dependencies are provided through interfaces or concrete implementations...
* Class dependencies analysis (something such as JDepend I guess?) CAN be implemented, but needs to make threads-safe accumulation of data; and it would break with the current analysis cache... but I guess it could make use of the metrics framework and make sure metrics are persisted too.
* Design pattern detection: I have no idea how you would go around this one. I'm really curious.

**Comment by ddashenkov** [comment]
The Design pattern detection is possible by creating a pattern-matcher fashion mechanism for the class structure. For instance, we may want to detect fields of specific types and methods with specific arguments and return types.
This mechanism should be applied to multiple classes and source files simultaneously.
The API for the mechanism should be designed using builders for each atomic statement of the design pattern description.

Example:
```
Pattern singleton = Pattern.ofSingleClass()                          // one participant class
                           .withField(staticFieldPattern)            // single instance
                           .withMethod(staticGetterPattern)          // single instance getter 
                           .withConstructor(privateNoArgCtorPattern) // private constructor
                           .build();

Pattern enumSingleton = Pattern.ofSingleClass()                           // one participant (outer) class
                               .withMethod(staticGetterPattern)           // single instance getter 
                               .withConstructor(privateNoArgCtorPattern)  // private constructor
                               .withInnerClass(instanceHolderEnumPattern) // enum type holding the instance
                               .build();

```
_Note:_ this is just a rough example of something I want to build. This interface is technically _made up_ and is a subject of rethinking, but it reflects the main purpose of the work.

To detect badly implemented design patterns, we may exclude one of the criteria from the list and match the input source code.

**Comment by ddashenkov** [comment]
__SOLID__, in this case, is dependent not only of a single `.java` file, but also is a set of checks on multiple files and classes (mostly for performing _Liskov substitution principle_ checks).
But for a start, we may try to implement this feature for just a single file contents.

**Comment by ddashenkov** [comment]
The __dependency analysis__ is something the two above features use. JDepend looks pretty interesting, but I'm not sure yet if we can use it for our needs (not only for quality checks but also for building custom logic on it).

**Comment by ddashenkov** [comment]
@jsotuyod, Sorry for such a long delay. Please see my comments. Also, let me know what do you think of the proposal in general. Should I already submit it officially?

**Comment by jsotuyod** [comment]
@ddashenkov very interesting answers. I wonder, should the API you drafted be good enough for all 3 scenarios you described? Or is this actually 3 separate projects joined by the need for multiple files for analysis? I'm just wondering if you are not trying to chew too much for the limited time available during GSoC.

**Comment by ddashenkov** [comment]
@jsotuyod, the API I've described is aimed to cover only the __Design Patterns__ feature.
If talking about the estimation, I suppose we may try to calibrate them, if you consider this not too sensible by removing one or two of the discussed features. The other way is to split those into 3 GSoC projects and submit them separately.

**Comment by jsotuyod** [comment]
@ddashenkov at first glance, this sounds big. I'd suggest you pick whichever of the 3 you like the most, and start drafting a full proposal for that. Let us know if you need any help from us, we will gladly review it.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
