### ISSUE TITLE
[GSOC] Contributing

### ISSUE THREAD

**Issue by oitsjustjose** [pmd/pmd#304]
Hey everyone! I'm very excited by the prospects of working for PMD this summer through the Summer of Code program! I'm mostly interested in contributing to **Auto Fixable Issues** or the **Metrics Framework**.

I've been working with Java and GitHub for about 5 years now, so I would love to be able to contribute to something greater than I ever have before!

EDIT: any chance I could get some advice on the actual GSOC side of things? I would love to submit a proposal, but I'm a bit unsure of what's expected in the "Final Proposal" PDF. These were my plans for the Auto-Fixable issues: 

Similarly to how it was discussed in the abstract on the [GitHub proposal page](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BMature%5D#auto-fixable-issues), I would plan to implement this by means of a predetermined list of issues which are caught by PMD. I would replace the problems by directly modifying the file, but **only modifications would be made which the user would approve of**. This would be by means of:

* A UI element which alerts the user of the replacement option
* A portion which shows the user the error and the suggested fix
* A button on said element which allows the user to fix just this issue
* A button on said element which allows the user to fix all issues like this
* A checkbox for remembering said decision to ease use of this tool later

This could all be accomplished with Swing for the popup and UI elements. Implementing a method of replacing these issues would not be difficult with the issues already being "caught", so the remaining work would be in coming up with a way to apply the existing code to a "schematic".

**Comment by jsotuyod** [comment]
@oitsjustjose welcome and thanks for your interest!

As for your questions regarding how to write your final proposal, I suggest you take a look [at this document](http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/). Let me know if you have further doubts.

As for auto fixable issues, the UI may be nice to have, but I can live if it's not part of the GSoC deliverable (the timeframe is limited, and we need to sketch a plan we can actually accomplish).

Bare in mind most PMD users right now are either using it through Maven, Gradle or an IDE, which means the bare minimum for applying the fixes on the file would either be an apply without user confirmation; or at most a command line interactive task. I think we will end up having a GUI for this, but again, it's very low on the priority list for this feature. Your ideas however, may still apply to such interactive mode.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
