### ISSUE TITLE
[vf] VfUnescapeEl: Inherently un-XSS-able built-in functions trigger false positives

### ISSUE THREAD

**Issue by jfeingold35** [pmd/pmd#3081]
**Affects PMD Version:** 
6.30.0

**Rule:**
VfUnescapeEl

<https://pmd.github.io/pmd-6.30.0/pmd_rules_vf_security.html#vfunescapeel>

**Description:**
VF has a ton of built-in methods. Some are invulnerable to XSS, but use of these methods still triggers false positives, even when the proper escape function is used.

**Code Sample demonstrating the issue:**

```
<apex:page showHeader="true" sidebar="true" standardController="testObj__c">
    <script>
        console.log({!IF(testObj__c.Text__c == 'foo', 'bar', 'baz')});
        console.log({!IF(BEGINS(testObj__c.Text__c, 'foo'), JSENCODE(testObj__c.Xss__c), 'bar')});
        console.log({!CASE(testObj__c.Name, testObj__c.Text__c, 'res1', 'else-res')});
        console.log({!CASE(testObj__c.Name, 'val1', JSENCODE(testObj__c.Text__c), 'else-res')});
    </script>
</apex:page>
```

**Expected outcome:**
Currently, all of these lines are incorrectly determined to violate VfUnescapeEl. All are false positives.
Line 1 is immune to XSS because the vulnerable condition is evaluated on the server and the only possible returns are literals.
Line 2 is immune to XSS because BEGINS returns an inherently safe boolean, and the identifier in the second parameter is JSENCODE'd.
Line 3 is immune to XSS because the only possible returns are 'res1' and 'else-res'.
Line 4 is immune to XSS because the returnable identifier testObj__c.Text__c is wrapped in JSENCODE.

**Running PMD through:** *[CLI]*

**Comment by erocheleau** [comment]
I still have that issue, was this ever released?
I am running `@salesforce/sfdx-scanner 3.14.0` as the plugin to the sfdx-cli

This line still triggers an `VfUnescapeEl` that only goes away if I add the `JSENCODE()` around the value, but it's invalid when trying to push the code to Salesforce as this is a Boolean and not a String.

```
// Apex Controller

public with sharing class MyController {
    public Boolean aBoolean { get; set; }
}


// Visualforce page

<apex:actionFunction name="whatever"
       action="doesntmatter"
       oncomplete="onCompleteHandler({!JSENCODE(somevalue)}, {!IF(aBoolean, true, false)})"  <------- This is where the error is
/>
```

And it's specifically the `{!IF(aBoolean, true, false)}` that's triggering it because if I move it to another line the error is moving with it.

**Comment by kasmaks** [comment]
@erocheleau have you found how to fix this issue? I have such getter for Boolean in apex and when I use in visualforce it triggers VfUnescapeEl. Should we mark it as false positive? Would be glad to hear, thanks!
	public Boolean getIsCorrect() {
		return true;
	}
