### ISSUE TITLE
[java] Parse error on method reference

### ISSUE THREAD

**Issue by WinterGrascph** [pmd/pmd#309]
**Description:**
Pmd determines the code to be syntactically incorrect (the code compiles just fine), produces to following error message:
```
net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "new" "new "" at line 6, column 38.
Was expecting:
    <IDENTIFIER> ...
```
**Code Sample demonstrating the issue:**

```
import java.util.*;

public class Main {
    public static void main(String[] args) {
        Runnable r11 = Main::<String>new;
        // IntFunction<int[]> r13 = int[]::<String>new; // produces the same results
    }
}
```

**Running PMD through:** *Designer*

**Comment by jsotuyod** [comment]
Are you sure you are using PMD 5.5.4 or master? This sounds like #207, which was fixed back on 33fd84d521517d91fbc020cadecc84f7e21329f4

**Comment by WinterGrascph** [comment]
I'm using master, ```Type::<generic>method``` does work, but ```Type::<generic>new``` does not.

**Comment by jsotuyod** [comment]
Weird, I would have guessed it was covered. Writing your proposal is paying off already!! 👍
