### ISSUE TITLE
[plsql] ParseException while parsing EXECUTE IMMEDIATE 'drop database link ' || linkname;

### ISSUE THREAD

**Issue by hvbtup** [pmd/pmd#3106]
It seems like PMD 6.31.0 does not like

    EXECUTE IMMEDIATE 'drop database link ' || linkname;

or more generally the case where the statement to be executed with EXECUTE IMMEDIATE is a concatenation:

Caused by: net.sourceforge.pmd.lang.plsql.ast.ParseException: Encountered " "||" "|| "" at line ..., column ....
Was expecting one of:
    ";" ...
    "INTO" ...
    "RETURN" ...
    "RETURNING" ...
    "USING" ...

Execute Immediate Statement Spec:
https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/EXECUTE-IMMEDIATE-statement.html#GUID-C3245A95-B85B-4280-A01F-12307B108DC8

**Comment by hvbtup** [comment]
I found the following fragment in the file https://github.com/pmd/pmd/blob/master/pmd-plsql/etc/grammar/PldocAST.jjt :

    ASTEmbeddedSqlStatement EmbeddedSqlStatement()  :
    {}
    {
       <EXECUTE> <IMMEDIATE> (StringLiteral() | Expression())
    	[ <INTO> Name() ("," Name())* ]
    	[ <USING> [ <IN> [ <OUT> ] | <OUT> ]  Expression() ("," [ <IN> [ <OUT> ] | <OUT> ]     Expression())* ]
    	[ ( <RETURN> | <RETURNING> )  <INTO> Expression() ("," Expression())*] ";"
    	// PIPELINED FUNCTION OUTPUT
          { return jjtThis ; }
    }

Just a wild guess: Maybe the StringLiteral() is superfluous and Expression() is enough here?

**Comment by oowekyala** [comment]
Thanks for reporting. I think you're correct and this should be just Expression... I'm not sure why #2332 changed this, maybe the author just wanted to clean up those comments (the language is [JavaCC](https://javacc.github.io/javacc/))
