### ISSUE TITLE
[jsp] Parse error on HTML boolean attribute

### ISSUE THREAD

**Issue by andypattenden** [pmd/pmd#311]
**Description:**
When parsing a Jsp containing HTML which contains [boolean attributes](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes), the following error message is produced:
```java
Caused by: net.sourceforge.pmd.lang.jsp.ast.ParseException: Encountered " <ATTR_NAME> "name "" at line 8, column 39.
Was expecting:
    "=" ...
```

**Code Sample demonstrating the issue:**
In the below, the attribute `checked` causes a parse error
```html
<label><input type='checkbox' checked name=cheese disabled=""> Cheese</label>
```

**Running PMD through:** *Ant*

**Comment by jsotuyod** [comment]
@andypattenden thanks for the report, you re absolutely right. The JSP grammar was never updated for HTML 5.

This one should be relatively easy to fix shall any one want to contribute.
