### ISSUE TITLE
[java] Infinite loop when parsing invalid code nested in lambdas

### ISSUE THREAD

**Issue by lihuaib** [pmd/pmd#3117]
**Affects PMD Version:** 
all versions (<= 6.31.0).

**Code sample reproducing the issue:**
``` java
import java.util.*;

public class InfiniteLoopInLookahead {

    public void exam1(List resList) {
        resList.forEach(a -> {
            resList.forEach(b -> {
                resList.forEach(c -> {
                    resList.forEach(d -> {
                        resList.forEach(e -> {
                            resList
                        });
                    });
                });
            });
        });
    }
}
```

dead loop when throw Exception here
net.sourceforge.pmd.lang.java.ast.JavaParser#generateParseException
--> jj_rescan_token();
----> jj_3_82();

dead loop scan the token

**Running PMD through:** *[java test code]*

**Comment by oowekyala** [comment]
The problem is caused by the fact the code is invalid, the lookahead must be backtracking or something. The loop is not infinite, but it appears to be exponential in the number of levels of nesting, so that 5 like here make this untractably slow.

The problem is not present in the current PMD 7.
