### ISSUE TITLE
[java] InvalidLogMessageFormat detection failing when String.format used

### ISSUE THREAD

**Issue by jcamerin** [pmd/pmd#3146]
New in 6.32, did not occur in 6.31

Make sure, to test with the latest PMD version.

**Description:**

The InvalidLogMessageFormat is incorrectly flagging logging statements for having the wrong number of arguments when String.format is used inline to build the msg parameter.

**Exception Stacktrace:**

```
Missing arguments, expected 1 argument but have 0.

Check for messages in slf4j and log4j2 (since 6.19.0) loggers with non matching number of arguments and placeholders.
```

**Code Sample demonstrating the issue:**

```
LOGGER.info(String.format("Skipping file %s because no parser could be found", entry.getName()));
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

Run mvn pmd:pmd to generate the false flag

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Java 8
Maven 3.5

**Comment by adangel** [comment]
Thanks for the report, this is a regression introduced by fixing #3133 .
