### ISSUE TITLE
[apex] Documentation flaw on Apex Sharing Violations

### ISSUE THREAD

**Issue by Presh-AR** [pmd/pmd#315]
Example in documentation is
`public class without sharing Foo`

This will lead to lot of misleading findings. Please replace by

`public without sharing class Foo`

then PMD is working fine

**Comment by jsotuyod** [comment]
@Presh-AR thanks for the report! I'll try not to miss any, as this seems to be in several places.

**Comment by jsotuyod** [comment]
I thought this was a documentation issue, but it seems it's not. The order of the sharing / class keywords seems not to matter. The Jorje parser will recognize both as correct.

On the apex documentation site they seems to prefer `with[out] sharing class`, but there is no formal grammar. The closest there is is [this](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_defining.htm#highlighter_331214), which is obviously not formal, as it would suggest that `abstract` or `virtual` classes can't define sharing, which they do.

Is there anything I'm missing here?

**Comment by jsotuyod** [comment]
@sgorbaty you sure can help us out here.

**Comment by sgorbaty** [comment]
@jsotuyod 
```public class without sharing Foo``` appears to be the wrong description. 
I just spun my developer org and a class defined as such results in a compilation error. 
The correct way is ```public without sharing class Foo```.

**Comment by up2go-rsoesemann** [comment]
@jsotuyod Why is this still open although a fix was merged in?

**Comment by adangel** [comment]
@up2go-rsoesemann the PR #323 is not yet merged - I'll merge it soon, then this issue will be closed, too.
