### ISSUE TITLE
[java]  UseProperClassLoader false positive

### ISSUE THREAD

**Issue by hgschmie** [pmd/pmd#3173]
**Rule** [UseProperClassLoader](https://pmd.github.io/latest/pmd_rules_java_errorprone.html#useproperclassloader)

**Affects PMD Version:** 
6.32.0 (should be all versions since 3.7)

Make sure, to test with the latest PMD version.

**Description:**

The `UseProperClassLoader` will match any method called `getClassLoader()`, not just `java.lang.Class.getClassLoader`, e.g. https://javadoc.io/static/io.dropwizard/dropwizard-core/2.0.20/io/dropwizard/setup/Bootstrap.html#getClassLoader--

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  ... use a dropwizard project, then call `bootstrap.getClassLoader()` in the `initialize` method of a dropwizard app, run pmd on it.
2.  ... run pmd on the project (maven or command line)

**Comment by adangel** [comment]
This has been fixed with PMD 7.0.0-rc1.
