### ISSUE TITLE
[GSoC] The Metrics Framework will have to somewhat depend on Complete Type Resolution for Java.

### ISSUE THREAD

**Issue by Oowekyala** [pmd/pmd#318]
Hi!

Some metrics require that the qualified names of all methods used and fields accessed be extracted from the measured method. These metrics are FDP, CDISP, CINT, CM, and CC (see [this page](https://github.com/Oowekyala/pmd-metrics-framework-wiki/wiki/Index-of-all-metrics-with-implementation-notes) for a description of those metrics), which primarily help to detect collaboration disharmonies (Shotgun Surgery, Dispersed Coupling, and Intensive Coupling).

Unfortunately finding the qualified names of those methods will require Type Resolution to handle method invocation and field access correctly. Until then, most of the above metrics cannot be computed at all. Some other metrics such as ATFD, BUR, LAA, or NOAV could be computed via AST exploration, but a faster, more accurate way would be to use signature matching, and would require Type Resolution to be completed.

Thus, the project I'm proposing is somewhat dependent on the type resolution project. I asked someone at Google how many slots are usually given to first-time participating organisations, and his answer was 2.  If @WinterGrascph 's project and my own are accepted, we could benefit from adapting our timelines to take that dependency into acount. Otherwise my project will have to stay confined to the detection of identity and classification (inheritance-related) disharmonies.

Related people: @adangel @jsotuyod

**Comment by WinterGrascph** [comment]
Hey! :)

This would be great, combining the two projects would bring triple the fun. I'm not much familiar with these metrics, but I suspect they are not dependant on things like method overloading. Simple field access and basic method invocation type resolution (ExpressionName.method(), no overloads)  shouldn't take too long to implement. I could move both of these to the beginning of the timeline and then you should be clear to proceed, complex rules for overloaded method resolution and what not can wait.

**Comment by Oowekyala** [comment]
Hi! That's great, thanks! :) 

Yeah method invocation and field access are the key thing here. Some other metrics need overload resolution but they wouldn't need your framework to support them at first, I've got an alternative way to implement them. Basically until mid July I shouldn't even need those capabilities, so you'd have 1 month and a half to work that out. After that if there's some delay on your part I can always elude metrics that cannot be supported until it's done, and come back on that later. 

Well anyway, happy to know we might work together!
.

**Comment by jsotuyod** [comment]
@Oowekyala @WinterGrascph I love watching you get involved and interacting this way. Let us know if you need any help or support.

**Comment by jsotuyod** [comment]
Marking this as closed to keep the tracker tidy. Proposals has been submitted, and review will go on over GSoC's formal channels.
