### ISSUE TITLE
[java] Deprecate rule DefaultPackage

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3206]
**Rule:** [DefaultPackage](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#defaultpackage)

**Is your feature request related to a problem? Please describe.** I just don't see any use case for this rule. This rule assumes that any usage of package-access is accidental, and by doing so, prohibits using a really fundamental and useful feature of the language.

To satisfy the rule, you have to make the member public even if it doesn't need to, or make it protected, which muddies your intent even more if you don't intend the class to be extended, and may be at odds with other rules like [AvoidProtectedFieldInFinalClass](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#avoidprotectedfieldinfinalclass).

Also, we already have [CommentDefaultAccessModifier](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#commentdefaultaccessmodifier), which flags the same thing, but has an escape hatch. This is I think a more reasonable rule, which should be used instead.

**Describe the solution you'd like** Deprecate the rule DefaultPackage for removal in pmd 7

**Describe alternatives you've considered** None

**Additional context**

**Comment by adangel** [comment]
FYI - this rule was originally in the ruleset controversial.
I think, suggesting to use CommentDefaultAccessModifier instead is a good idea.
