### ISSUE TITLE
Writing Rule to check the code coverage of a Apex Test class .

### ISSUE THREAD

**Issue by bashagithub** [pmd/pmd#325]
[apex] :  How to write a Rule in Pmd to check the code coverage of a apex test class .

Rule Set:  

Description:* how to write a Rule to check the code coverage of apex test class*

Code Sample demonstrating the issue:
  Currently we have only two rules in PMD while testing the apex unit test classes.
     1.	 ApexUnitTestClassShouldHaveAsserts. 2.  ApexUnitTestShouldNotUseSeeAllDataTrue.

Running PMD through:*Eclipse* *[CLI | Ant | Maven | Gradle | Designer | Other]
    Note: we installed PMD plug-in in eclipse IDE for apex code analyzing.

**Comment by up2go-rsoesemann** [comment]
@bashagithub I'm sorry to say that but thats an undoable task for PMD.

Code coverage needs to know runtime behavior of code which a static code analyzer like PMD (only parses code without compiling and running it) cannot do. 

The problem gets even worse with a cloud infrastructure like Salesforce.com where code never can be compiled locally but only on a Salesforce pod.

**Comment by jsotuyod** [comment]
@bashagithub I fear @up2go-rsoesemann is right.

Computing code coverage usually requires code instrumentation (modifying the generated code either at compile or runtime), to add tracking code to be part of unit test execution. After tests run, the tracked data is collected and aggregated. 

PMD does not modify nor execute the code, and therefore can't reliably compute coverage.

You can however use the official tools for code coverage computation, such as Force.com IDE.
