### ISSUE TITLE
[apex] Operation with limits in loop - Incorrect finding in IF statement

### ISSUE THREAD

**Issue by stefanoportelli** [pmd/pmd#3334]
**Affects PMD Version:**

6.35.0

**Description:**

We receive a warning "Operation with limits in loop" for the below line in bold

```
if(article.ToPublishDate__c != null){
Approval.UnlockResult ur = Approval.unlock(article.Id);        <-------
KbManagement.PublishingService.scheduleForPublication(article.KnowledgeArticleId, article.ToPublishDate__c);
}
```

**Steps to reproduce:**
Use the test.txt class  
[Test.txt](https://github.com/pmd/pmd/files/6636656/Test.txt)

And the following apex ruleset
[apex_ruleset.txt](https://github.com/pmd/pmd/files/6636666/apex_ruleset.txt)

run pmd and you will receive:
"5","","Test.txt","1","20","Operation with limits in loop","Performance","OperationWithLimitsInLoop"

**Running PMD through:** *[CLI]*

**Comment by jonathanwiesel** [comment]
Hi @stefanoportelli, looking at your test.txt file I see that the `unlock` statement is in fact inside a `for` loop block where you are iterating knowledge articles.

Taking into account that `Approval.unlock` does impact on governor limits you can iterate in the `for` loop to gather the identifiers of all articles then call only once the  `Approval.unlock` passing the list of ids [as mentioned in the docs](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_approval.htm).

**Comment by stefanoportelli** [comment]
Thanks @jonathanwiesel I missed the {} of the for!
