### ISSUE TITLE
[java] [doc] Add suggestion to use StringUtils#isBlank for InefficientEmptyStringCheck

### ISSUE THREAD

**Issue by mkordas** [pmd/pmd#334]
Currently [InefficientEmptyStringCheck](https://pmd.github.io/pmd-5.5.5/pmd-java/rules/java/strings.html#InefficientEmptyStringCheck) suggests to create a loop. We can point there that [isBlank](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-) can be used or its code can be copied if we don't want to have `commons-lang` on classpath.

**Comment by jsotuyod** [comment]
Sounds reasonable. A simple documentation improvement.

**Comment by Oowekyala** [comment]
Good idea, that may save some time to many. I made PR #382 to close that

**Comment by ryan-gustafson** [comment]
CPD anyone? :)  We're really going to suggest copying the code from an Apache project as a suggest solution?

**Comment by Oowekyala** [comment]
@ryan-gustafson Well I may be wrong but CPD wouldn't report it unless commons-lang was analysed too, would it? Besides, I feel like fixing a violation of this rule should be simpler than writing a new method from scratch especially since it's already coded somewhere ^^ Maybe we could only suggest that the user "take inspiration" from Apache's code?

**Comment by ryan-gustafson** [comment]
@Oowekyala It's the irony (hypocrisy?) of suggesting cut-n-paste as a solution when one of the major tools in the PMD toolbelt is designed to detect such behavior so you can squash it.

I'd rather we suggest they adopt a method from a selection of libraries which implement good solutions and leave it at that.  Suggesting to cut-n-paste is presuming a problem they may not have.  If they did have a problem adopting, they should address that problem directly and remove the roadblock.  I can't recall the last time I was painted into a corner so badly I had to resort to copying method implementations from a 3rd party library.

As far as what to suggest, is that new territory for PMD?  I don't know PMD rules generally advocate for choosing a "winner" among libraries.  If I had to, I guess I'd prefer to point to something like a stackoverflow discussion to inform of technical alternatives (e.g. https://stackoverflow.com/questions/23419087/stringutils-isblank-vs-string-isempty) and/or provide at least the two "popular" options if we're going to start naming explicit libraries to use.  Even that changes over time, new libraries appear, the JDK changes, it's a messy business in general.

**Comment by adangel** [comment]
@oowekyala @ryan-gustafson 
I agree, we shouldn't advocate to copy-paste the code. If one can't include a 3rd party library for whatever reason, I'm sure, they know, how to lookup the code.

I like it, that we extend the description to suggest to use a library/off-the-shelf-solution. The current rule description helps to understand the problem and the solution, but the solution is quite low level.
I did a quick search and found one additional implementation from the spring framework. So, if we want to offer alternatives, we could point the users to
* [Apache Commons Lang](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-): `isBlank(...)`
* [Spring's StringUtils](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/util/StringUtils.java#L139): `hasText(...)`

**Comment by oowekyala** [comment]
@ryan-gustafson @adangel Ok I get your point, suggesting to copy paste is not a good solution. Merely referencing existing implementations is enough for the user and it isn't contradicting what PMD's preaching

I'll modify my PR ;)
