### ISSUE TITLE
[java] SwitchStmtsShouldHaveDefault and implicit default

### ISSUE THREAD

**Issue by ben-manes** [pmd/pmd#3346]
**Affects PMD Version:** 
6.35.0

**Rule:**
[SwitchStmtsShouldHaveDefault](https://pmd.github.io/pmd-6.35.0/pmd_rules_java_bestpractices.html#switchstmtsshouldhavedefault)

**Description:**
ErrorProne's [UnnecessaryDefaultInEnumSwitch](https://errorprone.info/bugpattern/UnnecessaryDefaultInEnumSwitch) suggests an alternative syntax for an exhaustive enum. Instead of a `default` clause, the statement after the switch will throw the exception. These two rules conflict, but have the same desired behavior. PMD could be more tolerant and allow this check to pass if it follows the error prone style.

```java
// PMD preferred, ErrorProne disfavored
enum State { ON, OFF }

boolean isOn(State state) {
  switch (state) {
    case ON:
      return true;
    case OFF:
      return false;
    default:
      throw new AssertionError(state);
  }
}
```

```java
// PMD disfavored, ErrorProne preferred
enum State { ON, OFF }

boolean isOn(State state) {
  switch (state) {
    case ON:
      return true;
    case OFF:
      return false;
  }
  throw new AssertionError(state);
}
```

**Comment by adangel** [comment]
The rule [SwitchStmtsShouldHaveDefault](https://pmd.github.io/pmd-6.35.0/pmd_rules_java_bestpractices.html#switchstmtsshouldhavedefault) should create a violation for switches over enums only, if not all cases are covered.

So, you should *not* get a violation with your second example. Can you confirm this?

If you get a violation, then PMD is not able to determine that State is a enum.
Then: How do you execute PMD? PMD can only determine all values of a enum, if you have compiled your code before running PMD and providing an auxclasspath for the analysis...

**Comment by ben-manes** [comment]
Thanks @adangel. Maybe I overly generalized the code. The exact [scenario](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/sketch/climbing/HillClimber.java#L102-L108) that fails for ErrorProne when `UnnecessaryDefaultInEnumSwitch` is added to the enabled [checks](https://github.com/ben-manes/caffeine/blob/3ccb1bf97ff93b9f20717e299ea0aa70469c8260/gradle/codeQuality.gradle#L114) is,

```java
public enum Type {
  HOLD, INCREASE_WINDOW, DECREASE_WINDOW
}

public String toString() {
  switch (type) {
    case HOLD: return "0";
    case INCREASE_WINDOW: return "+" + amount;
    case DECREASE_WINDOW: return "-" + amount;
    default: throw new IllegalStateException();
  }
}
```

```
warning: [UnnecessaryDefaultInEnumSwitch] Switch handles all enum values: move code from the default case to
execute after the switch statement to enable checking for non-exhaustive switches. That is, prefer: 
`switch (...) { ... } throw new AssertionError();` to 
`switch (...) { ... default: throw new AssertionError(); }`
        default: throw new IllegalStateException();
        ^
    (see https://errorprone.info/bugpattern/UnnecessaryDefaultInEnumSwitch)
  Did you mean to remove this line?
```

When I switch to ErrorProne's recommendations the code looks like
```java
public String toString() {
  switch (type) {
    case HOLD: return "0";
    case INCREASE_WINDOW: return "+" + amount;
    case DECREASE_WINDOW: return "-" + amount;
  }
  throw new IllegalStateException();
}
```

and PMD fails with `SwitchStmtsShouldHaveDefault`. This is why I believe the two checkers have conflicting rules but the same intent, so the allowed style could be more flexible.

PMD is run using Gradle:
```
$ gradle :simulator:pmdMain -Dpmd --console plain
-PchecksumUpdateAll is specified, so the build won't fail in case of the checksum mismatch
> Task :simulator:downloadCaffeineLocal UP-TO-DATE
> Task :caffeine:downloadCaffeineLocal UP-TO-DATE
> Task :simulator:processResources UP-TO-DATE
> Task :caffeine:compileJavaPoetJava UP-TO-DATE
> Task :caffeine:processJavaPoetResources UP-TO-DATE
> Task :caffeine:javaPoetClasses UP-TO-DATE
> Task :caffeine:generateLocalCaches UP-TO-DATE
> Task :caffeine:generateNodes UP-TO-DATE
> Task :caffeine:compileJava UP-TO-DATE
> Task :caffeine:processResources NO-SOURCE
> Task :caffeine:classes UP-TO-DATE
> Task :caffeine:compileCodeGenJava SKIPPED
> Task :caffeine:jar UP-TO-DATE
> Task :simulator:compileJava UP-TO-DATE
> Task :simulator:classes UP-TO-DATE
> Task :simulator:pmdMain FAILED
/Users/ben/projects/caffeine/checksum.xml is up to date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':simulator:pmdMain'.
> 1 PMD rule violations were found. See the report at: file:///Users/ben/projects/caffeine/simulator/build/reports/pmd/main.html
```

**Comment by jsotuyod** [comment]
This is not reproducible under PMD 7.0.0. If the auxclasspath is complete and the switch is exhaustive, no violation should be issued for missing default.
