### ISSUE TITLE
[java] InvalidSlf4jMessageFormat applies to log4j2

### ISSUE THREAD

**Issue by ryan-gustafson** [pmd/pmd#336]
The InvalidSlf4jMessageFormat rule can apply to log4j2 as well.  However, the rule name and the java code is hardcoded to specifically to slf4j.  One could change the LOGGER_CLASS and LOGGER_LEVELS to support the levels/methods used by log4j2 would suffice.  I'd also consider allowing changing of the {} placeholder, although this likely less useful.  

   https://logging.apache.org/log4j/2.0/manual/messages.html
   https://logging.apache.org/log4j/2.x/manual/customloglevels.html

log4j2 also supports printf style format strings, in which case the placeholders are more complex, and have their own mini-language.  But, the same rule applies, does the argument count match.  One could even think of applying this to other non-logging APIs (e.g. String.format(...)).

This is issue is just one example of how the different rules around logging are a bit haphazard.  Some effort could go into giving better coverage across the different logging apis (Java, SLF4J, log4j, log4j2. logback, etc).  Codify which logging frameworks/versions are supported, and which usage patterns are detected for each.  And then perhaps adding appropriate meta-logging rules, to keep things easy for the end PMD users (e.g. like MoreThanOneLogger).

Poking through the code, I notice, for example, that MoreThanOneLogger would support log4j version 1, but not log4j v2:
https://pmd.github.io/pmd-5.5.5/pmd-java/xref/net/sourceforge/pmd/lang/java/rule/logging/MoreThanOneLoggerRule.html

**Comment by jsotuyod** [comment]
Most interesting! Would you consider submitting PRs to address these? I see you already diged into the code, and some of these fixes seem rather trivial (fixing `MoreThanOneLoggerRule`).

It would certainly help us to add Log4J2 support much faster, even maybe on time for next release!

**Comment by markhall82** [comment]
@jsotuyod as this is a good first issue, would you like me to take a look? I know it's old, is it still relevant?

**Comment by jsotuyod** [comment]
@markhall82 this is still relevant and your contribution is more than welcomed!

**Comment by markhall82** [comment]
Thanks @jsotuyod . 

It seems a simple change however to add the log4j2 class and log levels to InvalidSlf4jMessageFormat.java - but should this particular class also be responsible for log4j2?

Also, I noticed that in logging-java.xml the rule has a 'deprecated' attribute.
`<rule ref="category/java/errorprone.xml/InvalidSlf4jMessageFormat" deprecated="true" />`

**Comment by jsotuyod** [comment]
> It seems a simple change however to add the log4j2 class and log levels to InvalidSlf4jMessageFormat.java - but should this particular class also be responsible for log4j2?

We have several rules that work on different libraries… most logger rules have been renamed to not mention the library and just work on all (java util logging, apache commons logging, log4j, slf4j, etc.); this is one we should probably rename to be more generic once the change is performed.

> Also, I noticed that in logging-java.xml the rule has a 'deprecated' attribute.
> `<rule ref="category/java/errorprone.xml/InvalidSlf4jMessageFormat" deprecated="true" />`

What is deprecated is the `logging-java.xml` ruleset, as in PMD 6 all rules where moved to categories and are to be referenced from there. The rule itself is still supported and maintained. See https://pmd.github.io/pmd-6.17.0/pmd_release_notes_old.html#rule-categories

**Comment by markhall82** [comment]
Thanks. I'll keep that in mind and make a PR, sometime soon hopefully.
