### ISSUE TITLE
Why do most of my contributions don't show up?

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#3421]
@adangel and @jsotuyod I recently had the change to get into free beta of a Githubtool but had to prove that I am and was quite active in an Open Source community. They rejected PMD as they only looked at the contributor stats which showed incorrectly that I on contributes a bunch of lines

![Screenshot 2021-07-27 at 15 15 34](https://user-images.githubusercontent.com/8180281/127160379-9340bd99-4c31-4220-aa91-e75524a43da8.png)

and not that I added a Language and had PRs since 2016

![Screenshot 2021-07-27 at 15 16 16](https://user-images.githubusercontent.com/8180281/127160483-2f7e2220-85af-4bf5-ab31-2c9119239676.png)

**Comment by oowekyala** [comment]
Check that the email address with which you signed your commits is associated with your github account

**Comment by oowekyala** [comment]
Looks like most of your commits use `robert.soesemann@up2go.com`

**Comment by adangel** [comment]
Here you can see which commits github thinks are yours: https://github.com/pmd/pmd/commits?author=rsoesemann

**Comment by adangel** [comment]
You can add your other emails here: https://github.com/settings/emails
If the email can't be verified, this is not a problem. This just means, you can't use it in github for notifications, but the commits still belong to you.

E.g. I once accidentally committed as "andreas@yildun", but since I added this email in my settings, the commit https://github.com/pmd/pmd/commit/9d96d974de3a9881355a5682c80e62e023b32d36 is associated with my github account.

**Comment by rsoesemann** [comment]
@adangel I added robert.soesemann@up2go.com to https://github.com/settings/emails. Thanks for that tip. I guess it takes a while until that is reflected in https://github.com/pmd/pmd/graphs/contributors, right?!

**Comment by rsoesemann** [comment]
It worked. Wonderful. Back in the Pro-League. Thanks guys for helping with that.

![Screenshot 2021-07-28 at 15 36 16](https://user-images.githubusercontent.com/8180281/127331669-9592d51d-e942-4d01-ac71-356e54c8dcb8.png)

**Comment by rsoesemann** [comment]
Strange. Sometimes it shows up correctly now and sometimes not. Maybe a caching issue. Thanks for your help.

![Screenshot 2021-07-28 at 15 50 55](https://user-images.githubusercontent.com/8180281/127333984-062ed29b-2759-4633-9fd0-d410d569734b.png)
