### ISSUE TITLE
[apex] VfUnescapeEl do not care about JSENCODE

### ISSUE THREAD

**Issue by stefanoportelli** [pmd/pmd#3422]
**Affects PMD Version:** 
6.36

**Rule:** [VfUnescapeEl](https://pmd.github.io/latest/pmd_rules_vf_security.html#vfunescapeel)

**Description:**
If a page contains the following code:

```xml
<apex:outputText escape="false" value="<b>Parsed value 1</b> {!JSENCODE(pod.node)} 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>Parsed value 2</b> {!JSENCODE(pod.indirizzo)}" /><br/>
```

that will fires two warnings for VfUnescapeEl even we used JSENCODE.

**Steps to reproduce:**
1. Download [test.page.txt](https://github.com/pmd/pmd/files/6886351/test.page.txt)
2. Rename the file to test.page
3. Run PMD

the output will contains the following:
"Problem","Package","File","Priority","Line","Description","Rule set","Rule"
"1","","C:\src\test.page","2","71","Avoid unescaped user controlled content in EL as it results in XSS","Security","VfUnescapeEl"
"2","","C:\src\test.page","2","71","Avoid unescaped user controlled content in EL as it results in XSS","Security","VfUnescapeEl"

**Running PMD through:** 
*CLI*

**Comment by adangel** [comment]
Since you are generating html text, maybe you just need to use `HTMLENCODE` instead of `JSENCODE`?

**Comment by stefanoportelli** [comment]
Hi @adangel you are absolutely right. Using the right encode solved the problem.
The main reference in this case is the following: 
[https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/pages_security_tips_scontrols.htm](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/pages_security_tips_scontrols.htm)

Thanks for your help!
