### ISSUE TITLE
[core] Deprecate `-language`, `-version`, `-min` options

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3426]
**Is your feature request related to a problem? Please describe.**
The couple of CLI options `-language` and `-version` are used to specify the language version to use when discovering a file for that language. They're virtually not documented, only work when they're specified together (and otherwise just don't do anything, but that doesn't produce a warning), and are not repeatable. Ultimately we could just use a single option and make it repeatable.
The option `-min` is a single-dash option for `--minimum-priority`. However, GNU style options allow to combine multiple single-dash options, so `-min` means actually `-m -i -n`. While we don't support this combination, keeping `-min` would prevent us from ever doing so.

**Describe the solution you'd like** 
* Introduce a new option `--use-version` (as per #3424) which has arity 2 (language AND version number). It would be used like `--use-version java 16`.
* Maybe make it repeatable if it's easy enough.
* Deprecate `-language` and `-version`. 
* Deprecate `-min` in favor or `--minimum-priority`

**Describe alternatives you've considered**

**Additional context**
Relevant current issues:

- #3424 
- #3425
- #3417 introduces `--force-language`

**Comment by jsotuyod** [comment]
As I assumed, doing `--use-version` with arity 2 is not properly supported.

The help can't provide different names to each value (ie: it would show `--use-version langver langver`).
The autocomplete also struggles with this. It can't do suggestions beyond the first value (reported to PicoCli on https://github.com/remkop/picocli/issues/1755)

A probably better approach is to use a single arity value, such as "java-16", "java-16-preview", "scala-2.12", etc. where we can have both "java" and "java-latest" as equivalent to the default / latest version. Doing this option repeatable is extremely cheap.

I think we should probably also revamp `--force-version` to use the same "lang-version" string format. Right now, we can force a language, but it will always use the default version. This approach would give consistency and solve that too.

**Comment by oowekyala** [comment]
Thanks for experimenting with this!

> A probably better approach is to use a single arity value, such as "java-16", "java-16-preview", "scala-2.12", etc. where we can have both "java" and "java-latest" as equivalent to the default / latest version. Doing this option repeatable is extremely cheap.

This sounds great

> I think we should probably also revamp `--force-version` to use the same "lang-version" string format. Right now, we can force a language, but it will always use the default version. This approach would give consistency and solve that too.

There is just a `--force-language` option, not `--force-version`. I think it should compose well with `--use-version` without changes, eg `--force-language java --use-version java-17`. Am I missing your point?

**Comment by jsotuyod** [comment]
> There is just a `--force-language` option, not `--force-version`. I think it should compose well with `--use-version` without changes, eg `--force-language java --use-version java-17`. Am I missing your point?

Well, right now it does neither… `--force-language` always forces the default version under PMD 6. So it was either forcing the composition as you suggest, or making `--force-language` able to set a language-version pair equivalent to what `--use-language` does.

Extending `--force-language` provides consistency, makes it easy to swap one option for the other, and is self-contained.

The composition on the other hand, helps to avoid any confusion as to why use one option vs the other.

I'm torn… I'll try your approach and see from there.
