### ISSUE TITLE
[core] Allow XPath rules to access the current file name

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3446]
### Discussed in https://github.com/pmd/pmd/discussions/3444

<div type='discussions-op-text'>

<sup>Originally posted by **rsoesemann** August  6, 2021</sup>
I want to use XPath rules to check whether files name comply with certain naming rules? Is that possible in PMD?</div>

-> not currently supported, we can add an attribute to apex root nodes in PMD 6. In PMD 7 we can add an attribute to all RootNodes

**Comment by rsoesemann** [comment]
@oowekyala would it be hard to make that work for arbitrary languages or at least XML? I need it for the hundreds of different XML metadata files that exist in the Salesforce ecosystem.

**Comment by oowekyala** [comment]
For xml ideally we'd use an xpath function, since we wouldn't want to add attributes that don't exist... I'll look into whether that's possible, if so, maybe we can make that language-independent
