### ISSUE TITLE
[javascript] CPD giving out of memory heap error

### ISSUE THREAD

**Issue by SwatiBGupta1110** [pmd/pmd#3480]
I am using pmd-bin-6.34.0 version for Scanning 7000 files of javascript around 1 GB of data.  
Below is the command I am executing.

D:\>setx PMD_JAVA_OPTS -Xms2g

D:\>set PMD_JAVA_OPTS=-Xms2g

(Allocating 2 GB RAM as instructed on https://pmd.github.io/latest/pmd_userdocs_cpd.html)

D:\>cpd.bat --skip-lexical-errors --minimum-tokens 75 --files D:\AIML --format csv --encoding CP1252 --language js>D:\output.csv 

**It gives me java.lang.OutOfMemoryError : Java Heap space**
I am scanning  It take around 15 mins of time for scanning with 32 GB RAM.
![Exception Screenshot](https://user-images.githubusercontent.com/89257671/130243094-e0153918-a70b-49dc-aa15-cca5e380dc9f.jpeg)
![Command_screenshot](https://user-images.githubusercontent.com/89257671/130243097-18ea2ed5-db88-434f-9290-58194640bb99.jpeg)

**Comment by adangel** [comment]
Can you try with the latest PMD version (6.37.0)?

With 6.35.0 we fixed a similar problem #2081.

Please note, that you'll need to use Java8 for analyzing Javascript since PMD 6.35.0 (see https://pmd.github.io/2021/05/29/PMD-6.35.0/#javascript-module-now-requires-at-least-java-8)

**Comment by SwatiBGupta1110** [comment]
Thanks a lot for your reply and quick response. Can I use anything greater
than version 8.0 of java. Currently I'm using openJDK 11.0
