### ISSUE TITLE
[java] Throwing Exception in method signature is fine if the method is overriding or implementing something

### ISSUE THREAD

**Issue by SUPERCILEX** [pmd/pmd#350]
**Rule Set:** typeresolution.html#SignatureDeclareThrowsException

**Code Sample demonstrating the issue:**

```java
@Override
public Team call() throws Exception {
     // ...
}
```

**Running PMD through:** Gradle

**Comment by jsotuyod** [comment]
This seems to be a bug. The rule makes extensive checks for JUnit classes, but should more generally just ignore overrides focusing solely on the original method declaration.
