### ISSUE TITLE
[java] AccessorClassGeneration throws ClassCastException when seeing array construction

### ISSUE THREAD

**Issue by ryan-gustafson** [pmd/pmd#352]
The rule `java/design/AccessorClassGeneration` fails with the following exception trace:
```
Caused by: java.lang.ClassCastException: net.sourceforge.pmd.lang.java.ast.ASTArrayDimsAndInits cannot be cast to net.sourceforge.pmd.lang.java.ast.ASTArguments
	at net.sourceforge.pmd.lang.java.rule.design.AccessorClassGenerationRule.visit(AccessorClassGenerationRule.java:78)
	at net.sourceforge.pmd.lang.java.ast.ASTAllocationExpression.jjtAccept(ASTAllocationExpression.java:21)
	at net.sourceforge.pmd.lang.java.rule.JavaRuleChainVisitor.visit(JavaRuleChainVisitor.java:41)
```

Using the following test case for `AccessorClassGeneration.xml`:
```
    <test-code>
        <description><![CDATA[
Array initializer is not a class body
     ]]></description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private class Bar {
        private int size;

        private Bar() {
        }

        void bar() {
            new Bar[size];
        }
    }
}
     ]]></code>
    </test-code>
```

This is related to issue https://github.com/pmd/pmd/issues/291 and pull request https://github.com/pmd/pmd/pull/293 in some fashion.

**Comment by jsotuyod** [comment]
I'm on it. @ryan-gustafson it's good to have you back

**Comment by ryan-gustafson** [comment]
I found this issue and the one I reopened on https://github.com/pmd/pmd/issues/330 merely by running all the Java rules against the source in the PMD code base as part of benchmarking.

Did anyone ever get around to creating a test harness which pulls down various open source projects and runs PMD against them looking for parser and rule evaluation errors?  Also to compare report results with previous PMD releases, looking for false positive regressions?

**Comment by jsotuyod** [comment]
@ryan-gustafson it's been discussed, but never so far implemented. The same goes for dogfooding, having PMD run on PMD.

I'd love if someone found the time to have Travis do analysis on Spring Framework, Solr and a bunch of other big projects; but so far we have only been able to work on automating releases (which has come a long way in allowing us to release faster and more often), maybe on the next iteration of Travis setup.

@adangel did find the time to add some basic [integration testing on the pmd-dist module](https://github.com/pmd/pmd/tree/master/pmd-dist/src/test/java/net/sourceforge/pmd/it), which could be useful to build such scenarios.

Feel free to submit a PR.

**Comment by ryan-gustafson** [comment]
@jsotuyod Cool, didn't notice pmd-dist, I'll check it out.  With everything broken out nowadays, a project depending on everything is exactly what would be needed.  I found some of my old code trying to solve this problem, I'll see if it's worth anything still.

I had created the dogfood ruleset way back when, and it seems to be listed in the top level pom. 
 Unfortunately, looks like I never finished getting it fully operational. 
 https://github.com/pmd/pmd/tree/master/pmd-core/src/main/resources/rulesets/internal

The Travis CI builds don't seem to use it from the logging of the most recent build.  I've no inclination to diagnose the Maven build that much, I've been using Gradle the last 5 years and my Maven is too rusty (don't really care to sharpen it again either).

**Comment by jsotuyod** [comment]
@ryan-gustafson no, it's not being used right now. It's probably just as you left it. We do intend to get it working and built into our self-testing / Travis though. All help is welcomed!

As for Maven, I know the feeling. PMD has been the only maven project I actively use for quite some time now... but I'm probably not that rusty. Let me know if I can help you in any way.

**Comment by adangel** [comment]
@ryan-gustafson the travis build runs PMD, but it won't fail for any violations found...
I've added #360 and #361 to not forget about these tasks.
