### ISSUE TITLE
[java] eclipse pmd plugin falsely reports java file having incorrect syntax

### ISSUE THREAD

**Issue by OverDrone** [pmd/pmd#362]
eclipse pmd plugin shows error log entry although file is correct. java file and exception attached
[BrogiCatalogConverter.zip](https://github.com/pmd/pmd/files/951678/BrogiCatalogConverter.zip)

**Comment by jsotuyod** [comment]
You seem to be using an unofficial plugin (https://github.com/acanda/eclipse-pmd), using an old version of PMD.

Consider updating the plugin to the latest version if not already, asking the plugin developers to update to the latest PMD release, or switching to [the official PMD plugin](https://github.com/pmd/pmd-eclipse-plugin)
