### ISSUE TITLE
[lang-test] Upgrade dokka maven plugin to 1.4.32

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#3759]
We currently need jcenter as a repository

https://github.com/pmd/pmd/blob/1290999ec2b4d0ce58d89c2fc57d0188f018d770/pom.xml#L931-L943

But jcenter is basically obsolete, although they keep it running as read-only (so that e.g. our build doesn't break): https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ .
However, this created already a problem for reproducible builds (https://github.com/jvm-repo-rebuild/reproducible-central/issues/70)

We currently use [dokka](https://github.com/Kotlin/dokka) 1.4.30.

It seems that upgrading to 1.4.32 is already sufficient, although this version still uses jcenter. At least I can build pmd with a fresh maven repo and without jcenter.

The new dokka version 1.6.10 only uses maven-central, but might require us to update kotlin etc.

**Comment by oowekyala** [comment]
Actually I wanted to update the kotlin version in this release... Should I do that early so that you can use the latest dokka 1.6.10?

**Comment by adangel** [comment]
> Actually I wanted to update the kotlin version in this release... Should I do that early so that you can use the latest dokka 1.6.10?

I tested it with 1.4.32 and the update is unproblematic (see PR #3760). So there is no urgency required. The fix for the reproducible build is actually independent (it's just adding jcentral as a repo), but I wanted to take the chance to remove jcenter directly.

**Comment by oowekyala** [comment]
Ok great! I found out about your PR after writing my comment, which made no sense given there's already a PR. Thanks for looking into this, it sounds like a nice fix.
