### ISSUE TITLE
[java] Parser Error for empty statements

### ISSUE THREAD

**Issue by mrlzh** [pmd/pmd#378]
this code will cause the error
`import java.util.Map;;
import java.util.Map;`

**Comment by ryan-gustafson** [comment]
Can you be more specific?  That is not the source code for a valid `.java` file.

**Comment by mrlzh** [comment]
import test1;;
import test2;

public class HelloWorld {
    public static void main(String[] args){
        System.out.println("Hello World!");
    }
}

**Comment by jsotuyod** [comment]
The problem seema to be that compilationunit accepts no empty statements. The same would happen for code such as

```
package foo;;
```

Curiosly, TypeDeclaration allows for empty statements, but the generated ast makes no sense

```
public class Foo {};
```

Produces a compilationunit with 2 type declarations, one for foo and one for ; completely empty.

We should probably remove this hack altogether and make sure empty statements can be parsed everywhere and produces a proper ast.

**Comment by adangel** [comment]
Seems like the eclipse compiler doesn't like the empty statements, too - however `javac` allows this.
