### ISSUE TITLE
[doc] Documentation website table of contents broken on pages with many subheadings

### ISSUE THREAD

**Issue by JerritEic** [pmd/pmd#3812]
**Description:**
Introduced by #3804 (oops), documentation pages with many subheadings result in an TOC too large for the screen.

**Steps to reproduce:**

Affects:
- [PMD 7.0.0 development](https://pmd.github.io/pmd/pmd_next_major_development.html#documentation)
- All Java Rules pages, for example: [Best Practices](https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html)
- [Index of Java code metrics](https://pmd.github.io/pmd/pmd_java_metrics_index.html)
- [Old Release Notes](https://pmd.github.io/pmd/pmd_release_notes_old.html)

![TOC_Too_Large](https://user-images.githubusercontent.com/60690273/155878730-8f3c771b-4b17-4c74-a666-5b5df5aeacf8.PNG)

**Comment by adangel** [comment]
Yeah, I noticed this today as well. If the toc is too large like on Old release notes, you can't scroll the toc.

We can either make the toc-node scrollable:

```css
#toc {
  height: 80%;
  overflow: auto;
}
```

Then you can scroll inside the toc.

Or we can remove the "affix" class, then the toc is not fixed but scrolls together with the page.
