### ISSUE TITLE
PMD User Survey

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3829]
### Discussed in https://github.com/pmd/pmd/discussions/3814

<div type='discussions-op-text'>

<sup>Originally posted by **adangel** February 28, 2022</sup>
We as PMD (<https://pmd.github.io>) maintainers want to learn more about our users, so that we can make PMD even better.

You can help in giving us some insights, how you actually use PMD.

This survey is anonymous. We might however publish a summary of the results publicly.

Survey URL to share: <https://forms.gle/4d8r1a1RDzfixHDc7>

Thank you for participating!
</div>

**Comment by adangel** [comment]
The survey is finished now.
Thank you for all your answers and feedback!
Read here about the results: https://pmd.github.io/2022/07/28/PMD-User-Survey/
