### ISSUE TITLE
[java] controversial.DataflowAnomalyAnalysis false positive in for statment 

### ISSUE THREAD

**Issue by Reissner** [pmd/pmd#387]
Running pmd 5.6.1 on code 

~~~
   public T addS(List<T> args) {
	T res = zeroS();
	for (T arg : args) {
	    res = res.add(arg);
	}

	return res;
    }
~~~

with the above code which I do with through maven, 
I obtain Found 'UR'-anomaly for variable 'arg' (lines '118'-'121').

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by adangel** [comment]
I think, it's this old bug: https://sourceforge.net/p/pmd/bugs/1383/ - the DFA code has never been updated to handle for-each-loops correctly.

**Comment by jsotuyod** [comment]
I'm merging this onto #1636, as we plan to drop UR-anomaly detection
