### ISSUE TITLE
Please add line numbers to the astdump

### ISSUE THREAD

**Issue by narc-Ontakac2** [pmd/pmd#3895]
I am currently importing a small projects XML astdumps into a basex database to the search them with XQuery. However almost any useful search result needs to point to lines in the source code. Unfortunately this information is missing from the XML astdump.

A line attribute in the astdump XML tags related to lines would be helpful.

**Comment by oowekyala** [comment]
The XML renderer already has a property for that, which you can set using `-PrenderCommonAttributes=true` as a CLI parameter.

See also the `--help` text for the ast-dump command (excerpt):
```
Available formats: xml                           XML format with the same structure as the one used in XPath
+ Properties                  
  + singleQuoteAttributes         Use single quotes to delimit attribute values (default true)
  + lineSeparator                 Line separator to use. The default is platform-specific. (default \n)
  + renderProlog                  True to output a prolog (default true)
  + renderCommonAttributes        True to render attributes like BeginLine, EndLine, etc. (default false)
```
