### ISSUE TITLE
[core] Stabilize tree export API

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3905]
The API around [TreeRenderer](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRenderer.java) has been `@Experimental` since it was introduced in PMD 6.21.0 (#2216). I think it's been rather stable and we could promote it to a stable API.

**Comment by jsotuyod** [comment]
#4059 does refactor its implementation (splitting JCommander CLI interface, configuration and actual logic into 3 separate classes), and adds debug / verbose flags, but probably after that we can reassess its maturity.

**Comment by adangel** [comment]
TODO: check net.sourceforge.pmd.util.treeexport.TreeExportConfiguration#setReportFile(java.nio.file.Path) is not used. Should be probably used by net.sourceforge.pmd.cli.commands.internal.TreeExportCommand. found in #4397.
