### ISSUE TITLE
[java] Java rule changes for PMD 7

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#3915]
Tracking issue, part of #3898 

## New rules

- [x] #2973

## Rule mergers/renamings
- none
## Misc rule improvements

(nice-to-haves)

- none

## Removals 

(todo deprecate on master)

- [x] #2127

### Probably for PMD 7
* none

### Postponed
* New Rules
  * #2849
  * #2926
  * #3216
  * #1034
  * #2023
  * #3776
* Rule mergers/renamings
  * #2892
  * #2972
  * #2974
  * #4286
  * #3273 
  * #3124
  * #3459
  * #4287
* Misc rule improvements
  * #3122
  * #3192
  * #3212
  * #3219
  * #3362
  * #3748
  * #3228
  * #4288
  * #4289
  * #4290
* Removals
  * #3741
  * #3295
  * #3217

**Comment by adangel** [comment]
Closing this tracking issue as done. The remaining tasks are either tracked by #3898 or are postponed.
