### ISSUE TITLE
[RFC] Support HTML

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#3941]
Note: this issue is just to document the decision for future reference.

# Support HTML

## Context and Problem Statement

PMD supports XML with the pmd-xml language module. But this only parses well-formed documents.
This prevents us from analyzing less strict formats such as HTML or Salesforce Lightning Web Components,
a HTML dialect/fragment.

## Considered Options

*   Integrate jsoup
*   Own simple HTML parser

## Decision Outcome

Chosen Option: Integrate jsoup

### Integrate jsoup

[jsoup](https://jsoup.org/) is a Java HTML Parser.

*   Neutral: Need to write an AST wrapper, like for javascript or apex (see "tree builder")
*   Neutral: Need to make sure that XPath is conformant

*   Good, because jsoup is very lax when parsing documents
*   Good, because jsoup is already available
*   Bad, because it adds another dependency

*   Option: jsoup -> XML dump -> pmd-xml
    *   Bad, because this will mess up file locations
*   Option: Maybe just Saxon wrapper for jsoup nodes
    *   Bad, too much work
*   Option: Maybe just use jsoup's "XPath" query mechanisms
    *   Bad, because that wouldn't allow to write java rules
    *   Bad, because that's a special solution for this language only

### Own simple HTML parser

*   Good, because in pmd 7 we already plan to use a custom parser for javadoc (which supports HTML)
*   Option: Use own javacc grammar
    *   Bad, because Javacc has no error tolerance, it’s more verbose
*   Own AST -> xpath

## Related issues

*   #3849
*   #3885

----
Note: This loosely uses [MADR](https://adr.github.io/madr/)

**Comment by rsoesemann** [comment]
FYI @SCWells72

**Comment by SCWells72** [comment]
Thanks, @rsoesemann. I saw your retweet earlier and already started implementing the integration but ran into a few issues that I've logged here as:

* #3951 which is easily worked around, and...
* #3952 which presents issues with HTML markup files with non-`html` file extensions in Visualforce and Aura.

Once I have a fix or workaround for the latter I'll complete the integration.
