### ISSUE TITLE
[java] CommentRequired: add properties to ignore @Override method and getters / setters

### ISSUE THREAD

**Issue by TehBakker** [pmd/pmd#396]
**Description:**
The Comment Required rule : http://pmd.sourceforge.net/pmd-5.0.4/rules/java/comments.html#commentRequired offers some properties already to tune the rule.
However from using PMD on various project, I find that a property to ignore overriding method (which mostly use the same javadoc as the overrided method) and getter & setter should be able to easily ignore the rule.

I know eclipse generate comment on getters and setters but to me adding 3 lignes of comments to give 0 extra informations is really useless.

**Code Sample demonstrating the issue:**

```
private Integer year;

/**
* Set year.
* @param year year
*/
public void setYear(final Integer year) {
       this.year = year;
}
```

**Comment by adangel** [comment]
@TehBakker Thanks for suggesting.
I guess, we would probably add a property to honor overridden methods based on "@Override" and another property to configure "getterSetterCommentRequirement".

**Comment by TehBakker** [comment]
Yep, that would be perfect.
