### ISSUE TITLE
[apex] Update parser to support new 'as user' keywords (User Mode for Database Operations)

### ISSUE THREAD

**Issue by Marcono1234** [pmd/pmd#3973]
**Affects PMD Version:** 

Commit 9d23d79802a963e4a4edee8ec7cfcf61cc1f4155 (PMD 6.45.0)

**Description:**

It looks like the Maven dependencies declared by pmd-apex-jorje do not match the actual dependencies of the currently used `apex-jorje-lsp.jar` anymore. In particular `jol-core` seems to not be used anymore, and some other dependencies are pulled in as transitive dependencies and might not have to be declared explicitly.

Do you think it would be possible to adjust the `create-local-repo.sh` script to automatically adjust the pmd-apex-jorje POM with the information from the `META-INF/maven` directory in the `apex-jorje-lsp.jar` file? (with exclusions for the `com.salesforce.apex` artifacts, since they are part of the JAR)

Maybe it would also be good to add a small comment to `create-local-repo.sh` explaining why `com/google/common*` is not removed from the JAR. Currently one has to dig into the Git history to find https://github.com/pmd/pmd/pull/773#issuecomment-349103658 which mentions that `apex-jorje-lsp.jar` is using a modified version of Guava.

**Comment by adangel** [comment]
> Do you think it would be possible to adjust the create-local-repo.sh script to automatically adjust the pmd-apex-jorje POM with the information from the META-INF/maven directory in the apex-jorje-lsp.jar file? (with exclusions for the com.salesforce.apex artifacts, since they are part of the JAR)

No, because it is incomplete. There is also `DEPENDENCIES` and probably more, which is just inside the jar. No idea, how this blob is created, since it is _not_ open source.

We are anyway trying to get rid of jorje in order to use a true open source alternative - see #3766.

I'm updating now and I found out, that there are additional classes in com.google.common which are not available anywhere else (e.g. `com.google.common.collect.MoreMaps`). I'll update the script to only keep the differing files (one manual comparison).

**Comment by Marcono1234** [comment]
> We are anyway trying to get rid of jorje in order to use a true open source alternative - see #3766.

That sounds promising, thanks for the info!

> I'm updating now and I found out, that there are additional classes in com.google.common which are not available anywhere else (e.g. `com.google.common.collect.MoreMaps`). I'll update the script to only keep the differing files (one manual comparison).

Even with the current Jorje setup under certain circumstances you could already run into issues when some Guava classes were loaded from the Jorje JAR but other classes had already been loaded by a parent class loader from a regular Guava JAR you had on your classpath. If the Jorje Guava classes tried to access the regular ones in the same package but from the regular Guava JAR, an `IllegalAccessError` would occur, see https://stackoverflow.com/q/7076414 which is about that problem in general.

I am a bit afraid that your proposed changes of removing some of the Guava classes could make it more likely that such issues occur.

Maybe an alternative would be to change the package name of the Guava classes in Jorje to avoid conflicts with regular Guava versions, for examples with the Jar Jar Links plugin or similar. Though of course changing package names is a bit risky in case there is reflective usage which is not detected by the tool performing the renaming.

**Comment by rsoesemann** [comment]
<img width="835" alt="Screenshot 2023-09-30 at 22 51 56" src="https://github.com/pmd/pmd/assets/8180281/97d20da7-d9a0-4248-8c8d-0e8cdbaa5ade">
Strange I still see the same parsing issue ?

**Comment by adangel** [comment]
It works with PMD 7.0.0-rc4:

```apex
public class UserMode {
  public void coverAllCasesWithTest() {
    Contact c;
    c = [SELECT Name FROM Contact WITH USER_MODE];
    // Should be flagged a critical issue
    Contact c2;
    insert c2;
    // Should be ignored
    insert as user c2;
    // Should be at best a warning because it ignores CRUD but explicitly
    insert as system c2;
    // Should be ignored
    update as user c2;
  }
}
```

![grafik](https://github.com/pmd/pmd/assets/1573684/0a814428-7e00-46e3-9e97-611fb7a99689)

Are you sure you are using rc4? From which software is your screenshot?

**Comment by pablogomez2197** [comment]
Hello we have installed the version [v7.0.0.rc4] and we have the error. When we are working on a apex class some pmd error appears but when we put 'as user' all that errors dissapears without any reason. Here are the pictures:
![image](https://github.com/pmd/pmd/assets/110610165/b902f912-4136-4b72-bca2-51d57155effd)
and with the 'as user':
![image](https://github.com/pmd/pmd/assets/110610165/943936bf-7345-4586-bf1f-8732be97b1c8)
I don't know if is a problem of the version or something else.

Thanks in advance.

**Comment by jsotuyod** [comment]
PMD 7.0.0 final release is out, I recommend you try it out and open a new issue if needed.
