### ISSUE TITLE
[doc] Upgrade PMD version at runtime for Maven PMD Plugin

### ISSUE THREAD

**Issue by Reissner** [pmd/pmd#402]
Instead of releasing a new version of the maven plugin 
one can configure the pmd-version the maven plugin uses (as long as the api fits)

This is done in the following way (example) 

```xml
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <version>3.8</version>
        <dependencies>
            <dependency>
                <groupId>net.sourceforge.pmd</groupId>
                <artifactId>pmd-core</artifactId>
                <version>5.7.0</version>
            </dependency>
            <dependency>
                <groupId>net.sourceforge.pmd</groupId>
                <artifactId>pmd-java</artifactId>
                <version>5.7.0</version>
            </dependency>
          </dependencies>
      </plugin>
```

This is already a feature but not accessible because not yet documented. 
Please add an entry in https://maven.apache.org/plugins/maven-pmd-plugin/ 
with an example overwriting the pmd version.

**Comment by Reissner** [comment]
Sorry, i did not take into account, that this site does not display xml-tags literally. 
The configuration looks like this: 

      &lt;plugin>
        &lt;groupId>org.apache.maven.plugins&lt;/groupId>
        &lt;artifactId>maven-pmd-plugin&lt;/artifactId>
        &lt;version>3.8&lt;/version>
        &lt;dependencies>
            &lt;dependency>
                &lt;groupId>net.sourceforge.pmd&lt;/groupId>
                &lt;artifactId>pmd-core&lt;/artifactId>
                &lt;version>5.7.0&lt;/version>
            &lt;/dependency>
            &lt;dependency>
                &lt;groupId>net.sourceforge.pmd&lt;/groupId>
                &lt;artifactId>pmd-java&lt;/artifactId>
                &lt;version>5.7.0&lt;/version>
            &lt;/dependency>
          &lt;/dependencies>
      &lt;/plugin>

**Comment by adangel** [comment]
Since this is a maven-pmd-plugin issue, I created it there: https://issues.apache.org/jira/browse/MPMD-239

However, it probably makes sense, to extend the documentation on our side, too.

**Comment by boris-github** [comment]
@adangel please correct the [Upgrading PMD at Runtime](https://maven.apache.org/plugins/maven-pmd-plugin/examples/upgrading-PMD-at-runtime.html) page:
```
<pmdVersion>...choose your version...</version>
->
<pmdVersion>...choose your version...</pmdVersion>
```

Otherwise you get a **Non-parseable POM** error.

**Comment by adangel** [comment]
Thanks for reporting. In PMD itself, it was already fixed -> https://pmd.github.io/latest/pmd_userdocs_tools_maven.html#upgrading-the-pmd-version-at-runtime

I've fixed it in maven-pmd-plugin as well for the next version (https://github.com/apache/maven-pmd-plugin/commit/5c5f40d8597ff728546a51fdfcbd2b7170aacfe4).
