### ISSUE TITLE
PMD-4.3.x God Class Detection Report and Feedback Questionnaire

### ISSUE THREAD

**Issue by khalidkh** [pmd/pmd#404]
Dear Respondent,

This questionnaire is part of my PhD thesis in the area of improving design smell detection. The purpose of the study is to measure the concordance level of human experts against the design smell detection tools. 
We analyzed the PMD-4.3.x project and detected the set of God Class (Large Class or The Blob) that you can find in this questionnaire. Completing this questionnaire should take about 15 minutes.

I would appreciate your kind attention and cooperation on sending your questionnaire feedback as soon as possible. Notice that all information related to respondent or contained in this questionnaire will be treated in strict confidence.

If you are not currently involved in the project, please forward this message to developers you think are a better target for this questionnaire

To fill the questionnaire click on:

https://docs.google.com/forms/d/e/1FAIpQLSeZ9nsZtmDLAfe1txCX4UKyyJyjrtItUOBAV7pQoz441MlNQg/viewform?c=0&w=1

Thank you in advance.
Yours sincerely,
Khalid Alkharabsheh
PhD Student at CITIUS, Santiago de Compostela University (Spain).
https://citius.usc.es/equipo/investigadores-en-formacion/khalid-alkharabsheh

**Comment by jsotuyod** [comment]
@khalidkh this is no the appropriate place for this. Most PMD developers are publicly reachable (see https://github.com/orgs/pmd/people and emails on git authors), myself included. Feel free to contact us by those means and we will happily assist you.

Also of interest, the version of PMD you are asking about is **really** old (4.3 came out on November 2011), so old that most of the questions in the questionnaire are meaningless. The current stable PMD version is 5.7.0, and 5.8.0 is under development.
