### ISSUE TITLE
[cli] Split off CLI implementation into a pmd-cli submodule

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#4079]
**Is your feature request related to a problem? Please describe.**
Currently the PMD and CPD CLI are implemented in pmd-core. This adds dependencies to pmd-core, which could essentially be a library on which PMD clients could rely (the CLI being only one such client).

**Describe the solution you'd like**
Restrict pmd-core to provide only a programmatic API. Move CLI-related classes and dependencies to a new pmd-cli module. #4059 implements this ticket.

**Describe alternatives you've considered**

**Additional context** @jsotuyod found out that this makes implementing #2234 easier.

**Comment by adangel** [comment]
Note, that this is also beneficial for logging infra: pmd-core can then just be a library, that uses slf4j-api only and the user of pmd-core can then decide, which logging implementation should be used. pmd-cli would then be the "official" user of pmd-core and provide slf4j-simple as a logging implementation.
