### ISSUE TITLE
[java] DFA not analyzing asserts

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#408]
I came across this StackOverflow post, I haven't checked if the issue remains, but since I was unable to find any related issue on our trackers it's highly probable that it's still an issue.

https://stackoverflow.com/questions/1150633/pmd-rule-dataflowanomalyanalysis-oddness

**Comment by oowekyala** [comment]
[DFA doesn't consider assert statements](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/dfa/StatementAndBraceFinder.java#L117)

I'll try to fix that
