### ISSUE TITLE
[java] RFC: Merge java-unnecessarycode/UnnecessaryFinalModifier and java-unnecessarycode/UnnecessaryModifier

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#411]
Both rules look for modifiers redundant for being given by the context, having one for finals and one for everything else seems pointless... The equivalent rule in Checkstyle, [RedundantModifier](http://checkstyle.sourceforge.net/config_modifier.html#RedundantModifier) does everything these 2 rules do.

At most we could add properties to indicate which modifiers to look for to allow users to fine tune their rulesets.

Comments?

**Comment by adangel** [comment]
Sounds good. However, I wouldn't remove one of the rules in the current 5.x.x development. I'd consider this for 6.0.0.
We could however already prepare this task, by adding the properties to UnnecessaryModifier (I assume, we'll take this rule as the merge-result) but have the default values set in a way, that - when both rules are active - we don't report duplicates.

**Comment by jsotuyod** [comment]
I was thinking of not removing the old rule in 6.0.0, but mark it as deprecated, and remove it in 7.0.0 to give users a proper migration time. Just as we did for `UseSingleton` (#379), which has been deprecated for quite some time before removal in 6.0.0.

And yes, I think sticking with `UnnecessaryModifier` is the best, and we can build all features there in minor versions with no problem. We may start with all flags to true except the one for finals, set that one to true by default on 6.0.0 (as the other one gets deprecated).

As for duplicates, it would probably have to be done in a hacky way as we currently avoid duplicates in `RuleSetFactory`.... not really sure how we can do that cleanly...
