### ISSUE TITLE
[java] EmptyCatchBlock don't fail when exception is named ignore / expected

### ISSUE THREAD

**Issue by vanniktech** [pmd/pmd#413]
**Rule Set:**
```xml
<rule ref="rulesets/java/empty.xml"/>
```

**Description:**

**Code Sample demonstrating the issue:**

```java
@RunWith(RobolectricTestRunner.class) public class MyTestClass {
  @Rule public final MockitoRule mockitoRule = MockitoJUnit.rule().strictness(STRICT_STUBS);

  @Mock private WebView webView;

  private HomeActivity activity;

  @Test public void onSaveInstanceState() {
    final Bundle bundle = new Bundle();

    try {
      activity.onSaveInstanceState(bundle);
      fail();
    } catch (NullPointerException ignore) {
      // This is expected when testing with Robolectric.
    }

    verify(webView).saveState(bundle);
  }
}
```

I'd expect this to not get flagged by PMD if the exception name is `ignore` or `expected`. Instead it'll be:

```xml
<violation beginline="30" endline="32" begincolumn="7" endcolumn="5" rule="EmptyCatchBlock" ruleset="Empty Code" package="com.coyoapp.mobile.main.feature.home" class="MyTestClass" method="onSaveInstanceState" externalInfoUrl="https://pmd.github.io/pmd-5.6.1/pmd-java/rules/java/empty.html#EmptyCatchBlock" priority="3">
Avoid empty catch blocks
</violation>
```

Especially if the catch branch has a comment.

**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment]
@vanniktech thanks for the report.

Adding a property with a whitelist of ignored names seems reasonable. It could be an enhancement for this rule.

As for commented blocks, there is already support for it. There is a property `allowCommentedBlocks` (defaults to false) to allow empty blocks if they contain any comment. More info is available [on the documentation site](https://pmd.github.io/pmd-5.7.0/pmd-java/rules/java/empty.html#EmptyCatchBlock)
