### ISSUE TITLE
[java] Java 8 parsing problem with annotations for wildcards

### ISSUE THREAD

**Issue by Snap252** [pmd/pmd#414]
pmd-java:
- Annotations are also allowed for generic wildcards (like NonNull-annotations in Lists)

run test case:
`net.sourceforge.pmd.lang.java.ast.ParserCornersTest.testParsersCases18()`
with
class ParserCornerCases18 modified:
`public List<@AnnotatedUsage ?> testWildCardWithAnnotation() {
    	return null;
    }`
result: parsing error
fix for java.jjt:

	void TypeArgument():
	{}
	{
	   (Annotation() {checkForBadTypeAnnotations();})* (ReferenceType() | "?" [ WildcardBounds() ])
	}

**Comment by jsotuyod** [comment]
@Snap252 thanks for the report! Given that you already have a proposed fix and a valid unit test, would you mind submitting a PR? That way you can get proper credit for the fix.

**Comment by Snap252** [comment]
Working in bigger git projects is new to me - so I will try my best tomorrow ;)

**Comment by jsotuyod** [comment]
@Snap252 let me know if you need help!
