### ISSUE TITLE
[java] UnnecessaryFinalModifier final in private method

### ISSUE THREAD

**Issue by Snap252** [pmd/pmd#421]
As private methods cannot be overridden in subclasses a private method is always final I think and discussed here:
[https://stackoverflow.com/questions/23161362/why-can-private-method-be-final](https://stackoverflow.com/questions/23161362/why-can-private-method-be-final)

if so -  possible test code for `/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unnecessary/xml/UnnecessaryFinalModifier.xml`:

    <test-code>
        <description>Unnecessary final of private method</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
	public class TestClass {
		private final int getValue() {
			return 0;
		}
	}
        ]]></code>
    </test-code>

**Comment by jsotuyod** [comment]
@Snap252 nice idea! Really good complement to cases already suggested in #412
