### ISSUE TITLE
[core] Error when running PMD from folder with space

### ISSUE THREAD

**Issue by OlafHaalstra** [pmd/pmd#429]
**Rule Set:**
NONE

**Description:**
When running the PMD command from a root folder with a space in the folder title, eg: "C:\PMD folder"
PMD throws an error:

**Code Sample demonstrating the issue:**

```
C:\PMD Folder>pmd
```
```
Error: Could not find or load main class folder\pmd-bin-5.7.0\bin\..\lib\*
```
Where class: "folder", stands for the last word from the "PMD folder"

**Running PMD through:** *[CLI ]*

**Comment by adangel** [comment]
Maybe we just miss quotes here: https://github.com/pmd/pmd/blob/master/pmd-dist/src/main/scripts/pmd.bat#L6

    java -classpath "%TOPDIR%\lib\*" %OPTS% %MAIN_CLASS% %*

**Comment by adangel** [comment]
It turns out, the script `run.sh` has the same problem:

    pmd-bin-5.7.0 with space$ bin/run.sh pmd
    Error: Could not find or load main class net.sourceforge.pmd.PMD
