### ISSUE TITLE
[java] [7.0-rc1] UnnecessaryImport - Unused static import is being used

### ISSUE THREAD

**Issue by ben-manes** [pmd/pmd#4432]
**Affects PMD Version:** 
7.0-rc1 upgrading from 6.55

**Rule:**
[Unused static import](https://pmd.github.io/pmd-7.0.0-rc1/pmd_rules_java_codestyle.html#unnecessaryimport)

**Description:**
This static method is [imported](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncLoadingCache.java#L19) and being [used](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncLoadingCache.java#L149). It comes from the parent interface on the outer class, but is being used by a static nested class so it must be imported.

**Expected outcome:**
PMD 7.0-rc1 reports a violation, but that's wrong and not reported by 6.55.

\# | File | Line | Problem
-- | -- | -- | --
1 | LocalAsyncLoadingCache.java | 19 | Unused static import 'com.github.benmanes.caffeine.cache.LocalAsyncCache.composeResult'

**Running PMD through:** *Gradle*
This requires workaround in https://github.com/gradle/gradle/issues/24502

**Comment by ben-manes** [comment]
I tried to suppress at the class and method levels, but that was not honored. The only way to resolve this rule is as a `ruleSet.xml` exclusion, which is broader than desired.

**Comment by oowekyala** [comment]
Thanks for the report. Have you tried using a `// NOPMD` comment on the line of the violation to suppress it?

**Comment by ben-manes** [comment]
Thanks for the tip. I had tried an `@SuppressedWarnings("PMD.UnnecessaryImport")`. Trying the `// NOPMD` on the import statement did not work, unfortunately.

**Comment by ben-manes** [comment]
Oh sorry, I did the line above the import. Commenting after the import statement works.
