### ISSUE TITLE
[java] [7.0-rc1] ReplaceHashtableWithMap on java.util.Properties

### ISSUE THREAD

**Issue by ben-manes** [pmd/pmd#4433]
**Affects PMD Version:** 
7.0-rc1 upgrading from 6.55

**Rule:**
[ReplaceHashtableWithMap](https://pmd.sourceforge.io/pmd-7.0.0-rc1/pmd_rules_java_bestpractices.html#replacehashtablewithmap)

**Description:**
The rule suggests replacing when (a) the subtype cannot be replaced due to the api contract and (b) Properties now delegates to a ConcurrentHashMap. This rule should not apply to subtypes where the api is out of the author's control.

**Code Sample demonstrating the issue:**
JCache returns Properties in its api, so this [code](https://github.com/ben-manes/caffeine/blob/d6ca5189849355e88d3af123f3a7af143292ae07/jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheManagerImpl.java) is flagged.

**Expected outcome:**
PMD reports a violation, but the user cannot make the suggested refactoring.

\# | File | Line | Problem
-- | -- | -- | --
1 | jcache/CacheManagerImpl.java | 48 | Consider replacing this Hashtable with the newer java.util.Map

**Running PMD through:** *Gradle*
This requires workaround in https://github.com/gradle/gradle/issues/24502

**Comment by road723** [comment]
JavaMail has a similar dependency on java.util.Properties so at least having this as a configurable property would be excellent
