### ISSUE TITLE
[doc] Documentation links in VS Code are outdated

### ISSUE THREAD

**Issue by davidcatindoy** [pmd/pmd#4438]
In VS Code there's a PMD warning: "The method constructOffers() has an NCSS line count of 67 (rule: Design-NcssMethodCount)apex pmd [NcssMethodCount](https://pmd.github.io/latest/pmd_rules_apex_design.html#ncssmethodcount)"

When the link is clicked, it redirected me to a broken URL. Please update PMD documentation in VS code.

**Comment by adangel** [comment]
Thanks for reporting!
That's a change happened with the latest 7.0.0-rc1 release. The docs are now hosted at https://docs.pmd-code.org/latest/ - so the new URL for NcssMethodCount is https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#ncssmethodcount

I'll try to setup a redirect.
