### ISSUE TITLE
[java] RFC: the three *CyclomaticComplexityRules should be merged together

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#445]
**Rule Set:** java/codesize

**Description:** The codesize ruleset currently has three different rules to calculate variants of the [Cyclomatic Complexity](https://www.wikiwand.com/en/Cyclomatic_complexity) (Cyclo) of a class/ method:
* `StdCyclomaticComplexityRule`: The *de facto* standard Cyclo metric in PMD. Every control flow statement counts as +1. Switch cases count as one, but not the switch itself ---the point is that a switch should have the same Cyclo value as the equivalent series of `if` statements. 
* `CyclomaticComplexityRule`: Adds the number of paths boolean expressions can take (equivalent to the number of `&&` and `||` operators in the expression) to the value of the previous metric
* `ModifiedCyclomaticComplexityRule`: First version but also counts switch statements as 1

I've refactored those rules to use the new Metrics Framework (coming soon!), however I don't see the point of keeping them separated, for the following reasons:
* Cyclomatic complexity has a standard, which seems to be the version of the second rule:
  * [McCabe's original 1976 paper](https://docs.google.com/viewer?url=http%3A%2F%2Fwww.literateprogramming.com%2Fmccabe.pdf) states that we should count paths in boolean expressions (see page 315 second paragraph on the left). The second document also precises that this is only true in languages with "short-circuit" boolean expression semantics (lazy evaluation).
  * This [second document](http://www.mccabe.com/pdf/mccabe-nist235r.pdf) shows on page 24 and 26 (34 - 36 in the pdf) that the complexity of a `switch` is the number of labeled case statements (that is, without counting the switch itself nor the default case) for languages which have a default switch case (like Java and C).

* We currently label the first version as standard, and give the three variants the same importance by giving each one its own rule
* The names of the three rules couldn't be less descriptive, which probably adds to the confusion

I've been working on the ability for metrics to accept options to easily amend part of their behaviour. I believe Cyclo should only be one metric, of which variants can be selected via an option. 

I think we could make one rule to rule them all from the three existing ones, and enforce the "standard" calculation of the metric as default behaviour (nice but not essential). The variant could be selected via a rule property. Merging the three rules would only be suitable for a major version but hopefully we can at least refactor them to use metrics once the ruleset schema is updated :) Comments?

**Comment by oowekyala** [comment]
After some more thinking I don't think it makes sense at all to keep a version of Cyclo that counts switch statements. Maybe something more interesting would be to discount fall-through cases in switches ---which would only be consistent with the variant where we do not count paths in expressions, as 
```java
switch (x) {
  case 1:
  case 2: foo(); break;
  default: break;
}
```
really translates to
```java
if (x == 1 || x == 2) {
  foo();
}
```

**Comment by ryan-gustafson** [comment]
I like the idea of simplification and having defaults which work well.  A single rule with well understood configuration properties is better than 3 with abstruse differences.

With regards to `switch`, need to be careful on what you mean by fall-through, I'd think this is different w.r.t number of paths:
```java
switch (x) {
   case 1: bar()
   case 2: foo(); break;
   default: break;
}
```

`StdCyclomaticComplexityRule` and `ModifiedCyclomaticComplexityRule` score your example as 2 and 2, and mine as 3 and 2, respectively.  It's not clear to me where the scoring for `ModifiedCyclomaticComplexityRule` is a "better" strategy, and why `switch` is singled out for the "gross over simplification" treatment.

Merging the rule behaviors and but keeping them available would require significant changes in their implementation such that anyone currently subclassing is likely to run into issues.  So, start deprecating now, make the actual changes later?  If metrics is part of a major version, this could be done during that effort.

**Comment by oowekyala** [comment]
@ryan-gustafson You're right, I hadn't noticed that `StdCyclomaticComplexity` already discounts labels with empty blocks (which was what I meant by fall-through). In your example `case 1` is also falling through to `case 2` but the resulting control flow graph has one more node and one more edge so Cyclo is the same (3), if we comply with McCabe's standard rules.

I agree I can't see a use case for `ModifiedCyclomaticComplexity` as, whatever the number of cases, it counts switches as contributing 1 which is irrealistic, and prevents the detection of big switches...

To sum up on what I think should be refactored:
* `StdCyclomaticComplexityRule` features a version of Cyclo consistent with not counting boolean operators, so we could keep it and refactor it into a variant of the Cyclo metric. 
* `CyclomaticComplexityRule` is inconsistent in that it does not count *empty* fall through blocks ---which are equivalent to using an `OR` between the equivalent `if` conditions, so they should be counted. This modified version would become the standard version of the Cyclo metric. 
* `ModifiedCyclomaticComplexityRule` should probably be removed

Regarding how to make these changes, it would probably make sense to create a temporary collection of refactored rules, like what was done with type resolution. We could then merge them back into the standard rulesets to replace the former implementations in a major version. @adangel ?

Some other rules should be refactored too, like `NcssMethodCountRule`, `NcssConstructorCountRule`, and `NcssTypeCountRule`, which could be merged together. `NPathComplexityRule` could also be made to use metrics, though atm I can't put my hands on a paper describing its calculation

**Comment by oowekyala** [comment]
After some research I found that Cyclomatic complexity does not have a standard version for calculation on a class. Seems like the most common way to calculate that is to calculate WMC (weighted method count), which is the sum of the complexity of all members of the class. Note that WMC is currently implemented as a standalone metric in the metrics framework. 

Currently, to calculate cyclomatic complexity on a class, we average the complexity of the methods of the class. I think it makes little sense, as that can be easily reproduced by ResultOptions (the implementation actually uses a ResultOption). 

Moreover, currently the cyclomatic complexity rule makes classes and methods share the same report level. That means that with our average strategy, a class is reported only if a sufficient proportion of methods are above the report level. The thing is those methods that cross the level will be reported independently: reporting classes that cross the average threshold adds no information to the report.

We have several options here to correct this behaviour:
* Remove the class version of CyclomaticComplexity. In that scenario we could change `CyclomaticComplexityRule` in the following ways:
  * Don't report classes at all
  * Report classes based on their WMC value. We'd then have a separate threshold for classes
* Make our own version of a class metric for CyclomaticComplexity. That calculation should not be the same as WMC to prevent redundancy. 
  * Based on [this SO question], we could for example calculate it as
    *  `<sum of complexity for all methods> - <number of methods> + 1`. That could be interpreted as the "deviation" of the class from a base level where all the methods have unit complexity. 
    * The proportion of the methods of a class that have a complexity above a certain level (first answer to the question). The denominator of the ratio could vary non-linearly with respect to the number of methods, like what's shown in the answer, to account for classes that have higher number of methods and stabilise the complexity for evolving projects.
  * We could implement both and use MetricVersions by the way. 
  * The rule would then have a separate report level for classes too.

I personally think it would be interesting to have our own version of the calculation, for example the second, provided it doesn't report too many classes... But it would be fine too to stay classic and remove the class version of Cyclo
