### ISSUE TITLE
PMD 7.0 rc2 upgrade issue: ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask

### ISSUE THREAD

**Issue by jbennett2091** [pmd/pmd#4554]
**Affects PMD Version:** 

I am attempting to upgrade my application from PMD 6.55.0 to PMD 7.0-rc2.  I had similar failures attempting upgrade to PMD 7.0-rc1, but did not report them.

**Description:**

My application uses gradle, and makes use of SpringBoot 2.7.11 plugin, the gradle PMD plugin, and builds with Java 17.0.7.  During the build process, PMD is invoked.  I see this in the build log:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':pmdMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.PmdAction
   > java.lang.ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':pmdTest'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.PmdAction
   > java.lang.ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Exception Stacktrace:**

No visible stacktrace

**Code Sample demonstrating the issue:**

N/A

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

gradle info --build

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle 8.1.1, Java 17.0.7, PMD 7.0-rc2

**Comment by jsotuyod** [comment]
PMD7 split away the CLI and Ant into separate modules (`pmd-cli` and `pmd-ant` respectively) to ensure a lighter bundle by avoiding transitive dependencies.

Gradle is yet to adapt to this change. In the meantime, you can use this workaround https://github.com/gradle/gradle/issues/24502
