### ISSUE TITLE
Add pass-through renderer to support API

### ISSUE THREAD

**Issue by espertus** [pmd/pmd#4574]
**Is your feature request related to a problem? Please describe.**
I am building an autograder and want to be able to access the `Report` directly, not the XML/JSON/etc. produced by a `Renderer`.

**Describe the solution you'd like**
I created a minimal renderer that just saves the `Report` into an instance variable that can be accessed after analysis is complete.

This solved the problem completely for me. I'd be happy to make a PR if you think this would be useful to others.

**Describe alternatives you've considered**
This sure beats trying to undo the work of existing renderers.

**Additional context**
Here's how easy it is to use:
```
        MinimalRenderer renderer = new MinimalRenderer();
        try (PmdAnalysis pmd = PmdAnalysis.create(configuration)) {
            pmd.files().addFile(path);
            pmd.addRenderer(renderer);
            pmd.performAnalysis();
        }
        return produceResults(renderer.getReport()); // access the report directly
```

**Comment by oowekyala** [comment]
Hi and thanks for the suggestion! You can actually just write 
```java
        Report report;
        try (PmdAnalysis pmd = PmdAnalysis.create(new PMDConfiguration())) {
            report = pmd.performAnalysisAndCollectReport();
        }
```

In PMD 7, you can additionally use the [listener API](https://docs.pmd-code.org/apidocs/pmd-core/7.0.0-SNAPSHOT/net/sourceforge/pmd/PmdAnalysis.html#addListener(net.sourceforge.pmd.reporting.GlobalAnalysisListener)). The above is actually just shorthand for
```java
        Report.GlobalReportBuilderListener reportBuilder = new Report.GlobalReportBuilderListener();
        try (PmdAnalysis pmd = PmdAnalysis.create(new PMDConfiguration())) {
            pmd.addListener(reportBuilder);
            pmd.performAnalysis();
        }
        Report report = reportBuilder.getResult();
```
You may want to use listeners directly if you are concerned about the memory usage of the global Report. In that case, and if you can handle violations in small batches (file by file) or individually, you can implement the GlobalAnalysisListener interface directly.
