### ISSUE TITLE
[dist] Download link broken

### ISSUE THREAD

**Issue by eant60** [pmd/pmd#4582]
Download link for latest release pmd-bin-7.0.0-rc3 returns "Not found"

https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc3/pmd-bin-7.0.0-rc3.zip

**Comment by adangel** [comment]
@eant60 Thanks for reporting. Yes, I missed that one on pmd.github.io. I'll fix it.

**Comment by wroth** [comment]
This still appears broken, albeit in a different way.

The README.md says:
_Download the latest binary zip from the [releases](https://github.com/pmd/pmd/releases/latest) and extract it somewhere._

Except that link redirects to https://github.com/pmd/pmd/releases/tag/pmd_releases/7.0.0-rc4, which **has no link** to download the latest binary zip.

I had to get it from https://sourceforge.net/projects/pmd/

**Comment by jsotuyod** [comment]
@wroth the link is correct. At the very bottom of that page, there is an *Assets* section where download links are listed.

You can check it here: https://github.com/pmd/pmd/releases/tag/pmd_releases/7.0.0-rc4#:~:text=22%20other%20contributors-,Assets,-7

<img width="1192" alt="image" src="https://github.com/pmd/pmd/assets/802626/1864778c-2756-446c-94dd-e444efb9f216">

**Comment by dpilafian** [comment]
For anyone who automates the download, here's what you need to know:
```
https://github.com/pmd/pmd/releases/download/pmd_releases%2F[VERSION]/pmd-bin-[VERSION].zip       //OLD
https://github.com/pmd/pmd/releases/download/pmd_releases%2F[VERSION]/pmd-dist-[VERSION]-bin.zip  //NEW
```

Also, the name of the script in the zip file changed:
```
$ ./pmd-bin-[VERSION]/bin/run.sh pmd ...  //OLD
$ ./pmd-bin-[VERSION]/bin/pmd check ...   //NEW
```
