### ISSUE TITLE
[java] Vulnerability SNYK-JAVA-COMBEUST-174815 in jcommander < 1.75

### ISSUE THREAD

**Issue by thomas-grininger** [pmd/pmd#4593]
[Snyk](https://security.snyk.io/vuln/SNYK-JAVA-COMBEUST-174815) reports a vulnerability in com.beust.jcommander in versions < 1.75 already since June 2019.
The vulnerability itself could be argued to not be that severe, nevertheless this potentially clutters the vulnerability tooling of many engineers that are using PMD to scan their Java code.

PMD-java is currently including com.beust.jcommander in [version 1.48](https://github.com/pmd/pmd/blob/e8dbb54cb5ed682d9dfd4f54895f4bbd73be728e/pmd-dist/pom.xml#LL175C36-L175C36)

Are there plans to bump this version or to get rid of this dependency?

**Comment by oowekyala** [comment]
Hi, this dependency has been removed by #4523. PMD 7 uses Picocli instead of jcommander. This change has been released in pmd 7.0.0-rc3.

**Comment by adangel** [comment]
I actually had to add this dependency back (to pmd-dist only) to get the pmd-designer running. Once https://github.com/pmd/pmd-designer/issues/61 is fixed and released, we can remove the dependency again.

**Comment by jsotuyod** [comment]
Marking it as finally done with rc4 through #4695
