### ISSUE TITLE
[core] Please externalize the pmd version in all rulesets part from externalInfoUrl to clean the git log

### ISSUE THREAD

**Issue by tkleiber** [pmd/pmd#462]
**Rule Set:**
all 

**Description:**
With every release we have to manually unzip and merge the changes of all rule sets with our customizing, as there coming new and corrected rules with the rules too.
With every release the externalInfoUrl changes, which means more differences to check.
If you could modularize the first part auf the Url to one central part this would saves up lot of time.

As alternative: Maybe there is away to use by default all the standard rule sets and overwrite only the configuration of specific **rules** I have overseen?

**Code Sample demonstrating the issue:**
          externalInfoUrl="https://pmd.github.io/pmd-5.7.0/pmd-java/rules/java/basic.html#JumbledIncrementer"

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@tkleiber I'm a bit confused about your use case.

The intended way for users to use / customize rules is by [writing their own ruleset](https://pmd.github.io/pmd-5.7.0/customizing/howtomakearuleset.html).

Such rulesets can reference either complete standard rulesets (ie: `<rule ref="rulesets/java/strings.xml"/>`), or specific rules (ie: `<rule ref="rulesets/java/unusedcode.xml/UnusedLocalVariable"/>`), and you can override properties for rules too.

So you could easily bring in all the standard rulesets you are interested in, configure all properties you may want, and just run PMD against that ruleset. PMD can be used as-is out of the box (this is actually the only way when using it from Ant / Maven / Gradle / IDE short of repackaging the jar).

Let me know if you need any extra help.

**Comment by tkleiber** [comment]
This was the reference I need - have converted now to the intended way. I think I had some restrictions in longer past, which prevents me from using this from the start on.
