### ISSUE TITLE
[java] LawOfDemeter - unable to set trustRatio

### ISSUE THREAD

**Issue by dbavery** [pmd/pmd#4656]
**Affects PMD Version:** 

v6.48.0 via megalinter 
https://plugins.jetbrains.com/plugin/1137-pmd

**Description:**

Current Behavior
In our attempts to set the trust radios for the law of demeter we get a parse failure on our file:

> SEVERE: Cannot load ruleset custom_java-pmd-ruleset.xml: Cannot set non-existent property 'trustRadius' on Rule LawOfDemeter

We expect to be able to customize the trustRadios based on:

documentation: https://pmd.github.io/pmd/pmd_rules_java_design.html#lawofdemeter
code: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java#L81
test cases: https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LawOfDemeter.xml#L439

I suspect we just missed the property definition in design.xml: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/category/java/design.xml#L938 but I am not really sure.

**Code Sample demonstrating the issue:**

The contents of the custom rule set is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Default ruleset used by the CodeClimate Engine for Salesforce.com Java" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>Default RuleSet for MegaLinter</description>

    <!-- IGNORE FILES -->
    <exclude-pattern>.*/java-domainbuilder/*.*</exclude-pattern>
    <exclude-pattern>.*/app-setup/*.*</exclude-pattern>
    <exclude-pattern>.*/fflib_*.*</exclude-pattern>
    <exclude-pattern>.*/json2java/*.*</exclude-pattern>

    <!-- https://docs.pmd-code.org/pmd-doc-7.0.0-rc3/pmd_rules_java_design.html#signaturedeclarethrowsexception -->

    <!-- STANDARD RULES -->
    <rule ref="category/java/design.xml">
        <!-- exclude so we can override trustRadius -->
        <exclude name="LawOfDemeter" />
    </rule>

    <rule ref="category/java/design.xml/LawOfDemeter">
        <properties>
            <property name="trustRadius" value="3" /><!-- THIS FAILS! Comment out and it loads -->
        </properties>
    </rule>

</ruleset>
```

**Steps to reproduce:**

Try to run the above ruleset - for us we get parse errors when running via megalinter in gitlab, or via intellij PMD plugin on MAC OS X.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Error seen using maven via git lab on java 8, and via PMD plugin on intellij (macos X).

**Comment by jsotuyod** [comment]
This property is only available in PMD 7.

In PMD 6 (an particularly 6.48.0) it was not available, as seen on the docs for that version https://docs.pmd-code.org/pmd-doc-6.48.0/pmd_rules_java_design.html#lawofdemeter
