### ISSUE TITLE
Identifying Custom vs Standard PMD Rule

### ISSUE THREAD

**Issue by BrundaSreedhar** [pmd/pmd#4663]
### Discussed in https://github.com/pmd/pmd/discussions/4662

<div type='discussions-op-text'>

<sup>Originally posted by **BrundaSreedhar** September  4, 2023</sup>
How do you identify if a PMD rule is a custom rule or a standard rule and get the category for the same?</div>

**Comment by adangel** [comment]
Please don't open issues for questions, you already opened as discussion, thanks.
