### ISSUE TITLE
[vf] Issue with rule VfUnescapeEl

### ISSUE THREAD

**Issue by SuvarnaYande** [pmd/pmd#4666]
The issue with VfUnescapeEl rule

**Affects PMD Version:** 

Make sure, to test with the latest PMD version.

**Description:**

I found that the issue is coming for the commented out line in the VF page script. 
Below is the sample code for your reference. The commented out line 
        //const var = '{!$CurrentPageReference.Parameters.Id}';
is raising the violation of VfUnescapeEl. 

**Code Sample demonstrating the issue:**

<apex:page controller="CAReportAvgFine" >
    
 <apex:sectionheader title="Compliance Advisory Report" subtitle="Saved Penalty"/>
 
 <apex:outputText id="fine"> 76534</apex:outputText>
  <script>
        //const var = '{!$CurrentPageReference.Parameters.Id}';
        document.getElementByID("{!$Component.fine}").innerHTML= "8965478" ;
  </script>

<style></style>
</apex:page>

**Comment by SuvarnaYande** [comment]
Any updates on this?

**Comment by jsotuyod** [comment]
Upon revision, we conclude this is not an issue at all. The visualforce template is rendered irrespective of the JS comment, and it may produce a line break, even producing code that escapes the comment.

This code, as is show, is therefore susceptible to XSS if the value of `CurrentPageReference.Parameters.Id` is properly crafted. This is effectively not a bug nor a false positive.
