### ISSUE TITLE
[apex] Warning messages about ANTLR version mismatch

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4678]
**Affects PMD Version:** 7.0.0

**Description:**

This problem seems to be back with apexlink 2.3.7 and apex-parser 3.6.0...

Root cause is unclear:
* PMD uses Antlr 4.9.3: https://github.com/pmd/pmd/blob/7fc083f3480cc48a378462d99330b75568c117bb/pom.xml#L105
* ApexLink doesn't use antlr directly?
* ApexLink and PMD use apex-parser, which uses Antlr 4.9.1 (https://github.com/apex-dev-tools/apex-parser/blob/19ccabe5e07050e0a44284f9255509dfd996b3fe/jvm/pom.xml#L193-L195)

**Comment by FedeAbella** [comment]
Strangely enough, this seems to still happen on latest 7.0.0 stable, *but only when setting the env variable `PMD_APEX_ROOT_DIRECTORY` only for that command*? :confused: 

![image](https://github.com/pmd/pmd/assets/65520926/b5c33682-78b7-470f-bd15-ac2be343a6e6)
Notice how when the env variable is set for the entire shell (1), the command runs with no stderr output (2), but when the env variable is set for that command only (3), we get the Antlr version mismatch errors on stderr (4).

This is an issue for some tools (such as `null-ls` on `nvim`) that rely on dynamically setting the env variable. Plus, it's a huge hassle to have to set it globally if you're working on multiple projects.

**Comment by adangel** [comment]
Thanks for the info. I didn't remember that I created this task at all. Much has happened since then:
- in the 7.0.0-rc* versions, we used jorje
- in 7.0.0 we use now apex-parser
- we had some code in, to suppress this message, but I removed it, because I thought, we now use versions that use antlr 4.9...

When PMD_APEX_ROOT_DIRECTORY is set, then apex-link is used for the rule [UnusedMethod](https://docs.pmd-code.org/latest/pmd_rules_apex_design.html#unusedmethod). It seems, the ApexLink uses some generated code that has been generated with antlr 4.8. While apex-link uses apex-parser 3.0.0, we override this dependency to use apex-parser 3.6.0, which uses antlr 4.9. So I thought, we don't suppress this message.
Anyway, suppressing means ignoring, and antlr is warning us, that something might not work, so better we solve it...

**Comment by FedeAbella** [comment]
You're welcome! Let me know if there's any other information I can get for you

**Comment by adangel** [comment]
@FedeAbella I can't reproduce this - neither with 7.0.0 nor with 7.1.0.

Please delete the directory `~/.local/bin/pmd-bin-7.0.0` and download a fresh copy and try again. Maybe you had some additional (old?) files in that directory.

Closing this as fixed for 7.0.0 now.
