### ISSUE TITLE
APEX NodeStream drop() does not work if you later iterate using getChild()

### ISSUE THREAD

**Issue by rcorfieldffdc** [pmd/pmd#4683]
**Affects PMD Version:** 

7.0.0 in development

**Description:**

It is possible to look at some of the children of a Node (in this case an `ASTMethodCallExpression`) using the `children()` method
and the `drop()` and `take()` methods. For example to get the first argument I am trying

```java
node.children().drop(1).take(1)
```

I have followed a suggestion in a base class to iterate using indices rather than forEach() for performance. For example:

```java
                    // this explicit loop is faster than iterating on a children node stream.
                    // copied from visitChildren implementation.
                    for (int i = 0, numChildren = relevantInputs.count(); i < numChildren; i++) {
                        ApexNode<?> child = node.getChild(i);
                        Boolean childResult = child.acceptVisitor(ExpressionSafetyCheckVisitor.this, currentScope);
                        log("areSafe() processing " + child.getImage() + " -> " + childResult);
                        if(childResult != null) isSafe &= childResult;
                    }
```

The debugging in this code reports the first child (the variable on which the method is called) rather than the second (its first argument).

**Code Sample demonstrating the issue:**

This code is part of the MethodBehaviour class at https://github.com/rcorfieldffdc/pmd/blob/8d23310b828fa30a84e8ed8dc719415197494022/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/soqlInjection/MethodBehaviour.java#L46
Its purpose is to identify whether the first parameter to a Database.query() call is safe from SOQL Injection.
It calls back to report a rule violation in this case.
Its return is false because a query result contains untrusted data when used in another query.
```java
        public boolean visit(ASTMethodCallExpression node, VariableScope scope, Callback callback) {
            // The first parameter is the query string.
            // The first child of the node is the Database class itself. Subsequent children are the parameters.
            boolean isInjection = !callback.areSafe(node.children().drop(1).take(1));
            if(isInjection) callback.registerViolation(node);
            
            // The results of a query are always unsafe
            return false;
        }   
```

The method it calls has been modified to allow debugging by printing (I can't debug in Eclipse at the moment as my setup is wrong). So there are two iterations here now.. The uninstrumented method is https://github.com/rcorfieldffdc/pmd/blob/8d23310b828fa30a84e8ed8dc719415197494022/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/security/soqlInjection/ExpressionSafetyCheckVisitor.java#L136

```java
                @Override
                public boolean areSafe(NodeStream<ApexNode<?>> relevantInputs) {
                    boolean isSafe = true;
                    List<ApexNode<?>> nodes = new ArrayList<ApexNode<?>>();
                    relevantInputs.forEach( (ApexNode<?> node) -> {
                        log("areSafe() collector adding " + node.getClass().getCanonicalName() + " " + node.getImage());
                        nodes.add(node);
                    });
                    
                    // this explicit loop is faster than iterating on a children node stream.
                    // copied from visitChildren implementation.
                    for (int i = 0, numChildren = relevantInputs.count(); i < numChildren; i++) {
                        ApexNode<?> child = node.getChild(i);
                        Boolean childResult = child.acceptVisitor(ExpressionSafetyCheckVisitor.this, currentScope);
                        log("areSafe() processing " + child.getImage() + " -> " + childResult);
                        if(childResult != null) isSafe &= childResult;
                    }
                    return isSafe;
                }
```

The input was the Apex expression `Database.query(foo)`
The output is as follows

```
|--areSafe() collector adding net.sourceforge.pmd.lang.apex.ast.ASTVariableExpression foo
|--ASTReferenceExpression: Database
|--areSafe() processing Database -> true
```

So we can see that when iterating by index we see the dropped item (the Database reference) not the desired item.

**Steps to reproduce:**

The linked branch is work in progress code. I am compiling it with 

```
mvn package -Dmaven.test.failure.ignore=true
```

My input class is

```java
public class Foo {
        private final String foo = String.escapeSingleQuotes(Flibble.somethingDangerous);
        private final List<SObject> bar = Database.query(foo);
}
```

After build and unzip I am testing with

```
./pmd-bin-7.0.0-SNAPSHOT/bin/pmd check  --force-language=apex -R category/apex/security.xml/ApexSOQLInjection -d /tmp/testsrc
```

**Comment by oowekyala** [comment]
If you write `node.children().drop(1).take(1)` you get a node stream of size 1 which only contains the second child of `node`. If you unroll your loop you can see you are calling `node.getChild(0)`, not `node.getChild(1)`. You should be calling `relevantInputs.get(i)` not `node.getChild(i)` (but if you do that you are not optimizing anything).

Applying this optimization is not recommended if you don't know how it works. Iterating without a nodestream is only better because you don't have to create a nodestream. Creating a nodestream just to count it is wasteful and negates the benefits of the indexed loop.

If you use a `NodeStream` parameter then presumably you want to abstract over where the nodes in the node stream are coming from. Hardcoding a children loop defeats this purpose, you would be better off passing start and end indices in the children list if you really want to use an indexed loop. I don't recommend this though. It's unlikely that your loop needs to be optimized at all, so I would suggest just using foreach on the nodestream and profile afterwards to see if it's worth optimizing. You know what they say about premature optimization.

**Comment by rcorfieldffdc** [comment]
I've changed my code to this:

```java
public boolean areSafe(NodeStream<ApexNode<?>> relevantInputs) {
           final boolean[] isSafe = {true};
           relevantInputs.forEach( (ApexNode<?> child) -> {
                Boolean childResult = child.acceptVisitor(ExpressionSafetyCheckVisitor.this, currentScope);
                log("areSafe() visited " + child.getImage() + " -> " + childResult);
                if(childResult != null) isSafe[0] &= childResult;
           });
           return isSafe[0];
 }
```

I'm afraid I'm having to learn the AST by jumping into the deep end - very quickly. So yes I may miss things :-) I'm making a lot of use of `System.out.println()` and `ast-dump`.

The `areSafe()` method was designed to take some collection of Nodes which the caller wants to know are safe from SOQL Injection nasties. It is assume that they are descendants of the Method Call we're visiting at the moment. I thought I could pass a drop() and take() nodestream down into it from the caller?

Maybe it's best I use something other than Node Streams for this? Though Streams seem the way the system is designed to deal with children.

Thanks
 - Richard

**Comment by rcorfieldffdc** [comment]
For information - I copied `AstVisitorBase` which contains this method.  (I was looking for a means of visiting children)

```java
    protected R visitChildren(Node node, P data) {
        // this explicit loop is faster than iterating on a children node stream.
        for (int i = 0, numChildren = node.getNumChildren(); i < numChildren; i++) {
            node.getChild(i).acceptVisitor(this, data);
        }
        return null;
    }
```

I note that works on the Node not the Stream so perhaps my mistake on a late night :-)

**Comment by rcorfieldffdc** [comment]
As an aside - I tried reducing with a Boolean::logicalAnd, but that failed for me. It could have been a NullPointer.

Would using `Boolean::logicalAnd` be the better way - as opposed to maintaining the single element array I have above?

**Comment by oowekyala** [comment]
I was about to suggest using `NodeStream::reduce` yes. You should make sure your `ExpressionSafetyCheckVisitor` never returns null

**Comment by rcorfieldffdc** [comment]
Re-reading the code I can see the error. I'd called `node.getChild()` not an equivalent on `relevantInputs` if there is one. So I'll close this.
