### ISSUE TITLE
[java] ViolationSuppress don't work at all

### ISSUE THREAD

**Issue by rechandler12** [pmd/pmd#4707]
**Affects PMD Version:** 
7.0.0-SNAPSHOT

**Description:**

I cannot make PMD to suppress rules via `violationSuppressRegex` or `violationSuppressXPath`.

**Exception Stacktrace:**

```
[INFO] --- pmd:3.21.1-pmd-7.0.0-SNAPSHOT:check (default) @ apk ---
[INFO] PMD version: 7.0.0-SNAPSHOT
[INFO] PMD Failure: com.decerto.ApkApplication:11 Rule:UseUtilityClass Priority:3 This utility class has a non-private constructor.
```

**Code Sample demonstrating the issue:**

Rule:

```xml
    <rule ref="category/java/design.xml/UseUtilityClass">
        <properties>
            <property name="violationSuppressRegex" value=".*ApkApplication.*"/>
        </properties>
    </rule>
```

```java
@EnableFeignClients
@EnableDiscoveryClient
@SpringBootApplication
public class ApkApplication {

    public static void main(String[] args) {
        SpringApplication.run(ApkApplication.class, args);
    }
}
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  I try to suppress rules for certain regex or xpath
2. I try do it through `violationSuppressRegex` or `violationSuppressXPath`
3. Then I run `mvn clean verify`
4. Despite exclusion PMD reports an error 

**Running PMD through:** *[Maven]*

**Comment by oowekyala** [comment]
The regex works on the violation message which here is "This utility class has a non-private constructor". So your regex won't match.  

Maybe try the XPath `.[contains(@BinaryName, 'ApkApplication')]` or `.[@SimpleName = "ApkApplication"]`

**Comment by rechandler12** [comment]
Alright my mistake, sorry about that. I also tried by using xpath expression but also doesn't work: `./ancestor::TypeDeclaration/Annotation/MarkerAnnotation/Name[@Image='SpringBootApplication']`

Could you help me with this expression?

**Comment by oowekyala** [comment]
There is also no more `TypeDeclaration`.
You should use `.[pmd-java:hasAnnotation('xxx.SpringBootApplication')]` and replace `xxx` with the package name of the annotation type.
