### ISSUE TITLE
[java] Unnecessary `@SuppressWarnings` Rule

### ISSUE THREAD

**Issue by armandino** [pmd/pmd#4715]
**Proposed Rule Name:** Unnecessary Suppression

**Proposed Category:** Code Style

**Description:** It would be nice if PMD could detect redundant (PMD-specific) `@SuppressWarnings` annotations. Sometimes code gets cleaned up so that it no longer violates a rule, but the annotation remains. 

**Code Sample:** 

```java
@SuppressWarnings({"PMD.CognitiveComplexity", "PMD.SystemPrintln"})
public void helloWorld() {
    System.out.println("Hello world");
}
```

would generate "Unnecessary suppression: PMD.CognitiveComplexity"

**Comment by jsotuyod** [comment]
Thanks for the suggestion. This is already being tracked under #648, and definitely something we would eventually love to have.

**Comment by armandino** [comment]
@jsotuyod that's great, thank you. Apologies for the duplicate. Did a search, but did not see that issue.
