### ISSUE TITLE
[core] Processing / parsing errors need more data

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#474]
When a problem raises with a rule we currently add an error with a generic message with little info on what went wrong.

We currently only log the name of the file that failed, but we are actively suppressing the stacktrace.

Usually the complete stacktrace is not needed (it's a `PMDException` wrapping the actual error), but at the very least the root cause should be kept, to facilitate detecting which rule failed, at what point and at which stage of analysis (symbol table, type resolution, rule chain, etc.)

**Comment by jsotuyod** [comment]
There seems to be processing errors not being added to the report, see https://github.com/pmd/pmd/issues/473#issuecomment-311423181

**Comment by lca-mse** [comment]
i cannot find this (very annoying bug) being fixed in 6.0.0. 
https://sourceforge.net/projects/pmd/files/pmd/6.0.0-SNAPSHOT/
is it just missing in the list of bugs being fixed or really not fixed. 
Note: here it happens intermittent on random files.

**Comment by jsotuyod** [comment]
@lca-mse the logging part was addressed on #533, but I keep this open since I haven't yet looked into scenarios where an error occurs but is not added into the `Report`.

Non the less, this issue is merely to improve output information on errors, not actually to prevent them.

If you do come across any processing errors, please make sure to report them. There are still a couple known issues we are committed to fix for 6.0.0 (in particular #328 ), but you may have stumbled upon something else.

**Comment by lca-mse** [comment]
I'm not sure how i can report a problem. we switched to PMD 5.8.1, and compiling our product at jenkins we now see intermittent pmd warnings. sometimes not, sometimes on this file and sometimes on that file....
It lools as follows
`.........[CHECKSTYLE] Parsing file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml
[CHECKSTYLE] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[CHECKSTYLE] Computing warning deltas based on reference build #25646
[JSHINT] Parsing file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml
[JSHINT] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[JSHINT] Computing warning deltas based on reference build #25646
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (default) > :pmd @ com.logicals.core.ui >>>
[PMD] No report found for mojo check
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ com.logicals.core.ui ---
[WARNING] There are 2 PMD processing errors:
[WARNING] /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/FileActionBarAdvisor.java: Error while processing /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/FileActionBarAdvisor.java
/app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/internal/handlers/EditorAreaDropAdapter.java: Error while processing /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/internal/handlers/EditorAreaDropAdapter.java
[PMD] Searching for all files in /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target that match the pattern pmd.xml
[PMD] Parsing 1 file in /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target
[PMD] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/pmd.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[PMD] Computing warning deltas based on reference build #25646
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (default) < :pmd @ com.logicals.core.ui <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (default) @ com.logicals.core.ui ---
[INFO] 
[INFO] `

**Comment by jsotuyod** [comment]
@lca-mse if the errors are included in the report, you can look them up there. If not, until we fix this in 6.0.0, the only way would be to run Maven in debug mode (`-X`), where you will be able to get a full stacktrace logged for each processing error.

**Comment by lca-mse** [comment]
I'm not sure how i can report a problem. we switched to PMD 5.8.1, and compiling our product at jenkins we now see intermittent pmd warnings. sometimes not, sometimes on this file and sometimes on that file....
It lools as follows
`.........[CHECKSTYLE] Parsing file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml
[CHECKSTYLE] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[CHECKSTYLE] Computing warning deltas based on reference build #25646
[JSHINT] Parsing file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml
[JSHINT] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/checkstyle-result.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[JSHINT] Computing warning deltas based on reference build #25646
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (default) > :pmd @ com.logicals.core.ui >>>
[PMD] No report found for mojo check
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ com.logicals.core.ui ---
[WARNING] There are 2 PMD processing errors:
[WARNING] /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/FileActionBarAdvisor.java: Error while processing /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/FileActionBarAdvisor.java
/app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/internal/handlers/EditorAreaDropAdapter.java: Error while processing /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/src/com/logicals/core/ui/internal/handlers/EditorAreaDropAdapter.java
[PMD] Searching for all files in /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target that match the pattern pmd.xml
[PMD] Parsing 1 file in /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target
[PMD] Successfully parsed file /app/jenkins/workspace/lc3gerrit@2/workspace/core-ui/com.logicals.core.ui/target/pmd.xml of module com.logicals.core.ui with 0 unique warnings and 0 duplicates.
[PMD] Computing warning deltas based on reference build #25646
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (default) < :pmd @ com.logicals.core.ui <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (default) @ com.logicals.core.ui ---
[INFO] 
[INFO] `

**Comment by lca-mse** [comment]
we will  try using this -X and add the report here. We tried 6.0-snapshot and now it has become much worse. Up to now we had 0 of these processing errors (with 4.*), with 5.8.1 we had between 0 and 3 for the full product, and now this is the result for a small bundle of the product:
G:\git\product-lc3c\modelrulechecker>type f:\mvci.err |grep -i "pmd processing"
[WARNING] There are 23 PMD processing errors:
[WARNING] There are 3 PMD processing errors:
[WARNING] There are 26 PMD processing errors:
[WARNING] There are 25 PMD processing errors:
[WARNING] There are 3 PMD processing errors:

**Comment by jsotuyod** [comment]
@lca-mse thanks for your support on this. I'll try a couple changes and probably I'll ask you to try a new 6.0 snapshot then. I'm committed to sorting this out before a 6.0.0 release.

**Comment by jsotuyod** [comment]
@lca-mse prcessing errors and config errors are now properly logged thanks to #519 and #533. However, Maven is not showing these, and the issue is being tracked as [MPMD-246](https://issues.apache.org/jira/projects/MPMD/issues/MPMD-246). Several processing errors were fixed in #653, but we recently were able to produce a couple more we are still missing.

Once we fix the known cases left, I'll ask you to try the 6.0.0 snapshot to asses if there are any scenario on your codebase we may be missing. Thanks for your patience so far.

**Comment by jsotuyod** [comment]
@lca-mse a new 6.0.0-SNAPSHOT is ready and fixes all previously known errors. However, PMD 6.0.0 is incompatible with the Maven plugin (a new release will be available once we ship PMD 6.0.0).

If you could try running the new snapshot PMD from CLI / Ant, or better yet, from Gradle to confirm your issues are gone and open a new issue if not it would be great. But I can perfectly understand if you can't.
