### ISSUE TITLE
[java] PMD designer cannot parse overly long formulas

### ISSUE THREAD

**Issue by NiceAsiv** [pmd/pmd#4747]
**Affects PMD Rule Designer Version: v6.14.0** 

**Description:**

PMD designer cannot parse overly long formulas

**Exception Stacktrace:**

```
# Copy-paste the stack trace here
```

**Code Sample demonstrating the issue:**

```java
public class A
{
    void foo()
    {   int j,k=5;
     j=k/3/12%2;
    }
}
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1. open the PMD Rule Designer and paste the code above
![image-20231117174025221](https://github.com/pmd/pmd/assets/70969752/9a609e2b-7d43-4e19-a544-e843ef6978b0)
   you cna see that PMD designer cannot parse the `/`

2. And the I delete `%`,it resolved the equation normally
![image-20231117174334075](https://github.com/pmd/pmd/assets/70969752/8627c671-15db-4263-8ad1-148c125b6476)

3. I replaced it with  `+`

![image-20231117174451432](https://github.com/pmd/pmd/assets/70969752/742ee325-b3d8-47c2-9ee7-9784d857cfd5)

This may caused by the high priority of `%`

**Running PMD through:** *[Maven]*

**Comment by jsotuyod** [comment]
Hi @NiceAsiv. I fear you are using an incredibly dated version of PMD (April 2019).
PMD 7 (currently at 7.0.0-RC4) completely rewrote this part of the AST and should parse this correctly (with a smaller tree). This may have been fixed in a later PMD 6 release, but I'm unsure about it.

**Comment by oowekyala** [comment]
> This may have been fixed in a later PMD 6 release, but I'm unsure about it. 

No it hasn't been fixed in PMD 6

**Comment by NiceAsiv** [comment]
Thank you for taking the time to reply. I appreciate your advice and will definitely give it a try in the lastest version. @jsotuyod

**Comment by NiceAsiv** [comment]
> > This may have been fixed in a later PMD 6 release, but I'm unsure about it.
> 
> No it hasn't been fixed in PMD 6

Yes ,This issue was not resolved until PMD7
