### ISSUE TITLE
[core] RFC: execute checkstyle check earlier in the build

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#476]
It's really frustrating when a build fails just for some checkstyle issues, especially so since the checkstyle plugin is *the last* task of the build: it executes after compilation, tests, javadoc attachment... Wouldn't it be better if it was one of the first tasks in the build? Builds would then fail quicker, and be corrected quicker, which would induce less frustration for everybody

**Comment by jsotuyod** [comment]
@oowekyala are you refering to CI? or locally building?

For local builds I don't know what you are using, but you can always have checkstyle run first: `./mvnw checkstyle:check whatever`

**Comment by oowekyala** [comment]
I was referring to local builds, I don't know in what order CI does its build. Well many thanks, I didn't know I could do that! :)

**Comment by jsotuyod** [comment]
@oowekyala anytime!
