### ISSUE TITLE
[java] SimplifyBooleanReturns - wrong suggested solution

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#4763]
**Affects PMD Version:** 7.0.0-rc4

**Rule:** [SimplifyBooleanReturns](https://docs.pmd-code.org/latest/pmd_rules_java_design.html#simplifybooleanreturns)

**Description:**

I think, the suggested solution would result in wrong code.

**Code Sample demonstrating the issue:**

```java
if (a == null) {
  return false;
}
return "FOO".equals(a.toString());
```

The suggestion is:

```
This if statement can be replaced by `return !{condition} || {elseBranch};`.
```

I think, this is wrong, it should be

```
This if statement can be replaced by `return !{condition} && {elseBranch};`.
```

**Comment by rethab** [comment]
With PMD 7.3.0, this is still wrong.

Code:

```java
if (StringUtils.isAnyBlank(stringA, stringB)) {
    return false;
}
return Objects.equals(stringA, stringB);
```

PMD Error:

```text
SimplifyBooleanReturns: This if statement can be replaced by `return !{condition} || {elseBranch};`
```

But as OP said, it should be `&&` instead of `||`.
