### ISSUE TITLE
[cli] Could not find or load main class

### ISSUE THREAD

**Issue by Scrates1** [pmd/pmd#4791]
**Affects PMD Version:** 

pmd-bin-7.0.0-rc4

**Description:**

Hi! GOOD DAY!

I set `JAVA_HOME` to `C:\Users\XXX\Program Files\corretto-1.8.0_372`

When I tring the CPD:

```bash
 .\pmd.bat cpd --no-fail-on-violation --minimum-tokens 30 --file-list XXX --language java --format xml
```

I got that:

```bash
错误: 找不到或无法加载主类 Files\corretto-1.8.0_372\lib\dt.jar;C:\Users\XXX\Program
```

"错误: 找不到或无法加载主类" means : Error, Could not found or load main class.

I guess it's because the JDK path is with space (space in `Program Files`).

Looking forward to be fixed!

Best wishes!

**Comment by adangel** [comment]
try setting JAVA_HOME with spaces, e.g.

```
set JAVA_HOME="C:\Users\XXX\Program Files\corretto-1.8.0_372"
```

You also need to set in addition the PATH:

```
set PATH=%JAVA_HOME%\bin;%PATH%
```

pmd.bat is just executing the java binary, that is on the path... (https://github.com/pmd/pmd/blob/2e7263af695638a90d8d6e4d61e290d3dc3c4a19/pmd-dist/src/main/resources/scripts/pmd.bat#L10)

Maybe you have also set the CLASSPATH env var - which we also use: https://github.com/pmd/pmd/blob/2e7263af695638a90d8d6e4d61e290d3dc3c4a19/pmd-dist/src/main/resources/scripts/pmd.bat#L75-L77

You might want to ensure, you have quoted the spaces in there as well. Or just unset the variable with `set CLASSPATH=`

**Comment by Scrates1** [comment]
Hi, I have tried to set JAVA_HOME with ""，and `set PATH=%JAVA_HOME%\bin;%PATH%`. It doesn't work.
