### ISSUE TITLE
pmd.github.io website appears outdated

### ISSUE THREAD

**Issue by vadcx** [pmd/pmd#4842]
The github io website is linked on this repository's sidebar.

It currently reads (note lack of Kotlin and others):

> About PMD

> PMD is a source code analyzer. It finds common programming flaws like unused variables, empty catch blocks, unnecessary object creation, and so forth. It supports Java, JavaScript, Salesforce.com Apex and Visualforce, PLSQL, Apache Velocity, XML, XSL.

> Additionally it includes CPD, the copy-paste-detector. CPD finds duplicated code in Java, C, C++, C#, Groovy, PHP, Ruby, Fortran, JavaScript, PLSQL, Apache Velocity, Scala, Objective C, Matlab, Python, Go, Swift and Salesforce.com Apex and Visualforce.

And I couldn't find an exact match for this. Through Github's Search I found this text is copy-pasted 3 times:

Readme.md:

> It supports Java, JavaScript, Salesforce.com Apex and Visualforce,
**Modelica**, PLSQL, Apache Velocity, HTML, XML and XSL.

pmd/docs/index.md (which is the source for https://pmd.sourceforge.io/snapshot/index.html)

> It's mainly concerned with Java and Apex, but supports 16 other
languages.

pom.xml (note Kotlin):

> It supports Java, JavaScript, Salesforce.com Apex and Visualforce,
        **Kotlin, Swift, Modelica**, PLSQL, Apache Velocity, JSP, WSDL, HTML, XML and XSL.

---

This makes it 4 different versions and I couldn't find the website's text in the source tree. Was it forgotten? See #1949.

I wanted to update the text but maybe the link to pmc.gihtub.io should be replaced instead? Then it'd be nice to add a deprecation banner over there.

**Comment by jsotuyod** [comment]
The site code is available on https://github.com/pmd/pmd.github.io/

The actual file containing that paragraph is [this one](https://github.com/pmd/pmd.github.io/blob/master/_includes/about.html)

And yes, it is heavily outdated.

The most accurate list of supported languages lies in our integration tests:

CPD supported languages: https://github.com/pmd/pmd/blob/642716fabf985d4ca53043d86164a41083af93ab/pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java#L31-L38

PMD supported languages (with language versions): https://github.com/pmd/pmd/blob/642716fabf985d4ca53043d86164a41083af93ab/pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java#L40-L68
