### ISSUE TITLE
[java] Unable to parse some Java9+ resource references

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#4912]
**Affects PMD Version:**
7.0.0

**Description:**

Since Java 9, PMD has allowed for concise resources (ie: not variables declared within the try-with-resources), but some constructs are currently rejected by the parser even if valid Java code.

**Code Sample demonstrating the issue:**

```java
class Foo implements AutoCloseable {
      void testThis() throws Exception {
          try (this) { // unsupported
          }
      }

     void testQualifiedThis() throws Exception {
          try (Foo.this) { // unsupported
          }
      }

     void testArrayAccess(AutoCloseable[] c) throws Exception {
          try (c[0]) { // unsupported
          }
      }

      @Override
      public void close() throws Exception {
      }
}
```

Probably others too…

**Running PMD through:** Any

Probably, the saner fix would be to simply remove this check altogether, and continue under the premise that the code compiles…

https://github.com/pmd/pmd/blob/a28943ae1b2e25d3aecb08108fdf1376e23d50f7/pmd-java/etc/grammar/Java.jjt#L2868-L2873

**Comment by oowekyala** [comment]
Interesting... We would need to make this method nullable and adapt the callers: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTResource.java#L52

Especially EmptyControlStatementRule needs new tests to disallow these constructs. Writing
```
try (this) {}
```
is weird and should be `this.close()`.

**Comment by oowekyala** [comment]
Also note that `c[0]` is not a valid resource. Javac errors with the following message:

> the try-with-resources resource must either be a variable declaration or an expression denoting a reference to a final or effectively final variable.

The only expressions allowed here are field accesses and variable accesses according to the [JLS 14](https://docs.oracle.com/javase/specs/jls/se22/html/jls-14.html#jls-14.20.3). It seems javac also accepts `this`, but that's all. So while we should support this corner case, I don't think we should remove the parser check altogether.
