### ISSUE TITLE
[cli] cpd-gui closes immediately

### ISSUE THREAD

**Issue by VishV-Android** [pmd/pmd#4913]
**Affects PMD Version:** 

pmd-bin-7.0.0

**Description:**

I am using pmd CLI for CPD but not able to open GUI of pmd cpd. It just open some window for a moment then it automatically close.

**Exception Stacktrace:**

```
# Not getting any exception.
```

**Code Sample demonstrating the issue:**

```java
C:\Users\baps\Downloads\pmd-dist-7.0.0-bin\pmd-bin-7.0.0\bin>pmd cpd-gui
```

**Comment by jsotuyod** [comment]
@VishV-Android thanks for bringing this to our attention. This is indeed an issue, and I've submitted a PR to get this fixed in the next release.

**Comment by VishV-Android** [comment]
@jsotuyod Your pull is merged, now how to get new updated cli? will they release new .zip file?

**Comment by jsotuyod** [comment]
PMD is back to monthly relesses. 7.1.0 should be released by the end of April including this fix.

**Comment by adangel** [comment]
For testing, you can also download the SNAPSHOT version from here: https://sourceforge.net/projects/pmd/files/pmd/7.1.0-SNAPSHOT/
