### ISSUE TITLE
[Core] Homepage's "existing rules" hyperlink gives 404 not found

### ISSUE THREAD

**Issue by crunsk** [pmd/pmd#493]
Hi!
On the homepage https://pmd.github.io/ the "existing rules" link tries to link to java's rulesets page.
Now the hyperlink points to "https://pmd.github.io/5.8.1/pmd-java/rules/index.html". This gives 404.
The correct link appears to be "https://pmd.github.io/pmd-5.8.1/pmd-java/rules/index.html"

**Comment by jsotuyod** [comment]
@crunsk you are absolutely right! Thanks for the heads up, as we move away from Sourceforge web hosting as part of #405
