### ISSUE TITLE
mvnw explicitly enable http proxies

### ISSUE THREAD

**Issue by grandinj** [pmd/pmd#498]
when building under Linux (in this case Ubuntu Linux)  using

    ./mvnw clean verify

from behind a proxy, the maven/java stuff will not use the system proxies unless explicitly told to do so, which is a problem when maven tries to download the jars it needs :-)

thanks

**Comment by grandinj** [comment]
specifically, I am talking about adding this to the java command line:

     -Djava.net.useSystemProxies=true

**Comment by grandinj** [comment]
tried adding to to the java invocation at the end of the mnvw script, and seems to work for me

**Comment by grandinj** [comment]
nope, that only got me the first jar, sigh, there must another script further in:

/home/noel/pmd
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/noel/.m2/wrapper/dists/apache-maven-3.5.0-bin/6ps54u5pnnbbpr6ds9rppcc7iv/apache-maven-3.5.0-bin.zip to /home/noel/.m2/wrapper/dists/apache-maven-3.5.0-bin/6ps54u5pnnbbpr6ds9rppcc7iv
Set executable permissions for: /home/noel/.m2/wrapper/dists/apache-maven-3.5.0-bin/6ps54u5pnnbbpr6ds9rppcc7iv/apache-maven-3.5.0/bin/mvn
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/wagon/wagon-ssh/2.10/wagon-ssh-2.10.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.apache.maven.wagon:wagon-ssh:2.10 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.wagon:wagon-ssh:jar:2.10 @ 
 @

**Comment by jsotuyod** [comment]
The maven wrapper is an autogenerated file, by running `mvn -N io.takari:maven:wrapper` (check https://github.com/takari/maven-wrapper). Editing it manually is fragile and wouldn't survive to updates.

You should consult with them on the best approach for this, it's possible they don't support it.

**Comment by grandinj** [comment]
thanks, logged as  https://github.com/takari/maven-wrapper/issues/58

**Comment by mosabua** [comment]
Just set it in .mvn/jvm.config  - see https://maven.apache.org/docs/3.3.1/release-notes.html

**Comment by grandinj** [comment]
@mosabua yes I can certainly do that, but:

(a) it doesn't exactly make for a pleasant start to my latest maven experience
(b) I've already configured my proxy settings in the global system preferences, why do I need to keep doing it again and again (in a different way each time) for each different java program out there?

**Comment by jsotuyod** [comment]
The issue was moved to maven wrapper.
