### ISSUE TITLE
Set appropriate log level in pmd-maven-plugin

### ISSUE THREAD

**Issue by delanym** [pmd/pmd#5032]
The `org.apache.maven.plugins.pmd.PmdViolationCheckMojo` goal logs violations at "info" level.
See example at https://github.com/pmd/pmd/issues/4001

I filter Maven log output based on the log level,  so I miss these after setting `printFailingErrors` to true.

If the `failOnViolation` is true, I expect violations logged at error level.
If the `failOnViolation` is false, I expect violations logged at warning level.

**Comment by jsotuyod** [comment]
This repository is about PMD itself. Maven PMD Plugin lives at [apache.org](http://apache.org/) -> https://issues.apache.org/jira/projects/MPMD/summary

As for pmd itself, the `failOnViolation` flag (or equivalent, depending on whether this is a cli, ant or programmatic invocation) should not affect where errors are reported. Failure is determined by the output (build status, status code, etc) and not the channel.
