### ISSUE TITLE
Remove extraneous log lines in pmd-maven-plugin

### ISSUE THREAD

**Issue by delanym** [pmd/pmd#5033]
The plugin is logging the pmd version with every execution of the check goal. If a project has 500 modules this results in an extra 1000+ log lines

`[INFO] PMD version: 7.0.0`

Could either make it configurable or remove entirely. The version can be inferred from the plugin version or inspecting the Maven config.

**Comment by adangel** [comment]
This is a duplicate of https://issues.apache.org/jira/browse/MPMD-391

Note: This repository is about PMD itself. Maven PMD Plugin lives at apache.org -> https://issues.apache.org/jira/projects/MPMD/summary
