### ISSUE TITLE
[apex] SonarQube support

### ISSUE THREAD

**Issue by TedHusted** [pmd/pmd#509]
Has anyone had success with using the Apex PMD plugin with SonarQube?

I see Apex on the PMD site, and I grabbed the latest SonarQube, but I don't see any reference to using the Apex plugin.

We're using CodeScan with SonarQube now, and I would like to see how this plugin compares.

-Ted.

**Comment by up2go-rsoesemann** [comment]
As you posted on the Salesforce success community it seems you found a solution by providing SonarCube the missing ruleset XML.

Can we close this issue then?

**Comment by TedHusted** [comment]
I'm able to run Apex PMD on its own, outside of any platform, such as SonarQube, Codacy, or CodeClimate, but I still have no idea of how to get Apex PMD to run with SonarQube.

**Comment by up2go-rsoesemann** [comment]
I don't know SonarCube but I would expect that it should work with Apex if it works with Java (and other PMD supported languages). What errors are you getting?

**Comment by up2go-rsoesemann** [comment]
@TedHusted ?!

**Comment by up2go-rsoesemann** [comment]
@jsotuyod I think we can close that.

**Comment by TedHusted** [comment]
I've confirmed with the SonarQube group that the SonarQube PMD plugin only supports Java, and mostly likely a new plugin would have to be implemented for multi-language support.

**Comment by loter** [comment]
was this resolved? still not working for me as expected.
I've generated report and set sonar.apex.pmd.reportPaths property value.

**Comment by adangel** [comment]
No, it was not resolved, see the last comment https://github.com/pmd/pmd/issues/509#issuecomment-321335170 :

> I've confirmed with the SonarQube group that the SonarQube PMD plugin only supports Java, and mostly likely a new plugin 
> would have to be implemented for multi-language support.
