### ISSUE TITLE
[apex] "No adapter exists for type" error message printed to stdout instead of stderr

### ISSUE THREAD

**Issue by ethan-sargent** [pmd/pmd#5094]
The error message "No adapter exists for type" error message is being printed to stdout instead of stderr.

This happens with the --json flag provided to PMD - which then causes JSON parsing on stdout to fail.

Full error printed: 
`No adapter exists for type com.google.summit.ast.declaration.VariableDeclarationGroup`.

Source to reproduce:
```java
SObject sobj = new Account();
switch on sobj {
  when Account acc {
    // ^^^ parsed as VariableDeclarationGroup
  }
}
```

Each branch with a `Type name` combination causes the error message to be printed out 1x.

Relevant line:
https://github.com/pmd/pmd/blob/e6397d5d5ce613d57280c04bf97cddd679259e09/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.kt#L190

Reproducible using CLI (`pmd check --format json path/to/example -R category/apex/bestpractices.xml --threads 0 --no-progress 2>/dev/null`)

**Comment by adangel** [comment]
Thanks for reporting.

Actually, instead of stderr, we should throw an exception in that case, because this messages means, there is some implementation missing.

Since this message is currently printed on stdout, you can use the CLI parameter [`--report-file`](https://docs.pmd-code.org/latest/pmd_userdocs_cli_reference.html#-report-file) to write the json data into a file without relaying on stdout not being corrupted.

**Comment by ethan-sargent** [comment]
No worries, seemed like a fairly niche failure scenario. 
That makes sense. Curious whether throwing an exception here would cause a complete parse failure, rather than just additional output in stdout?

Something that would probably be a bigger change (potentially in summit-ast?) - might be useful to have a sealed class or an enum with all of the node types so that the switch statement can be exhaustive without needing to have an else branch?
That way it'd be a compile time failure to have some of the implementation missing rather than a runtime failure.


I didn't know about the report-file flag so that's good to know, thank you - I'm actually using the JSON output to show PMD results on save in neovim so writing and reading from a file would be a bit harder to integrate. Happy to wait for the fix to land instead of hacking something together.
