### ISSUE TITLE
CPD should give same file duplicated blocks

### ISSUE THREAD

**Issue by thunderpycode** [pmd/pmd#5115]
We are running CPD, using "pmd cpd --minimum-tokens 10 --dir force-app_latest/main/default/classes --format xml --language apex",
We want to identify duplicate block of code within a same file but it is giving duplicates between the two files.
Can we use CPD to detect duplicate block of code within a same file ?
@himanshu-devops

**Comment by jsotuyod** [comment]
This is actually a question, https://github.com/pmd/pmd/discussions/5114

**Comment by thunderpycode** [comment]
This is same question from my side.
