### ISSUE TITLE
[apex] OperationWithHighCostInLoop not firing in triggers

### ISSUE THREAD

**Issue by jfeingold35** [pmd/pmd#5139]
**Affects PMD Version:** 7.3.0

**Rule:** [OperationWithHighCostInLoop](https://docs.pmd-code.org/latest/pmd_rules_apex_performance.html#operationwithhighcostinloop)

**Description:**
Violations for `OperationWithHighCostInLoop` no longer happen within triggers.

**Code Sample demonstrating the issue:**

```apex
trigger accountTrigger on Account (before insert, before update) {
		integer i = 0;
		for (i = 0; i <15; i++) {
			SObjectType token = Schema.getGlobalDescribe().get('Account');
		}
}
```

**Expected outcome:**
A violation for `OperationWithHighCostInLoop` should be thrown, the same way it was in 7.2.0.

**Running PMD through:** *[CLI]*

**Comment by jsotuyod** [comment]
Related to #5138, probably the grammar / AST changed the node types /structure for triggers

**Comment by jfeingold35** [comment]
@jsotuyod , yeah, I figured. But I wanted to explicitly call it out because it's one of the ones I saw when inspecting the results.
