### ISSUE TITLE
Add support for detecting and reporting superfluous/redundant suppressions

### ISSUE THREAD

**Issue by SCWells72** [pmd/pmd#5174]
Apologies if this has already been logged somewhere or is even implemented, but I was unable to find anything after a number of (perhaps cursory?) searches.

PMD already supports suppression of rule violations as documented here:

https://pmd.github.io/pmd/pmd_userdocs_suppressing_warnings.html

However, it's not unusual for something that was suppressed at one point to no longer require suppression later. Minimally this can result in superfluous/redundant suppressions in the code base.

The JetBrains IDEs provide a **Redundant suppression** code inspection that actually highlights this situation clearly, and I was thinking that it would be wonderful if PMD might be able to do the same. Basically when processing rules, if a given scope suppresses a rule ID and no violations are ever added within that scope with that rule ID, a warning-level violation would be added for the suppression itself (if the Redundant suppression rule was also enabled, of course).

Thoughts?

**Comment by jsotuyod** [comment]
This is indeed something we want but don't have right now. It's being tracked under #648. PRs are always welcome to help it move faster.

**Comment by SCWells72** [comment]
Got it. Feel free to merge this into #648 if you'd like. I'm certainly happy to help if possible -- I've contributed a decent bit in the past around the Apex ruleset -- but I'm not sure if I'll have an opportunity anytime soon. If I come up for air at some point I'll see if I can take a look, though.
