### ISSUE TITLE
[java] Allow @SuppressWarnings with constants instead of literals

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#520]
**Description:**
PMD allows violation suppression through the `@SuppressWarnings` annotation, but such suppression currently only allows for a literal even when constants are valid in the Java grammar.

Edge cases (initialization on a static block with arbitrary code), or calls to static methods can't be properly resolved, but the most basic case can certainly be with the current infrastructure.

**Code Sample demonstrating the issue:**

```
public class NewClass {
    private final static String PMD_UNUSED_FORMAL_PARAMETER = "PMD.UnusedFormalParameter";

    @SuppressWarnings(PMD_UNUSED_FORMAL_PARAMETER)
    public void someMethod1(Object param) {
        System.out.println("someMethod1");
    }
}
```

**Running PMD through:** *any*

**Comment by oowekyala** [comment]
> Edge cases (initialization on a static block with arbitrary code), or calls to static methods can't be properly resolved, but the most basic case can certainly be with the current infrastructure.

Annotation values must be constant expressions, so only inlined compile-time constants are allowed (not blank constant fields), and static methods are also prohibited. The only edge case is when the constant is defined in another compilation unit, in which case we need multifile analysis/ classpath info.

This is not a difficult problem per se but it would require a bit of logic to evaluate constant expressions. Given the current complicated expression grammar, I'd rather implement this on 7.0, with the good grammar.
