### ISSUE TITLE
[java] Wrong message for LambdaCanBeMethodReference with method of enclosing class

### ISSUE THREAD

**Issue by hgschmie** [pmd/pmd#5214]
**Affects PMD Version:** 7.5.0 

**Rule:** LambdaCanBeMethodReference

Please provide the rule name and a link to the rule documentation:
https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#lambdacanbemethodreference

**Description:**

PMD 7.5.0 flags this line: https://github.com/basepom/maven-plugins/blob/maven-plugins-v5/dependency-scope/src/main/java/org/basepom/mojo/dependencyscope/DependencyScopeMojo.java#L178

with 

```
[WARNING] PMD Failure: org/basepom/mojo/dependencyscope/DependencyScopeMojo.java:178 Rule:LambdaCanBeMethodReference Priority:3 Lambda expression could be written as a method reference: `this::findViolations`.
```

implying that the code could be rewritten as

```java
ListenableFuture<Set<DependencyViolation>> subfuture =
    subcontext.map(this::findViolations)
    .orElseGet(() -> Futures.immediateFuture(ImmutableSet.of()));
```

**Code Sample demonstrating the issue:**

```java
    private ListenableFuture<Set<DependencyViolation>> findViolations(TraversalContext context) {
[...]
        Futures.addCallback(resolveArtifactDescriptor(context.currentArtifact()), new FutureCallback<>() {
[...]
            @Override
            public void onSuccess(ArtifactDescriptorResult artifactDescriptor) {
[...]
                        ListenableFuture<Set<DependencyViolation>> subfuture =
                                subcontext.map(traversalContext -> findViolations(traversalContext))
                                        .orElseGet(() -> Futures.immediateFuture(ImmutableSet.of()));
}
```

note that the `map(traversalContext -> findViolations(traversalContext))` call is within a callback instance and has no access to the enclosing `findViolations()` method. However, PMD seems to get scope confused and flags this as being possible to rewrite as lambda (it is not, both IntelliJ and the java compiler refuse it).

**Expected outcome:**

PMD reports a violation at line 178, but that's wrong. That's a false positive.

**Running PMD through:** *Maven*

**Comment by oowekyala** [comment]
You can write `DependencyScopeMojo.this::findViolations` i think. İ think this is probably not a false positive, but the error message has a problem

**Comment by hgschmie** [comment]
Thank you for pointing this out. Yes, `DependencyScopeMojo.this::findViolations` would work.
