### ISSUE TITLE
[java rules]How to get param's class?

### ISSUE THREAD

**Issue by JiayuK** [pmd/pmd#5243]
### Discussed in https://github.com/pmd/pmd/discussions/5242

<div type='discussions-op-text'>

<sup>Originally posted by **JiayuK** September 29, 2024</sup>
Please help me, I need to check if instance a uses methods containing special characters, if this class extends from the specified class.
for example
`public class A extends Aa{}`
`public class main{
public static void main(String[] args){
   A a = new A();
   setDump(a);
}
}`
I don't want to extends the instance of Aa and set it to dump.

My current implementation method,
`public class Dump extends AbstractJavaRule {
    @Override
    public Object visit(ASTExpressionStatement node, Object data) {
        Node node1 = node.getFirstChild();
        if (node1.getImage().contains("setDump")) {
        }
        return super.visit(node, data);
    }`
Question 1: I don't know how to traverse and find the VariableAccess of ArgumentList
Question 2: The Variable Access I obtained through traversal is of type Node, and I don't know how to obtain the class corresponding to the variable

![6CF64D54-2852-40E4-BF05-6872040A99B7](https://github.com/user-attachments/assets/b3e69d27-b6a7-42e5-9569-44f53705ba7c)

Please help me, thanks</div>

**Comment by jsotuyod** [comment]
Not an issue, follow up on discussions.
