### ISSUE TITLE
[apex] Trying to find the documentation for apex-jorje-semantics

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#531]
Hi, would anyone know where the javadoc for the apex-jorje-semantic jar is? In fact, any info about what that jar is would be appreciated. The apex module has it as a  maven dependency, yet I found no trace of it in the central maven repo and google only leads back to pmd-apex... 

Thanks!

**Comment by up2go-rsoesemann** [comment]
There is no such thing as a javadoc or maven repo entry for this parser. It is still a closed source parser used only for their open source IDE. Back then when I ported PMD to support Apex I asked for help and permission in this thread https://github.com/forcedotcom/idecore/issues/167.

Salesforce.com will eventually release on open source parser for their language but until then we have to live with this workaround. 

What are you trying to do? Maybe I can use my network to get you the infos you need even under those circumstances.

**Comment by oowekyala** [comment]
Thanks for linking to the thread, that was very informative!

I'm trying to implement a Metrics Framework for Apex. One goal of my GSoC project was to abstract the Java framework enough that it's easy to build a similar framework for another language. Trying a real use case is the best way to find out, plus, it could benefit Apex rule developers

No worries, I don't need javadoc that much, it's just I was confused by the API when first exploring it. I was trying to find a way to get the modifiers of a method as strings, but I finally used the ModifierNode. But thanks for proposing ;)

Though would you know if the `TypeInfo.getNameSpace()` method works correctly with pmd's parser ? I don't really know how to check that without the Force IDE

**Comment by up2go-rsoesemann** [comment]
Puhhh. I don't know but I see two options for finding that out quickly.

1) Open an issue at https://github.com/forcedotcom/idecore/issues mention PMD and great features for Apex. Mention me and I will bug people until you got your answers. BTW: I love that you choose Apex to make your great extension running ;-)

2) Download the free IDE https://developer.salesforce.com/page/Force.com_IDE yourself or just the Eclipse plugin (even better) and debug it inside yourself.

What do you think?

**Comment by oowekyala** [comment]
@up2go-rsoesemann Thanks for your feedback! 

I've verified that the `getNameSpace()` method doesn't work (it returns the empty string) by running a dummy rule printing info against the sources of [this apex project](https://github.com/SalesforceFoundation/Cumulus). I've also tried to use the Salesforce eclipse plugin as you suggested but I think I can't use it without a Salesforce developer organisation... 

The metrics framework doesn't really need to resolve namespaces, we actually only need some way to name classes and method unambiguously (some sort of fully qualified name). Namespace would only needed if the analysed project contains sources that are in different namespaces. Is that's frequent in Apex projects? If so, without namespace prefix, name clashes would mess up the metric memoization logic.

Namespace resolution would be neat and prevent such clashes. I think the AST produced by jorje is not type resolved, as I got several times the string "!Unresolved!" when using `TypeInfo.toString()`. From the thread you linked, it seems that offline compilation wasn't available at the time you added support for Apex to PMD, maybe it's been dealt with now. If it is, we could perhaps add type resolution to pmd-apex. I can open an issue in idecore to ask about it ;)

Btw, I do want to be upfront and tell you that this falls out of the scope of my GSoC project, and as the summer ends soon that's not one of my priorities right now

**Comment by up2go-rsoesemann** [comment]
Namespaces in the Salesforce world have a somewhat different semantics. I guess the method indeed works but the code is from a yet namespaceless package. See this for details https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/namespaces_intro.htm

**Comment by oowekyala** [comment]
Hum I see. I've checked against [the Apex ESAPI implementation](https://github.com/forcedotcom/force-dot-com-esapi), which I think is released [on the AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N30000009x7hPEAQ) so should declare a namespace (AFAIK). Results are the same, namespace is the empty string. To be honest I don't know enough about the Apex ecosystem to know if that's normal or not. Are namespaces usually declared somewhere in the sources?

**Comment by up2go-rsoesemann** [comment]
It's part of seperate metadata files. Not the *.cls PMD is parsing. I guess this field is only populated when the Jorjeparser knows more about the "org" where the code is deployed. So if it just parsed the source code there is no way for the parser to find out about namespaces.

BTW: I really like how you improved writing complex rules using you GSoC metrics idea.  Did I get this right from you commits that you converted some Apex rules to this new model?

**Comment by oowekyala** [comment]
Hum ok. Maybe there's a way to get more info about the org/ project with the parser but I guess the current rules will work for now

Yes I converted the rule about cyclomatic complexity! There will soon be some doc on the site about writing metrics/ using the framework if you're interested ;)

**Comment by up2go-rsoesemann** [comment]
Would you mind spending 15min + in a short skype call we me to show how this works so I can better transform other rules?

**Comment by oowekyala** [comment]
Sure! When's a good time? Btw I don't use skype, the linux version is buggy as hell. I'd rather use google hangouts or discord. May I send you a discord link? You wouldn't need an account

**Comment by oowekyala** [comment]
@up2go-rsoesemann I think we can close this. There's now doc about writing metrics [here](https://pmd.github.io/pmd/pmd_devdocs_metrics_howto.html) if you'd like to populate the Apex metrics framework! Btw Ncss, NPath, and their associated rules could perhaps be ported from the Java module without too much trouble
