### ISSUE TITLE
[java] False negative in PreserveStackTrace with string concatenation

### ISSUE THREAD

**Issue by albfernandez** [pmd/pmd#543]
**Rule Set:**
PreserveStackTrace

**Description:**
PMD should fire PreserveStackTrace in the following code

    public void foo(String a) throws Exception {
        try {
            int i = Integer.parseInt(a);
        } catch(Exception e){
            throw new Exception("something bad:" + e); // Stack trace is lost, but no violation is reported!!
        }
    }

**Code Sample demonstrating the issue:**

    <test-code>
        <description>False negative with String concatenation </description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
    public class Foo {
        public void foo(String a) throws Exception {
            try {
                int i = Integer.parseInt(a);
            } catch(Exception e){
                throw new Exception("something bad:" + e);
            }
        }
    }
        ]]></code>
    </test-code>

**Comment by jsotuyod** [comment]
Very interesting! Thanks for the report!
