### ISSUE TITLE
[java] Consecutive Literal Appends

### ISSUE THREAD

**Issue by suruchidawar** [pmd/pmd#547]
Please, prefix the report title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

Consecutive Literal Appends

StringBuffer (or StringBuilder).append is called {0} consecutive times with literal Strings. Use a single append with a single combined String."

StringBuffer xml = new StringBuffer();
String test = "user" ; // This is coming from another java file and is a dynamic variable
String pwd = "password"; // This is coming from another java file and is a dynamic variable
xml.append(test);
xml.append(pwd);

Can you tell why is this reported as a violation since these are not literals which are used in append statement ?

**Comment by jsotuyod** [comment]
Hard to tell without actual code / a more accurate snippet. The one you provided has 2 literal strings (even if stored to local variables) and would not be a false positive.
