### ISSUE TITLE
[cpd] Feature: Support for Kotlin

### ISSUE THREAD

**Issue by vanniktech** [pmd/pmd#551]
I saw that swift has support in `cpd` and I'd like to have Kotlin support too.

I'm sorry if that's not the right place to ask this but is this anyhow planned? I saw that the `pmd-swift` module is rather small and adding kotlin might be the same effort if not less since kotlin can be abstracted away using AST / UAST.

**Comment by jsotuyod** [comment]
We already have a feature request for Kotlin supprt (see #419).

Full support needs a proper support for Antlr (already in roadmap) or an abstraction like the one built for Apex. CPD support, as you say, is simpler and have fewer requirements. We will support Kotlin eventually, but it's unlikely to happen on the next couple of releases.

However, PRs are more than welcome to help us bring this forward faster.
