### ISSUE TITLE
[doc][java] Add hint for guava method in documentation of InefficientEmptyStringCheck

### ISSUE THREAD

**Issue by mmoehring** [pmd/pmd#571]
The documentation for `InefficientEmptyStringCheck` mentions methods from Apache Commons and Spring Stringutils. For the users of Google Guava a hint to the Guava CharMatcher would be nice.
For reference, the call is `CharMatcher.whitespace().matchesAllOf(foo)`.

**Comment by jsotuyod** [comment]
@mmoehring thanks for the suggestion! Please, feel free to submit a PR if you feel like it.

**Comment by mmoehring** [comment]
Uh..sorry for the commit rewrite spam, one of my first PRs.

**Comment by jsotuyod** [comment]
@mmoehring looks good! Thanks!
