### ISSUE TITLE
[java] LiteralsFirstInComparisons should consider constant fields

### ISSUE THREAD

**Issue by JJengility** [pmd/pmd#575]
**Rule:** [PositionLiteralsFirstInComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#positionliteralsfirstincomparisons) (deprecated), [PositionLiteralsFirstInCaseInsensitiveComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#positionliteralsfirstincaseinsensitivecomparisons) (deprecated) and [LiteralsFirstInComparisons](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#literalsfirstincomparisons)

**Description:** (Position)LiteralsFirstInComparisons do not appear to be properly checking this rule completely, perhaps due to use of constants or some other factor

**Code Sample demonstrating the issue:**

```java
private static final String ABOVE_CORE = "Above-Core";
if (abc.getOm() == 1 && abc.getCore().equals(ABOVE_CORE)) {
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@JJengility very interesting! Thanks for the report!
