### ISSUE TITLE
[java] Java 9 support

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#584]
This issue is merely to track our progress on fully supporting / taking advantage of Java 9, as per https://github.com/pmd/pmd/pull/582#issuecomment-325430511

* [ ] Add new Java version to the [`JavaLanguageModule`](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java)
* [ ] Support [`module-info.java`](http://openjdk.java.net/projects/jigsaw/quick-start) syntax.
* [x] Since we support analyzing sources directly from jar-files, we maybe need to improve our code to support [JEP 238: Multi-Release JAR Files](http://openjdk.java.net/jeps/238) (although it might just work - but some classes might be duplicated then and confuse typeresolution and metrics...).
* [ ] Support language changes introduced on [JEP 213: Milling Project Coin](http://openjdk.java.net/jeps/213) (private interface methods, `_` is an illegal identifier)
* [x] Have Travis build and run on JDK 9
* [x] Check for other changes on [Java Release Page](http://docs.oracle.com/javase/9/language/toc.htm)
* [ ] Use [JEP 236: Parser API for Nashorn](http://openjdk.java.net/jeps/236) when available instead of Rhino (non-critical for JDK 9 release)

**Comment by adangel** [comment]
I'm ticking off the Multi-Release JAR files point: I believe, we don't need to change there anything. These Multi-Release JAR files contain the compiled class-files - so this is not relevant to how we load the source files, we want to analyze.
It might be relevant to the auxclasspath feature. However, we depend on URLClassLoader, and this one has been adjusted, to see only one of the possible variants of a class. And which one is chosen, depends on the current java runtime. This means, we won't have problems with duplicated classes. 
However, PMD's results might vary depending on the java runtime it is used. One workaround would be, to run PMD multiple times and compare the results. It's easy, if the goal is, to have no violations - then you'll need to make sure, to have no violations, if you analyze your project with PMD running java8 and java9...

**Comment by Fernal73** [comment]
Is Java 9 not supported yet? 

Running PMD version 6.15.0 on a Project marked Java9 through the PMD ANT TASK produces the following output:

pmd:
      [pmd] Jun 10, 2019 1:31:24 PM net.sourceforge.pmd.cache.FileAnalysisCache loadFromFile
      [pmd] INFO: Analysis cache loaded

BUILD FAILED
/data/data/com.termux/files/home/LearnJava/Cleaner/build.xml:112: The following language is not supported:<sourceLanguage name="java" version="1.9" />.

Total time: 4 seconds                             @l

**Comment by Fernal73** [comment]
The Java project with its build file is located at:  https://github.com/Fernal73/LearnJava/tree/master/Cleaner

**Comment by Fernal73** [comment]
I also receive the following warning message while running the Java Ant Task:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sourceforge.pmd.ant.Formatter (file:/data/data/com.termux/files/home/LearnJava/lib/pmd-core-6.15.0.jar) to field java.io.Console.cs
WARNING: Please consider reporting this to the maintainers of net.sourceforge.pmd.ant.Formatter     WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release.

I'm running Ant against an Open Jdk 1.10 version on Arch Linux on Termux.

**Comment by oowekyala** [comment]
@Fernal73 Your `version` has the value `1.9`, although the version number we use for Java 9 is `9`

https://github.com/Fernal73/LearnJava/blob/9c6a254b53384fc1fc790dd176099beaf8fe6667/Cleaner/build.xml#L113

https://github.com/Fernal73/LearnJava/blob/9c6a254b53384fc1fc790dd176099beaf8fe6667/Cleaner/build.properties#L6

https://pmd.github.io/pmd-6.15.0/pmd_userdocs_tools_ant.html#language-version-selection

I'll open another ticket for the reflective access

**Comment by Fernal73** [comment]
It should accept both forms. If I'm not mistaken, the Java compiler accepts
both versions.

**Comment by Fernal73** [comment]
Unless PMD has decided to follow only the following versioning scheme:

https://blogs.oracle.com/java-platform-group/a-new-jdk-9-version-string-scheme

And what do you think of this?

https://jaxenter.com/java-9-version-numbering-scheme-137544.html

Thanks for the links. I did look at the document but I was under the
impression that it was merely illustrative.
There must be a 'must' attached to the versioning when it's that inflexible.

Thank you very much again.

Regards,
Linus.

**Comment by oowekyala** [comment]
@Fernal73 You have a point, I opened #1861 to track that

**Comment by Fernal73** [comment]
Thank you.

**Comment by Fernal73** [comment]
You might want to add this to your ticket for reflective access.
https://dzone.com/articles/java-19-reflection-and-package-access-changes

Regards,
Linus.
