### ISSUE TITLE
[ui] RFC: new rule designer

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#599]
For a while I've been frustrated with the current rule designer, so I made another with JavaFX 8.

It's still WIP in [this branch](https://github.com/oowekyala/pmd/tree/fx-designer), but I think it's nice enough to show you. It has most of the features of the current designer, with a few things (copy xml to clipboard, display scope hierarchy) not yet done.

The main class is [`n.s.pmd.util.fxdesigner.Designer`](https://github.com/oowekyala/pmd/blob/fx-designer/pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/Designer.java), all the code is in `pmd-ui` and needs a Java 8 runtime.

I think, the design is scalable enough that we could use it as a base for a more complete UI, if you're interested. For example, a ruleset editor, or even a full-on PMD GUI.

Here are some features I've thought about which I think could be nice:
* Rule debugger/ analyser:
  * Select any rule and evaluate it on the code snippet, displaying violations
  * Load the source from a file on filesystem
  * Highlight the nodes that trigger an exception, to spot errors more easily
  * Discriminate exceptions during typeres, symbol table, and other execution phases
  * Export code in the `test-code` xml format
* Edit Java rules (maybe just let the user specify a path to the java file so that they can edit it in their IDE, and let them evaluate the rule on the snippet)
* Display metric values for relevant nodes **(edit: that's done)**
* Focus the AST node in the treeView from the source
* Syntax highlighting in the editor area **(edit: that's done for Java, still WIP for the rest)**. I use a custom code area control from [RichTextFX](https://github.com/TomasMikula/RichTextFX), that allows to style spans of text with CSS. Syntax highlighting may be done easily after some reengineering of the control's API (it sucks). Improving the API will anyway be necessary to highlight failure nodes for the debugger feature
* Specific logo for the app (maybe just the "P" with the gun?). I currently use the full logo that's on our site
* ...?

What do you think?

**Comment by jsotuyod** [comment]
@oowekyala any chance to include screenshots?

I'll try to review this over the weekend, will depend on how much spare time I manage to have.

**Comment by oowekyala** [comment]
@jsotuyod Sure! Here's a demo:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24524930/30125838-133a2c98-933a-11e7-93df-be0fd561e883.gif)

**Comment by jsotuyod** [comment]
@oowekyala that looks beautiful!

**Comment by oowekyala** [comment]
@jsotuyod thanks! It's one of the main reasons I wanted a change :)

**Comment by oowekyala** [comment]
The current version looks like so:
![ezgif com-crop](https://user-images.githubusercontent.com/24524930/31623781-d8af9546-b2a0-11e7-9d1b-e830bb79067d.gif)

Some features are still WIP, but overall it's usable. There are a few limitations however:
* It doesn't run on a java 9 runtime, due to the code area component. From what I've seen support for Java 9 [is a matter of weeks](https://github.com/FXMisc/RichTextFX/issues/270)
* I couldn't make it compile for java 8 with a java 9 sdk. The problem is that java 9 ships JavaFX in a separate jigsaw module, whereas java 8 has javafx on the classpath by default. For now I use a java 8 toolchain to build the module. An alternative would be nice if you can think of one, ideally we could make it work on both java 8 and 9 when RichTextFX is ported to Java 9

I've packaged a fat jar for you to try it, [available here](https://we.tl/GAv9qL4jZd) ^^ Don't forget to use a java 8 runtime ;)

**Comment by jsotuyod** [comment]
@oowekyala this just keeps getting better! This seems like a huge step forward from our current designer.

I think once a java 9 compatible version is ready, you should submit a first PR. In it's current form it is probably already as feature complete as the old designer, plus it will be easier to review before it keeps getting larger.

**Comment by oowekyala** [comment]
Closing this, discussions can move to #714, #711 and future PRs
