### ISSUE TITLE
[core] Incremental analysis should detect changes to jars in classpath

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#604]
Follow up on https://github.com/gradle/gradle/issues/2862

We currently only check for changes in the classpath (order and elements in it), but not the referenced jars themselves.

This should be easy enough to fix.

**Comment by jsotuyod** [comment]
FYI @blindpirate - PR submitted for 6.0.0

**Comment by blindpirate** [comment]
Thanks for the follow-up!
