### ISSUE TITLE
[core] Add DEBUG log when applying incremental analysis

### ISSUE THREAD

**Issue by blindpirate** [pmd/pmd#608]
It seems that no debug message is outputted when running incremental analysis. When I run pmd 5.8.1 with incremental analysis on and log level debug, I always receive message `Processing file xxxx` in every pmd analysis process. It's outputted [here](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/ant/internal/PMDTaskImpl.java#L160) . There's no debug information at all when cache hit or miss [here](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java#L92). 

From log, I can't learn whether the incremental analysis is done or not.

**Comment by jsotuyod** [comment]
@blindpirate PR #614 has been submitted to address this among other concerns.

Let me know if for some reason you still think it's not enough / we are missing visibility.

**Comment by blindpirate** [comment]
Thanks!
