### ISSUE TITLE
[core] Incremental Analysis doesn't close file correctly on Windows upon a cache hit

### ISSUE THREAD

**Issue by blindpirate** [pmd/pmd#618]
Hi I'm a developer of Gradle and recently I found there might be some issue in pmd plugin. If I turn on the incremental analysis, some files wouldn't be closed correctly on Windows .

To reproduce it, you should have a windows machine. Mine is Windows 7. Here're the steps:

- checkout `blindpirate/pmd-issue` branch of https://github.com/gradle/gradle
- run `./gradlew codeQuality:integTest --tests '*WithIA*'`, this will run the [`WithIA.groovy`](https://github.com/gradle/gradle/blob/ad6e6860093a998dc8e3eabad7e3fd9671af0b57/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/WithIA.groovy), two simple tests with incremental analysis on. And it results in the error:

```
java.io.IOException: Unable to delete file: C:\tcagent1\work\6031ced305d8bea4\subprojects\code-quality\build\tmp\test files\PmdPluginIncrementalAnalysisIntegrationTest\incremental_analysi...e_enabled\p9laj\src\main\java\org\gradle\GoodClass.java
```

Looks like some files are not closed correctly, so the cleanup failed. As a comparison, you can run `./gradlew codeQuality:integTest --tests '*WithoutIA*'`, this will run the [`WithoutIA.groovy`](https://github.com/gradle/gradle/blob/ad6e6860093a998dc8e3eabad7e3fd9671af0b57/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/WithoutIA.groovy) and everything works well, the only difference is that this test turn off the incremental analysis.

I'm not familiar with pmd, so I'm here for help, is there any possibility of not closing file correctly?

@jsotuyod Could you help me?

![image](https://user-images.githubusercontent.com/12689835/30382895-f6146b58-98d2-11e7-899f-d7b540359549.png)

**Comment by jsotuyod** [comment]
@blindpirate nice catch!

Definitely our bug, here is the culprit https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/SourceCodeProcessor.java#L92-L105

I'll patch it soon, so you may try with the 6.0.0-SNAPSHOT
