### ISSUE TITLE
[apex] Empty catch block

### ISSUE THREAD

**Issue by JAertgeerts** [pmd/pmd#624]
**Rule Set:** Apex

**Description:** New Rule: `EmptyCatchBlock` support for Apex.

**Code Sample demonstrating the issue:**

```
public void doSomething() {
  ...
  try {
    insert accounts;
  } catch (DmlException dmle) {
    // not good
  }
}
```

**Comment by JAertgeerts** [comment]
Nearly all Java rules in the Empty set could be duplicated and put in action with Apex. I'll open a PR.

**Comment by up2go-rsoesemann** [comment]
I absolutely agree. I simple didn't port them back then because I had not enough time.
