### ISSUE TITLE
[core] Exclude specific files from command line

### ISSUE THREAD

**Issue by rajiff** [pmd/pmd#649]
**Description:**
We run PMD in CI/CD as a command line executable to all the projects in our organisation Repository, so that we are not dependent on Maven 

However from Command line we don't have a way to exclude a specific file/folder pattern

Can we please know a way to achieve this

**Running PMD through:** * [CLI ]*

**Comment by jsotuyod** [comment]
@rajiff just wondering here. You want to ignore some files / packages for the whole ruleset, or just for some specific rules?

**Comment by adangel** [comment]
@rajiff 

Current solution would be, to generate a file list and pass it along with `-filelist` at the command line. See https://pmd.github.io/pmd-5.8.1/usage/running.html . So you would decide on the files, before PMD is started.

Another solution is, using exclude-patterns in the ruleset xml, see https://pmd.github.io/pmd-5.8.1/customizing/howtomakearuleset.html 

Both would exclude the files for all rules....

For the command line, we don't have such a option yet. We would probably need exclude/include flags, which can be mutliple and support [ant-like patterns](https://ant.apache.org/manual/dirtasks.html#patterns).

**Comment by adangel** [comment]
Old sourceforge ticket: https://sourceforge.net/p/pmd/bugs/1229/
and discussion: https://sourceforge.net/p/pmd/discussion/188192/thread/0d97f42f/

**Comment by darakian** [comment]
This is still a desired feature :)

**Comment by darakian** [comment]
PR submitted
https://github.com/pmd/pmd/pull/1407

**Comment by adangel** [comment]
@rajiff The PR by @darakian will add the functionality to provide a list of files, that should be ignored.
If you want to provide just a folder and/or pattern, then please open a new feature request.

**Comment by Fernal73** [comment]
Is there a way to exclude specific files from a specific rule, not the complete rule set?

**Comment by ad-zsolt-imre** [comment]
Would have been nice to be able to do e.g. something like `--exclude *_test.go` so we could easily exclude Golang test files from analysis. (We use PMD to check for duplicated code)
