### ISSUE TITLE
[java] Make AtLeastOneConstructor Lombok-aware

### ISSUE THREAD

**Issue by GiantCrocodile** [pmd/pmd#667]
We already have Lombok-aware rules, but `AtLeastOneConstructor` is currently not among them.

The rule should be extended to consider classes annotated as `@Data`, `@Value`, `@Builder`, `@NoArgsConstructor`, `@RequiredArgsConstructor` and `@AllArgsConstructorAtLeastOneConstructor`

**Comment by adangel** [comment]
Thanks for the suggestion! We have already some limited support for the rules [UnusedPrivateField](https://pmd.github.io/pmd-5.8.1/pmd-java/rules/java/unusedcode.html#UnusedPrivateField), [ImmutableField](https://pmd.github.io/pmd-5.8.1/pmd-java/rules/java/design.html#ImmutableField) and [SingularField](https://pmd.github.io/pmd-5.8.1/pmd-java/rules/java/design.html#SingularField).

For missing constructors, which rule are you referring to? Is it [AtLeastOneConstructor](https://pmd.github.io/pmd-5.8.1/pmd-java/rules/java/controversial.html#AtLeastOneConstructor)? This could be probably extended to be less strict, when Lombok is used.

Are there other rules, you would see, that could benefit from "Lombok-Awareness"?

**Comment by GiantCrocodile** [comment]
Hey @adangel. I think that some specific rules should respect the `@Data` annotation of Lombok and the `@Entity` annotation . Right now I have these warnings in my Lombok models:

- UnusedPrivateField (unlikely with Entity annotation)
- AtLeastOneConstructor (unlikely with Lombok)

These two warnings are very unlikely to be true if they are in a class which has these two annotations.

**Comment by jsotuyod** [comment]
@GiantCrocodile`@Entity` is not a lombok annotation as far as I know... are you referring to `javax.persistence.Entity`?

If so, I'm not sure it would be ok to whitelist it... it simply grants serialization / deserialization from the DB, but no way to access the field in application code / no usage in `hashCode`, `equals`, `toString`... Putting / retrieving stuff from the db when never used in application logic seems unnecessary, and usually points to a dead code issue... I see only 2 reasons to do this:

1. the db is shared with another application that requires that field. A very specific scenario which is better handled by `@SuppressWarning` / an XPath suppression rule.
2. altering the db schema is a costly operation we want to avoid / defer to downtime. Again, an either transient or very specific scenario.

What's your scenario? I may be missing a point here...


As for `@Data`, we should already be handling it, at least for the `UnusedPrivateField`. If so, this is a false-positive we should definitely address.

`AtLeastOneConstructor` should definitely be relaxed to avoid issues with classes annotated as `@Data`, `@Value`, `@Builder`, `@NoArgsConstructor`, `@RequiredArgsConstructor`, `@AllArgsConstructor`

**Comment by GiantCrocodile** [comment]
Yes I mean the `@Entity` annotation you mentioned. Although I suspected it to do more and this is why I mentioned it here too. Honestly I'm not sure where I saw a relation between this entity and Lombok. Maybe because I knew it is used somewhere else but it is impossible to detect that I think. Otherwise you would have to have a logical interpretation of the whole source code to see if this model's variable is used somewhere. Mentioning it wasn't related to any of the two scenarios you thought of.

I agree on the other points you mentioned afterwards. Regarding `UnusedPrivateField`, either this is a false-positive or an outdated rule.

**Comment by jsotuyod** [comment]
@GiantCrocodile I reworked the report according to our discussion.

I'd like to ask you to confirm the `UnusedPrivateField` false positive under PMD 5.8.1, and if so, open a new issue to track it separately. Thanks in advanced.

**Comment by GiantCrocodile** [comment]
@jsotuyod PMD 5.8.1 was released 01-July-2017. I think I'm already using 5.8.1 because when I reported this the version was already out some months. Are you sure you mean 5.8.1 or am I wrong somehow?

**Comment by jsotuyod** [comment]
@GiantCrocodile yes, 5.8.1 is the last release before the upcoming 6.0.0. If you are certain, I'd please ask you to submit a new issue with the code snippet triggering the issue, since it's not being covered by our [current test case](https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/unusedcode/xml/UnusedPrivateField.xml#L469-L541)

**Comment by GiantCrocodile** [comment]
I just noticed that I was wrong. I forgot to put `@Data` annotation above one of my classes and thus violation of rule `UnusedPrivateField` was triggered.

**Comment by jsotuyod** [comment]
@GiantCrocodile it happens! Awesome then, we just need to work on the `AtLeastOneConstructor` rule

**Comment by jsotuyod** [comment]
@GiantCrocodile I don't think so. We are too close to 6.0.0 to change it's scope. But definitely doable for 6.0.1. After 6.0.0 we should return to our one month release cycles.

**Comment by GiantCrocodile** [comment]
Any news on this :)?

**Comment by bke2027** [comment]
@UtilityClass also doesn't quiet the UseUtilityClass rule

**Comment by jsotuyod** [comment]
@bke2027 added #1094 to track that unrelated improvement.

**Comment by jsotuyod** [comment]
@GiantCrocodile this has long been overdue. I've finally submitted a PR to fix this for 6.5.0. Along the way, I found and fixed a couple of FNs.

Please, check it out and provide your feedback.

**Comment by GiantCrocodile** [comment]
Thank you @jsotuyod!
