### ISSUE TITLE
[plsql] Parse error with Cursor For Loop

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#681]
As per https://stackoverflow.com/questions/46883415/error-while-parsing-pkb-file

**Description:**

![image](https://user-images.githubusercontent.com/802626/31904162-d0e259ba-b800-11e7-88b7-e377f0ef001b.png)

**Code Sample demonstrating the issue:**

```
        FOR sum_res IN (SELECT SUM(loss_reserve) loss_reserve,
                               SUM(expense_reserve) exp_reserve
                          FROM gicl_clm_reserve a, gicl_item_peril b
                         WHERE a.claim_id = b.claim_id
                           AND a.item_no  = b.item_no
                           AND a.peril_cd = b.peril_cd
                           AND a.claim_id = p_claim_id
                           AND (NVL(b.close_flag, 'AP') IN ('AP','CC','CP') OR 
                                NVL(b.close_flag2, 'AP') IN ('AP','CC','CP')))
        LOOP
           v_loss_res_amt  := sum_res.loss_reserve;
           v_exp_res_amt   := sum_res.exp_reserve;
        END LOOP;
```

**Running PMD through:** Any

**Comment by jabautista** [comment]
Hi I'm the one who encountered this bug, do you need me to send you the pkb file so you can test it?

**Comment by jsotuyod** [comment]
@jabautista if you can (it's not sensitive) please do so. Thanks

**Comment by jabautista** [comment]
I think it's okay. Here:
[claim_status.zip](https://github.com/pmd/pmd/files/1409192/claim_status.zip)
