### ISSUE TITLE
[javascript] Update Rhino library to 1.7.13

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#699]
For PMD parsing, we use [Rhino](https://github.com/mozilla/rhino). The latest version requires at least Java 8.
Fixing this issue means, we'll need to move the javascript module to the java8-requiring modules (like apex, visualforce, scala).

See also #201 : Note, the grammar is only used for CPD tokenization. We should drop the grammar in favor of Rhino parsing, as long as we can keep the behavior for comment-based suppressions. (see #1039)

**Comment by adangel** [comment]
Actually, it's not required for 6.0.0 - could also go to 6.1.0, since it *should* just be an enhancement...

**Comment by adangel** [comment]
1.7.7.2 is a compatible enhancement/improvement.
But 1.7.8 would be incompatible on the runtime requirements, since it needs a java8 runtime.

@jsotuyod @oowekyala Should we consider a general switch to java8 for PMD 7.0.0? Or we could just add ecmascript to the java8 modules...

**Comment by jsotuyod** [comment]
@adangel having ES use Java 8 should be straight forward...

As for moving up to Java 8 for all PMD...
1. I'd love it (I miss default interface methods when avoiding breaking API changes; as lambdas, streams and Optionals)
2. I'm ok with keeping support for the ~3 latest Java versions, which would be Java 8, 9 and 18.3 once it's released. However, we'd have to check how the adoption for those move forward.... We still see too many people stuck on Java 6.
