### ISSUE TITLE
[core] Relative Path to Path rather than absolut in reports

### ISSUE THREAD

**Issue by mnunezdm** [pmd/pmd#712]
Hi I have a possible enhancement for pmd core

My suggestion is to be able to select to display the relative path in the reports rather than the absolut

for example this is the paths im facing right now

With this launch command

```
bin/run.sh pmd -R rules.xml -f csv -r $WIN_HOME/Desktop/pmd-result.csv -d $WIN_HOME/Proyectos/devops/migrationtool/backup/postToCORE/post
```
Im getting this file output

```
/mnt/c/Users/mnunezdm/Proyectos/devops/migrationtool/backup/postToCORE/post/classes/CaseHistoryController.cls
```
I think that something like this would be much more human readable
```
classes/CaseHistoryController.cls
```

What do you think?
Thanks!

**Comment by jsotuyod** [comment]
@mnunezdm thanks for your feedback, and welcomed!

Have you tried the `-shortnames` parameter? Any reason that wouldn't fit your needs?

**Comment by mnunezdm** [comment]
@jsotuyod that was exactly what i was searching for, sorry!
