### ISSUE TITLE
[java] LinkageError with aux classpath

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#732]
There is one integration test with the maven-pmd-plugin, that fails with PMD 6.0.0: It uses the aux classpath (maven dependency scope test) and should detect a subclass of JUnit's TestCase, which has no test methods.

It seems, we load some classes twice. Error Message:

Could not find class it.TestSupport, due to: java.lang.LinkageError: loader (instance of  net/sourceforge/pmd/util/ClasspathClassLoader): attempted  duplicate class definition for name: "org/custommonkey/xmlunit/XMLTestCase"

Since we couldn't determine the type of TestSupport, we didn't figure out that the class `NoTestsHere` is actually a TestCase, too, and do not report the violation.

**Comment by adangel** [comment]
I've added a test case, see https://github.com/adangel/scratchpad/tree/master/pmd-issue-732

@jsotuyod Could you have a look at this? I have no clue, what's going on... It also seems to be the class XMLTestCase always, I've also seen XMLConstants. It looks like it is related to #680 ...

**Comment by jsotuyod** [comment]
@adangel I'll look into this. Thanks for the scratchpad!

**Comment by jsotuyod** [comment]
Just FYI, I'm making some progress with this.

I've identified the root cause and i'm looking for a fix. In the meantime I've found a race condition on the classloader I've already fixed. I hope to get a PR ready soon.
