### ISSUE TITLE
[core] XPath rules cannot declare multi valued properties

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#735]
XPath rules declare new properties using the `type` attribute,  which can be eg `Boolean` or `Integer`. The corresponding multivalued properties are declared with a `type` attribute like `List<Boolean>` or `List<Integer>`, since the properties refactoring of this summer.

I just realised that `<` and `>` are forbidden characters in xml attributes, so those properties cannot be used lol

I think I'll fix that with a `List[Integer]` and `List[Boolean]` syntax, à la Scala

**Comment by adangel** [comment]
Hm... can't the chars `<` and `>` be used via their entity escapes: `&lt;` and `&gt;` ?

**Comment by oowekyala** [comment]
Actually you're right, there even were tests doing that ^^ It's just slightly inconvenient. I think this issue can be closed then
