### ISSUE TITLE
[java] Prepare for Java 10

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#743]
Java 10 (aka. Java 18.3) is going to introduce the local-variable declaration syntax `var XXX = ...;`

This requires the type of the variable to be inferred from the type of the expression used to initialize it. We will therefore need to heavily work on type resolution to get this fully supported.

Also, this will possibly break a bunch of rules that assume the type of the variable can be found by looking at the declaration. We will be forced to always use type resolution to achieve this.

The full JEP can be found here: http://openjdk.java.net/jeps/286

**Comment by adangel** [comment]
See also https://www.javaspecialists.eu/archive/Issue255.html
