### ISSUE TITLE
[java] JavaOperationSignature's getter detection ignores the `hasXX` boolean getter pattern

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#745]
It also ignores the `isXX` pattern when the field is not named exactly `XX`, though a common pattern is to name boolean fields and their getters the same way, both starting with `is`. The following examples are thus wrongly classified as methods:
```java
    private boolean isBig;
    private boolean hasLegs;

    public boolean isBig() {
        return isBig;
    }
    
    public boolean hasLegs() {
        return hasLegs;
    }
```

**Comment by jsotuyod** [comment]
This class is no longer part of PMD.
