### ISSUE TITLE
[java] The rule SimplifyStartsWith suggests inequivalent code transformation

### ISSUE THREAD

**Issue by dakov** [pmd/pmd#750]
**Rule Set:**
Optimization
**Description:**
The rule SimplifyStartsWith suggest transforming calls to `(string).startsWith` to `(string).charAt(0)`, when a single leading character is being checked.

However, the proposed transformation does not produce equivalent results. 

When the `(string)` is empty, `(string).startsWith` will produce `false` as a result for any comparison, while `(string).charAt(0)` will throw `IndexOutOfBoundsException`.

If intended, it may confuse developers, and it should be at least mentioned in the rule description.

**Code Sample demonstrating the issue:**

```
String s = "Hello";
s.startsWith("H");
>>> true

s.charAt(0) == 'H';
>>> true

s = "";
s.startsWith("H");
>>> false

s.charAt(0) == 'H';
>>> throws IndexOutOfBoundsException
```

**Running PMD through:** *CLI*

**Comment by jsotuyod** [comment]
@dakov thanks for the feedback! You are absolutely right about this one, the correct would be to suggest using `!s.isEmpty() && s.charAt(0) == 'H'`, however, this may not be actually faster than `startsWith` (although it probably is marginally better). I'll try to do some microbenchmarks and see whether it holds, but definitely after 6.0.0 is released.

**Comment by tweimer** [comment]
For the sake of readability, I would always use `s.startsWith("H")` instead of `!s.isEmpty() && s.charAt(0) == 'H'`. The first one is clear and easy to read.

Even if the last one is faster (I doubt), I cannot see a situation where this would actually matter.

**Comment by philci52** [comment]
Have the benchmarks been completed?  If they are slower then startsWith, then I suggest this rule be eliminated as it suggests code that may result in ArrayIndexOutOfBoundsException.  At a very minimum the documentation should be updated to reflect the appropriate replacement code.

**Comment by oowekyala** [comment]
The documentation was updated in #2723, the benchmark part is tracked by #2740. This existing issue was probably overlooked when #1868, a duplicate, was opened.
