### ISSUE TITLE
[xml]How to develope the rule aboul the xml file, not the java file

### ISSUE THREAD

**Issue by kuanrongdelvdou** [pmd/pmd#752]
**Rule Set:**

**Description:** I want to develope a rule that can check the xml's content are fit the rule or not. 

**Code Sample demonstrating the issue:**

```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@kuanrongdelvdou please, refer to the documentation on writing a rule:
* https://pmd.github.io/pmd/pmd_devdocs_writing_pmd_rules.html
* https://pmd.github.io/pmd/pmd_devdocs_writing_xpath_rules.html

You can either write a Java rule, or an XPath expression for any of the supported languages to be analyzed, which of course includes XML. The only difference is the AST structure for each language.

Using the rule designer (as stated on the documentation) is of great usage to getting to better understand the AST structure.

You can also look around at the existing rules for XMLs on PMD by looking at the categories defined here: https://github.com/pmd/pmd/tree/master/pmd-xml/src/main/resources/category

**Comment by kuanrongdelvdou** [comment]
e.g
this is the xlm file bellow i need to check:
<?xml version="1.0" encoding="UTF-8"?>
<bookstore>
<book category="COOKING">
  <title lang="en">Everyday Italian</title>
  <author>Giada De Laurentiis</author>
  <year>2005</year>
  <price>30.00</price>
</book>
</bookstore>
the rule: if the node <year>'s  text value is not equals '2007' then give the error message 
 question: how could write this rule.  first, i need defiend my own rule class that implements the abstract class "AbstractDomXmlRule".right?  then, override the visit() method and write the rule method like 'xmlCheckYear()', right?  .....

**Comment by jsotuyod** [comment]
Yes, or you could use an XPath expression such as this one: https://github.com/pmd/pmd/blob/master/pmd-xml/src/main/resources/category/pom/errorprone.xml#L57-L88

Just check for `//bookstore/book/year/text[@Image != '2007']`

**Comment by kuanrongdelvdou** [comment]
@jsotuyod  could  you give the demo that can run

**Comment by jsotuyod** [comment]
Simply create your custom ruleset such as:

```xml
<?xml version="1.0"?>
<ruleset name="My ad-hoc ruleset"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

    <description>
Rules to enforce my custom rules, gracefully provided by the people from PMD.
    </description>

    <rule name="InvalidYearBooks"
          language="xml"
          message="This book is not from 2007"
          class="net.sourceforge.pmd.lang.rule.XPathRule">
        <description>
We just want books from 2007.
        </description>
        <priority>3</priority>
        <properties>
            <property name="xpath">
                <value>
<![CDATA[
//bookstore/book/year/text[@Image != '2007']
]]>
                </value>
            </property>
        </properties>
    </rule>
```

And give that to PMD to run.

I'm closing this issue as it's not an issue, questions should be directed at stackoverflow under the PMD tag.
