### ISSUE TITLE
[apex] Replace old Jorje parser with new one

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#766]
As discussed in https://github.com/pmd/pmd/issues/677 and confirmed by Salesforce employees the Jorje parser we are using is a dead end road:

> The version of Jorje that is packaged with Force.com IDE will not be updated. 

But, the one for VS Code is constantly updated at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out. This is because, moving forward, our flagship IDE is shifting from Eclipse to VS Code. The jar at https://github.com/forcedotcom/salesforcedx-vscode/tree/develop/packages/salesforcedx-vscode-apex/out is a über jar with all the dependencies packaged. 

As Salesforce recently released new Apex language features that user want to use and parse via PMD (like Switch statements) we should replace the old Uber jar with the new one.

@adangel @jsotuyod  Is this something which can be done easily with your recent changes to the packaging of the parser?

**Comment by jsotuyod** [comment]
@up2go-rsoesemann switching the dependency is trivial, however we should see how much things break between jorje versions (the last update had it's share of breaks in the grammar).

We can probably leave out updating the rules to these new language constructs for 6.1.0; but just getting the build to pass with a new jorje version is hard to estimate. Hopefully it win't be too hard and we can get it to 6.0.0

**Comment by adangel** [comment]
@jsotuyod I'll give it a try. Depending on what the content of the uber-jar is, it might be easier or harder :)
