### ISSUE TITLE
[doc] Wrong information in the Release Notes about the Security ruleset

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#782]
**Affects Version:** 6.0.0

In the [Release Notes](https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html#rule-categories) it is mentioned that one of the new categories is `Security`. However, using `<rule ref="category/java/security.xml"/>` gives a `The RuleSet category/java/security.xml has been deprecated.` warning. I guess the release notes are wrong because I can't see `Security` in other places in the documentation also.

**Comment by jsotuyod** [comment]
Thanks for the concern.

The defined categories are global, used for all languages for consistency. However, not all languages have rules under all of these categories, and such is the case of Java and security (apex for instance does have fully understood the security category)

Non the less, the depreciation message is certainly incorrect
