### ISSUE TITLE
pom.xml for Apex only distributions

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#787]
I was starting to upgrade https://github.com/Up2Go/codeclimate-apexmetrics with PMD 6.0.0 when I stumbled over steps required and described in my wiki (https://github.com/Up2Go/codeclimate-apexmetrics/wiki/Replace-PMD-used-by-the-engine).

To keep the CodeClimate engine small we used a simplyfied pom.xml that only builds the artefacts related to Apex and Visualforce. I tried to strip down the 6.0.0 pom.xml but failed as it contains new elements that I don't fully understand.

It would be great if @adangel or @jsotuyod could provide me we an updated version. Besides that any changes to the build process?

**Comment by adangel** [comment]
See https://github.com/adangel/scratchpad/tree/master/pmd-apex-vf for an example.

**Comment by up2go-rsoesemann** [comment]
Great. Thanks @adangel fot your time having this Skype call and providing this solution. Maybe we can make this an integral part of PMD. Micro distributions for tool providers that just use PMD for a specific language like @SCWells72 from Illuminated Cloud.
