### ISSUE TITLE
[doc] Documentation site reorganisation

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#791]
I think our documentation site could a clearer structure:
* User documentation mixes things about using PMD and trivia about PMD. 
* Developer documentation mixes things about making rules (like we encourage our users to), extending PMD by adding languages/ metrics framework (clearly something not all rue developers are up to), and information for PMD committers (eg making releases), which concerns even less people.

All of that makes it unclear to whom the content of each page is addressed (harder to write), and makes it harder for anyone to find what they're looking for. Specifically, I think we should try to address separately different types of readers, and reflect that in the structure:
* Users who only want configuration (understanding rulesets, making their own, using properties)
* Users who want extensibility (writing XPath and Java rules, defining properties, testing rules). These one don't necessarily want to know about building PMD from source or our Checkstyle guidelines, unlike...
* Users who'd like to contribute to PMD (they should find info about PR-making interesting). Again, not all of them would like to know about adding a whole new language, but some would.
* PMD committers, who're probably the only ones interested in technical info about merging PRs or releasing 

In comparison, I find [Checkstyle's website](http://checkstyle.sourceforge.net/license.html) is really well organised and easy to navigate. Taking that into account, I propose the following reorganisation of the existing documentation pages. Please leave comments ;)

#### About

* Userdoc/Introduction
* Userdoc/Release notes
* Userdoc/Getting help

#### User documentation

* Userdoc/Getting started
* Userdoc/Understanding rulesets
* Devdoc/Making rulesets
* Userdoc/Best practises
* Devdoc/{Working with properties (first half) => Using properties}
* Userdoc/{Suppressing => Suppressing warnings}
* Extending PMD (softcore) // Custom rule making
    * Understanding the AST // doesn't exist yet
    * Devdoc/Writing XPath rules
    * Devdoc/Writing a rule 
    * Devdoc/{Working with properties (second half) => Defining properties}
    * Devdoc/Using code metrics
    * Devdoc/Rule guidelines
    * Devdoc/Test framework
* Userdoc/Copy-paste detection
* Userdoc/Tools + integrations
    * Maven PMD plugin
    * Ant
    * Other tools
    
#### Developer documentation // specifically oriented toward contribution

* Devdoc/Developer resources
* Devdoc/Setting up your IDE // merge with devdoc/Building PMD from source  
* Devdoc/{Pull requests (half about making PRs) => Contributing} // merge with devdoc/Code style
* Devdoc/How PMD works (merge with Devdoc/Architecture)
* Extending PMD (hardcore)
    * Devdoc/Adding a new language
    * Devdoc/Adding a new CPD language
    * Devdoc/Adding metrics support to a language
* Devdoc/Roadmap
  
#### Project documentation

* General information
    * Trivia about PMD
      * Userdoc/PMD in the press
      * Userdoc/Products + books
      * Userdoc/Similar projects
      * Userdoc/What does PMD mean?
    * Userdoc/Credits
    * Userdoc/License
    * Userdoc/Old release notes
* Project management // info for committers mainly
    * Devdoc/{Pull requests (part about merging) => Merging PRs}
    * Devdoc/Releasing

**Comment by jsotuyod** [comment]
@oowekyala I think you make an excelente point. I totally support this.

I think the new site was a huge step forward, and we improved and updated a lot of content (even if there still plenty of old stuff in there still); but we can certainly make it more accessible to new users with your suggestions.

Feel free to tackle this.

**Comment by oowekyala** [comment]
@jsotuyod Thanks for your support! I'll probably have time for it next week

**Comment by adangel** [comment]
@oowekyala Great work! Sorry, just came around to have look at this. This new structure totally makes sense.
