### ISSUE TITLE
[doc] Broken documentation links for 6.0.0

### ISSUE THREAD

**Issue by lgoldstein** [pmd/pmd#794]
When navigating to `https://pmd.github.io/pmd/pmd_userdocs_getting_started.html#incremental-analysis` there are supposedly links to [Maven](https://pmd.github.io/pmd_userdocs_tools_maven.html) and/or [Ant](https://pmd.github.io/pmd_userdocs_tools_ant.html) specific documentation - specifically the [Enabling Incremental Analysis](https://pmd.github.io/pmd/pmd_userdocs_getting_started.html#enabling-incremental-analysis) section. These links are broken - as can be easily ascertained by trying to click on their respective links in this issue.

In this context, I have not found any mention of the capability to activate the caching feature (as specified in the incremental analysis) in the [Maven PMD plugin documentation](https://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html)

**Comment by jsotuyod** [comment]
Thanks for the report! I'll get these fixed ASAP. In the meantime, to enable incremental analysis, you need to tell PMD where to cache results for the analysis. Ant uses the `cacheLocation` attribute on the `<pmd>` node to enable incremental analysis. Maven uses the [`analysisCacheLocation`](https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html#analysisCacheLocation) config element.

**Comment by adangel** [comment]
@jsotuyod FYI - currently the link points to the github pages build by github from the master branch. We could construct a link to the specific version (https://pmd.github.org/pmd-6.0.0/pmd_userdocs_getting_started.html#incremental-analysis) at runtime using `PMD.VERSION`.

**Comment by lgoldstein** [comment]
@jsotuyod FYI the link you sent to the _analysisConfigLocation_ seems wrong - it points to _https_ whereas the page is accessible as _http_
