### ISSUE TITLE
[cpd] java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by cyw3** [pmd/pmd#795]
bin/run.sh cpd --minimum-tokens 120 --format csv_with_linecount_per_file --encoding utf-8 --ignore-literals --ignore-annotations --ignore-usings --skip-duplicate-files --skip-lexical-errors --failOnViolation false --files path/to/project --language cpp

![image](https://user-images.githubusercontent.com/11549103/34208777-9dc8c54e-e5ca-11e7-848e-4aa60144892a.png)

**Comment by jsotuyod** [comment]
@cyw3 thanks for the report, this is unfortunately a known issue (see https://github.com/pmd/pmd/issues/185#issuecomment-273597773). We have a pending issue to refactor report rendering for CPD.

In the meantime, you can try increasing the heap space CPD has available.

**Comment by cyw3** [comment]
I have set JAVA_OPTIONS="-Xms32m -Xmx6512m", but it is not ok.

**Comment by cyw3** [comment]
@jsotuyod 
I fixed the bug.

**Comment by jsotuyod** [comment]
@cyw3 I've just submitted a PR fixing this for good. Should be part of PMD 6.1.0
