### ISSUE TITLE
PMD 6.0.0 configuration warnings / deprecations with 5.8.1 config

### ISSUE THREAD

**Issue by vanniktech** [pmd/pmd#805]
Congrats on getting 6.0.0 out of the door. 🎉 

I'm a bit at loss with the new documentation and all of the deprecation warnings.

With PMD 5.8.1 I was able to use this configuration file:

```xml
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Android Application Rules"
 xmlns="http://pmd.sf.net/ruleset/1.0.0"
 xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd"
 xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd">
   <description>PMD Ruleset</description>

   <exclude-pattern>.*/R.java</exclude-pattern>
   <exclude-pattern>.*/R2.java</exclude-pattern>
   <exclude-pattern>.*/gen/.*</exclude-pattern>

   <rule ref="rulesets/java/coupling.xml">
    <exclude name="LawOfDemeter"/>
    <exclude name="ExcessiveImports"/>
    <exclude name="LoosePackageCoupling"/>
  </rule>
  <rule ref="rulesets/java/design.xml">
    <exclude name="AbstractClassWithoutAbstractMethod"/>
    <exclude name="EmptyMethodInAbstractClassShouldBeAbstract"/>
    <exclude name="UseVarargs"/>
    <exclude name="UseUtilityClass"/>
    <exclude name="ConfusingTernary"/>
    <exclude name="UseCollectionIsEmpty"/>
    <exclude name="TooFewBranchesForASwitchStatement"/>
    <exclude name="FieldDeclarationsShouldBeAtStartOfClass"/>
    <exclude name="AvoidProtectedFieldInFinalClass"/>
    <exclude name="ReturnEmptyArrayRatherThanNull"/>
  </rule>
  <rule ref="rulesets/java/empty.xml"/>
  <rule ref="rulesets/java/naming.xml">
    <exclude name="ShortMethodName"/>
    <exclude name="ShortVariable"/>
    <exclude name="AvoidFieldNameMatchingTypeName"/>
    <exclude name="AvoidFieldNameMatchingMethodName"/>
    <exclude name="LongVariable"/>
    <exclude name="ShortClassName"/>
    <exclude name="AbstractNaming"/>
  </rule>
  <rule ref="rulesets/java/junit.xml">
    <exclude name="JUnitTestsShouldIncludeAssert"/>
    <exclude name="JUnitAssertionsShouldIncludeMessage"/>
    <exclude name="JUnitTestContainsTooManyAsserts"/>
  </rule>
  <rule ref="rulesets/java/migrating.xml"/>
  <rule ref="rulesets/java/strictexception.xml">
    <exclude name="AvoidThrowingNullPointerException"/>
    <exclude name="AvoidThrowingRawExceptionTypes"/>
    <exclude name="AvoidCatchingGenericException"/>
  </rule>
  <rule ref="rulesets/java/unnecessary.xml"/>
  <rule ref="rulesets/java/unusedcode.xml"/>
  <rule ref="rulesets/java/optimizations.xml">
    <exclude name="AvoidInstantiatingObjectsInLoops"/>
  </rule>
  <rule ref="rulesets/java/typeresolution.xml"/>
  <rule ref="rulesets/java/android.xml"/>
  <rule ref="rulesets/java/clone.xml"/>
  <rule ref="rulesets/java/finalizers.xml"/>
  <rule ref="rulesets/java/imports.xml">
    <exclude name="TooManyStaticImports"/>
  </rule>
  <rule ref="rulesets/java/logging-java.xml">
    <exclude name="LoggerIsNotStaticFinal"/>
  </rule>
  <rule ref="rulesets/java/braces.xml"/>
  <rule ref="rulesets/java/sunsecure.xml"/>
  <rule ref="rulesets/java/strings.xml">
    <exclude name="AvoidDuplicateLiterals"/>
  </rule>
  <rule ref="rulesets/java/basic.xml"/>

  <rule ref="rulesets/java/design.xml/AvoidDeeplyNestedIfStmts">
    <properties>
      <property name="problemDepth" value="3"/>
    </properties>
  </rule>
</ruleset>
</details>
```

Now when I update to PMD 6.0.0, I'm getting these warnings:

```
The RuleSet rulesets/java/coupling.xml has been deprecated.
The RuleSet rulesets/java/coupling.xml has been deprecated.
The RuleSet rulesets/java/design.xml has been deprecated.
The RuleSet rulesets/java/design.xml has been deprecated.
The RuleSet rulesets/java/empty.xml has been deprecated.
The RuleSet rulesets/java/empty.xml has been deprecated.
The RuleSet rulesets/java/naming.xml has been deprecated.
The RuleSet rulesets/java/naming.xml has been deprecated.
The RuleSet rulesets/java/junit.xml has been deprecated.
The RuleSet rulesets/java/junit.xml has been deprecated.
The RuleSet rulesets/java/migrating.xml has been deprecated.
The RuleSet rulesets/java/migrating.xml has been deprecated.
The RuleSet rulesets/java/strictexception.xml has been deprecated.
The RuleSet rulesets/java/strictexception.xml has been deprecated.
The RuleSet rulesets/java/unnecessary.xml has been deprecated.
The RuleSet rulesets/java/unnecessary.xml has been deprecated.
The RuleSet rulesets/java/unusedcode.xml has been deprecated.
The RuleSet rulesets/java/unusedcode.xml has been deprecated.
The RuleSet rulesets/java/optimizations.xml has been deprecated.
The RuleSet rulesets/java/optimizations.xml has been deprecated.
Use Rule name category/java/bestpractices.xml/LooseCoupling instead of the deprecated Rule name rulesets/java/coupling.xml/LooseCoupling. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/bestpractices.xml/LooseCoupling instead of the deprecated Rule name rulesets/java/coupling.xml/LooseCoupling. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/CloneMethodMustImplementCloneable instead of the deprecated Rule name rulesets/java/clone.xml/CloneMethodMustImplementCloneable. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/CloneMethodMustImplementCloneable instead of the deprecated Rule name rulesets/java/clone.xml/CloneMethodMustImplementCloneable. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/bestpractices.xml/UnusedImports instead of the deprecated Rule name rulesets/java/imports.xml/UnusedImports. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/bestpractices.xml/UnusedImports instead of the deprecated Rule name rulesets/java/imports.xml/UnusedImports. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/design.xml/SignatureDeclareThrowsException instead of the deprecated Rule name rulesets/java/strictexception.xml/SignatureDeclareThrowsException. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/design.xml/SignatureDeclareThrowsException instead of the deprecated Rule name rulesets/java/strictexception.xml/SignatureDeclareThrowsException. Future versions of PMD will remove support for this deprecated Rule name usage.
The RuleSet rulesets/java/typeresolution.xml has been deprecated.
The RuleSet rulesets/java/typeresolution.xml has been deprecated.
The RuleSet rulesets/java/android.xml has been deprecated.
The RuleSet rulesets/java/android.xml has been deprecated.
The RuleSet rulesets/java/clone.xml has been deprecated.
The RuleSet rulesets/java/clone.xml has been deprecated.
The RuleSet rulesets/java/finalizers.xml has been deprecated.
The RuleSet rulesets/java/finalizers.xml has been deprecated.
The RuleSet rulesets/java/imports.xml has been deprecated.
The RuleSet rulesets/java/imports.xml has been deprecated.
The RuleSet rulesets/java/logging-java.xml has been deprecated.
The RuleSet rulesets/java/logging-java.xml has been deprecated.
The RuleSet rulesets/java/braces.xml has been deprecated.
The RuleSet rulesets/java/braces.xml has been deprecated.
The RuleSet rulesets/java/sunsecure.xml has been deprecated.
The RuleSet rulesets/java/sunsecure.xml has been deprecated.
The RuleSet rulesets/java/strings.xml has been deprecated.
The RuleSet rulesets/java/strings.xml has been deprecated.
The RuleSet rulesets/java/basic.xml has been deprecated.
The RuleSet rulesets/java/basic.xml has been deprecated.
Use Rule name category/java/design.xml/AvoidDeeplyNestedIfStmts instead of the deprecated Rule name rulesets/java/design.xml/AvoidDeeplyNestedIfStmts. Future versions of PMD will remove support for this deprecated Rule name usage.
Use Rule name category/java/design.xml/AvoidDeeplyNestedIfStmts instead of the deprecated Rule name rulesets/java/design.xml/AvoidDeeplyNestedIfStmts. Future versions of PMD will remove support for this deprecated Rule name usage.
The RuleSet rulesets/java/coupling.xml has been deprecated.
The RuleSet rulesets/java/coupling.xml has been deprecated.
The RuleSet rulesets/java/design.xml has been deprecated.
The RuleSet rulesets/java/design.xml has been deprecated.
The RuleSet rulesets/java/empty.xml has been deprecated.
The RuleSet rulesets/java/empty.xml has been deprecated.
The RuleSet rulesets/java/naming.xml has been deprecated.
The RuleSet rulesets/java/naming.xml has been deprecated.
The RuleSet rulesets/java/junit.xml has been deprecated.
The RuleSet rulesets/java/junit.xml has been deprecated.
The RuleSet rulesets/java/migrating.xml has been deprecated.
The RuleSet rulesets/java/migrating.xml has been deprecated.
The RuleSet rulesets/java/strictexception.xml has been deprecated.
The RuleSet rulesets/java/strictexception.xml has been deprecated.
The RuleSet rulesets/java/unnecessary.xml has been deprecated.
The RuleSet rulesets/java/unnecessary.xml has been deprecated.
The RuleSet rulesets/java/unusedcode.xml has been deprecated.
The RuleSet rulesets/java/unusedcode.xml has been deprecated.
The RuleSet rulesets/java/optimizations.xml has been deprecated.
The RuleSet rulesets/java/optimizations.xml has been deprecated.
The RuleSet rulesets/java/typeresolution.xml has been deprecated.
The RuleSet rulesets/java/typeresolution.xml has been deprecated.
The RuleSet rulesets/java/android.xml has been deprecated.
The RuleSet rulesets/java/android.xml has been deprecated.
The RuleSet rulesets/java/clone.xml has been deprecated.
The RuleSet rulesets/java/clone.xml has been deprecated.
The RuleSet rulesets/java/finalizers.xml has been deprecated.
The RuleSet rulesets/java/finalizers.xml has been deprecated.
The RuleSet rulesets/java/imports.xml has been deprecated.
The RuleSet rulesets/java/imports.xml has been deprecated.
The RuleSet rulesets/java/logging-java.xml has been deprecated.
The RuleSet rulesets/java/logging-java.xml has been deprecated.
The RuleSet rulesets/java/braces.xml has been deprecated.
The RuleSet rulesets/java/braces.xml has been deprecated.
The RuleSet rulesets/java/sunsecure.xml has been deprecated.
The RuleSet rulesets/java/sunsecure.xml has been deprecated.
The RuleSet rulesets/java/strings.xml has been deprecated.
The RuleSet rulesets/java/strings.xml has been deprecated.
The RuleSet rulesets/java/basic.xml has been deprecated.
The RuleSet rulesets/java/basic.xml has been deprecated.
```

I'm having a hard time believing that there's no replacement for all of those rules. Is there anything I'm missing?

**Comment by jsotuyod** [comment]
@vanniktech in PMD 6.0.0 all rules have been reorganized into 8 standard categories. No rule has been dropped without a proper replacement.

The messages may be a it confusing, but that's to be expected. When you refer to a complete ruleset, such as `rulesets/java/braces.xml`, there is no one-line replacement. The rules that used to be there have been split among the different categories.

For single rules on the other hand, we can easily tell you exactly where the rule is located now, as is the case for `rulesets/java/design.xml/AvoidDeeplyNestedIfStmts`

You can check where each rule was moved to by having a look at the definitions for:
 * [`android`](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/android.xml)
 * [`basic`](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/basic.xml)
 * [`braces`](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/braces.xml)
 * etc. (just check the corresponding file here: https://github.com/pmd/pmd/tree/master/pmd-java/src/main/resources/rulesets/java

For more info on rule categories, please check the release notes: https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html#rule-categories


@adangel maybe for 6.0.1 we should consider logging deprecation warnings when loading each rule of a deprecated ruleset?

**Comment by vanniktech** [comment]
That makes sense. Is there any way I can tell PMD to activate all rules by default and then only exclude certain rules? That might make the configuration on my part easier. Or even doing so on a category base would be easier.

**Comment by adangel** [comment]
@vanniktech We have no single ruleset yet, that includes all rules. But you can use the categories like rulesets before (technically they are just rulesets):

```
<rule ref="category/java/bestpractices.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/codestyle.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/design.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/documentation.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/errorprone.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/multithreading.xml">
    <exclude name="..." />
</rule>
<rule ref="category/java/performance.xml">
    <exclude name="..." />
</rule>
```

@jsotuyod Yes, that would be probably helpful, if we log out the new rule locations.

**Comment by vanniktech** [comment]
Interestingly I get an exception when wanting to use those new categories:

```
> Can't find resource 'category/java/bestpractices.xml' for rule 'null'.  Make sure the resource is a valid file or URL and is on the CLASSPATH. Here's the current classpath: /Users/nik/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4/lib/gradle-launcher-4.4.jar
```

**Comment by jsotuyod** [comment]
@vanniktech sorry for the delay, but I can't reproduce it. PMD 6.0.0 running through Gradle 4.4 with a ruleset referring to a whole java category.

Can you share your current configuration?

**Comment by vanniktech** [comment]
Huh. Seems like it might be a Gradle Daemon issue. It works now. Thanks for all the help. I'll leave it up to you whether you want this issue open or not.

**Comment by TWiStErRob** [comment]
@jsotuyod I think instead of individual deprecations you should put all this info in this issue into a Migration Guide 5 &rarr; 6 document and put a link as into the `"The RuleSet " + ref + " has been deprecated."` line.

Even if there's only a rough equivalence mapping from `ruleset/*` to `category/*` it's a good starting point for upgraders.

Alternatively: count the deprecation warnings and if it's more than some, log the link.

**Comment by asarkar** [comment]
I've the same problem after upgrading PMD, and after reading the conversation here, feel like the answer from the PMD team "the rules have been moved somewhere, go find it" flippant and seriously inadequate. I can see all the java/basic rules are deprecated, but nothing tells me where I can find the new ones. Why can't PMD tell me at build time, or at least, files like [this](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/basic.xml) adequately commented?

**Comment by jsotuyod** [comment]
@asakar thanks for your concern and be welcomed.

I fear however that you may have misread this conversation. We are actually discussing alternatives to have PMD log for each rule where it has been moved, even if referenced by whole ruleset. Other ideas such as migration guides have also been proposed. We will certainly keep working on this / easier migrations before 7.0.0 where deprecated things in 6 will stop working (unsurprisingly, this issue remains open, as it's still unaddressed). Everyone will have plenty of time to migrate before things stop working, and you can still safely use the latest PMD while you do.

As for comments on files such as the one you cite, they are redundant. The `ref` attribute on that file tells you exactly where the rule is currently located.

Constructive feedback and ideas are always welcomed.

**Comment by TWiStErRob** [comment]
Actually I just understood what @jsotuyod (PMD) is saying, the file he and @asarkar linked contain all the info we need. Check https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/basic.xml again, and notice that it links to the rules' new locations (good ol' self-documenting code). In our 5.x configs we include `rulesets/java/basic.xml` which used in 6.x will include the relocated rules, and flag them as deprecated. This is why we're receiving all those warnings.

The best migration strategy based on this information is:
 * Leave the old config unaffected for now
 * Copy https://github.com/pmd/pmd/issues/805#issuecomment-353777796 into the config (without the `...` so it's a valid file)
 * For each `ruleset/java/foo.xml/RuleName` reference (be it `<exclude name` or `<rule ref` override)
   * open `foo.xml` in https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/
   * find `RuleName` and observe its `category/`
   * replace `ruleset/java/foo.xml` with `category/java/bar.xml`  
     for `exclude`s this may involve moving the `<exclude` tag to within another `<rule ref="category/` block

@jsotuyod @adangel this sounds like something that could be automated.

**Comment by jsotuyod** [comment]
@TWiStErRob that's exactly what I meant!

Your approach seems to be valid as for output on PMD 6.0.0 specifically, but not necessarily the best practice. Referencing a whole category / ruleset + excludes may be shorter when including lots of rules, but produces unexpected changes when updating PMD, as new rules in those categories / ruleset are automatically included, which can trigger situations such as #847 

The best approach would be to expand all ruleset references and include all rules independently. Users are encouraged to go over the [new rules](https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html#new-rules), [modified rules](https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html#modified-rules) and [deprecated rules](https://pmd.github.io/pmd-6.0.0/pmd_release_notes.html#deprecated-rules) of the release notes and look for improvements to their rulesets as part of the PMD upgrade. This is equivalent to what other tools such as Checkstyle do (all new rules are disabled by default, you would need to add them explicitly and manually).

We have ideas for a visual rule designer at some point in the future, which along with the quickstart rulesets will make this process easier, but given que nature of some of the rules, I don't think we can ever do something sane in an automatic way.

**Comment by asarkar** [comment]
I have created a migration tool to help other poor souls. It is available here: https://github.com/asarkar/pmd-migration-tool. A sample run looks as follows:

Input file

```
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         name="ruleset"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
    <description>This ruleset checks my code for bad stuff</description>
    <rule ref="rulesets/java/basic.xml"/>
    <rule ref="rulesets/java/braces.xml"/>
    <rule ref="rulesets/java/clone.xml"/>
    <rule ref="rulesets/java/codesize.xml"/>
    <rule ref="rulesets/java/controversial.xml">
        <exclude name="OnlyOneReturn"/>
        <exclude name="DefaultPackage"/>
        <exclude name="AvoidLiteralsInIfCondition"/>
        <exclude name="AtLeastOneConstructor"/>
        <exclude name="NullAssignment"/>
    </rule>
    <rule ref="rulesets/java/coupling.xml">
        <exclude name="LoosePackageCoupling"/>
        <exclude name="LawOfDemeter"/>
    </rule>
    <rule ref="rulesets/java/design.xml">
        <exclude name="UncommentedEmptyConstructor"/>
    </rule>
    <rule ref="rulesets/java/empty.xml"/>
    <rule ref="rulesets/java/finalizers.xml"/>
    <rule ref="rulesets/java/imports.xml">
        <exclude name="TooManyStaticImports"/>
    </rule>
    <rule ref="rulesets/java/imports.xml/TooManyStaticImports">
        <properties>
            <property name="maximumStaticImports" value="25"/>
        </properties>
    </rule>
    <rule ref="rulesets/java/j2ee.xml"/>
    <rule ref="rulesets/java/javabeans.xml">
        <exclude name="BeanMembersShouldSerialize"/>
    </rule>
    <rule ref="rulesets/java/junit.xml"/>
    <rule ref="rulesets/java/naming.xml">
        <exclude name="AvoidDollarSigns"/>
        <exclude name="ShortVariable"/>
        <exclude name="LongVariable"/>
        <exclude name="AvoidFieldNameMatchingMethodName"/>
    </rule>
    <rule ref="rulesets/java/naming.xml/ShortVariable">
        <properties>
            <property name="minimum" value="1"/>
        </properties>
    </rule>
    <rule ref="rulesets/java/naming.xml/LongVariable">
        <properties>
            <property name="minimum" value="36"/>
        </properties>
    </rule>
    <rule ref="rulesets/java/optimizations.xml">
        <exclude name="MethodArgumentCouldBeFinal"/>
        <exclude name="LocalVariableCouldBeFinal"/>
    </rule>
    <rule ref="rulesets/java/strictexception.xml">
        <exclude name="SignatureDeclareThrowsException"/>
        <exclude name="AvoidCatchingGenericException"/>
        <exclude name="AvoidThrowingRawExceptionTypes"/>
    </rule>
    <rule ref="rulesets/java/strings.xml">
        <exclude name="AvoidDuplicateLiterals"/>
    </rule>
    <rule ref="rulesets/java/strings.xml/AvoidDuplicateLiterals">
        <properties>
            <property name="skipAnnotations" value="true"/>
        </properties>
    </rule>
    <rule ref="rulesets/java/sunsecure.xml"/>
    <rule ref="rulesets/java/typeresolution.xml">
        <exclude name="SignatureDeclareThrowsException"/>
    </rule>
    <rule ref="rulesets/java/unnecessary.xml">
    </rule>
    <rule ref="rulesets/java/unusedcode.xml"/>
</ruleset>
```
Output

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ruleset" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>This ruleset checks my code for bad stuff</description>
  <rule ref="category/java/bestpractices.xml"/>
  <rule ref="category/java/codestyle.xml">
    <exclude name="AtLeastOneConstructor"/>
    <exclude name="AvoidDollarSigns"/>
    <exclude name="DefaultPackage"/>
    <exclude name="LocalVariableCouldBeFinal"/>
    <exclude name="LongVariable"/>
    <exclude name="MethodArgumentCouldBeFinal"/>
    <exclude name="OnlyOneReturn"/>
    <exclude name="ShortVariable"/>
    <exclude name="TooManyStaticImports"/>
  </rule>
  <rule ref="category/java/codestyle.xml/LongVariable">
    <properties>
      <property name="minimum" value="36"/>
    </properties>
  </rule>
  <rule ref="category/java/codestyle.xml/ShortVariable">
    <properties>
      <property name="minimum" value="1"/>
    </properties>
  </rule>
  <rule ref="category/java/codestyle.xml/TooManyStaticImports">
    <properties>
      <property name="maximumStaticImports" value="25"/>
    </properties>
  </rule>
  <rule ref="category/java/design.xml">
    <exclude name="AvoidCatchingGenericException"/>
    <exclude name="AvoidThrowingRawExceptionTypes"/>
    <exclude name="LawOfDemeter"/>
    <exclude name="LoosePackageCoupling"/>
    <exclude name="SignatureDeclareThrowsException"/>
  </rule>
  <rule ref="category/java/documentation.xml">
    <exclude name="UncommentedEmptyConstructor"/>
  </rule>
  <rule ref="category/java/errorprone.xml">
    <exclude name="AvoidDuplicateLiterals"/>
    <exclude name="AvoidFieldNameMatchingMethodName"/>
    <exclude name="AvoidLiteralsInIfCondition"/>
    <exclude name="BeanMembersShouldSerialize"/>
    <exclude name="NullAssignment"/>
  </rule>
  <rule ref="category/java/errorprone.xml/AvoidDuplicateLiterals">
    <properties>
      <property name="skipAnnotations" value="true"/>
    </properties>
  </rule>
  <rule ref="category/java/multithreading.xml"/>
  <rule ref="category/java/performance.xml"/>
</ruleset>
```

**Comment by jsotuyod** [comment]
@asarkar thanks for the tool! As stated in https://github.com/pmd/pmd/issues/805#issuecomment-359210540 this approach is not the recommended best practices, but equivalent to the behavior of the old ruleset. I may try to submit a PR to add support for it, if I get the time to play with Kotlin...

In the meantime, 6.0.1 should be released today, which among several fixes, will produce better logging as per #865:
 - we explicitly say on which version of PMD deprecated rulesets / rule names will be removed (we use semantic versioning, so it's not hard to guess anyway, but just in case)
 - we log the new location of each rule referenced, even if by whole ruleset. It will be noisier, but you will be able to update your ruleset with the log only, without having to check PMD deprecated rulesets' xml

The issue remains open for other users reference until we come up with a full migration guide on the site + maybe a distributable autoupdate tool such as the one suggested.

**Comment by vanniktech** [comment]
Can this be closed now given that 6.1.0 was released?

**Comment by jsotuyod** [comment]
I'd keep it for a while as new users may come across this. Also, we should consider having @asarkar's migration tool fully tested, and readily available (binary form) from our doc's site.

**Comment by krichter722** [comment]
Is there a link to the (WIP) migration guide or the issue proposing it (to be able to track the progress)?

**Comment by jsotuyod** [comment]
@krichter722 the migration tool mentioned can be found [here](https://github.com/asarkar/pmd-migration-tool) but I found some issues when migration some older rulesets with it. The migrator tool favors the whole category + excludes approach, which ends up not being equivalent to what the user had.

1. New rules added to PMD are automatically included, as they are not excluded.
2. Old rules that were not included (yet not excluded) are automatically included if moved to a category from which you are referencing at least one rule.

ie: the PMD 5 ruleset:

```xml
<rule ref="rulesets/java/coupling.xml">
    <exclude name="ExcessiveImports"/>
</rule>
```

has 4 rules enabled, but gets converted to:

```xml
<rule deprecated="false" ref="category/java/bestpractices.xml" typeResolution="false"/>
<rule deprecated="false" ref="category/java/design.xml" typeResolution="false">
  <exclude name="ExcessiveImports"/>
</rule>
```

that has 44 rules in the bestpractices ruleset, and 45 in the design ruleset (-1 excluded), giving a grand total of 88 included rules.

The best approach would be to simply add all the rule references as independent lines. Ruleset will be larger, but more granular and far closer to what the user actually had before, producing:

```xml
<rule ref="category/java/bestpractices.xml/LooseCoupling"/> 
<rule ref="category/java/design.xml/CouplingBetweenObjects"/> 
<rule ref="category/java/design.xml/LawOfDemeter" /> 
<rule ref="category/java/design.xml/LoosePackageCoupling" /> 
```

which has exactly the 4 referenced rules.

**Comment by asarkar** [comment]
@jsotuyod Good idea. The migration tool was based on a the rulesets we were using at work, so I'm not surprised that there are other use cases I didn't think of. I already fixed a couple of bugs reported, but if there's larger interest in it, I'm happy to take PRs or make the proposed changes when I find some time.

**Comment by asarkar** [comment]
@jsotuyod @krichter722  I've created a new branch [issue-5](https://github.com/asarkar/pmd-migration-tool/tree/issue-5) that fixes https://github.com/asarkar/pmd-migration-tool/issues/5. I'll give it a few days before merging in case you're interested in verifying it.

**Comment by asarkar** [comment]
v1.0.3 of the migration tool released.
