### ISSUE TITLE
[java] Excessive*Length ignores too much

### ISSUE THREAD

**Issue by TWiStErRob** [pmd/pmd#825]
**Affects PMD Version:** 6.0.0

**Rule:** `ExcessiveClassLengthRule` and `ExcessiveMethodLengthRule`

**Description:** I was checking a class with a 200-line constructor in our codebase and `ExcessiveMethodLength` didn't pick it up. I fired up the debugger and found out that the constructor `DataPoint`s are not added to the `StatisticalRuleHelper`.

**Resolution:** `ExcessiveLengthRule` ctor needs to be vararg and
* `ExcessiveMethodLengthRule` call `super(ASTMethodDeclaration, ASTConstructorDeclaration, ASTAnnotationMethodDeclaration)`
* `ExcessiveClassLengthRule` call `super(ASTClassOrInterfaceDeclaration, ASTEnumDeclaration, ASTAnnotationTypeDeclaration)`

From a user perspective (everyday developer), all of those are methods and all of those are classes.

Alternatively the AST needs to change and let Constructor/AnnotMethod extend Method, and Enum/AnnotType extend ClassOrIface. Maybe it was in the past?

**Code Sample demonstrating the issue:**
```
class ExcessiveConstructor {
	ExcessiveConstructor() {
		// 300 lines of garbage
	}
}
```
[ExcessiveConstructor.java.txt](https://github.com/pmd/pmd/files/1595591/ExcessiveConstructor.java.txt)

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]* CLI:
```shell
pmd -d ExcessiveConstructor.java -f text -R category/java/design.xml/ExcessiveMethodLength
<no output>
```

**Comment by oowekyala** [comment]
Interesting, thanks for the feedback! The simplest way to fix that would be to use the existing `ASTMethodOrConstructorDeclaration` and `ASTAnyTypeDeclaration` interfaces. These abstract method and constructors nodes under a single type, and similarly for enum, class, annotation and interface type declarations. 

A more long-term solution would be to refactor ExcessiveLengthRules to use the metrics framework (using the existing [Lines of Code](https://pmd.github.io/pmd-6.0.1/pmd_java_metrics_index.html#lines-of-code-loc) (LOC) metric).  Besides, it's a project of us to drop support for StatisticalRule over time, as discussed in #483. It wasn't a priority but now seems a good time to move forward with that. 

I think we could fix those rules for the time being using the interface types and deprecate them, and create a single new rule with the metrics framework to replace the old ones, similarly to what was done with NcssCount (which replaced NcssConstructorCount, NcssMethodCount and NcssClassCount).

Btw this is the kind of rule that could be easily expressed in XPath if we had a way to match nodes based on a supertype of the node, eg `//AnyTypeDeclaration[metric('LOC') > $reportLevel]`. It's kind of frustrating to write Java rules when the XPath alternative could be so terse

**Comment by TWiStErRob** [comment]
Oh, cool, I saw the super class, but I mis-remembered how `isInstance()` works. I thought it was exact match not like `instanceof`.

When running XPath is there an actual XML file generated in memory or there's some magic going on?

**Comment by oowekyala** [comment]
No it's not an XML file, we have an adapter that makes the translation between the structure expected by the XPath library (Jaxen or Saxon) and our AST structure. See eg [DocumentNavigator](https://github.com/pmd/pmd/blob/c34519431cf1d25f0fc3d0d979099b3e07cdbc10/pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/DocumentNavigator.java#L125) . An instance of that is passed to Jaxen and with it it can navigate the AST like it would an XML document, querying it for eg the parent or child of the current node

**Comment by TWiStErRob** [comment]
Thanks. The it would be possible to fake a tree that has all the super-classes as well. Maybe a bit hacky though:
 1. Adjust `getXPathNodeName`:

    ```java
    String getXPathNodeName(Class<?> as) {
        if(as == getClass()) return <current value>;
        else return <super-class-specific value>;
    }
    ```
2. Wrap `Node` into

    ```java
    class NodeWrapper {
        Node node;
        Class as;
    }
    ```
3. Modify `NodeIterator`'s next/prev to consider all super-classes. So if `A extends B extends C (extends Object)` then `(node, Class<A>), (node, Class<B>), (node, Class<C>)` are all visited before going on to `(node2, Class<T>)`.

...and I think I see why this wouldn't work just as I wrote this down. `following`/`preceeding` would be broken as 1. it would include `self` most of the time, 2. immediate sibling/indexing would break as `self == following[1] == following[2]` could be true.

---

How about `//*[isA('AnyTypeDeclaration') and metric('LOC') > $reportLevel]`? May not be as performant, but at least possible.

---

I'm sure you've considered many of these though, I just thought I would give it a quick thought.

**Comment by oowekyala** [comment]
Actually I don't remember having ever discussed that with the team. Thanks for your insights, this is really interesting! 

The last solution you proposed could indeed be used right now, I'll compare performance with a Java rule to see if it's interesting to replace the existing statistical rules with something like that 

As for the first solution, it looks to me like it's going to break things, as you said. I'm not that familiar with our XPath engine, but maybe @jsotuyod or @adangel could provide interesting insights about that
