### ISSUE TITLE
[java] Rule Excludes do not work anymore in 6.0.0

### ISSUE THREAD

**Issue by mkeller-ergon** [pmd/pmd#829]
**Affects PMD Version:** 
6.0.0

**Rule:**
various

**Description:**
Just tried to upgrade from 5.2.x to 6.0.0 but the rules excludes (often but not always) do not work anymore.
For example I'm trying to exclude "category/java/codestyle.xml/OnlyOneReturn":
This used to work but does not anymore:
```
<rule ref="category/java/codestyle.xml">
  <exclude name="OnlyOneReturn"/>
</rule>
```

The only way I've found is:
```
<rule ref="category/java/codestyle.xml/OnlyOneReturn">
  <properties><property name="violationSuppressRegex" value=".*"/></properties>
</rule>
```

However, for _some_ rules the first way does work, for example this works:
```
<rule ref="category/java/documentation.xml">
  <exclude name="CommentRequired"/>
</rule>
```

**Running PMD through:** *Gradle* via: 
```
pmd {
	ruleSetFiles = files("$rootProject.projectDir/config/pmd/pmd-rules.xml")
	ruleSets = [] // Remove built-in rule sets
	toolVersion = '6.0.0'
	ignoreFailures = true
}
```

**Comment by jsotuyod** [comment]
@mkeller-ergon I can't reproduce it. Please, attach / link to a working sample project so we can asses it.

You *may* have an issue on your ruleset. PMD has always accepted a rule to be excluded in one point, and configured at another, so you may be having the rule added unawarely. Look for any pending references to the old `controversial` ruleset.

**Comment by mkeller-ergon** [comment]
@jsotuyod: Thanks, that was it, I didn't realize an 'include' might have precedence over an 'exclude'. I've cleaned up our rules file now from the old rulesets to only contain the new categories and it works as expected now.

**Comment by jsotuyod** [comment]
@mkeller-ergon glad to hear! Let us know if you come across any further issues.
