### ISSUE TITLE
[java] StackOverflow in JavaTypeDefinitionSimple.toString

### ISSUE THREAD

**Issue by lslonina** [pmd/pmd#831]
**Affects PMD Version:** 
6.0.0

**Rule:**
Don't know if this is related to any particular rule, can check further.

**Description:**
With 5.8.1 pmd everything works fine, with 6.0.0 I'm getting StackOverflowException from toString method when called from MethodTypeResolution(358):
`LOG.log(Level.FINE, "Method {0} couldn't be resolved", String.valueOf(methodType));
`
```
Cause: java.lang.StackOverflowError
	at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.toString(JavaTypeDefinitionSimple.java:246)
	at net.sourceforge.pmd.lang.java.typeresolution.typedefinition.JavaTypeDefinitionSimple.toString(JavaTypeDefinitionSimple.java:246)
...

```
**Code Sample demonstrating the issue:**
```
public abstract class MessageBuilder<T extends MessageBuilder, U extends PartBuilder<U>> implements IMessageBuilder {
	public T addComponent(U builder) {
		components.add(builder);
		return (T) this;
	}
}

```
**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment]
@lslonina thanks for the report and the sample. I'll investigate.

**Comment by jsotuyod** [comment]
@lslonina I can't seem to reproduce it. The type for the `MessageBuilder.addComponent` is properly inferred and can be stringified without an issue... is this by any chance an OSS we may clone and look into?

If not, I'd ask a little extra info from you.

1. Which version of Gradle are you using (the contents of the auxclasspath may vary)
2. If running gradle with `--debug`, PMD will in turn run in verbose mode. Which will print plenty of messages such as `[DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Processing pathToFile`. Look for the last one before the stackoverflow. We need to know how `addComponent` is getting called on that file to produce this (which type information is present upon the method call).
3. Is `addComponent` an overload? is it an override? If so, please tell us which class defines such overloads / overrides and how these are defined.

Thanks in advanced! We greatly appreciate your help in making PMD better!

**Comment by jsotuyod** [comment]
@lslonina amazing! I'll get working on this ASAP.
