### ISSUE TITLE
[java] AvoidThrowingNullPointerException documentation suggestion

### ISSUE THREAD

**Issue by huxi** [pmd/pmd#832]
**Affects PMD Version:** 
6.0.0

**Rule:**
AvoidThrowingNullPointerException

**Description:**
Currently, [AvoidThrowingNullPointerException](https://pmd.github.io/pmd-6.0.0/pmd_rules_java_design.html#avoidthrowingnullpointerexception) documentation says the following:

> Avoid throwing NullPointerExceptions. These are confusing because most
> people will assume that the virtual machine threw it. Consider using
> an IllegalArgumentException instead; this will be clearly seen as a
> programmer-initiated exception.

#### Example(s):
```java
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}
```

This is one reason for activating the **AvoidThrowingNullPointerException** rule, true.

But a different - equally valid - reason for activating this rule would be the requirement to use the standard `java.util.Objects.requireNonNull()` methods (available as of Java 1.7) instead of throwing a `NullPointerException` manually.

In that case, the current documentation of **AvoidThrowingNullPointerException** would point the developer in the wrong direction by suggesting the use of `IllegalArgumentException` instead of `NullPointerException`.

I'd suggest to enhance the current documentation to point out both reasons and adding the Effective Java quote and examples below:

> **Effective Java, 3rd Edition, Item 72: Favor the use of standard exceptions**
> 
> Arguably, every erroneous method invocation boils down to an illegal
> argument or state, but other exceptions are standardly used for certain kinds
> of illegal arguments and states. If a caller passes `null` in some parameter
> for which `null` values are prohibited, convention dictates that
> `NullPointerException` be thrown rather than `IllegalArgumentException`.

#### Example(s):
```java
public class Foo {
    private String exampleValue;

    void setExampleValue(String exampleValue) {
        if(exampleValue == null) { // manual check
            throw new NullPointerException("exampleValue must not be null!"); // manual throw
        }
        this.exampleValue = exampleValue; // assignment
    }
}

import java.util.Objects;
public class Foo {
    private String exampleValue;

    void setExampleValue(String exampleValue) {
        // check, throw and assignment in a single standard call
        this.exampleValue = Objects.requireNonNull(exampleValue, "exampleValue must not be null!");
    }
}
```

**Comment by varunu28** [comment]
@huxi I would like to take up on this issue. Can you please assign it to me?

**Comment by jsotuyod** [comment]
@varunu28 @huxi I can't (he's not part of the organization nor the reporter), but feel free to tackle this. We usually don't take the issues labeled as `good first use` ourselves unless we don't have anything more critical to do / we are close to a release and have low hanging fruit; in order to foster newcomers.

**Comment by varunu28** [comment]
@jsotuyod  I will start working on this and would update you on the status
