### ISSUE TITLE
[doc] Test failures when building pmd-doc under Windows

### ISSUE THREAD

**Issue by SupunArunoda** [pmd/pmd#848]
**Affects PMD Version:** 6.0.0

**Rule:** Test Failure in pmd:doc

**Description:** pmd:doc failure occurs when building the project using mvnw.cmd clean verify -Dpmd.skip=true command with java 9 and mvn 3.5.2

**Running PMD through:** *[CLI | Maven |]*
[INFO] PMD Documentation Generator ........................ FAILURE [  5.065 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:06 min
[INFO] Finished at: 2018-01-13T19:20:46+05:30
[INFO] Final Memory: 113M/767M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project pmd-doc: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Projects\gsc\bac\pmd\pmd-doc\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by adangel** [comment]
Thanks for the report. It works for me, but I use Linux. It might be a Windows-only issue.
I'll try to fix this for PMD 6.1.0.
