### ISSUE TITLE
[apex] ApexCRUDViolation writes errors to stdout instead of stderr

### ISSUE THREAD

**Issue by up2go-rsoesemann** [pmd/pmd#851]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
All containing the rule ApexCRUDViolation

**Rule:**
ApexCRUDViolation

**Description:**
ApexCRUDViolation is writing a stack trace for an NPE to stdout instead of stderr, so it's being interleaved into the valid runtime output. 

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
all tools

**Comment by up2go-rsoesemann** [comment]
@jsotuyod you can assign this to me

**Comment by jsotuyod** [comment]
@up2go-rsoesemann done, although is it enough to write it to stderr? shouldn't it end in a `ProcessingError` rather than a message to stderr?

**Comment by up2go-rsoesemann** [comment]
I think this is a duplicate to what I already fixed in https://github.com/pmd/pmd/issues/788
The problem is not where the NPE is routed to. It simply should not happen.
