### ISSUE TITLE
[java] Performance degragation after update from 5.8.1 to 6.0.0

### ISSUE THREAD

**Issue by koma0277** [pmd/pmd#862]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
6.0.0
**Description:**
We build a huge multi module project with ANT 1.10.0 and Java 8. Compiling and packaging (with PMD checks) takes 16 minutes with PMD 5.8.1. After the update to PMD 6.0.0 and adapting the ruleset to the new rule definitions it takes 21 minutes. But I always get the hint to use the new cache feature. Adapting the configuration to check with cache it takes 30 minutes!!!

**Running PMD through:** 
ANT 1.10.0

**Comment by jsotuyod** [comment]
@koma0277 thanks for the report! I'm most interested in this scenario. PMD 6.0.0 increased the depth of it's analysis on type resolution / metrics, which may increase analysis time (we plan to come back to them for performance upgrades similar to those in PMD 5.5.1-5.6.0). However, the cache should not produce a regression.

So, let me better understand your use scenario:

1. You have a multi module project. Are you running PMD separately on each module or the project as a whole? If running on each module separately, are the cache files for each run unique?
2. Are you certain the cache file is not deleted upon a new ant run? Maybe you store the cache in a location that is cleaned as part of the build?
3. I assume that time corresponds to a clean run. What's the time for a second run (with or without local changes)? Seeing the same times would point to the cache being lost / completely invalidated upon each run.
4. If none of the above point to a configuration error, please run ant with `-debug | grep -i "incremental analysis" > cache.log` and upload the cache.log. It will contain file names, if you don't want them publicly, my email is public on my profile, you can send it directly to me.

**Comment by jsotuyod** [comment]
@koma0277 any update on this?

**Comment by koma0277** [comment]
Sorry for the delay. I'm busy with the current project right now.
I have tested a little bit around. It doesn't seem so bad as in the first post.

1. PMD is running separately on each module because of the classpath. Right now I have only tried it with one global cache file. 
2. Because we only do clean builds every time I believe the caching functionality doesn't make sense for our project.

It seems that there were some other problems with our build server on that day I have tested PMD 6.0.0. I will do further testing and post the results.

**Comment by jsotuyod** [comment]
@koma0277 ok, please note that the cache is "per project". If using the same file for different modules, each one will overwrite the other, meaning the cache is never actually used. Use separate files for each module.

Doing clean builds on CI is ok, but on local machines you may want to avoid cleaning the PMD cache (you can still clean your compiled Java files), the cache is smart enough to avoid issues with this and can figure out on it's own what's stale and what's not.

I'm closing this for the time being, but please, keep me posted, and reopen if anything new arises.

**Comment by koma0277** [comment]
@jsotuyod I have retested it with PMD 6.2. Same result.
Using PMD 5.8.1 takes 20:16 minutes for our build process including PMD.
Using PMD 6.2 takes 33:03 minutes for the same source code on the same machine.

**Comment by jsotuyod** [comment]
@koma0277 thanks for the update. Just to make sure, are you currently:

1. Disabling cache? 
2. Using cache, with a separate file per analysis, and without cleaning it? 
3. Still using the old setup?

If the answer is 3, please review my last response. If 1 or 2, please provide a sample ant task configuration and the exact command run under ant (ie: are you running in debug / verbose mode?). Feel free to edit these for confidential information.
