### ISSUE TITLE
[core]about inter-procedural  analysis

### ISSUE THREAD

**Issue by tiandiyixian** [pmd/pmd#863]
**Affects PMD Version:** 
6.0
**Rule:**

**Description:**
Does pmd dfa support inter-procedural  analysis?such as cross function  or cross file.I want to realize a taint analysis about tracing the data flow  between source and  sink .
thanks
**Code Sample demonstrating the issue:**

```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by jsotuyod** [comment]
@tiandiyixian PMD currently doesn't perform inter procedural analysis. It's in [our roadmap](https://github.com/pmd/pmd/wiki/Project-Ideas-%5BInception%5D#data-flow-analysis-and-control-flow-graph) and we are even considering proposing some work on DFA as part of Google Summer of Code 2018.

As always, all PRs and contributions to help move this forward faster are greatly welcomed.
