### ISSUE TITLE
[apex] Contact me as quality gate for Salesforce-based rules.

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#887]
Recently there was huge interest in the Salesforce community for rules contributions. I did a small webinar on how to write rules. In case people submit rule issues or even PRs please let me be a the quality gate here @adangel @jsotuyod. Maybe you can give me permissions to review code.

In the past some really low-quality rules have been added by some devs and I don't want to fast fix those. (Recently many IDEs failed because of the ApexCRUDRule.)

**Comment by jsotuyod** [comment]
@rsoesemann great to hear! You should already be able to comment in detail on any PR submissions. I'll mention you if they appear non the less.
