### ISSUE TITLE
[all] Use slf4j

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#896]
Part of #2524 

Rationale: In order to make it easier to integrate PMD into other tools, it might be better to use the de-facto-standard [slf4j](https://www.slf4j.org/).
We could then provide some basic simplelogger configuration in our binary distribution, but integrations have full freedom on which logging framework they want to use.

This would at slf4j-api as an additional compile-time dependency and maybe slf4j-impl as runtime dependency in our pmd-bin-xxx.zip distribution.

Currently we are using java util logging.

Tasks:
- [x]   Decide on the logging backend (log4j, logback, ...) and provide a default runtime + test
    configuration
    * Simplelogger from slf4j: That's a simple logger implementation without additional transitive dependencies that can still be configured (selection of loggers) - https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html
    * Logback: It would have support for color output on the console - https://logback.qos.ch/
    * We start with simplelogger to keep it simple. The implementation can be switched later, if needed.
- [x] Integrate it into the CLI flags (`-debug`)
- [x] Fix dist (add missing dependency, provide default simplelogger.properties)
- [x] Test dist
- [x] Fix ant (AntLogger)
- [x] Remove logback-classic from apex-jorje
- [x] Create a custom PMD rule to avoid usage of java.util.logging - only slf4j should be allowed. In build-tools.
- [x] Refactor logging statements (split into tasks/PRs for each pmd module)

**Comment by jsotuyod** [comment]
@adangel I totally support this, I think it's the most versatile approach. Also, the use of placeholders (`{}`) along with variable argument lists, can let us avoid guarding log statements, which may clean up the code a little bit without any performance cost.

We may have trouble with things such as Jorje internally using java util logging, although we are currently silencing some of it's output, so it may not be an issue.

**Comment by adangel** [comment]
Yes, probably something for a major version change. Also the command line output (format) might change.

By the way - it's no problem to integrate j.u.logging into slf4j. I did the same for the latest m-pmd-p, where I redirect PMD's logging into maven (https://github.com/apache/maven-pmd-plugin/blob/ffa915f02bc70a9eaea57a24093169e589e8e8be/src/main/java/org/apache/maven/plugins/pmd/AbstractPmdReport.java#L547)

**Comment by jsotuyod** [comment]
@adangel / @oowekyala any reason why this task is still open? I don't see any pending task in the description.

**Comment by adangel** [comment]
This is done for PMD7 via #3789
