### ISSUE TITLE
[core] Allow to set additional java runtime options on CLI

### ISSUE THREAD

**Issue by adangel** [pmd/pmd#898]
When running PMD from command line, it might be useful to set specific Java Options, like memory settings. With our current scripts (`run.sh` / `pmd.bat`), this is not possible. One would need to modify the script in order to run PMD with different memory settings.

Maven uses MAVEN_OPTS to configure such thinks, Tomcat CATALINA_OPTS.

We could introduce PMD_OPTS or just use a generic JAVA_OPTS environment variable.

Note: there is a HEAPSIZE variable, that can be used for configuring -Xmx, which is also [documented for CPD](https://pmd.github.io/pmd-6.0.1/pmd_userdocs_cpd.html#examples)

**Comment by oowekyala** [comment]
This looks fixed already. We have had PMD_JAVA_OPTS since 6.13.0. It's [documented here](https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#additional-java-runtime-options)
