### ISSUE TITLE
[java] Add new node for anonymous class declaration

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#905]
Proper metrics support for anonymous classes would need anonymous class declaration to be an ASTAnyTypeDeclaration. For now though, anonymous class declarations are just AllocationExpression or ASTEnumConstant with a body, which means that if those nodes extended ASTAnyTypeDeclaration, most of the time they *wouldn't be* an actual type declaration. 

The cleanest solution I see to preserve the type safe API of the metrics framework would be to add a child node of these nodes that's there only if they declare an anonymous class (an ASTAnonymousClassDeclaration), which contains the ASTClassOrInterfaceBody. This requires a change to the AST, and would certainly break some rules, so we can't do that before 7.0.0. 

Other ideas?

**Comment by jsotuyod** [comment]
I totally support this.

It would also be a good chance to deprecate `isAnonymousInnerClass` from `ASTClassOrInterfaceBody` and from `ASTClassOrInterfaceBodyDeclaration` (neither of which should probably expose `isEnumChild` either).

The find boundary would also have to be moved from `ASTClassOrInterfaceBodyDeclaration` to this new node type.

**Comment by oowekyala** [comment]
This is implemented since #1759, now we need the following deprecations on master:

* ASTClassOrInterfaceBody::isAnonymousInnerClass
* ASTClassOrInterfaceBody::isEnumChild

No deprecations planned for ASTClassOrInterfaceBodyDeclaration or ASTAllocationExpression since those nodes don't exist anymore in pmd 7
