### ISSUE TITLE
[ui] About the development of the designer

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#938]
Some of the components of the designer are not directly related to the core logic of the designer, and could be moved out into libraries that are developed separately. I'm talking specifically about the new persistence logic, and the code area to some extent, but some other future components could be externalised too 

This would be nice to speed up development of the designer, so that improvements to these components, which wouldn't directly affect the UX or features of the designer, could be made without the need to necessarily pass code review on this repo, which puts an unnecessary burden on the maintainers.

If we decide to move out some pieces, and if they're worth a specific library, the best way would be to version them with Maven, and publish them in the central repo. Some of the most pmd-specific components could belong to pmd's group id, eg the code area, which is too pmd-specific to be really developed outside of PMD. Maybe a "designer-tools" artifact could do the trick

Also, I'm not familiar with how to publish to Maven, but I guess it may take some time, so maybe we'd have to use unamanaged dependencies for some time

I also wanted to talk about the possibility of using components written in Scala. I'm working on a piece of code that we could use in the designer, but which really should be written outside of it (for the same reasons as above). I'd love to write it in Scala, and I figured since we already ship the Scala standard lib with our binary distributions, making the designer depend indirectly on a Scala runtime environment would not be a burden so long as the version matches that of pmd-scala.

@adangel @jsotuyod  Would you be ok with that? What would be your preferred development process for the designer?

**Comment by jsotuyod** [comment]
@oowekyala @adangel I'm not certain what's the benefit of moving these parts outside of PMD...

So far I see little interest from the community to use these independently (this of course may change over time). Having it separately, also hampers our ability to perform refactors atomically / keep in sync all parts and libs.

I personally don't think of code review as a burden, but a cornerstone practice to ensure quality and help detected undesired byproducts (we have effectively prevented breaking API changes, inconsistencies and bugs by doing it).

Shall you think some PRs are taking too long to get merged (I think over the last month or two this may have been in fact the case), I believe we can work around it. For instance, by adding labels with priority to tell other reviewers how critical the original author of the PR considers the changeset in the larger line of work it's pursuing (ie: in the past I've had 4-5 related PRs that needed to get merged in order as part of a larger change).

Maybe better understanding the reasons behind your proposal could helps us come up with a solution collaboratively that works for all.

As for the usage of Scala... I have only 2 concerns to expose:
1. to have it tied to the version of the Scala runtime shipped means it's harder for us to upgrade pmd-scala; even more if the scala parts of the ui are on a separate repository that's even outside the PMD organization.
2. even though it's true the binary distribution ships with the scala runtime, this would not be the case for tools such as Maven or Gradle. We don't currently offer this, but I think we should have a task to launch the GUI from these, just like [Findbugs offers `findbugs:gui`](https://gleclaire.github.io/findbugs-maven-plugin/gui-mojo.html). Our GUI has matured a lot, and will keep doing so; making it easier to access to users would be nice, specially considering we have far more users of PMD using these than ant / CLI.

**Comment by oowekyala** [comment]
@jsotuyod You're right, moving pieces out will complicate refactoring... My primary concern was modularizing the designer more than it currently is, keeping things that are not part of the business logic mostly out of the way, to separate concerns and clean up diffs. 

> Shall you think some PRs are taking too long to get merged

That was part of my reasoning (#801). The cause I suspected was that that PR contained many changes that were not *essential* to the designer's functioning, making it harder to review if you're short on time and want to skip to the essential. In particular, #801 introduced a component (the persistence framework) that is somewhat complex internally, but has a relatively simple external API (a few documented methods and annotations). It could have been easier to review if the implementation of this component had been left out, and took the form of another PR/ changeset, possibly in another repo. The point is not to skip code review, but to reduce the amount of code to review on *this* repo, so that it moves faster. If you're telling me that wasn't an issue with 801, then I may have misevaluated the problem.

> In the past I've had 4-5 related PRs that needed to get merged in order as part of a larger change

Until now I have actively avoided doing this, and prefer proposing PRs one-by-one, after the previous is merged, so that I can rebase to clean the history until the last minute. AFAIK there's also no way Github can display the diff of a PR with respect to another pending PR. I wasn't sure how you felt about having several PRs open in the same changeset, but if you find it's ok I can start doing that in the future.

Btw, maybe using a github [project](https://github.com/pmd/pmd/projects) could help us sort these better.

...

About Scala:

> to have it tied to the version of the Scala runtime shipped means it's harder for us to upgrade pmd-scala...

That's true, but if it's a concern, we could also keep those Scala components close to PMD to ease upgrading.

> Even though it's true the binary distribution ships with the scala runtime, this would not be the case for tools such as Maven or Gradle...

Good point. Users of a designer task for these tools could have to download a Scala runtime... we'd have to weigh that against the possible code size and time gain of writing some pieces of code in Scala. Tbh, for me it's also a question of fun, but on the other hand, I'm not sure if there are any other prospective developers of the designer that are interested and skilled in writing/ maintaining Scala code. So, lots of pros and cons...

**Comment by jsotuyod** [comment]
@oowekyala I think we can achieve that modularization just using proper packages. No need to split it into separate projects.

As for #801 in particular, yes, it was a little too large to get it easily reviewed. ~3000 added lines, ~900 removed is a little too much. I usually try to keep it at ~600 LoCs so that it's reviewable in depth well within an hour. Maybe the change could have been split into smaller chunks (the framework and it's usage on the the rest of the system could have been a plausible split; just as it would have been if they were part of separate repositories; but possibly not the only one).

> Until now I have actively avoided doing this, and prefer proposing PRs one-by-one, after the previous is merged, so that I can rebase to clean the history until the last minute. 

That's what I do. I have the nested feature branches locally and submit the PRs one by one. Just let us know if a given PR is part of a larger changeset and should be prioritized.

As for Scala, I'm not too familiar with it, but I'm not opinionated. I do wonder if this would be a barrier of entry to new contributors....

If it's just a thing for fun, maybe something truly independent, more one-off (ie: the ruleset migration tool for PMD 6) could be a better fit within PMD.

**Comment by oowekyala** [comment]
@jsotuyod I think you're right, there's no real use case to split the repo. I'll just be more careful with big PRs, as you said

About Scala, I think it shouldn't be a barrier of entry if essential parts of the designer remain written in Java. Controllers and related UI logic could remain written in Java (the JavaFX API is not made for Scala anyway), but Scala is a great tool to write elegant "library code", that is relatively isolated from the UI logic. For example, it could definitely help us remove that dependency on Apache BeanUtils and its appalling API, in very few lines of code compared to a Java solution. Overall I think it could be a win for the designer, though I'm certainly opinionated. 

@adangel I'd love to hear your opinion about that.
