### ISSUE TITLE
[java] InvalidSlf4jMessageFormat false positive with Throwable

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#939]
```java
Throwable t = new Throwable();
LOGGER.error("some text {}", 1, t);
```

This gives a `Too many arguments, expected 1 argument but have 2` warning while it shouldn't. Using `Exception` instead of `Throwable` works fine.

First mentioned in https://github.com/pmd/pmd/issues/935.

**Comment by jsotuyod** [comment]
@boris-petrov awesome! thanks!

**Comment by jsotuyod** [comment]
@boris-petrov I can't reproduce this on master with the given snippet.

**Comment by boris-petrov** [comment]
@jsotuyod - what about:

```java
Thread.setDefaultUncaughtExceptionHandler((thread, exception) ->
    LOGGER.error("Uncaught exception - {}", thread.getName(), exception));
```

I'm using PMD 6.1.0 and this gives me the warning.

**Comment by jsotuyod** [comment]
yes, that one will fail. The current type resolution code can't yet infer types of lambdas if not explicitly stated.

**Comment by jsotuyod** [comment]
This issue is no longer reproducible under PMD 7.0.0
