### ISSUE TITLE
[java] Refactor how we ignore annotated elements in rules

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#956]
As per https://github.com/pmd/pmd/pull/951#discussion_r172187305

We have a bunch of rules doing suppression based on certain annotations.

* `UnusedPrivateMethod` is customizable, and ignores `@Deprecated` by default
* `UnusedPrivateField` is customizable, and ignores `@Deprecated` AND `@FXML` by default
* `AbstractLombokAwareRule` defines rules for child rules to ignore certain lombok annotations, depending in the case

We can probably refactor all this into a base rule defining the property (the same name for consistency), allowing subclasses to set their defaults, and call the check on the node.

**Comment by djydewang** [comment]
My idea:
```
Public class AbstractIgnoredAnnotationsRule extends AbstractJavaRule {

         protect boolean hasAnnotation(Node node, List<String> annotationFullyQualifiedNameList) {
             // TODO
         }

        protect boolean hasAnnotation(Node node, List<Class<?>> annotationTypeList) {
             // TODO
         }

}
```

What's your suggesttion?

**Comment by jsotuyod** [comment]
@djydewang we can probably have a new `Annotateable` interface, and have all AST nodes that can be annotated implement it. The interface `CanSuppressWarnings` should probably extend `Annotateable`.

The base rule class would:

1. define the property (so it's named the same everywhere)
2. provide methods to get an `Annotateable` and check if it contains any of the annotations configured in the property. Similar to your but with only 1 method, and not receiving the list, as the property is already defined in the abstract base rule.

**Comment by oowekyala** [comment]
@djydewang @jsotuyod I think it's Annotatable nodes that should have the logic to check if they have a specific annotation. Much like a `j.l.reflect.Method` or Class has the method [`isAnnotationPresent`](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/AccessibleObject.html#isAnnotationPresent(java.lang.Class)). The trouble here would be to share the implementations, which would be nearly identical (we could delegate to a package private static class, then use default methods when we move to java8). I'm really no fan of putting that logic in AbstractJavaRule, it seems to me like a classification error.

To me, Annotatable should ideally look like that:
```java
public interface Annotatable extends JavaNode {
  List<ASTAnnotation> getDeclaredAnnotations();

  boolean isAnnotationPresent(Class<? extends Annotation> clazz);
  boolean isAnnotationPresent(String annotQualifiedName);

  boolean isAnyAnnotationPresent(Collection<Class<? extends Annotation>> classes);
  boolean isAnyAnnotationPresent(Collection<String> annotNames);
}
```

The base rule class could look like that:
```java
public abstract class AbstractIgnoredAnnotationsRule extends AbstractJavaRule {

  protected final StringMultiProperty suppressionAnnotations = StringMultiProperty.named("...").defaultValue(defaultSuppressionAnnotations())...; 

  protected abstract Collection<String> defaultSuppressionAnnotations();
}
```

**Comment by jsotuyod** [comment]
@oowekyala I agree the tree transversal from the annotateable node to the annotations are for sure in the node itself. That's completely dependent on the AST, and although similar, can be different from node to node.

As a developer however, it's easier to call `isIgnored(annotatedNode)` than `annotatedNode. isAnyAnnotationPresent(getProperty(suppressionAnnotations))`. We could go as far as overriding the `addViolation` methods and filter there....

On the other hand, the current logic for `CanSuppressWarnings` (other than transversal, which goes to `Annotateable`) is definitely something to be moved into the `AbstractJavaRule`. All knowledge of how an annotation suppresses a rule is dependent on the rule.

1. either by a `@SuppressWarnings("PMD.rulename")` or `@SuppressWarnings("PMD")`, the first depending on the rule's name
2. either by a `@SuppressWarnings("unused")`, `@SuppressWarnings("serial")` or `@SuppressWarnings("all")`, where the contents need to be analyzed when checking if it applies to a particular rule (this is currently in the `ASTAnnotation`, but it's wrong... the rules should know the AST, not the other way around, and specially not as hardcoded strings which are broken upon renaming rules)

https://github.com/pmd/pmd/blob/0967d5027539d8528deb025d6b6d0ecece41d8f9/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotation.java#L16-L20

Having the node know the rule in any way creates a cycle in class dependency => tight coupling.

**Comment by oowekyala** [comment]
> As a developer however, it's easier to call isIgnored(annotatedNode)

I see your point. That `isIgnored` method could be defined as a shortcut to writing `annotatedNode. isAnyAnnotationPresent(getProperty(suppressionAnnotations))`, so that the `isAnyAnnotationPresent` method would be available to other rules (since it's on the node)

> On the other hand, the current logic for CanSuppressWarnings (other than transversal, which goes to Annotateable) is definitely something to be moved into the AbstractJavaRule

Ok yes that completely makes sense. We should be careful when modifying ASTAnnotation to implement that, since significant code changes to that file are still pending in #912. That could cause merge conflicts. I think the two problems could be tackled as separate PRs, one to add Annotatable and the base rule class (#958), another to move the suppression logic. The second will wait until #912 is merged

**Comment by oowekyala** [comment]
Looking at it more deepbly, making a base rule class doesn't look like a good idea. For example, UnusedPrivateField extends AbstractLombokAwareRule, so how should it extend  the AbstractIgnoredAnnotationsRule? Another problem is that different rules could have different default ignored annotations, which can't be done if we use a single property descriptor for all those rules.

Another, more flexible idea would be to add a static method to AbstractJavaRule that returns a StringMultiProperty builder with a pre-filled name, that we could then use to initialize the property descriptor in each rule.

In fact, I think base rule classes should be avoided, see #971

**Comment by jsotuyod** [comment]
@oowekyala `AbstractLombokAwareRule` would be a special case of this new proposed class. It's the same thing, ignoring rules based on node's annotations. They simply are defaults. I actually listed it as one of the examples to refactor in the first comment of this issue.

I see your point in general, but don't think it necessarily applies to this particular case. The added property definition, the compelling to setup defaults and the helper to check for annotations are in my view clear, feature-related and concise.

Furthermore, we may even go to the length of overriding `addViolation` methods, and have them automatically discard annotated nodes, making it truly transparent to the rule itself, having it only to care about properly detecting violations.
