### ISSUE TITLE
[core] PMD 6.0.1 Docs - Broken link to XPath Rule Tutorial

### ISSUE THREAD

**Issue by GuyPaddock** [pmd/pmd#959]
Please, prefix the report title with the language it applies to within brackets, such as [java] or [apex].
If not specific to a language, you can use [core].

**Affects PMD Version:** 
6.0.1

**Description:**
The link to the XPath Rule tutorial on the following page is broken:
https://pmd.github.io/pmd-6.0.1/pmd_userdocs_suppressing.html 

It leads the user to:
https://pmd.github.io/pmd_devdocs_writing_xpath_rules.html

This should probably go to:
https://pmd.github.io/pmd-6.1.0/pmd_userdocs_extending_writing_xpath_rules.html

**Comment by jsotuyod** [comment]
@GuyPaddock thanks for the report!

**Comment by oowekyala** [comment]
Closed via #967
