### ISSUE TITLE
[core] Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by refactormyself** [pmd/pmd#978]
In the [Documentation Section of CONTRIBUTING.md](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md#documentation) there is a broken link 
https://github.com/pmd/pmd/tree/master/src/site

**Comment by jsotuyod** [comment]
@refactormyself you are absolutely right. This is a really easy fix for anyone trying to start getting their hands dirty.

**Comment by refactormyself** [comment]
@jsotuyod Okay Please assign me to this

**Comment by refactormyself** [comment]
Please I will like to clarify the intention of the link. Is it supposed to point to https://github.com/pmd/pmd/blob/master/pom.xml

**Comment by jsotuyod** [comment]
@refactormyself assigned

The link should probably point to https://github.com/pmd/pmd/tree/master/docs, and is no longer a maven site, but a github pages site.

**Comment by refactormyself** [comment]
I just realised that this issue got me confused and led to this https://github.com/pmd/pmd.github.io/pull/6
