### ISSUE TITLE
[doc] Combine two different documentation on Building from source into one

### ISSUE THREAD

**Issue by refactormyself** [pmd/pmd#985]
Currently there are two different documentation on Building from source :

https://github.com/pmd/pmd/blob/master/docs/pages/pmd/devdocs/building.md
and
https://github.com/pmd/pmd/blob/master/BUILDING.md

I prefer the second one but I think there some useful bits that can be borrowed from the first one.
I suggest combining these two documents into one.

**Comment by oowekyala** [comment]
There is also the [wiki page](https://github.com/pmd/pmd/wiki/Setup-IDE) about IDE setup, which seems mature enough to be promoted to the website

**Comment by adangel** [comment]
Closing this one in favor of #2492
