### ISSUE TITLE
[doc] Delete duplicate page contributing.md on the website

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#994]
[Contributing](https://pmd.github.io/pmd-6.1.0/pmd_devdocs_contributing.html) is less maintained and complete than [CONTRIBUTING.md](https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md).

I'd say we should simply delete it to avoid the discrepancy. Especially since [Developer resources](https://pmd.github.io/pmd-6.1.0/pmd_devdocs_development.html#contributing) already points to CONTRIBUTING.md

**Comment by ishanSrt** [comment]
I would like to be assigned to this

**Comment by adangel** [comment]
@ishanSrt I've sent you an invite via github. Once you accept it, we can assign the issue to you.

**Comment by ishanSrt** [comment]
Please give me the owner priveleges for https://github.com/pmd/pmd.github.io so that I can delete it.
Or i can just delete all the files and sumit it as a PR

**Comment by ishanSrt** [comment]
so shall I set the links to the contributing page if any to contributing.md on GitHub?

**Comment by adangel** [comment]
@ishanSrt Please create a PR for whatever you want to change.
Also note, that almost everything is generated, either from the rule documentation or from the jekyll sources under https://github.com/pmd/pmd/tree/master/docs . On every release, we take the generated page and upload it to pmd.github.io. IMHO, it is not necessary to change pmd.github.io for the old version, we just need to make sure, we change the documentation for upcoming versions of PMD.

I think, linking from the menu item "Contribution" directly to https://github.com/pmd/pmd/blob/master/CONTRIBUTING.md make most sense.

**Comment by ishanSrt** [comment]
@adangel please review
